### ISSUE TITLE
etcd support?

### ISSUE THREAD

**Issue by rbucker** [micro/go-micro#1]
Is there any interest in etcd support?

**Comment by asim** [comment]
Sure. Seems like a reasonable idea.

**Comment by asim** [comment]
I've now added an etcd store. I will add support for the registry later if there is interest for that.

**Comment by rbucker** [comment]
Excellent. I'll need to try this out ASAP.  I was in the process of putting together a PR but got distracted as I was trying to build some testcases... oh well. Thank. I look forward to testing it out.
