### ISSUE TITLE
glog issue

### ISSUE THREAD

**Issue by justintv90** [micro/go-micro#10]
From glog requires flag.Parse() to use his flags, micro dont use flag.Parse() so when excuting the micro-based code, it will show the Error in log. I think we should change log system or put a flag.Parse() into cmd.Init() to bypassing these errors , what do you think ?

**Comment by asim** [comment]
I will test it out and see how it works. I had issues with use of the flag package and codegangsta/cli in the past. Perhaps just calling flag.Parse after the other initialisation will be fine.

**Comment by kynrai** [comment]
putting a flat.Parse() at the start of cmd.Init() appears to work for this, but not at the end.

**Comment by asim** [comment]
You notice that if you then try execute --help it gets swallowed by the flag package. Bit painful.

**Comment by justintv90** [comment]
flag.parse() will overide whole micro-go flag function, putting flag.Parse() ath the start of cmd.Init() is not a soulution :dancer:

**Comment by crackcomm** [comment]
Possible solution would be to add glog flags to [cmd.Flags](https://github.com/myodc/go-micro/blob/master/cmd/cmd.go#L34) and after parsing moving values to glog package using `flag.Set()`.

Second possible solution is to copy all flags on run-time from standard flag library to `cmd.Flags` and then moving parsed values back.

**Comment by asim** [comment]
I will experiment with both ideas later this evening and commit a solution. Hate to see this linger on.

**Comment by asim** [comment]
Opted to add glog flags and then use flag.Set(). Still needs some work as I believe its ignoring log_dir https://github.com/myodc/go-micro/commit/b94c5d4026ff48190a7a295f2dfd8775e6c306f7

**Comment by crackcomm** [comment]
Last time I was trying to use -log_dir flag it didn't work aswell so it's possible that's a glog issue.

EDIT: Also make sure You are using latest glog version ([look](https://github.com/golang/glog/commit/65d674618f712aa808a7d0104131b9206fc3d5ad)).

**Comment by asim** [comment]
You're right. Go get and all is good. Closing this issue as I think we've got this sorted now.
