### ISSUE TITLE
How about add CA support for transport

### ISSUE THREAD

**Issue by xujinzheng** [micro/go-micro#100]
If we use `transport.Secure(true)`, and did not set`tls.config`, then the transport will automatic generate self-signed cert, but the cert is not trusted, we could use  `InsecureSkipVerify` for ignore secure issue while we make a client request, but some tools could not skip it like tool of `ab`, and if we want for support `http2`,  the tools `nghttp`,`h2load` would not support insecure cert too.

I use these tools to have a load test, it will directly to request to a service node as following:

``` bash
 go run main.go
2016/06/06 11:12:06 Listening on [::]:54897
2016/06/06 11:12:06 Broker Listening on [::]:54898
```

`postdata`

```
{"method":"Say.Hello","params":[{"name":"world"}],"id":0}
```

```
ab -c 100 -n 1000000 -H 'Content-Type: application/json' -p postdata  https://127.0.0.1:54897/`
```

I generated a private CA Cert, and let system `trusted`, so while we use `transport.Secure(true)`,  set `transport.CACert(certFilepathFromENV, keyFilepathFromENV)`, it will generate cert and issued by this `CA`, so the address of `https://127.0.0.1:54897/` we be trusted, if we do not give CA Cert, then it will generate `self-signed` cert. 

---

while I to do this work, I coded a tls lab `github.com/gogap/misc/lib/tls`

it will work as following:

``` go

import  gogapTLS "github.com/gogap/misc/lib/tls"

if p.opts.Secure {

        if tlsConfig == nil {
            var hosts []string
            if h, _, e := net.SplitHostPort(addr); e == nil {
                if h == "" {
                    hosts = getIPAddrList()
                } else {
                    hosts = append(hosts, addr)
                }
            }

            caConf := getCAConfig(p.opts.Context)

            var err error
            if cert, key, err = gogapTLS.GenerateCertificate(
                gogapTLS.Host(hosts...),
                gogapTLS.CAFile(caConf.cert, caConf.key),
            ); err != nil {
                return nil, err
            }

            var cer tls.Certificate
            if cer, err = tls.X509KeyPair(cert, key); err != nil {
                return nil, err
            }

            tlsConfig = &tls.Config{Certificates: []tls.Certificate{cer}}
        }

        fn := func(addr string) (net.Listener, error) {
            return tls.Listen("tcp", addr, tlsConfig)
        }

        l, err = listen(addr, fn)
    } else {
        fn := func(addr string) (net.Listener, error) {
            return net.Listen("tcp", addr)
        }

        l, err = listen(addr, fn)
    }
```

**Comment by asim** [comment]
Thanks for the suggestion but I think this goes beyond the scope of what the self signed cert was for. If you want to use a CA then you should be generating the tls.Config and passing that in yourself.

**Comment by xujinzheng** [comment]
Ok, I see, I think I will improve `utils` package for this feature.
