### ISSUE TITLE
[FEATURE] OpenFaas support

### ISSUE THREAD

**Issue by BitPhinix** [micro/go-micro#1006]
**Is your feature request related to a problem? Please describe.**
Deployment of microservices is a pain, even with a manged k8s cluster you have to extensively describe deployments using e.g. helm to integrate it into a CI/CD pipeline.

**Describe the solution you'd like**
Add an option to deploy microservices developed using go micro with https://www.openfaas.com/. This is especially powerful with the https://github.com/openfaas-incubator/kafka-connector connector and would simplify deployments by a lot.

**Additional context**
https://www.openfaas.com/blog/stateless-microservices/

**Comment by asim** [comment]
No support for now
