### ISSUE TITLE
Error 404 of github.com/micro/go-config

### ISSUE THREAD

**Issue by wlf061** [micro/go-micro#1027]
Hi,
Our project has used the package url, but now it  seems can't be accessed.
When i check the doc, it seems go-config is under https://github.com/micro/go-micro/config,should i change it to the new url, right?
If i mistake  something, please let me know.

Thanks~~

**Comment by lqczzz** [comment]
go-config is integrated in go-micro as a submodule since go-micro1.3.

i have switched and used it for a long time

the apis are not changed, you can safely switch to new version

**Comment by lqczzz** [comment]
> Hi,
> Our project has used the package url, but now it seems can't be accessed.
> When i check the doc, it seems go-config is under https://github.com/micro/go-micro/config,should i change it to the new url, right?
> If i mistake something, please let me know.
> 
> Thanks~~

go-config is integrated in go-micro as a submodule since go-micro1.3.

i have switched and used it for a long time

the apis are not changed, you can safely switch to new version

**Comment by asim** [comment]
As above ^^
