### ISSUE TITLE
MsgPack Codec

### ISSUE THREAD

**Issue by bruth** [micro/go-micro#103]
Is there interest in adding a [msgpack](http://msgpack.org/) codec in the core? I implemented one that I can submit a PR for.

**Comment by bruth** [comment]
Here is the [code](https://github.com/harvest-platform/micro-msgpack-codec) that would be contributed.

**Comment by asim** [comment]
Only json and proto are supported at the core. This would likely live in go-plugins/codecs. I would argue that it should maybe work with existing msgpack implementations out there. https://msgpack.wordpress.com/2010/05/04/introduction-to-messagepack-rpc/. 

json-rpc is a specification and widely supported and so the codec conform to that. proto-rpc conforms to net/rpc's interface and was lifted from youtube/vitess. The expectation is that we try implement codecs that can interact with other systems.

Also your codec appears to Write a message as is but then in ReadHeader reads a custom Message type within the codec. I'm not sure that will actually work.

**Comment by bruth** [comment]
Thanks and understood. I will read, fix, and re-open the PR in the go-plugins repo.
