### ISSUE TITLE
[BUG] No status received when calling GRPC service

### ISSUE THREAD

**Issue by alidawud** [micro/go-micro#1040]
**Describe the bug**

1. What are you trying to do?
Call service from nodejs GRPC client

2. What did you expect to happen?
No error

3. What happens instead?
Service responded: 
```json
{
  "error": "2 UNKNOWN: No status received"
}
```

**How to reproduce the bug:**
* Create a new micro service from micro command line
```
micro new order --namespace=com.example --type=srv
```
* Write a nodejs client to call the service or use [Bloomrpc](https://github.com/uw-labs/bloomrpc)

**Environment:**
Go Version: go version go1.13.4 darwin/amd64
```
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/ali/Library/Caches/go-build"
GOENV="/Users/ali/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/ali/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.13.4/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.13.4/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/ali/Desktop/order/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/hd/_2kmgh7x2yb0_rmyzswc4dgc0000gn/T/go-build501579234=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

**micro version:**
micro golang library: v1.18.0
micro version runtime: v1.18.0-2f6e1f8-1575822130

**Comment by alidawud** [comment]
It works after I change:

`micro.NewService`

to

`grpc.NewService`

**Comment by marvin-liu-sx** [comment]
> It works after I change:
> 
> `micro.NewService`
> 
> to
> 
> `grpc.NewService`

I have the same problem, how can I solve it
