### ISSUE TITLE
[FEATURE] Options for var jsonpbMarshaler = &jsonpb.Marshaler{}

### ISSUE THREAD

**Issue by allenkaplan** [micro/go-micro#1050]
**Is your feature request related to a problem? Please describe.**
The current jsonpbMarshaler does not allow for options per the jsonpb godoc at https://godoc.org/github.com/golang/protobuf/jsonpb#Marshaler. Specifically, I am looking to enable the "EmitDefaults bool"

**Describe the solution you'd like**
Add the ability set options for the client and server grpc marshaler

https://github.com/micro/go-micro/blob/744b19d6250a93bbb3bd7eae92d030be4732b0ca/server/grpc/codec.go#L26

https://github.com/micro/go-micro/blob/744b19d6250a93bbb3bd7eae92d030be4732b0ca/client/grpc/codec.go#L23

**Additional context**
_Enum default value of 0 is not sent as protobuf treats enums as ints in Go._ As well, other int fields such as a score, cost or number of people will not be marshaled. If there is a solution I do not see, please let me know.

**Comment by vtolstov** [comment]
Did you mind to send pr for this? If no, i can take this.I think that we can receive Marshaler and Unmarshaler structs via global codec variable

**Comment by allenkaplan** [comment]
So I took a look at how codec works to ensure things are clean.

Other than the gRPC client and gRPC server, the only two places that the jsonpb is imported `go-micro/codec/json/json.go` and `go-micro/codec/json/marshaler.go`, but neither the client or server import `go-micro/codec/json`. 

I'm not too sure where the options would be added from whoever is using go-micro; perhaps this would be better as a plugin to the codec?

**Comment by vtolstov** [comment]
@asim may be we need to move codec from grpc server to codec dir?

**Comment by asim** [comment]
Potentially. Good to only have one codec.

**Comment by uxgnaw** [comment]
I copy grpc/codec to github.com/lifenglin/micro-library, in main.go, i add "connect.RegisterJSONCodec()" to resolve this
