### ISSUE TITLE
streams mux 

### ISSUE THREAD

**Issue by jamsonzan** [micro/go-micro#1057]
hello!

at server-side, streams are multiplexed on Micro-Stream or Micro-Id header
![go-micro-mux](https://user-images.githubusercontent.com/31194068/71343290-51747780-259a-11ea-98f6-22a946592c09.png)

but client.Stream only new a connection? :joy:

rpc_client.go
```go
c, err := r.opts.Transport.Dial(address, dOpts...)
```
http_transport.go
```go
conn, err = newConn(func(addr string) (net.Conn, error) {
			return net.DialTimeout("tcp", addr, dopts.Timeout)
		})(addr)
```

**Comment by asim** [comment]
Due to the complexity of stream multiplexing the client side has not yet been implemented.

**Comment by jamsonzan** [comment]
ok, thanks for your answer! :smile:
