### ISSUE TITLE
support grpc client mux

### ISSUE THREAD

**Issue by jamsonzan** [micro/go-micro#1060]
grpc client supports mux, but we now only get a connection from pool. why not use the pool as a streams pool? we can use maxStreams to control the number of streams on a connection. while maxStreams = 1, it degenerate into a connection pool. [this is the code](https://github.com/jamsonzan/go-micro/blob/master/client/grpc/grpc_pool.go).
and we use maxIdle to control the number of idle conn. if need, i can create a pr.

**Comment by vtolstov** [comment]
can you share some info for example speedup, or minimization of resource allocations, or some other benefits ?

**Comment by jamsonzan** [comment]
yes, i had finished a [test](https://github.com/jamsonzan/testpool)

**Comment by vtolstov** [comment]
nice, can you provide pr?
