### ISSUE TITLE
[BUG]{"id":"go.micro.client.transport","code":500,"detail":"404 Not Found: 404 page not found\n","status":"Internal Server Error"}

### ISSUE THREAD

**Issue by namhoangle1996** [micro/go-micro#1061]
**Describe the bug**

1. What are you trying to do?
  my system is using GRPC with go-micro v 1.18
   I use graphql client (99design ) , try to get data from server side but when i get , my graphql print: 
   
**receivevevev error {"id":"go.micro.client.transport","code":500,"detail":"404 Not Found: 404 page not found\n","status":"Internal Server Error"}**

my code client :+1: 
			streamFetch, err := resolver.Client.FetchChanByDevice(context.Background(), &graphql_rpc.Fetch{
				Id: 2,
			})
			for {
				rsp, err := streamFetch.Recv()
				if err == io.EOF {
					break
				}
				if err != nil {
					log.Print("receivevevev error ", err.Error())
				}
			}

i feel stupid. hope everyone help me
**Environment:**
Go Version: please paste `go version` output here
```
go v1.13.5

**Comment by namhoangle1996** [comment]
anyone help me????

**Comment by bhoriuchi** [comment]
Seems like same issue here https://github.com/micro/go-micro/issues/1017

**Comment by asim** [comment]
No longer an issue
