### ISSUE TITLE
Confused by the registration check in server.rpcServer.Start method.

### ISSUE THREAD

**Issue by spacewander** [micro/go-micro#1066]
Quoted from https://github.com/micro/go-micro/blob/master/server/rpc_server.go#L830:
```go
	Loop:
		for {
			select {
			// register self on interval
			case <-t.C:
				s.RLock()
				registered := s.registered
				s.RUnlock()
				if err = s.opts.RegisterCheck(s.opts.Context); err != nil && registered {
					log.Logf("Server %s-%s register check error: %s, deregister it", config.Name, config.Id, err)
					// deregister self in case of error
					if err := s.Deregister(); err != nil {
						log.Logf("Server %s-%s deregister error: %s", config.Name, config.Id, err)
					}
				} else {
					if err := s.Register(); err != nil {
						log.Logf("Server %s-%s register error: %s", config.Name, config.Id, err)
					}
				}
			// wait for exit
			case ch = <-s.exit:
				t.Stop()
				close(exit)
				break Loop
			}
		}

		// deregister self
		if err := s.Deregister(); err != nil {
			log.Logf("Server %s-%s deregister error: %s", config.Name, config.Id, err)
		}
```

If the `RegisterCheck` call here returns an error, and `registered` is false, `s.Register()` will be called.

This behavior is different from https://github.com/micro/go-micro/blob/master/server/rpc_server.go#L781, which `s.Register()` is called only when `RegisterCheck` doesn't return an error.

Moreover, if `s.Deregister()` is called in the `for` loop, and then it is called again when the server exits, the `config.Registry.Deregister(service)` callback will be triggered twice. See https://github.com/micro/go-micro/blob/master/server/rpc_server.go#L716.

Maybe we should guard the callback with the `if !s.registered {` check like https://github.com/micro/go-micro/blob/master/server/rpc_server.go#L722?

**Comment by vtolstov** [comment]
thanks!
