### ISSUE TITLE
conn leak in `client.pool`?

### ISSUE THREAD

**Issue by tzongw** [micro/go-micro#1068]
An existing conn will be reused or closed when calling `pool.Get`, but what about conns belong to an died node? Since a node died, we will never call `pool.Get` with that address

**Comment by vtolstov** [comment]
seams reasonable
so we need to watch registry inside pool and when node dies remove from pool all connections to that node

**Comment by asim** [comment]
No. Nodes have a ttl, we simply have to remove anything where the ttl has been exceeded and the connection was not used.

**Comment by vtolstov** [comment]
@asim this is slowly, but can work too.

**Comment by asim** [comment]
If a connection returns an error we throw it away, so in the case of dead nodes after one failed call the connection leaves the pool, in the case of nodes no longer called, they will be discarded after a ttl period if the pool removes them. It seems the simplest path without abusing the registry.

**Comment by vtolstov** [comment]
yes, you right.

**Comment by asim** [comment]
Was fxe

**Comment by AprilFiv** [comment]
> If a connection returns an error we throw it away, so in the case of dead nodes after one failed call the connection leaves the pool, in the case of nodes no longer called, they will be discarded after a ttl period if the pool removes them. It seems the simplest path without abusing the registry.

That means we should accept an error at least once, right?
