### ISSUE TITLE
codec/jsonrpc: Handle missing result key gracefully

### ISSUE THREAD

**Issue by thcyron** [micro/go-micro#107]
Unmarshalling the following panics because the result key is missing. I think it should gracefully handle all sorts of responses (also invalid or incomplete ones) from a service.

``` json
{"id":0,"error":null}
```

https://github.com/micro/go-micro/blob/dddcdc3/codec/jsonrpc/client.go#L92

**Comment by asim** [comment]
That is basically invalid json-rpc. It should probably not panic but you should also not be sending that.

**Comment by asim** [comment]
It's unlikely that I'll add panic handling in the codec itself. I think that's the wrong place for it. It should ideally be in the client.

**Comment by thcyron** [comment]
I don’t care where and how the check is done, I just don’t want my API gateway to crash/panic if a service sends malformed json-rpc responses.

**Comment by asim** [comment]
Helpful, cheers. I don't think anyone wants the gateway to panic. PRs always welcome.

**Comment by asim** [comment]
Here's a graceful catch all that should resolve. https://github.com/micro/go-micro/commit/02481c4446f2bb8c9e59f6ba81fd37ab0b0c9b34

Close issue if satisfied. Thanks.

**Comment by thcyron** [comment]
What’s wrong with just checking result is not nil before dereferencing?

https://github.com/micro/go-micro/compare/master...thcyron:check-result

**Comment by asim** [comment]
Also worth doing. `recover()` just covers anything that will cause it to bomb out.

**Comment by thcyron** [comment]
Yep. I prefer to prevent it from panicking in the first place, but maybe we should do just both.

**Comment by asim** [comment]
https://github.com/micro/go-micro/commit/0190b1ab3a3e201c87dbc64f26043d102bdbb529

Done and done.

**Comment by thcyron** [comment]
👍
