### ISSUE TITLE
Why the broker of http does not have the same advertising parameters as "rpc_service".

### ISSUE THREAD

**Issue by Abson** [micro/go-micro#1072]
Like the title, I am using the go-micro in the docker and register the broker in the other container, but there is something confusing me is that I can't modify the broker registry address for discovery. But the parameter of "advertise" in rpc_service is available. So, there is something other solutions?

**Comment by skyjia** [comment]
@Abson 
```go
	if err := broker.Init(broker.Registry(r)); err != nil {
		log.Fatalf("Broker Init error: %v", err)
	}
```
Hope it helps.
