### ISSUE TITLE
One runs service and the other runs Client

### ISSUE THREAD

**Issue by Jokergz** [micro/go-micro#1073]
Hi,
Run service and client on the same computer, this works fine.
When I run service on one computer and Client on the other,
It does not work:
{"id": "go.micro.client", "code": 500, "detail": "service greeter: not found", "status": "Internal Server Error"}

Please tell me how to do it.

**Comment by skyjia** [comment]
@Jokergz Please make the client connected to the same registroy as the one which the server registered its service to. 
https://micro.mu/docs/framework.html#discovery
