### ISSUE TITLE
[BUG] web go get github.com/micro/go-micro # github.com/lucas-clemente/quic-go/internal/handshake ../../../../pkg/mod/github.com/lucas-clemente/quic-go@v0.14.1/internal/handshake/crypto_setup.go:433:40: not enough arguments in call to h.conn.GetSessionTicket         have ()         want ([]byte)

### ISSUE THREAD

**Issue by helloycboy** [micro/go-micro#1074]
**Describe the bug**

1. What are you trying to do?
2. What did you expect to happen?
3. What happens instead?

**How to reproduce the bug:**

If possible, please include a minimal code snippet here.

**Environment:**
Go Version: please paste `go version` output here
```
please paste `go env` output here
```

**Comment by helloycboy** [comment]
> **Describe the bug**
> 
> 1. What are you trying to do?
> 2. What did you expect to happen?
> 3. What happens instead?
> 
> **How to reproduce the bug:**
> 
> If possible, please include a minimal code snippet here.
> 
> **Environment:**
> Go Version: please paste `go version` output here
> 
> ```
> please paste `go env` output here
> ```

**Comment by nicolasfeoli** [comment]
Im having same issue here: 

- go version 1.13.5
- go env : GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/nicolasfeoli/Library/Caches/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/nicolasfeoli/go"
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/bb/1zb1ywv169n1fc1vszjzl4540000gn/T/go-build553186397=/tmp/go-build -gno-record-gcc-switches -fno-common"

**Comment by asim** [comment]
export GO111MODULE=on

And only do `go get` without the -u

**Comment by johnwoz123** [comment]
Did anyone find a solution?

**Comment by TheTeaParty** [comment]
Clear require() in go.mod those that are related to go-micro and do go get ./... again. Additionally you can clear go mod cache.
