### ISSUE TITLE
This problem persists when acquiring your dependencies。

### ISSUE THREAD

**Issue by helloycboy** [micro/go-micro#1077]
# github.com/lucas-clemente/quic-go/internal/handshake
../../../pkg/mod/github.com/lucas-clemente/quic-go@v0.14.1/internal/handshake/crypto_setup.go:433:40: not enough arguments in call to h.conn.GetSessionTicket
        have ()
        want ([]byte)

**Comment by PhantomMatthew** [comment]
Yes, I met the same problem that I go get go-micro.

**Comment by asim** [comment]
Please use go modules and do go get without the use of -u

**Comment by ricardojonathanromero** [comment]
I tried to use go get ./... and i have the same problem (I have implemented go modules) but I could solved it. I modified a privacy project but I could not update the project, so, I removed the dependency from the go.mod file and then executed go get again and it worked.

**Comment by athirah-yahya** [comment]
Having the same problem also here

**Comment by asim** [comment]
export GO111MODULE=on

go get github.co/micro/go-micro

**Comment by asim** [comment]
If you have run go get -u or changed go mod you will have problems

**Comment by brunowego** [comment]
Same here. Using `goenv` and go version is `1.13.5`. Fresh install in Catalina.

```
GO111MODULE=on go get github.com/micro/micro
```

```sh
/usr/local/go/1.13.5/pkg/mod/github.com/lucas-clemente/quic-go@v0.14.1/internal/handshake/crypto_setup.go:433:40: not enough arguments in call to h.conn.GetSessionTicket
	have ()
	want ([]byte)
```

**Comment by ankitjena** [comment]
> export GO111MODULE=on
> 
> go get github.co/micro/go-micro

This is not solving the issue. Still getting it
```
 github.com/lucas-clemente/quic-go/internal/handshake
../../../../../pkg/mod/github.com/lucas-clemente/quic-go@v0.14.1/internal/handshake/crypto_setup.go:433:40: not enough arguments in call to h.conn.GetSessionTicket
        have ()
        want ([]byte)
```

**Comment by jakexks** [comment]
From a completely fresh state (e.g. `docker run --rm -it golang:1.13`) I can't reproduce the issue, both the latest release and master are go gettable:

```
$ docker run --rm -it golang:1.13
root@ffc72439b087:/go# export GO111MODULE=on
root@ffc72439b087:/go# go get github.com/micro/go-micro # gets 1.18.0
root@ffc72439b087:/go# go get github.com/micro/go-micro@master # gets master
```

It's likely at some point in your project you've either done go get -u or pulled in another package with a clashing dependency, which is inside your go.mod/sum now, leading to your error.

**Comment by ankitjena** [comment]
> It's likely at some point in your project you've either done go get -u or pulled in another package with a clashing dependency, which is inside your go.mod/sum now, leading to your error.

@jakexks yes. But how do I resolve the issue now?

**Comment by jakexks** [comment]
If it was just a mistake and not a clashing dependency you can delete go.sum, edit go.mod like [this previous comment](https://github.com/micro/go-micro/issues/1077#issuecomment-570887164) and try again. I can't troubleshoot your code for you!

**Comment by crazybber** [comment]
just following the <go mod> way. 
go get with <-u> will cause conflict.

**Comment by ankitjena** [comment]
Thanks @jakexks , that worked
