### ISSUE TITLE
[BUG] content-length wrong cause HTTP2  ERROR_PROTOCOL 

### ISSUE THREAD

**Issue by TSuanHM** [micro/go-micro#1079]
http1.1->micro api ->srv (grpc)

```
	header := make(map[string]string)
	if md, ok := metadata.FromContext(ctx); ok {
		for k, v := range md {
			header[k] = v
		}
	}
```

frontend request http1.1 header (key: Content-Length)  was put in backend request metadata directly，but  the content-length was changed
when I use micro with istio , the envoy (nghttp2 will verify content-length，then cause ErrCodeProtocol )

```
//here is nghttp2  integration-tests
func TestH2H1BadRequestCL(t *testing.T) {
	st := newServerTester(nil, t, noopHandler)
	defer st.Close()

	// we set content-length: 1024, but the actual request body is
	// 3 bytes.
	res, err := st.http2(requestParam{
		name:   "TestH2H1BadRequestCL",
		method: "POST",
		header: []hpack.HeaderField{
			pair("content-length", "1024"),
		},
		body: []byte("foo"),
	})
	if err != nil {
		t.Fatalf("Error st.http2() = %v", err)
	}

	want := http2.ErrCodeProtocol
	if res.errCode != want {
		t.Errorf("res.errCode = %v; want %v", res.errCode, want)
	}
}
```

**Comment by asim** [comment]
Do you know the source of where the content-length is added back in?

**Comment by TSuanHM** [comment]
> Do you know the source of where the content-length is added back in?

github.com/micro/go-micro/util/ctx

`func FromRequest(r *http.Request) context.Context {
	ctx := context.Background()
	md := make(metadata.Metadata)
	for k, v := range r.Header {
		md[k] = strings.Join(v, ",")
	}
	return metadata.NewContext(ctx, md)
}
`

**Comment by asim** [comment]
Stale
