### ISSUE TITLE
Can anyone explain how client.Retries(int) works

### ISSUE THREAD

**Issue by ghost** [micro/go-micro#1084]
"github.com/micro/go-micro/client"

to test it out should I need to kill-server and check whether client is re-trying 3 times.
just want to know the actual use case

**Comment by vtolstov** [comment]
how much services do you have, that provides data for such client?

**Comment by ghost** [comment]
I have 3 servers

**Comment by asim** [comment]
By default there is 1 request and 1 retry. If you set retries to any number the client will attempt to retry the request in the case of a 408 or 500 error for that number of retries up till the timeout period.

**Comment by ghost** [comment]
Thank you!
