### ISSUE TITLE
rpc server/client

### ISSUE THREAD

**Issue by bohutang** [micro/go-micro#109]
Hi,

I found go-micro is very graceful, but how to use it as a normal rpc framework(like grpc) disable service discovery?
I can't find any more options to disable them.
Thanks.

**Comment by asim** [comment]
If you want to strip away that functionality then you need to use the client and server directly.

https://godoc.org/github.com/micro/go-micro/server
https://godoc.org/github.com/micro/go-micro/client

`client.CallRemote` allows you to call a particular address directly. `server.Start` can be used to start the server without registering with service discovery.

**Comment by bohutang** [comment]
Hello asim,

I like the micro.NewService and register style,it's simple,not every user want the consul, maybe they want a simple rpc.

**Comment by asim** [comment]
Micro is a pluggable framework for microservices. One of the key requirements of microservices is service discovery. If you do not want to use Consul you can use any number of Registry plugins in the  go-plugins repo https://github.com/micro/go-plugins. 

Micro does not look to provide standalone RPC with `micro.NewService`. Please refer to net/rpc, gorilla toolkit or other similar projects for that.

Thanks
