### ISSUE TITLE
Any way to select server node according to request data?

### ISSUE THREAD

**Issue by shisoft** [micro/go-micro#110]
Thank you for your great work on micro. It made tracking node status in a large cluster very easy.
I have noticed that selector in micro can be use for load balance in round robin, last connection, etc. But in my use case, I want to staticky dispatch requests from one user to one server according to it's user id. What's in my mind is to hash the user id and use the mod or DHT to determine what server to send the request. Usually, user id may appear in request.
In your [example](https://github.com/micro/go-micro/blob/master/examples/client/selector/selector.go) , I can't find anything related in Select function to get the request data.
Is there any alternative way for me to dispatch requests by their data?

Thanks

**Comment by asim** [comment]
Hey. The best way to do this is to write a Select Filter and pass it in as part of the call. The Filter allows you to keep the nodes you want before it moves on to something else. The Filter could basically throw away everything except the node you care about. Then round robin or random strategy will just always select the one node there.

The filter definition is `type Filter func([]*registry.Service) []*registry.Service`.

Here's an example filter that looks for service version.

```
func FilterVersion(version string) Filter {
    return func(old []*registry.Service) []*registry.Service {
        var services []*registry.Service

        for _, service := range old {
            if service.Version == version {
                services = append(services, service)
            }
        }

        return services
    }
}
```

And then the usage

```
client.Call(ctx, request, response, client.WithSelectOption(FilterVersion("1.0.0")))
```

If you are using proto generated code you can pass in client options to the methods there too.

**Comment by shisoft** [comment]
Just wondering. If client.NewRequest have already specified service, why I still need to iterate over the old registry.Service in the filter, not filtering nodes in a single registry.Service in the function?

**Comment by asim** [comment]
I'm not sure what you mean. client.NewRequest just creates an object that stores service name, request and content type. When you call client.Call the selector will use the registry to retrieve a list of services once then pass that in to any filters that are specified, each time passing a list that will be mutated by the filers.
