### ISSUE TITLE
micro service has not received all of subscribed messages

### ISSUE THREAD

**Issue by cesardeng** [micro/go-micro#1100]
Our services use micro and NSQ . There is a service: subscribe a topic, and then put it to the other two topic after processing (the logic is: put it to channel after receiving, then publish it after processing by goroutine).

Question:
When there are too many goroutines, we find that some messages are lost. From the nsqadmin, topic is empty, and the number is the correct , but the micro service has not received all of them (the  withmaxinflight is not set).

**Comment by vtolstov** [comment]
can you write easy reproducible test case? after that can you say docker image name for nsq for easy testing?

**Comment by vtolstov** [comment]
P.S. this issue must be in go-plugins repo. As nsq broker present in go-plugins repo

**Comment by asim** [comment]
Please move to go-plugins repo as specified
