### ISSUE TITLE
How can I use --profile command

### ISSUE THREAD

**Issue by ljxqxq** [micro/go-micro#1101]
I want to know micro api gateway cpu and memory stats .
so use `micro api ` command to start default API Gateway.
micro docs said this:
`--profile value                 Debug profiler for cpu and memory stats [%MICRO_DEBUG_PROFILE%]`

so, please tell me :
1. set goenv MICRO_DEBUG_PROFILE value is?
2. command `--profile` how can i use?

Thank u very much...

**Comment by asim** [comment]
https://micro.mu/docs/debugging.html

**Comment by ljxqxq** [comment]
Thank u a lot... @asim 
but i set environment variables like that:
`setx MICRO_DEBUG_PROFILE http`, and os is Windows 10.

Then,How can i start API Gateway command, i use command like that, but it not work:
`micro --profile=http --api_handler=rpc --api_namespace=go.micro.srv api`

no log printed to start a http server on :6060, so `http://localhost:6060` can not be requested...

Please help me , what's wrong with that?

**Comment by asim** [comment]
Not sure, but we're refactoring so will come back to it later
