### ISSUE TITLE
Web service doesn't work when using grpc instead of default rpc

### ISSUE THREAD

**Issue by pengrongbo** [micro/go-micro#1102]
I tried to use the grpc to replace the default rpc at the service layer, but the web service API returns the error as below, are there anything I need to configure?

"error": "{\"id\":\"go.micro.client.transport\",\"code\":500,\"detail\":\"malformed HTTP response \\\"\\\\x00\\\\x00\\\\x06\\\\x04\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x05\\\\x00\\\\x00@\\\\x00\\\"\",\"status\":\"Internal Server Error\"}"

**Comment by zqkgo** [comment]
make sure to use same transport

**Comment by pengrongbo** [comment]
@zqkgo thanks! it's fixed.

**Comment by doubleycn** [comment]
cl := grpc.NewClient()
使用这样的方式获取客户端。
