### ISSUE TITLE
Consul endpoint registration information is incorrect

### ISSUE THREAD

**Issue by bkrahmer** [micro/go-micro#113]
We are seeing an issue where the our micro dashboard is giving us endpoint information that isn't correct.  It's basically displaying camel-case parameters where they should be snake-case.

Example request protobuf message:

message ReserveRequest {
  string vehicle_id = 1;
  string journey_id = 2;
  sint32 ttl = 3;
}

Example of information that is registered in consul (I hit the consul catalog enpoint, hex-decoded it and unzipped it):

"values":[{"name":"VehicleId" ...

thanks,
brian

**Comment by bkrahmer** [comment]
Yeah, the way I did it on the java side was to use the FieldDescriptors and then get the name directly from the FieldDescriptor.  Doing it that way mirrors the original protobuf any way it is coded.

**Comment by asim** [comment]
This should address the issue but is only applicable for struct fields https://github.com/micro/go-micro/pull/114

**Comment by asim** [comment]
PR is merged.
