### ISSUE TITLE
Configure UnaryInterceptor for gRPC Service

### ISSUE THREAD

**Issue by jgrusewski** [micro/go-micro#1132]
Hi, 

I tried to find how I can add an UnaryInterceptor for a grpc service.
I cannot figure out how to do this? 

Can you provide me the right way?

**Comment by asim** [comment]
We support the grpc protocol but avoid leaking the abstraction. Please use go-micro wrappers.

**Comment by vtolstov** [comment]
for now we encourage users to use wrappers.
