### ISSUE TITLE
[BUG] web dashboard is ignoring registry_address settings

### ISSUE THREAD

**Issue by Napas** [micro/go-micro#1134]
**Describe the bug**

1. What are you trying to do?
I'm running a web dashboard in the Docker container and passing `--registry=service --registry_address="registry:8000" web`
2. What did you expect to happen?
I expect it to use `registry:8000` as the registry address
3. What happens instead?
```
Server register error: {"id":"go.micro.client","code":500,"detail":"connection error: desc = \"transport: Error while dialing dial tcp 127.0.0.1:8000: connect: connection refused\"","status":"Internal Server Error"}
```

**How to reproduce the bug:**

If possible, please include a minimal code snippet here.
```
docker run -it -p "8080:8082" micro/micro --registry=service --registry_address="registry:8000" web
```

**Environment:**
Go Version: please paste `go version` output here
I'm using official Docker image - 1.13 I presume.

**Comment by asim** [comment]
I dont understand. Whats running on 8000? Are you running it?

**Comment by Napas** [comment]
I am running a registry on the host "registry" and port 8000. Host "registry" resolves to an IP address which is not 127.0.0.1, but web dashboard trying to register to the 127.0.0.1.

**Comment by asim** [comment]
But it sounds like whatever is set is resolving it that way, so registry must be resolving to 127.0.0.1. Are you linking to the other container? I mean where is this host registry. This feels like a docker configuration issue more than a micro issue.

**Comment by Napas** [comment]
No, it's resolving correctly inside the container.

It looks like registry address is always overridden by the Advertise address (which is by default 127.0.0.0): https://github.com/micro/go-micro/blob/master/web/service.go#L59

**Comment by Napas** [comment]
🤦‍♂ `docker pull micro/micro` probably pulled an older version of the container.

`docker run -it micro/micro:v1.18.0 --registry=service --registry_address=registry:80 web` works as expected.

Sorry!
