### ISSUE TITLE
[BUG] unable to connect to service

### ISSUE THREAD

**Issue by m15ch4** [micro/go-micro#1137]
**Describe the bug**

1. I register service with:
```
func main() {
	repo := &Repository{}
	srv := micro.NewService(
		micro.Name("consignment"),
	)

	srv.Init()

	pb.RegisterShippingServiceHandler(srv.Server(), &service{repo})

	if err := srv.Run(); err != nil {
		fmt.Println(err)
	}
}
```
Client application try to call one of the remote functions but it returns error saying:

`2020-01-27 18:53:36.124720 I | Could not greet: {"id":"go.micro.client","code":500,"detail":"connection error: dial tcp: lookup \u003cnil\u003e: no such host","status":"Internal Server Error"}`

Additionally when I run `micro get service consignment` I get the following information about registered service
```
service  consignment

version 2020.01.27.18.54

ID      Address Metadata
consignment-c928f6e1-989a-4f9d-a5db-4b5d4a8c382e        <nil>:53156     protocol=mucp,registry=mdns,server=mucp,transport=http,broker=http

Endpoint: ShippingService.CreateConsignment
...truncated output...
```

What is interesting service is registered but IP address is set to <nil> and I think this could be a reason of error that client application returns. 

**Environment:**
go version go1.13.6 darwin/amd64
```
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/misza/Library/Caches/go-build"
GOENV="/Users/misza/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/misza/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/zn/9xnl_4jj3y95xsqdyk_70vz00000gn/T/go-build446172940=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

**Comment by vtolstov** [comment]
what environment used to run this app (local mac os x, or some cloud provider) ? Do you have some firewalls? can you provide info about ip addresses? (on linux run `ip a s`)

**Comment by vtolstov** [comment]
close as no response

**Comment by yexm** [comment]
> close as no response

i had occurred the same problem in k8s with the code that writed by go micro

**Comment by vtolstov** [comment]
@yexm create new issue and provide needed info like go-micro version, used registry and source code part that can reproduce the issue.

**Comment by liuaiyuan** [comment]
I also encountered this problem, MacOS
