### ISSUE TITLE
Using with flutter GRPC

### ISSUE THREAD

**Issue by winwisely99** [micro/go-micro#1152]
Do grpc services generated from go-micro work with grpc flutter ?

I ask because go-micro grpc was not standard grpc according to what I read a while ago and I can't find any examples of people using it with flutter.

**Comment by asim** [comment]
What's the expected interop with flutter? We use grpc-go internally so for all intents and purposes its the same.

**Comment by vtolstov** [comment]
if you generate grpc code based on proto you can able to connect to micro grpc service from generated client code. I'm do such stuff for python and it works fine

**Comment by winwisely99** [comment]
Thank you - all these responses help !!


Dart GRPC is very mature btw and i have been using standard golang GRPC with Dart GRPC and its been very smooth experience. Glad to hear with Python its also good.

Some Architectural blockers i see that mean that the full gamut of functionality might not be available for Clients. I would really like to hear peoples own thoughts on these worries i have ...

Will the Subscriptions work ? 
I ask because the Go-micro is an interesting beast in that NATS is wrapped under the hood but presented as a GRPC API. 

Also the lack of Load balancers and the reliance on the emergent Routing tables / DHT makes it very much NOT standard GRPC.  It seems to use QUIC to help make a Mesh / tunnel transport.

Probably a few other surprises i have missed.

Sp here is what i think might work to alleviate the above concerns for our project at least:

1. Server: Standard go-micro Micro Services in a DataCenter, but also on rasp PI's

2. Client Proxy: Use gomobile to make go-micro golang clients.  

- This talks over GRPC to to the GO-micro Servers.

3. Client GUI: Use Flutter with the gomobile. This BTW is very easy to do and many are doing this.

- Client GUI and Client Proxy talk to each other over a Flutter Channels. This is pretty standard stuff and well known and risk free. A bit of boiler plate but can be code generated easily.

- On Desktop we run the Client Proxy out of Process from the GUI. Not sure Yet but i think we can use an adaption of the Flutter Channels.

- On Rasp Pi we do exactly what we do on Desktop. Flutter GUI is foreground process and Client proxy is background Service ( always on ).

**Comment by asim** [comment]
All of these are valid and interesting ideas but one for the development repo under design/ideas
