### ISSUE TITLE
Removal of Mock client (github.com/micro/go-micro/client/mock)

### ISSUE THREAD

**Issue by crashdump** [micro/go-micro#1158]
Hello,

I noticed that the package `go-micro/client/mock` has been removed in go-micro v2.0.0 ([See commit](https://github.com/micro/go-micro/commit/a47ff65529234033dea02cd9ec4024734b8ff96a)).

Is there any plan to replace it with something similar? If not, is there a better approach for my cross-services tests?

Thanks,

**Comment by asim** [comment]
The mock client moved to go-plugins, you can still import it from there

**Comment by crashdump** [comment]
I completely missed that. Thank you!
