### ISSUE TITLE
RoundRobin

### ISSUE THREAD

**Issue by xizho10** [micro/go-micro#116]
Dear Asim，
     I am interesting this go-micro project. I find bug of roundrobin strategy algorithm in strategy.go , It always send to one node.

**Comment by asim** [comment]
If you look at the way the [Selector](https://github.com/micro/go-micro/blob/master/selector/selector.go#L15) works, it returns a Next function each time the selection is made. This is called per request and then the function is executed. If the request fails, the client will execute the function again to retrieve another node. When using the roundrobin strategy that will retrieve the next node in the list. This indexing doesn't however persist across requests so it ends up with the same node. Indexing would have to be managed outside the execution of the strategy so it could persist.

Example

```
func RoundRobin() func (services []*registry.Service) Next {
        // per service index
        var mtx sync.Mutex
        index := make(map[string]int)

        return func (services []*registry.Service) Next {
                var nodes []*registry.Node

                for _, service := range services {
                        nodes = append(nodes, service.Nodes...)
                }

                return func() (*registry.Node, error) {
                        if len(nodes) == 0 {
                                return nil, ErrNoneAvailable
                        }

                        mtx.Lock()
                        // get index for service
                        service := services[0].Name
                        i := index[service]

                        // get node
                        node := nodes[i%len(nodes)]

                        // increment and save index
                        i++
                        index[service] = i
                        mtx.Unlock()

                        return node, nil
                }
        }
}
```
