### ISSUE TITLE
Issue on example Pub - Sub Client

### ISSUE THREAD

**Issue by zean00** [micro/go-micro#117]
Just tried the example as it is for the client - server and they seems to work just fine, all message and request seems delivered to the server, but then I found some issue when I only run the pub - sub client and comment out the others

When I execute only `pub()` method, the server seems not picking up any message from client. But then if I add another call after the pub, then the server will pickup both the pub - sub message and the call request
`pub()`
`call(0)`

But then if I switch the sequence, the server will only pick up the call request, not the pub-sub message
`call(0)`
`pub()`

If I call the pub() twice, then the server will pickup the message but only once
`pub()`
`pub()`

I'm not sure whether the server code or the client code has the issue, or did I miss something here

**Comment by asim** [comment]
As mentioned in the Slack. Publishing is asynchronous and it's likely that the server is exiting before the message is acknowledged.
