### ISSUE TITLE
Config Source not using CLI flag default value [BUG]

### ISSUE THREAD

**Issue by diegoortizmatajira** [micro/go-micro#1171]
**Describe the bug**

1. What are you trying to do?
- Setting a custom flag using `micro.Flags` with a default value.
```
const expectedValue string = "flagvalue"
// Create a new service using the configuration settings
service := micro.NewService(
		micro.Flags(
			&cli.StringFlag{
				Name:    "flag",
				Usage:   "It changes something",
				EnvVars: []string{"flag"},
				Value:   expectedValue,
			},
		),
	)
```
- Adding CLI config source
- Reading from config and retrieve the flag default value ("flagvalue")

2. What did you expect to happen?
I expect to receive the flag default value ("flagvalue")

3. What happens instead?
Instead I'm receiving the default value provided by `config.Get("flag").String("default")`

**How to reproduce the bug:**

If possible, please include a minimal code snippet here.

clone the repo [https://github.com/diegoortizmatajira/go-micro-test](https://github.com/diegoortizmatajira/go-micro-test)

execute `go run main.go`

`INFO[0000] Expected value (flagvalue) Found value (default) `

**Environment:**
go version go1.13.7 linux/amd64

```
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/diegoortizmatajira/.cache/go-build"
GOENV="/home/diegoortizmatajira/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/diegoortizmatajira/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build254212204=/tmp/go-build -gno-record-gcc-switches"

```

**Comment by vtolstov** [comment]
i'll take this

**Comment by vtolstov** [comment]
please try go-micro master, also i'm add test case based on your example code
