### ISSUE TITLE
Can't rpc_call an another service with event handler context

### ISSUE THREAD

**Issue by hunyadvari-peter** [micro/go-micro#1172]
If handling a topic event, and using the context from it, the rpc call thinks its an another Micro-Topic event sending.

1. What are you trying to do?
Make an rpc call to an another service with context got from an event.
2. What did you expect to happen?
The rpc call to happen
3. What happens instead?
Nothing, we got. (I think we need to remove the Micro-Topic from response ctx headers, so we can reuse it for rpc call)

**How to reproduce the bug:**

Send an event with an app.
Service b got an event, and try to call service c with the context

**Environment:**
Go Version: 1.13.6

**Comment by vtolstov** [comment]
as i understand you try to use default server and default client and use go-micro before 2.0.0 ?

**Comment by vtolstov** [comment]
please, try latest micro master (go get github.com/micro/go-micro/v2@master )

**Comment by vtolstov** [comment]
close as fixed, if you have any issues, please write about it
