### ISSUE TITLE
Some problem when  use consul cluster

### ISSUE THREAD

**Issue by xizho10** [micro/go-micro#118]
When i try this command:
./micro --registry_address 192.168.0.197,192.168.0.196
 It will exit if connect first registry(192.168.0.197) fail. 
How  try to connect second registry if first fail?

--registry_address  Comma-separated list of registry addresses [$MICRO_REGISTRY_ADDRESS]

**Comment by asim** [comment]
If you look at the consul registry implementation, there's nothing currently configured to handle rotating addresses. Registering/Deregistering from different consul nodes in a cluster can have some strange side effects so rotating addresses isn't a simple thing.

**Comment by xizho10** [comment]
We still some problem when use consul:
How to prevent  single node failure of consul cluster ?
How Micro service continue work while the connecting node of consul cluster  killed ?

**Comment by asim** [comment]
There are a few options here. 
1. The first as mentioned is to implement a registry which rotates the addresses of the consul nodes. The Go library for consul does not support multiple addresses or highly available configuration on the client side. 
2. Configure the consul cluster behind some form of proxy which provides a fixed address to the client and will rotate the backends based on a healthcheck. Haproxy will work for that but if you're using kubernetes then it will provide this functionality to you via service loadbalancers.
3. Use the [cache](https://godoc.org/github.com/micro/go-micro/selector/cache) selector which maintains an in memory cache of anything retrieved from the registry. On failure of consul the micro services will continue to work by using the cache.
