### ISSUE TITLE
[FEATURE] add server reflection support for grpc server

### ISSUE THREAD

**Issue by vtolstov** [micro/go-micro#1181]
**Is your feature request related to a problem? Please describe.**
Add ability to use with micro grpc service standalone grpc tools like web ui or grpc curl

**Describe the solution you'd like**
https://github.com/grpc/grpc-go/blob/master/Documentation/server-reflection-tutorial.md#enable-server-reflection

**Additional context**
simple change, needs to investigate drawbacks

**Comment by vtolstov** [comment]
not so simple as looks before:
as we don't have standard grpc and have micro, we need to implement reflection server by providing
https://github.com/grpc/grpc-go/blob/master/reflection/grpc_reflection_v1alpha/reflection.proto
and have only one rpc for it
rpc ServerReflectionInfo(stream ServerReflectionRequest) returns (stream ServerReflectionResponse);
}

if we fill response with valid data all stuff works fine with it

**Comment by vtolstov** [comment]
mostly we need to do copy/paste https://github.com/grpc/grpc-go/blob/master/reflection/serverreflection.go

**Comment by asim** [comment]
Now that's interesting. I did not know that we could hack around the problem with this. An interesting solution. How much effort to do you think it is to add this by default to all services? We could add in server/grpc where we do extraction, have a reflection.go file for it?

**Comment by vtolstov** [comment]
I think that this is must be option to server. Because it adds additional handler to it. And also may be used to abuse it or something bad. Mostly we can add reflection.go file and slightly modify it for our use-case

**Comment by asim** [comment]
So `Reflection()` option in grpc server package to enable it?

**Comment by vtolstov** [comment]
yes, probably

**Comment by heisonyee** [comment]
Consider adding an option for exposing grpc.Server, it will help us do more about things, such as registering prometheus, reflection, health etc..

**Comment by vtolstov** [comment]
we don't plan to leak abstraction and expose grpc.Server

**Comment by danielzheng** [comment]
any updates for this feature?

**Comment by vtolstov** [comment]
no updates, i know how to do it, but not have free time

**Comment by k1ng440** [comment]
hey @vtolstov any luck on this yet?

**Comment by vtolstov** [comment]
yes, i have some stuff for grpc server, but don't know when i can pr something to go-micro.

**Comment by hellodudu** [comment]
So how do we mock a grpc call through cli in v3? I tried many ways but with no luck since grpc server didn't open `ServerReflection`.

**Comment by Vilsol** [comment]
Is there a reason this issue is closed? I don't see this implemented anywhere, or am I missing something? @vtolstov 

I tried using `grpc.Server()` and provide a pre-reflected server, but seems like it doesn't end up hooking the handler, which makes that method useless.

I think something as simple as allowing to "get" the internal server would suffice, or at least passing options for the constructed server object.

**Comment by vtolstov** [comment]
i'm close it as dont have time for support asim/go-micro
for my fork i found good solution - create proto for grpc reflection and implement it interface. also for this stuff protoc-gen-go-micro must be changed too
