### ISSUE TITLE
[BUG]does not contain package

### ISSUE THREAD

**Issue by nextpkg** [micro/go-micro#1182]
```bash
go get -u ./... 

# ........

cannot load github.com/micro/go-plugins/registry/etcdv3: module github.com/micro/go-plugins@latest found (v2.0.1+incompatible), but does not contain package github.com/micro/go-plugins/registry/etcdv3
```

**Comment by vtolstov** [comment]
don't do go get -u it updates all deps and always broken

**Comment by nextpkg** [comment]
> don't do go get -u it updates all deps and always broken

How shoud I do instead?

`go get -u github.com/micro/go-micro` is the same

**Comment by asim** [comment]
```go get github.com/micro/go-micro```

Remove the `-u`

**Comment by nextpkg** [comment]
> `go get github.com/micro/go-micro`
> 
> Remove the `-u`

After `go get github.com/micro/go-micro && go mod tidy`
It report:
```bash
vscs/kernel imports
	github.com/micro/go-plugins/registry/etcdv3: module github.com/micro/go-plugins@latest found (v2.0.1+incompatible), but does not contain package github.com/micro/go-plugins/registry/etcdv3
vscs/kernel imports
	github.com/micro/go-plugins/transport/utp: module github.com/micro/go-plugins@latest found (v2.0.1+incompatible), but does not contain package github.com/micro/go-plugins/transport/utp
vscs/kernel imports
	github.com/micro/go-plugins/wrapper/service: module github.com/micro/go-plugins@latest found (v2.0.1+incompatible), but does not contain package github.com/micro/go-plugins/wrapper/service
```

I had clean all my `go.mod` yet

**Comment by nextpkg** [comment]
> don't do go get -u it updates all deps and always broken

I added `replace` at the top of `go.mod` and it work!

```bash
replace github.com/coreos/etcd => github.com/coreos/etcd v3.2.28+incompatible
replace github.com/micro/go-plugins => github.com/micro/go-plugins v1.5.1
```

I find that `https://github.com/micro/go-plugins/releases` has confused tag like`wrapper/validator/v2.0.2 release`, why not v2.0.2

**Comment by vtolstov** [comment]
this is needed for v2 in case of submodules

**Comment by nextpkg** [comment]
> this is needed for v2 in case of submodules

Thank you for you  reply, maybe I should wait for v2 completed because `go.mod` depends on release tag like va.b.c

**Comment by vtolstov** [comment]
v2 already completed
