### ISSUE TITLE
I'm a new micro user。I have some problems. I don't know what to do。

### ISSUE THREAD

**Issue by arCzWw** [micro/go-micro#1190]
In the outer layer, I have a web service. I access the server through API, and then the server uses micro to access SRV to return results. Now I don't know how to access SRV with grpc. What should I do？

My service is like this
I want to use Python to call the method of **backend servic** with grpc. What should I do
![image](https://user-images.githubusercontent.com/60876909/74395088-5b538200-4e49-11ea-8635-edc447af0759.png)

**Comment by sim2github** [comment]
[https://github.com/micro/examples/greeter/api/gin](https://github.com/micro/examples/tree/c27eeb9d2dec1e3cbac0a5c0686d937c4d3036eb/greeter/api/gin)
