### ISSUE TITLE
[BUG] health error

### ISSUE THREAD

**Issue by uxgnaw** [micro/go-micro#1194]
**Describe the bug**
When i upgrade go-micro to 1.17.1, health sidecar get err: Code:500, Detail:"OK: HTTP status code 200; transport: missing content-type field

I debug this on go-micro and find the reason:  
rpc_server.go:
```

defer func() {
		// only wait if there's no error
		if gerr == nil {
			// wait till done
			wg.Wait()
		}

		// close all the sockets for this connection
		pool.Close()

		// close underlying socket
		sock.Close()

		// recover any panics
		if r := recover(); r != nil {
			log.Log("panic recovered: ", r)
			log.Log(string(debug.Stack()))
		}
	}()
```
gerr always have error when health call on 175 line: EOF or body closed by handler

**Comment by toujourser** [comment]
me too

**Comment by asim** [comment]
Use 1.18.0?

**Comment by toujourser** [comment]
> Use 1.18.0?

1.18.0 has the same problem

**Comment by asim** [comment]
This bug is filed in the wrong place if its related to the heath sidecar. Please file correctly.
