### ISSUE TITLE
Switching off Broker

### ISSUE THREAD

**Issue by janekolszak** [micro/go-micro#120]
Hi, great project! Thank you so much for providing this!

**Is there a way to completely switch off Broker?**

Thanks!

**Comment by asim** [comment]
You can swap out the broker with a mock one if need be. The current default implementation is a http broker which just leverages service discovery to register subscriber interest. It's not necessarily "on" unless you use it.

**Comment by janekolszak** [comment]
This works, thanks!

I jut don't want any unneeded opened ports, that's all
