### ISSUE TITLE
Why the consul is no longer the default registry?

### ISSUE THREAD

**Issue by chenyingdi** [micro/go-micro#1207]
@asim Hello, I am a Chinese user. I was going to build a project with micro service a week ago, and I knew Micro. I quickly realized that Micro is a fantastic framework, but it's a pity only a few people know Micro. Articles on our network also use consul as the default registry, then I knew that consul has been moved to go-plugins. I want to get the reason, _**because someone wrote that you found some bugs when use consul as the registry**_. Is it really?

**Comment by vtolstov** [comment]
may be, but we want to use etcd as registry. feel free to use consul via go-plugins
