### ISSUE TITLE
Proper way to stop the Service

### ISSUE THREAD

**Issue by janekolszak** [micro/go-micro#121]
I add go-micro to an existing micro service that already handles graceful closure.
It catches SIGTERM, waits for all calls to end and then terminates.

I integrate go-micro as a separate goroutine:

``` go
        //...
    // Handle go-micro
    go func() {
        err = model.Service.Run()
        if err != nil {
            panic(err)
        }
    }()
        //...
```

**What would be the proper way to close the Service and quit the Run() method?**

**Comment by asim** [comment]
This is an unsupported use case. The Service handles graceful exit itself. If you want Start/Stop semantics then use the Server within the service.

**Comment by janekolszak** [comment]
Is there any way to plug into Service's graceful exit and run some code upon SIGTERM?

**Comment by asim** [comment]
You can use the AfterStop option to do this. Please look at the godoc https://godoc.org/github.com/micro/go-micro

**Comment by asim** [comment]
If you would like to discuss this further please join the slack. This is usage rather than an issue.
