### ISSUE TITLE
[BUG] Infinite loop in rpc_server

### ISSUE THREAD

**Issue by TriAnMan** [micro/go-micro#1214]
There is an infinite loop in rpc_server using NATS as a transport when NATS broker goes down an NATS transport fails to reconnect.

Steps to reproduce:

Have such command:
```
package main

import (
	"fmt"
	"github.com/micro/go-micro/server"
	"github.com/micro/go-micro/transport"
	"github.com/micro/go-plugins/transport/nats"
	natsIO "github.com/nats-io/nats.go"
	"os"
)

func main() {
	natsOptions := natsIO.GetDefaultOptions()
	natsOptions.AllowReconnect = false // or wait for 2 minutes

	natsTransport := nats.NewTransport(
		transport.Addrs("192.168.56.101:4222"),
		nats.Options(natsOptions),
	)

	serverOptions := []server.Option{
		server.Address(":12345"),
		server.Transport(natsTransport),
	}
	rpcServer := server.NewServer(serverOptions...)

	if err := rpcServer.Start(); err != nil {
		fmt.Printf("%T, %s", err, err)
		os.Exit(1)
	}

	<-make(chan os.Signal, 1)
}
```

Launch NATS on 192.168.56.101:4222
Launch command.
Terminate NATS.
You will get an infinite loop like:
```
2020-02-17 20:21:25.745606 I | Transport [nats] Listening on :12345
2020-02-17 20:21:25.748529 I | Broker [http] Connected to [::]:53471
2020-02-17 20:21:25.885129 I | Registry [mdns] Registering node: go.micro.server-27d46f63-834b-40be-a0f9-1c9348c72593
2020-02-17 20:21:36.347707 I | Accept error: nats: connection closed
2020-02-17 20:21:37.347832 I | Accept error: nats: connection closed
2020-02-17 20:21:38.347956 I | Accept error: nats: connection closed
2020-02-17 20:21:39.348053 I | Accept error: nats: connection closed
2020-02-17 20:21:40.348130 I | Accept error: nats: connection closed
.......
.......
```

See more details in https://github.com/micro/go-micro/pull/1210

It will be nice if rpc_server had a callback or another way to control errors in underlying transport.

**Comment by TriAnMan** [comment]
@asim
> The problem should likely be solved by the NATS transport rather than the level up.

I guess that that any transport implementation can introduce such behavior.
For example in HTTP transport it can happens that you lose an interface you've serving on.

**Comment by vtolstov** [comment]
@asim i think that we need to detect underline transport errors  and be something smart like persistent errors and temporary (go can return such errors in some cases).
For example grpc code part:
```
 // micro: go ts.Accept(s.accept)                   
 go func() {                                        
   if err := g.srv.Serve(ts); err != nil {          
     log.Log("gRPC Server start error: ", err)      
   }                                                
 }()                                                
```
if listener is closed, Serve return error and we log it, but after that server "work" and not stopped..
