### ISSUE TITLE
Omit waiting for method response

### ISSUE THREAD

**Issue by janekolszak** [micro/go-micro#122]
I want to call a remote method but I don't need to wait for the response.

**How do I send such "signals" with go-micro?**

**Comment by asim** [comment]
This is what the broker is for. Asynchronous messaging. The RPC client deals with synchronous communication. If you do not want to wait for a response just fire the request in a go routine but the correct way would be to use the Publish method.

**Comment by janekolszak** [comment]
Can I Publish just to one service? (I want to use the client side load balancing. )

**Comment by asim** [comment]
Publish is a method which uses the broker. For only a single service to receive the message requires the use of a Queue which ensures messages are only sent to one subscriber. 

The client side load balancing you speak of is only for synchronous RPC communication.

**Comment by asim** [comment]
If you would like to discuss this further please join the slack. This is usage rather than an issue.
