### ISSUE TITLE
[BUG] Some json output data field got different (hump naming) from proto files

### ISSUE THREAD

**Issue by LLLLLancelot** [micro/go-micro#1221]
**Describe the bug**

1. What are you trying to do?
request through micro tool or http
2. What did you expect to happen?
get correct field name defined in the proto file
3. What happens instead?
in the json style output, some fields got transformed into hump naming

**How to reproduce the bug:**
Just call a service by http, it will happen. Besides, In the v2.1.0 of micro, this bug happens, while not found in old version.
If possible, please include a minimal code snippet here.
Here is my proto file:
```
message Model {
	int32 id = 1;
	string key = 2;
	string secret = 3;
	string ip_white_list = 4;
	string comment = 5;
	int32 member_id = 6;
        string create_datetime = 7;
        ...
}
```
and here is *.go file generated:
```
type Model struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Key                  string   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Secret               string   `protobuf:"bytes,3,opt,name=secret,proto3" json:"secret,omitempty"`
	IpWhiteList          string   `protobuf:"bytes,4,opt,name=ip_white_list,json=ipWhiteList,proto3" json:"ip_white_list,omitempty"`
	Comment              string   `protobuf:"bytes,5,opt,name=comment,proto3" json:"comment,omitempty"`
	MemberId             int32    `protobuf:"varint,6,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
        CreateDatetime       string   `protobuf:"bytes,7,opt,name=create_datetime,json=createDatetime,proto3" json:"create_datetime,omitempty"`
        ....
}
```
While i got result when doing request:
```
[nobody@iwala53 digifinex.micro]$ ./cores/micro call go.micro.srv.etscts UserApi.Query '{"key":"5b5e7b669dca0"}'
{
	"model": {
		"id": 55,
		"key": "5b5e7b669dca0",
		"secret": "d63e26ae39a9db7b676cf01a7cbd312405b5e7b66",
		"comment": "挖矿大大",
		"memberId": 121681,
		"createDatetime": "2019-05-30 10:43:50",
	}
}
```
you can see that the filed memberId and createDatetime have a Hump naming, that's seems not correct.
**Environment:**
Go Version: please paste `go version` output here
```
please paste `go env` output here
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/duanhaipeng/.cache/go-build"
GOENV="/home/duanhaipeng/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/data/vhosts/trade"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build276583482=/tmp/go-build -gno-record-gcc-switches"
```

**Comment by vtolstov** [comment]
please, provide full example of service, that can returns such data

**Comment by LLLLLancelot** [comment]
> please, provide full example of service, that can returns such data

func (e *UserApi) Query(ctx context.Context, req *etscts.QueryRequest, rsp *etscts.QueryResponse) error {
	log.Log("Received UserApi.Query request")
	var data models.IwalaApikey
	db := mysql_service.NewGorm()
	if err := db.First(&data, "`key` = ?", req.Key).Error; err != nil {
		return err
	}
	rsp.Model = dbModel2ProtoModel(&data)
	// 密钥解密
	if decodeSecret, err := utils.AesDecrypt(rsp.Model.Secret, conf.UserApiAesKey); err != nil {
		return err
	} else {
		rsp.Model.Secret = string(decodeSecret)
	}
	return nil
}

This is my handle service.

**Comment by LLLLLancelot** [comment]
> please, provide full example of service, that can returns such data

func (e *UserApi) Query(ctx context.Context, req *etscts.QueryRequest, rsp *etscts.QueryResponse) error {
log.Log("Received UserApi.Query request")
var data models.IwalaApikey
db := mysql_service.NewGorm()
if err := db.First(&data, "key = ?", req.Key).Error; err != nil {
return err
}
rsp.Model = dbModel2ProtoModel(&data)
// 密钥解密
if decodeSecret, err := utils.AesDecrypt(rsp.Model.Secret, conf.UserApiAesKey); err != nil {
return err
} else {
rsp.Model.Secret = string(decodeSecret)
}
return nil
}

type etscts.QueryResponse struct {
	Model                *Model   `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

This is my handle service.

**Comment by LLLLLancelot** [comment]
I found that if i just removed the tag field:
    ,json=ipWhiteList,
    ,json=createDatetime
all response will be lower_case naming, like in the proto file.

**Comment by vtolstov** [comment]
in proto you have [json_name="XXX"] you can specify needed stuff here and output json have such name
