### ISSUE TITLE
Is NATS really not support ACKs?

### ISSUE THREAD

**Issue by wudi** [micro/go-micro#1225]
https://github.com/micro/go-micro/blob/88457b812e7e69901dfef5e1fe55a4c0500ac654/broker/nats/nats.go#L65-L68

NATS support ACKs form official documents and examples. 

https://docs.nats.io/nats-concepts/acks
https://docs.nats.io/nats-concepts/reqreply
https://docs.nats.io/developing-with-nats/receiving/reply

**Comment by vtolstov** [comment]
yes, may be we need to fix that

**Comment by vtolstov** [comment]
Ok, what use for respond data? Empty string?
