### ISSUE TITLE
[BUG] Cannot install go-micro in Windows 10

### ISSUE THREAD

**Issue by nicoabie** [micro/go-micro#1226]
**Describe the bug**
Cannot install go-micro in Windows 10

1. What are you trying to do?
 go get github.com/micro/go-micro
2. What did you expect to happen?
go-micro is installed without errors
3. What happens instead?
The following errors are displayed in the console:
..\go\src\github.com\coreos\etcd\clientv3\auth.go:125:72: cannot use auth.callOpts (type []"github.com/coreos/etcd/vendor/google.golang.org/grpc".CallOption) as type []"go.etcd.io/etcd/vendor/google.golang.org/grpc".CallOption in argument to auth.remote.AuthEnable
..\go\src\github.com\coreos\etcd\clientv3\auth.go:130:74: cannot use auth.callOpts (type []"github.com/coreos/etcd/vendor/google.golang.org/grpc".CallOption) as type []"go.etcd.io/etcd/vendor/google.golang.org/grpc".CallOption in argument to auth.remote.AuthDisable
..\go\src\github.com\coreos\etcd\clientv3\auth.go:135:72: cannot use auth.callOpts (type []"github.com/coreos/etcd/vendor/google.golang.org/grpc".CallOption) as type []"go.etcd.io/etcd/vendor/google.golang.org/grpc".CallOption in argument to auth.remote.AuthStatus
..\go\src\github.com\coreos\etcd\clientv3\auth.go:140:152: cannot use auth.callOpts (type []"github.com/coreos/etcd/vendor/google.golang.org/grpc".CallOption) as type []"go.etcd.io/etcd/vendor/google.golang.org/grpc".CallOption in argument to auth.remote.UserAdd
..\go\src\github.com\coreos\etcd\clientv3\auth.go:145:144: cannot use auth.callOpts (type []"github.com/coreos/etcd/vendor/google.golang.org/grpc".CallOption) as type []"go.etcd.io/etcd/vendor/google.golang.org/grpc".CallOption in argument to auth.remote.UserAdd
..\go\src\github.com\coreos\etcd\clientv3\auth.go:150:86: cannot use auth.callOpts (type []"github.com/coreos/etcd/vendor/google.golang.org/grpc".CallOption) as type []"go.etcd.io/etcd/vendor/google.golang.org/grpc".CallOption in argument to auth.remote.UserDelete
..\go\src\github.com\coreos\etcd\clientv3\auth.go:155:122: cannot use auth.callOpts (type []"github.com/coreos/etcd/vendor/google.golang.org/grpc".CallOption) as type []"go.etcd.io/etcd/vendor/google.golang.org/grpc".CallOption in argument to auth.remote.UserChangePassword
..\go\src\github.com\coreos\etcd\clientv3\auth.go:160:104: cannot use auth.callOpts (type []"github.com/coreos/etcd/vendor/google.golang.org/grpc".CallOption) as type []"go.etcd.io/etcd/vendor/google.golang.org/grpc".CallOption in argument to auth.remote.UserGrantRole
..\go\src\github.com\coreos\etcd\clientv3\auth.go:165:80: cannot use auth.callOpts (type []"github.com/coreos/etcd/vendor/google.golang.org/grpc".CallOption) as type []"go.etcd.io/etcd/vendor/google.golang.org/grpc".CallOption in argument to auth.remote.UserGet
..\go\src\github.com\coreos\etcd\clientv3\auth.go:170:72: cannot use auth.callOpts (type []"github.com/coreos/etcd/vendor/google.golang.org/grpc".CallOption) as type []"go.etcd.io/etcd/vendor/google.golang.org/grpc".CallOption in argument to auth.remote.UserList
..\go\src\github.com\coreos\etcd\clientv3\auth.go:170:72: too many errors

**How to reproduce the bug:**

If possible, please include a minimal code snippet here.

**Environment:**
Go Version: go version go1.13.7 windows/amd64
```
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\ngallinal\AppData\Local\go-build
set GOENV=C:\Users\ngallinal\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\ngallinal\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=c:\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\ngallinal\AppData\Local\Temp\go-build712120278=/tmp/go-build -gno-record-gcc-switches
```
 
Posibly related issues: #1059 #851

I think it has to do with the fact that etcd was moved from coreos to go.etcd.io but don't know how to fix this.

**Comment by vtolstov** [comment]
please, recheck that you enable go modules via GO111MODULE=on or using go 1.13.
also , use v2 of go-micro via go get github.com/micro/go-micro/v2
