### ISSUE TITLE
Is it possible to setup service's name by command line parameter?

### ISSUE THREAD

**Issue by liweijian** [micro/go-micro#1238]
Is it possible to setup service's name by command line parameter? For example:

```
$ go run main.go -name demo1
```

Then will get:
```
2020-02-23 18:03:36  Starting [demo1] frozen
```

According the [micro.Flags example](https://github.com/micro/examples/blob/master/service/main.go):

```
service := micro.NewService(
	micro.Name("greeter"),
	micro.Version("latest"),
	micro.Metadata(map[string]string{
		"type": "helloworld",
	}),

	micro.Flags(cli.BoolFlag{
		Name:  "run_client",
		Usage: "Launch the client",
	}),
)

service.Init(
	micro.Action(func(c *cli.Context) {
		if c.Bool("run_client") {
			runClient(service)
			os.Exit(0)
		}
	}),
)
```

We could get command line's parameter as above, I've tried to get a string parameter by `cli.StringFlag`, but we had setup services' name by `micro.Name("greeter")` before `service.Init` been called.

I've tried to use Golang's default [flag](https://gobyexample.com/command-line-flags) package, but it seems that micro will override the **flag**.

I was wondering if there's any way to make it work?

**Comment by asim** [comment]
Use --server_name

**Comment by liweijian** [comment]
> --server_name

@asim Awesome thanks! You made my day!

**Comment by asim** [comment]
Are you guys using micro at Snap?

**Comment by liweijian** [comment]
> Are you guys using micro at Snap?

Sorry, I am not sure for this thing.

I found go-micro is really cool,  and took some time to learn about it in weekend.
