### ISSUE TITLE
Help Needed On Cookie setting

### ISSUE THREAD

**Issue by dinilv** [micro/go-micro#124]
Hello,

Can we add Custom cookies to *api.response like below ?

func (ad _Adserve) Search(ctx context.Context, req *api.Request, rsp *api.Response) error {
    rsp.Header = map[string]_api.Pair{"Cookie-id": {Key: "Cookie-id", Values: values}}
//other code goes

NB: Please add me to Slack Community and groups, for go-micro as well as micro , so that i can look into more codes 👍  
Email: dinil.vamanan@gmail.com

**Comment by asim** [comment]
The API will write whatever headers you pass back in the response. 

You can invite yourself to the slack via this link http://slack.micro.mu which is in the readme of this repo. Please direct future questions to the slack.
