### ISSUE TITLE
go-micro (v1.18.0), but does not contain package github.com/micro/go-micro/cmd

### ISSUE THREAD

**Issue by laredoer** [micro/go-micro#1245]
**Describe the bug**

1. What are you trying to do?
2. What did you expect to happen?
3. What happens instead?

**How to reproduce the bug:**

github.com/micro/go-grpc imports
  github.com/micro/go-plugins/client/grpc imports
        github.com/micro/go-micro/cmd: module github.com/micro/go-micro@latest found (v1.18.0), but does not contain package github.com/micro/go-micro/cmd

If possible, please include a minimal code snippet here.

**Environment:**
```
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/wule/Library/Caches/go-build"
GOENV="/Users/wule/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=" -mod="
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/wule/go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn"
GOROOT="/usr/local/go"
GOSUMDB="off"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/wule/work/nob-calorie/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/f3/bt3vnbd148b8lj8qw7_x6qww0000gn/T/go-build900886831=/tmp/go-build -gno-record-gcc-switches -fno-common"

```

**Comment by vtolstov** [comment]
don't use github.com/micro/go-grpc  as it stale, all stuff moved to go-micro repo (and cmd is in go-micro/config/cmd)

**Comment by vtolstov** [comment]
also you need to enable go modules support

**Comment by laredoer** [comment]
thanks
