### ISSUE TITLE
[BUG] Errors in 'readLoop' goroutines are not handled

### ISSUE THREAD

**Issue by atakanozceviz** [micro/go-micro#1255]
Errors should be handled in the following goroutines;
https://github.com/micro/go-micro/blob/b4a743898ee62b9cc8c56b154327668014162a8e/proxy/grpc/grpc.go#L108
https://github.com/micro/go-micro/blob/b4a743898ee62b9cc8c56b154327668014162a8e/proxy/mucp/mucp.go#L521

**Comment by vtolstov** [comment]
yeah, @asim what is preferred way - return error via channel and in outer loop handle it, or write log inside readLoop and close stream?

**Comment by asim** [comment]
Proxy is just acting as an intermediary so this is really down to the logic of the code. Errors need to be passed back and forth appropriately. Where there's a fatal error in some processing then it may need to be logged. 

Its a fairly complex thing so unless someone specifically has an issue thats not surfacing I'm not looking at it right now. I would welcome anyone who wants to test all the scenarios for the proxy.
