### ISSUE TITLE
How to disable base64 encoding when publishing messages through kafka broker?

### ISSUE THREAD

**Issue by hamster1979** [micro/go-micro#1274]
In https://github.com/micro/examples/blob/master/broker/producer/producer.go
I have added Content-Type to message header:
```
func pub() {
	tick := time.NewTicker(time.Second)
	i := 0
	for range tick.C {
		msg := &broker.Message{
			Header: map[string]string{
				"Content-Type": "application/json",
				"id":           fmt.Sprintf("%d", i),
			},
			Body: []byte(`{"test":"test"}`),
		}
		if err := broker.Publish(topic, msg); err != nil {
			log.Printf("[pub] failed: %v", err)
		} else {
			fmt.Println("[pub] pubbed message:", string(msg.Body))
		}
		i++
	}
}
```
Then I started with  
```
./broker --broker kafka --broker_address localhost:9092 --client http
```
In kafka I got message
```
"value": {
	"Header": {
		"Content-Type": "application/json",
		"id": "0"
	},
	"Body": "eyJ0ZXN0IjoidGVzdCJ9"
}
```
eyJ0ZXN0IjoidGVzdCJ9 is base64 encoded of "{"test":"test"}"
How can I avoid (change to json or plain text) Body base64 encoding?

**Comment by vtolstov** [comment]
You cant transfer json inside json. broker.Message marshaled to json, and in it body you have json.
You need either base64 that provided automatic by encoding/json package. Or write own codec for broker that do strconv.Quote/strconv.Unquote json in body of message.

**Comment by hamster1979** [comment]
> broker.Message marshaled to json, and in it body you have json.

That's not so!

Let we have
```
		msg := &broker.Message{
			Header: map[string]string{
				"Content-Type": "application/json",
				"id":           fmt.Sprintf("%d", i),
			},
			Body: []byte("Any text"),
		}
```
 broker.Message does not have an interface{} in the Body, only [ ]byte. When json.Marshal encodes an array of bytes, I get in message body something base64, not a json string! But I need to get JSON. I expected JSON.  How can i do this?  Or. How to publish a raw text message without encoding in a standard way? without writing your own encoder? Does Go-Micro have any way to do this?

**Comment by hamster1979** [comment]
Something like this will decide the problem
in broker.go
```
type Message struct {
	Header map[string]string
	Body   interface{} //[]byte
}
```
in rpc_server.go/subsciber.go/service.go
```
		body:        []byte(*msg.Body.(*string)),
```
after this can transfer body as object json, raw string or base64 byte array:
```
test := []byte("hello world")
msg := &broker.Message{
    Header: map[string]string{
        "Content-Type": "application/json",
    },
    Body: &test,
}
broker.Publish(topic, &test)
```
Body:"aGVsbG8gd29ybGQ="


```
test:="hello world"
...
```
Body:"hello world"



```
type MyStruct struct {
	Hello string `json:"hello"`
}
test:=MyStruct{Hello: "world"}
...
```
Body:"{"hello": "world"}"

**Comment by vtolstov** [comment]
in this case you have leak in abstraction. I can share you my rawjson codec that i'm use to transfer json without base64. But for such thing it uses escape symbols to allow json in body of broker message

**Comment by hamster1979** [comment]
Right abstractions is very good thing but without raw messaging all your broker publishing mechanism limited by "go-micro service" ->broker->"go-micro service" usage. But in real life applications we must use hundreds of third party Subscribers with its own message formats (such as Kafka Connect, Telegraf of TICK stack, Graphite and so on). This is a basic and general usage of broker messaging as for me. Does your rawjson codec with escapes will be allow to support the format kafka Influxdb Sink? Or I will be forced to write unescaped-formatting script on kafka-Sink side to get right json ?

**Comment by vtolstov** [comment]
https://gist.github.com/c7caa595498844d6d6d075b2ccbec7c1

**Comment by vtolstov** [comment]
I don't know about you formats. If you send micro compatible message like 
```
{
  "header": {

  },
  "body": ""
}
```
all must works fine

**Comment by hamster1979** [comment]
Workaround for me is using only Header for messaging, because Body has "only string" limitation.
```
{
  "Header": {
      "Content-Type": "application/json",
      "Body": {
             //json body
       }
  },
  "Body": ""  //Empty
}
```
