### ISSUE TITLE
How to implement msgp.Encodable

### ISSUE THREAD

**Issue by qAison** [micro/go-micro#128]
```
cli := client.NewClient(
    client.ContentType("application/msgpack"),
    client.Codec("application/msgpack", msgpackrpc.NewCodec),     
)

length := 4
req := client.NewRequest("rand", "Rand.Digit", length)
cli.Call(context.TODO(), req, reply)

```

return error in: https://github.com/micro/go-plugins/blob/master/codec/msgpackrpc/rpc.go#L56

Request body(value = 4):How to implement msgp.Encodable

**Comment by asim** [comment]
It apparently expects the message to be of type msgpack. Feel free to fix the codec so that it can take any type. Not core go-micro related so closing the issue. Open issue against go-plugins where the codec exists. Thanks.
