### ISSUE TITLE
go-micro grpc client creates a client connection to the given target ?

### ISSUE THREAD

**Issue by jw-devops-n** [micro/go-micro#1280]

**Comment by jw-devops-n** [comment]
pgrpc "google.golang.org/grpc"
rpcConnect, err = pgrpc.Dial("127.0.0.1:50053", pgrpc.WithInsecure())
or
//create client
	c := grpc.NewClient(
		client.Selector(static.NewSelector()),
		client.RequestTimeout(10*time.Second),
	)
	//use the generated client stub
	rpcService = localc.NewSipServerService("10.0.0.33:50053", c)

**Comment by vtolstov** [comment]
can you provide understandable question, what you need?

**Comment by jw-devops-n** [comment]
I need go-micro grpc client to request golang grpc server 。

**Comment by jw-devops-n** [comment]
But when I specified the request address,I will get:
[[{"id":"go.micro.client","code":500,"status":"Internal Server Error"}]]

**Comment by vtolstov** [comment]
You must use grpc transport in you client and server. If both of them is go-micro based, use client.Transport/server.Transport options to client and server
