### ISSUE TITLE
Slow requests

### ISSUE THREAD

**Issue by dzen-it** [micro/go-micro#129]
The are two microservices, the maximum load was about 500 requests per second. This is normal? How can I improve the performance?
[Example of code](https://github.com/dzen-it/testmicro)

**Comment by asim** [comment]
Each request does the following:
1. Lookup service discovery for service
2. Select node from service list
3. Create new connection to node
4. Make request
5. Teardown connection

If you want more performance you can use the caching selector https://godoc.org/github.com/micro/go-micro/selector/cache and client side connection pooling https://godoc.org/github.com/micro/go-micro/client#PoolSize. 

You can either do this in code or with flags like so:

```
--selector=cache # enables in memory caching of discovered nodes
--client_pool_size=10 # enables the client side connection pool
```

If you want to discuss further please join the slack.
