### ISSUE TITLE
[BUG] rpc远程主机无法连接

### ISSUE THREAD

**Issue by fucktx** [micro/go-micro#1301]
**Describe the bug**

type UserService struct {
	client proto.UserService
}
func NewUserService() *UserService {
	return &UserService{client: proto.NewUserService(commons.AuthApiNode,  client.DefaultClient)}
}

再生产的pb.micro文件中 
![image](https://user-images.githubusercontent.com/9391575/75954670-3655aa80-5eef-11ea-881b-41aef9c91326.png)
func (c *userService) QueryUserByName(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "User.QueryUserByName", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}
err这里直接抛出异常，但是以前版本v2版本生成这样的写法没问题
昨晚开始new项目后拉去代码，出现这个问题
异常信息:{"id":"go.micro.client.transport","code":500,"detail":"read tcp 10.0.75.1:59235-\u003e10.0.75.1:59219: wsarecv: An existing connection was forcibly closed by the remote host.","status":"Internal Server Error"}

If possible, please include a minimal code snippet here.

**Environment:**
go 1.13.1  windows
go-micro  v2.2.0

**Comment by vtolstov** [comment]
Please, use english - it is common language for all devs.
