### ISSUE TITLE
Support ETCD User&Password in Go Micro API Command Line

### ISSUE THREAD

**Issue by smalltangcai** [micro/go-micro#1314]
Currently, go micro api seems can't use etcd with username&password authentication as the registry. In my scenario, i want to reuse existing etcd, but as go micro api doesn't support etcd username&password, i can't use it. 

Is there any plan to support etcd basic auth in go micro api? it's quite demanding feature.

**Comment by ben-toogood** [comment]
Hey @smalltangcai this isn't in the short-term roadmap, we'd welcome a PR for this!

**Comment by smalltangcai** [comment]
@ben-toogood thx for your quick response. Does it mean that currenlty all micro commands don't support any registry authentication?

**Comment by xpunch** [comment]
I've this issue too, I used the etcd.Auth("github.com/micro/go-micro/v2/registry/etcd") registry.Option to do the auth.
`go
service := micro.NewService()
service.Options().Registry.Init(etcd.Auth(username, password))
`
Currently, there is no general interface for registry authentication, not all kinds of registry need authentication. So maybe need to abstract the authentication interface for registries.

**Comment by asim** [comment]
We'll reassess flag parsing soon
