### ISSUE TITLE
{"id":"go.micro.client","code":500,"detail":"connection closed","status":"Internal Server Error"}

### ISSUE THREAD

**Issue by fengpf** [micro/go-micro#1318]
1、 go version
go version go1.13.8 darwin/amd64
2、go-micro v2@v2.2.0
3、etcd -version
etcd Version: 3.3.8
Git SHA: GitNotFound
Go Version: go1.10.3
Go OS/Arch: darwin/amd64

**Comment by Kuri-su** [comment]
need more info plz

**Comment by heshiyingx** [comment]
I had the same problem
