### ISSUE TITLE
[BUG] can not set web and api namespace by command

### ISSUE THREAD

**Issue by mint-studio** [micro/go-micro#1329]
I create a micro service , and execute below command in terminal window :
   micro web --namespace mg.core.web
but the result namespace is default go.micro.web

// Terminal console as below

C:\Hayden\02.Develop\03.Temp\mg.core\github.com\mint-studio\mg.core\service\user>micro web --namespace=mg.core.web
2020-03-11 17:36:23 HTTP API Listening on [::]:8082
2020-03-11 17:36:23 Starting [service] go.micro.web
2020-03-11 17:36:23 Server [grpc] Listening on [::]:62178
2020-03-11 17:36:23 Registry [mdns] Registering node: go.micro.web-0f1a20a3-f04d-4068-ad29-5cfc7670892c

I hope to change the default namespace 'go.micro.web' to 'mg.core.web', but the command has no effect, I try to set environment MICRO_NAMESPACE=mg.core, it dose not work yet.

**Environment:**

Go Version: GO 1.14
Windows Version: win10

**Comment by mlboy** [comment]
the environment name is MICRO_WEB_NAMESPACE

**Comment by asim** [comment]
The output does not reflect the namespace. The service name has not changed. We can make it change but its not something we've currently configured.
