### ISSUE TITLE
[BUG] repeated code

### ISSUE THREAD

**Issue by ipiao** [micro/go-micro#1339]
**Describe the bug**
repeated code in serve/rpc_router.go lines 539-560

**Comment by ipiao** [comment]
![image](https://user-images.githubusercontent.com/17923206/76596471-3da53580-6539-11ea-8fcd-fdb310c0ff9a.png)

**Comment by ipiao** [comment]
// check whether the handler is a pointer
			if handler.reqType.Kind() == reflect.Ptr {
				req = reflect.New(handler.reqType.Elem())
			} else {
				req = reflect.New(handler.reqType)
				isVal = true
			}

			// if its a value get the element
			if isVal {
				req = req.Elem()
			}

			if handler.reqType.Kind() == reflect.Ptr {
				req = reflect.New(handler.reqType.Elem())
			} else {
				req = reflect.New(handler.reqType)
				isVal = true
			}

			// if its a value get the element
			if isVal {
				req = req.Elem()
			}

**Comment by vtolstov** [comment]
thanks!
