### ISSUE TITLE
[FEATURE] Support to work with external Service Mesh

### ISSUE THREAD

**Issue by liemle3893** [micro/go-micro#1347]
**Is your feature request related to a problem? Please describe.**
Currently there are no document about how to combine/integrate with external Service Mesh such as Istio, Consul. When we first develop application, Service Mesh may not a case but when application growth, some may wish to disable Internal Service Mesh and use external service mesh.

Internal Service Mesh or Cross Cutting Concerns (CCC) is what we already have in go-micro.

**Describe the solution you'd like**
When create new Client, support a way to disable all internal CCC and accept service address instead of service name. Eg: 
- With Istio service address may be: greeting.development.srv.local:8080
- With Consul service address may be: localhost:8080

P/s: I'm not deploy any real application, but I see no document about integrate with Service Mesh so just wan to rise it.

**Comment by asim** [comment]
Service mesh operates transparently in the context of micro. If you do not want service discovery use the static selector or static router. Otherwise make calls with CallOption set with address.
