### ISSUE TITLE
How to get real remote_addr.

### ISSUE THREAD

**Issue by LLLLLancelot** [micro/go-micro#1363]
Before asking, please check if your question has already been answered: 

1. Check the documentation - https://micro.mu/docs/
2. Check the examples and plugins - https://github.com/micro/examples & https://github.com/micro/go-plugins
3. Search existing issues

Hi, I can get correnct client addr from my service when requests are delivered through service[micro proxy] by pick it from metadata, below is my code.
```
p,ok := metadata.FromContext(ctx)
if ok {
    log.Infof("recv request from: %s", p["Remote"])
}
```
but when the requests are delivered from service[micro api] or service[micro web]. I can only get the addr of service[micro api] or service[micro web].The real addr is not visable. I wonder how to get real client ip by anyhow.
Thank you, hope you can help me.

**Comment by x1nchen** [comment]
You can use  nginx or openresty to get the real ip and then add it to http header, micro api will pass the header to micro service.

example

1. nginx site config

```
    location / {
        proxy_set_header HTTP-X-REAL-IP $remote_addr;
        proxy_pass http://micro-api:8080;
    }
```

2. micro api gets the header and store it into metadata

3. service or middleware gets the ip from metadata

```go
md, ok := metadata.FromContext(ctx)
if ok {
    callerAddress = md["X_REAL_IP"]
    ctx = context.WithValue(ctx, "Address", callerAddress)
}
```

**Comment by asim** [comment]
You can pull "Remote" from the metadata. The server fills in this information to signify where the remote connection is from. 

@x1nchen please do not answer where you do not have the info.

**Comment by x1nchen** [comment]
> You can pull "Remote" from the metadata. The server fills in this information to signify where the remote connection is from.
> 
> @x1nchen please do not answer where you do not have the info.

Okay.
