### ISSUE TITLE
[FEATURE] grpc service can't be as a normal micro service

### ISSUE THREAD

**Issue by AWaterColorPen** [micro/go-micro#1376]
**Is your feature request related to a problem? Please describe.**
I am using micro grpc service. when I update the package from v1 to v2, I find that grpc service is different with normal micro service. 
*micro service* uses [service interface](https://github.com/micro/go-micro/blob/master/service.go) and 
[options struct]https://github.com/micro/go-micro/blob/master/options.go

*grpc service* uses [service interface](https://github.com/micro/go-micro/blob/master/service/service.go) and 
[options struct]https://github.com/micro/go-micro/blob/master/service/options.go

they are not same interface and struct. 
so that *grpc service* can not gain latest FEATURE from micro `options/service` code change

**Describe the solution you'd like**

I would like to enable all micro feature for grpc service.
If not, it is hard for me to work my project with micro

**Additional context**

**Comment by vtolstov** [comment]
by default go-micro v2 uses grpc service inside it.
onle grpc transport must be set, to communicate with it via grpc from non go-micro services.

**Comment by AWaterColorPen** [comment]
In my case, I have a lot of services. Some are go-micro services and others are not. So that, I have to use  *grpc service* and hope *grpc service*  can gain latest FEATURE as *micro service*

**Comment by vtolstov** [comment]
So you need to add grpc transport to be used by services

**Comment by AWaterColorPen** [comment]
oh, thanks.

**Comment by AWaterColorPen** [comment]
oh, thanks. I found that micro start service with

**Comment by AWaterColorPen** [comment]
oh, thanks. I found that micro v2 start service with `grpc` by default. 
```
2020-03-25 22:22:53  level=info Starting [service] greeter
2020-03-25 22:22:53  level=info Server [grpc] Listening on [::]:59406
2020-03-25 22:22:53  level=info Registry [mdns] Registering node: greeter-59b3e2cc-a707-4fec-9b0b-be740a3a4643
```

**Comment by AWaterColorPen** [comment]
micro v1 start service with `http` by default
