### ISSUE TITLE
github.com/micro/go-micro/v2/client 504 Gateway Timeout

### ISSUE THREAD

**Issue by flanchegong** [micro/go-micro#1377]
Before asking, please check if your question has already been answered: 

build command-line-arguments: cannot load github.com/micro/go-micro/v2/client: module github.com/micro/go-micro/v2/client: reading https://athens.azurefd.net/github.com/micro/go-micro/v
2/client/@v/list: 504 Gateway Timeout

**Comment by vtolstov** [comment]
do you have go modules enabled and go bigger when 1.12 ?

**Comment by vtolstov** [comment]
i think that this is mostly problem with go mod proxy
