### ISSUE TITLE
add call option for proxy, make proxy can be used dynamically

### ISSUE THREAD

**Issue by hb-chen** [micro/go-micro#1389]
**Is your feature request related to a problem? Please describe.**

Sometimes only part of the traffic needs to pass through the proxy. I think we can add a CallOption, make proxy can be used dynamically.

**Describe the solution you'd like**
simple code, or CallOption first.
```go
	// get proxy
	if prx := os.Getenv("MICRO_PROXY"); len(prx) > 0 {
		service = prx
	} else if len(opts.Proxy) > 0 {
		service = opts.Proxy
	}
```

**Additional context**

**Comment by asim** [comment]
Not implementing at this time
