### ISSUE TITLE
[BUG]Error generating template project for protobuf

### ISSUE THREAD

**Issue by xgaxpp** [micro/go-micro#1392]
**Describe the bug**
I created a new project, via the command line micro new, and then through the command line protoc --proto_path =. --Go_out =. --Micro_out = .proto / user / user.proto generate protobuf files.
Service.Server () in xx.RegisterUserHandler () in main.go reports an error, like this:
Cannot use 'service.Server ()' (type "github.com/micro/go-micro/v2/server".Server) as type" github.com/micro/go-micro/server".Server Type does not implement 'server.Server' as some methods are missing: Handle (Handler) error, I found that always introduced in main.go is github.com/micro/go-micro/v2. And introduced in protobuf is github.com/ micro / go-micro / server, so hope you can get the solution.
and also. These words come from Google Translate.
**Environment:**
Go Version: please paste `go version` output here
```
go version go1.14 darwin/amd64

libprotoc 3.11.4
```
```
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/hulk/Library/Caches/go-build"
GOENV="/Users/hulk/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/hulk/go"
GOPRIVATE=""
GOPROXY="https://goproxy.io"
GOROOT="/usr/local/Cellar/go/1.14/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.14/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/lm/jn0gk8f52t343mg4_d5ml7wm0000gn/T/go-build622709679=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

**Comment by crazybber** [comment]
- update your micro protoc tool :
```
go get github.com/micro/protoc-gen-micro/v2
```
- make sure all package only depended on v2

- clean other go-micro and micro mod  except v2 from mod file.

**Comment by xgaxpp** [comment]
> * update your micro protoc tool :
> 
> ```
> go get github.com/micro/protoc-gen-micro/v2
> ```
> 
> * make sure all package only depended on v2
> * clean other go-micro and micro mod  except v2 from mod file.

thank you,This method solved the problem

**Comment by Xuzan9396** [comment]
Haha, I found the answer
