### ISSUE TITLE
Bad calls in Kubernetes package

### ISSUE THREAD

**Issue by kynrai** [micro/go-micro#14]
When trying to build a service, the build process fails with the following error. This appears to be from the latest commit.

github.com/myodc/go-micro/registry/kubernetes
../../../myodc/go-micro/registry/kubernetes/kubernetes.go:41: not enough arguments in call to c.client.Services(c.namespace).List
../../../myodc/go-micro/registry/kubernetes/kubernetes.go:78: not enough arguments in call to c.client.Services(c.namespace).List
../../../myodc/go-micro/registry/kubernetes/watcher.go:69: not enough arguments in call to svi.List

**Comment by kynrai** [comment]
I believe this commit broke the List call in kubernetes as they add in fields.

https://github.com/kubernetes/kubernetes/commit/647aa1bc8cef005c01b2c7e966e2bc0d81998e30

**Comment by asim** [comment]
Fixed. Thanks.
