### ISSUE TITLE
feature request: support "deregister_critical_service_after" for consul 0.7+

### ISSUE THREAD

**Issue by zjx20** [micro/go-micro#142]
@asim consul 0.7 introduced a new option for automatically deregistering unhealth nodes, which seems to be useful. Would you consider to support it?

Quote from https://github.com/hashicorp/consul/blob/v0.7.0/CHANGELOG.md:
> **Automatic Service Deregistration**: Added a new `deregister_critical_service_after` timeout field for health checks which will cause the service associated with that check to get deregistered if the check is critical for longer than the timeout. This is useful for cleanup of health checks registered natively by applications, or in other situations where services may not always be cleanly shutdown. [GH-679]

**Comment by asim** [comment]
The change for this was added yesterday. It's the last commit https://github.com/micro/go-micro/commit/c289f6acaa54cc07079762681ead39bc23a91dc4

**Comment by zjx20** [comment]
My apology, I should have checked the latest code first :(

**Comment by asim** [comment]
No worries. Appreciate the request to include that feature, its pretty critical given stale nodes can pile up.
