### ISSUE TITLE
go.etcd.io/etcd migration?

### ISSUE THREAD

**Issue by nicocesar** [micro/go-micro#1433]
https://github.com/micro/go-micro/blob/45ee5e9ad18bb993cb6ff7963744e908f4a50e15/registry/etcd/etcd.go#L16

I'm bumping into issues like
https://github.com/etcd-io/bbolt/issues/211

Is it possible that the import lines should all be replaced from github.com/coreos/etcd to go.etcd.io/etcd ...? since it seams that there is some import conflicts with those projects

**Comment by nicocesar** [comment]
This is my proposed solution basically.

```
cd ~/go/src/github.com/micro/go-micro
find -name *.go -exec perl -p -i -e 's@github.com/coreos/etcd@go.etcd.io/etcd@g' {} \;
go mod tidy
```

**Comment by asim** [comment]
We're using go modules so this shouldn't really be an issue. The reason we can't move is because the etcd concurrency package still references the old path.

**Comment by nicocesar** [comment]
Are you sure of this ....? 
My very small example is the following https://github.com/nicocesar/tokenplay

please make sure that you start from scratch (as in rm ~/go/{src,pkg} ) and you use go 1.14 with modules on 

```
$ go version
go version go1.14.1 linux/amd64
$ env | grep GO
GO111MODULE=on
```

this gave me the following result:
```
$ make build 
protoc --proto_path=/home/nico/go/src:. --micro_out=. --go_out=. proto/tokenplay/tokenplay.proto
/home/nico/go/src: warning: directory does not exist.
go build -o tokenplay-srv *.go
# github.com/coreos/etcd/clientv3/balancer/picker
../../go/pkg/mod/github.com/coreos/etcd@v3.3.18+incompatible/clientv3/balancer/picker/err.go:37:44: undefined: balancer.PickOptions
../../go/pkg/mod/github.com/coreos/etcd@v3.3.18+incompatible/clientv3/balancer/picker/roundrobin_balanced.go:55:54: undefined: balancer.PickOptions
# github.com/coreos/etcd/clientv3/balancer/resolver/endpoint
../../go/pkg/mod/github.com/coreos/etcd@v3.3.18+incompatible/clientv3/balancer/resolver/endpoint/endpoint.go:114:78: undefined: resolver.BuildOption
../../go/pkg/mod/github.com/coreos/etcd@v3.3.18+incompatible/clientv3/balancer/resolver/endpoint/endpoint.go:182:31: undefined: resolver.ResolveNowOption
make: *** [Makefile:12: build] Error 2

```

**Comment by vtolstov** [comment]
because they not released fixed version
after redhat acquire coreos etcd continually breaks things

**Comment by asim** [comment]
The simplest thing you can do

- Check out go-micro
- Run your command
- Run go test -v ./...

If it compiles and tests pass submit a PR

**Comment by nicocesar** [comment]
For the record: commit 8282e781e46062c98c9cf8feaf1c015d4259d026, test wont pass with my proposed change. (as @asim pointed out.)

I'm closing this ticket because it seems that is a bigger problem in the ecosystem, and not a simple search and replace quick fix.

Thanks for the time taken to explain me this.
