### ISSUE TITLE
[BUG]应该需要改成mhttp.WithRegistry(s.opts.Registry),

### ISSUE THREAD

**Issue by yuanzhangcai** [micro/go-micro#1436]
https://github.com/micro/go-micro/blob/8282e781e46062c98c9cf8feaf1c015d4259d026/web/service.go#L271

应该需要改成mhttp.WithRegistry(s.opts.Registry),

**Comment by crazybber** [comment]
@asim @vtolstov @ben-toogood   we can close this now.
