### ISSUE TITLE
pass default http headers via metadata from api gateway

### ISSUE THREAD

**Issue by vtolstov** [micro/go-micro#1443]
api gateway needs to pass via metadata kv ttp headers to underlining services.
Mostly this fields contains:
* Host
* X-Forwarded-Host
* Forwarded
* X-Forwarded-For
* X-Forwarded-Proto
* Authorization
* Origin
* Content-Type

**Comment by vtolstov** [comment]
it already filled in api/handler/rpc
may be in other handler this is not needed...

**Comment by asim** [comment]
The helper method ctx.FromRequest deals with this

**Comment by asim** [comment]
What we need is to set X-Forwarded headers because they don't normally exist

**Comment by vtolstov** [comment]
As i see now, this X-Forwarded stuff is not relevant for rpc handler. It always run as http handler and detect source ip is work for middleware. As it can be in X-Real-Ip or X-Forwarded-For or Forwarded and other cases.
