### ISSUE TITLE
"micro api" getting error "...accept4: too many open files..." after usage for a while

### ISSUE THREAD

**Issue by tomogoma** [micro/go-micro#146]
## Issue

After running micro api for some time all new requests to the api stop being served.
The logs yield the following message:

```
2017/01/13 19:05:19 http: Accept error: accept tcp [::]:8080: accept4: too many open files; retrying in 1s
```

## SetUp

I'm running `micro api` command as a systemctl service on an Ubuntu 16.04 server with 1GB RAM and 2GB swap space ...together with consul `consul agent -dev -advertise=127.0.0.1` (also as a systemctl service) with 4 microservices (no redundancy) behind the setup.

This is the first time I'm experiencing the issue after running the setup for nearly a month. Restarting the 'service' seems to solve the problem.

**Comment by asim** [comment]
Please file the issue against the relevant project https://github.com/micro/micro

**Comment by tomogoma** [comment]
Thank you @asim . I've filed it at https://github.com/micro/micro/issues/85
