### ISSUE TITLE
API Gateway and Web Gateway http host header -> service mapping

### ISSUE THREAD

**Issue by discount-elf** [micro/go-micro#1464]
I am trying to accomplish the following:

user -> web gateway (`micro web`) 
-> service (signup.example.com)
-> service (accounts.example.com)

I would like to do the request mapping based on the http header hostname, hostname = service name.

It does not appear that I can accomplish this with the options provided via the web command. However utilizing `micro api --handler http --resolver host` looks like it should work but alas it does not and I lose the websocket proxy. Additionally the web command doesn't allow me to specify an index, I would like to not serve the dashboard on /, and serve something else.

I was unable to find any documentation on implementing my own gateway utilizing go-micro. Any pointers on how to accomplish the above would be helpful.

**Comment by vtolstov** [comment]
you can try to look at https://github.com/micro/go-micro/blob/master/api/router/router_test.go
this is example how write own api gateway and combine it with grpc service.
