### ISSUE TITLE
Any way to use go-micro with fabio

### ISSUE THREAD

**Issue by ipfans** [micro/go-micro#147]
[fabio](https://github.com/eBay/fabio) is a fast, modern, zero-conf load balancing HTTP(S) router for deploying microservices managed by consul. It used "urlprefix-" tag to identify the service path or domain.

I noticed that go-micro also support to set Metadata to service register. But all metadata will be encode. So any way I can register service with tags spec with ```go-micro/registry```?

**Comment by asim** [comment]
Easiest way would be to write your own consul registry plugin that conforms to fabio's encoding format in consul. Otherwise there's no integration support via the default consul registry. Although considering micro has its own zero-conf API gateway, not sure why fabio would be needed.

**Comment by pauldub** [comment]
Also it is pretty easy to query micro registry within fabio.
