### ISSUE TITLE
service.Service and micro.Service

### ISSUE THREAD

**Issue by crazybber** [micro/go-micro#1473]
service.Service https://github.com/micro/go-micro/blob/master/service/service.go#L10
micro.Service https://github.com/micro/go-micro/blob/master/micro.go#L16

they have compatible signature  and **same with option**

should we unify  these interface to [go-micro/service/service.go](https://github.com/micro/go-micro/blob/master/service/service.go) or you guys have other design consideration and why  ?

@asim

**Comment by asim** [comment]
We will unify but haven't decided on the right approach. Maybe using import . Or aliasing

**Comment by crazybber** [comment]
a preview PR proposed  , https://github.com/micro/go-micro/pull/1484  which discussion can go  from

**Comment by crazybber** [comment]
talking will be followed up in PR: https://github.com/micro/go-micro/pull/1484
