### ISSUE TITLE
Etcd Watcher Nil pointer Exception

### ISSUE THREAD

**Issue by printfcoder** [micro/go-micro#1481]
https://github.com/micro/go-micro/blob/7f8b35e295e60fb077db48542c7d2dd657ad3f79/registry/etcd/watcher.go#L69

reappear:

1. run micro api 

2. run any micro  app then shut it off

the api will throw nil pointer exception:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x49bf18e]

goroutine 114 [running]:
github.com/micro/go-micro/v2/registry/etcd.(*etcdWatcher).Next(0xc00000e080, 0x5385418, 0x55696c0, 0xc00000e080)
        /Users/me/workspace/go/pkg/mod/github.com/micro/go-micro/v2@v2.4.1-0.20200403140722-7f8b35e295e6/registry/etcd/watcher.go:69 +0x22e
github.com/micro/go-micro/v2/registry/cache.(*cache).watch(0xc00027d7a0, 0x55696c0, 0xc00000e080, 0x0, 0x55696c0)
        /Users/me/workspace/go/pkg/mod/github.com/micro/go-micro/v2@v2.4.1-0.20200403140722-7f8b35e295e6/registry/cache/cache.go:405 +0xad
```

**Comment by x1nchen** [comment]
I can not reproduce this issue on master branch of https://github.com/micro/micro just now.

**Comment by asim** [comment]
Cannot be reproduced

**Comment by lcp8474140** [comment]
I have the save problem.
1.use cache 
2.use etcd registry
3.when a service is down. it panic. because the ev.PrevKv is nil

**Comment by lcp8474140** [comment]
I know the reason, it will panic when use lower version of etcd
