### ISSUE TITLE
How to initialize a handler 

### ISSUE THREAD

**Issue by jbrodriguez** [micro/go-micro#15]
What to do if some variables, structs need to be initialized before any calls are made ?

They shouldn't be initialized in the handler function, for optimization purposes.

I'm not finding a way to do it, except for using the golang init function

Any other ideas ?

```
package handler

import (
    "log"

    "golang.org/x/net/context"
)

type Handler struct {}

var test = "not set"

func init() {
    test = "initialized"
}

func (h *Handler) Work(ctx context.Context, req *handler.Request, rsp *handler.Response) error {
    log.Printf("Received Handler.Work request: %v", req)

    // do something
    log.Printf("test=%s", test)

    return nil
}

```

**Comment by crackcomm** [comment]
[(example)](https://github.com/myodc/go-micro/blob/master/examples/server/main.go)

``` Go
type Handler struct {
    test string
}
```

``` Go
server.Handle(
    server.NewHandler(
        &Handler{test: "initialized"},
    ),
)
```

**Comment by jbrodriguez** [comment]
Thank you @crackcomm , but what if I need to run some code to initialize the variables (rather than a static initialization as in the example) ?

**Comment by crackcomm** [comment]
Then use a function.

``` Go
package handler

type Handler struct {
    // ...
}

// New - Constructs a new Handler.
func New(opts interface{}) *Handler {
    // do the stuff (dialing database probably does not belong here)
    return &Handler{}
}

```

``` Go
server.Handle(
    server.NewHandler(handler.New("initialized")),
)
```

**Comment by asim** [comment]
Łukasz's above example works fine for this. Alternatively you can use the sync package Once type https://golang.org/pkg/sync/#Once.Do. There's no clean one time startup initialisation as of yet. It was purposely kept out to keep things simple at first and see where the use cases came in for other things. 

I think we'll potentially add the notion of before/after functions for start, stop and handler requests.

**Comment by jbrodriguez** [comment]
ok, thanks @crackcomm and @asim !
