### ISSUE TITLE
ignore if query parameter is empty

### ISSUE THREAD

**Issue by santoshkowshikhr** [micro/go-micro#1503]
Hi Guys,

I am using go-micro frame work to build an microservice. Can anyone help me how to continue with the request if the query parameter is empty?

**Main:**
func main() {
	log.Println("Starting")
	service := web.NewService(
		web.Name("ms.api"),
		web.Address(":8081"),)
	if err := service.Init(); err != nil {
		log.Fatal(err)
	}

	cl = list.NewListService("ms.list", client.DefaultClient)

	ing := new(List)
	wc := restful.NewContainer()

	ws := new(restful.WebService)
	ws.Consumes(restful.MIME_XML, restful.MIME_JSON, restful.MIME_OCTET).
		Produces(restful.MIME_JSON).
		Path("/services/list")

	ws.Route(ws.GET("/env/{env}/type/{type}").To(ing.GetList))

	wc.Add(ws)
	service.Handle("/", wc)

	if err := service.Run(); err != nil {
		log.Fatal(err)
	}
}

**My Function:**
func (ing *List) GetList(req *restful.Request, rsp *restful.Response) {
	log.Println("Get List")
	env := req.PathParameter("env")
	type := req.PathParameter("type")
	**max := req.QueryParameters("max")**
	**sort := req.QueryParameters("sort")**
}

Here **max** and **sort** are my parameters from the URL. If both the value are passed then the URL is processed and no issues there. Suppose the parameter max or sort is not passed the code breaks and does not respond. I need help to understand is there a way i can make these parameters not mandatory? if either of them is not passed my service should process the URL request.

**Comment by x1nchen** [comment]
Are you using this framework https://github.com/emicklei/go-restful ? You can provide a minimal reproducible code or add the error information where "the code breaks and does not respond".

BTW,  I read the source code of go-restful, if the parameter max or sort is not passed, max and sort will be `[]string{}`

```go
max := req.QueryParameters("max")
sort := req.QueryParameters("sort")
```

**Comment by asim** [comment]
This seems like a go-restful issue rather than a micro issue
