### ISSUE TITLE
[BUG] env crashed: cannot append two different types (map, string)

### ISSUE THREAD

**Issue by marvinliu1** [micro/go-micro#1525]
**Describe the bug**
import "github.com/micro/go-micro/v2/config/source/env"
/*
I have 2 built-in sys env variables in win10, they are:
userdomain=my_pc_name
userdomain_roamingprofile=my_pc_name
*/
1. What are you trying to do?
   I was trying to load the environment variables from my windows 10
2. What did you expect to happen?
   Env variables should get loaded
3. What happens instead?
   It will throw an error when processing the 2nd variable userdomain_roamingprofile: 
   **cannot append two different types (map, string)**
How to reproduce the bug:

If possible, please include a minimal code snippet here.

    line #52 in   github.com/micro/go-micro/v2/config/source/env/env.go 
		if err := mergo.Map(&changes, tmp); err != nil {
			return nil, err
		}
   Note:
    **&changes** already have one key value pair: [userdomain] -> my_pc_name
    when trying to merge the 2nd one like [userdomain] -> [ [roamingprofile] -> my_pc_name ] into 
    the first one, 
    it will throw the generic error because it would not be able to merge [map[string]interface{}] into 
    map[string]string

Go Version: please paste `go version` output here
    github.com/micro/go-micro/v2 v2.4.0
    go version go1.14 windows/amd64

**Comment by x1nchen** [comment]
not easy to handle this issue. we can discard the key userdomain and keep userdomain_roamingprofile, then the result is 

```json
"userdomain": {
	"roamingprofile":       "my_pc_name"
},
```

or the other way

```json
"userdomain": {
        "_v": "my_pc_name",
	"roamingprofile":       "my_pc_name"
},
```

**Comment by domwong** [comment]
@marvinliu1 @x1nchen I see this behaviour only with the latest version, 0.3.9 of mergo. If you stick with the one per the go-micro go.mod file which is 0.3.8 it will not throw an error. 

With version 0.3.8 it will succeed with the last write winning - e.g. in your case it will be userdomain -> roamingprofile -> my_pc_name

**Comment by asim** [comment]
Closing as resolved based on mergo version.
