### ISSUE TITLE
[BUG] github.com/micro/go-micro/v2/util/log.Logf error

### ISSUE THREAD

**Issue by x-mark** [micro/go-micro#1528]
**Describe the bug**
When I use  "github.com/micro/go-micro/v2/util/log.Logf" the format not be decode.

**Fix**
at source code

https://github.com/micro/go-micro/blob/3ce2ab88f553bf490a8af54da670315c014cd130/util/log/log.go#L120

maybe `nlog.DefaultLogger.Logf` replace ` nlog.DefaultLogger.Log`

**Comment by vtolstov** [comment]
please, don't use that path. we moved to github.com/micro/go-micro/v2/logger

**Comment by vtolstov** [comment]
mostly i think that we drop this util/log dir in next major release
