### ISSUE TITLE
allow to include "raw" tags in consul, not just encoded metadata

### ISSUE THREAD

**Issue by DimShadoWWW** [micro/go-micro#153]
I will use https://github.com/containous/traefik as reverse proxy to access my services
if you use consul's catalog as configuration backend, some parameters should be customized as tags: [consul-catalog-backend](https://github.com/containous/traefik/blob/7d830279542e317eb773122d0f2ab8c445f2a85b/docs/toml.md#consul-catalog-backend)
for example: 

> traefik.enable=false    (to enable/disable access to the registered service from outside the network, using traefik)
> traefik.backend.loadbalancer=drr (to modify the load balancer in traefik)

in go-micro the tags in consul are encoded metadata, is there a way to include this "raw" tags??

I tried adding a Tag field (and functions.. taking Metadata as template to make the changes) in some structs .. and using the field in registry/consul_registry.go without the encode part ... but it didn't work
the tags can be seen in in service.Init() (go-micro/service.go) but in registry/consul_registry.go Tags is empty .. I could not find where it was lost

**Comment by DimShadoWWW** [comment]
I created a go-micro's plugin with support for raw tags in [go-micro-consul-traefik](https://github.com/DimShadoWWW/go-micro-consul-traefik)
to create a raw tag just add "RAW-" before the tag in server_metadata:

> --server_metadata RAW-traefik.enable=true --server_metadata RAW-traefikackend.loadbalancer=drr

this will insert **traefik.enable=true**  and **traefikackend.loadbalancer=drr**  in consul's catalog as service's tags

**Comment by asim** [comment]
The default consul registry is built to operate within the micro ecosystem. We have our own "http proxy" for external access using the micro api which is one of the components of the micro toolkit https://github.com/micro/micro. 

The default consul registry is unlikely to change at this point. As you've done there, creating a consul plugin to suit your personal needs makes sense. Please use that registry as opposed to the built in one.

Thanks
