### ISSUE TITLE
Use the stdlib context

### ISSUE THREAD

**Issue by freman** [micro/go-micro#154]
Like this https://github.com/divisionone/protobuf/commit/169101f3839806f7a7a39d9192276a329deb45d8

my server_wrapper doesn't work so well because I use "context" not "golang.org/x/net/context"

**Comment by asim** [comment]
There are currently no plans to make this breaking change without finding a way that works seamlessly for the existing community of users who have significant numbers of services in production.

**Comment by freman** [comment]
Perhaps as a branch or a tag, it's something one could even automate.

**Comment by asim** [comment]
You need to look at the micro ecosystem itself to understand the extent of this change. Context is at the core of the Client/Server packages in go-micro. Go-micro is at the core of every single piece of software in the repository. All the go-plugins, the micro toolkit, all the micro services. And that's just the micro repo. Now imagine all the developers and companies currently using micro and their dependencies and their services. 

At the moment I'm not interesting in maintaining a separate state for this. I may introduce some sort of Go build related change to enforce at 2.0. We'll see.

**Comment by freman** [comment]
We've kind of landed on using go-micro at the heart of our future plans.

I've knocked up a script that lets me track your repos swapping out context for stdlib (you can see the results here: https://github.com/divisionone/go-micro/commit/ef5f89274296566157387f99a6d26605eabbfc4f)

I don't suppose you'd be willing to add some webooks on push so it can be fully automatic?

edit: maybe a new github user? micro-stdlib? :D
