### ISSUE TITLE
[BUG] Micro API fails on streaming endpoint unexpected nil error

### ISSUE THREAD

**Issue by OGKevin** [micro/go-micro#1540]
**Describe the bug**

1. What are you trying to do?
Run micro api gateway and call a streaming endpoint
2. What did you expect to happen?
Success, actual response
3. What happens instead?
```
{
    "code": 500,
    "detail": "grpc: client streaming protocol violation: get <nil>, want <EOF>",
    "id": "go.micro.client",
    "status": "Internal Server Error"
}
```

**How to reproduce the bug:**
`micro version 2.0.0`
` micro api --address :8085 --namespace some.ns --handler rpc`
`http localhost:8085/my/streaming/endpoint`

If possible, please include a minimal code snippet here.
```
       ctx, cancel := context.WithCancel(ctx)
	ch, errCh := data.GetSomeData(ctx, cancel, s.db, s.service)

	for {
		select {
		case <-ctx.Done():
			stream.Close()
			return nil
		case err := <-errCh:
			return err
		case msg := <-ch:
			if msg == nil {
				return nil
			}
			err := stream.Send(msg)
			if err != nil {
				cancel()
				for len(ch) > 0 {
					<-ch
				}
				return errors.InternalServerError(s.service.Name(), err.Error())
			}
		}
	}
```
**Environment:**
Go Version: please paste `go version` output here
```
go version go1.13.1 darwin/amd64
```

**Comment by asim** [comment]
How are you calling the API and what do you expect back? The api was no made for streaming rpc. The micro proxy is used for gRPC if thats what you're looking for.

**Comment by OGKevin** [comment]
> How are you calling the API
> http localhost:8085/my/streaming/endpoint

>what do you expect back

A JSON list with the options, so I expect the api gateway to wait until the streaming stops and spits out one big JSON repose I guess. 

> The api was no made for streaming rpc. 

Thats not mentioned here https://micro.mu/docs/api.html 😔 I have a service that has both streaming and non streaming endpoints and I want to expose these with a JSON api. So instead of building my own little GRPC to JSON service in front of it, I thought I  would use API gateway 😕. 

> The micro proxy is used for gRPC if thats what you're looking for.
According to https://micro.mu/docs/proxy.html the proxy has a different purpose. I want e.g. a react app for example to be able to call streaming endpoints via API gateway. Non streaming endpoints indeed work fine.

**Comment by OGKevin** [comment]
Worst case scenario I have to implement the same method twice, one streaming and one not streaming.

**Comment by asim** [comment]
I will cc in @vtolstov to look at the above

**Comment by vtolstov** [comment]
@OGKevin this can be possible with api/handler/rpc can you share full example with you service and generated files, to easy guide you?

**Comment by OGKevin** [comment]
@vtolstov the server side code for the streaming method is shared in the issue body, is that not enough ? What extra code do you need exactly ? 

The following is the GRPC service that has the streaming method.
```
func (s *DataHandler) GetData(ctx context.Context, _ *store.Null, stream store.Data_DataStream) error {
	ctx, cancel := context.WithCancel(ctx)
	ch, errCh := data.GetSomeData(ctx, cancel, s.db, s.service)

	for {
		select {
		case <-ctx.Done():
			stream.Close()
			return nil
		case err := <-errCh:
			return err
		case msg := <-ch:
			if msg == nil {
				return nil
			}
			err := stream.Send(msg)
			if err != nil {
				cancel()
				for len(ch) > 0 {
					<-ch
				}
				return errors.InternalServerError(s.service.Name(), err.Error())
			}
		}
	}
}
```

So this service is running with the above method. 

Then, I boot up API getaway 

`micro api --address :8085 --namespace some.api.ns --handler rpc`

and call

`http localhost:8085/store/GetData`

and get the stream error.

The proto contains the following method:
`	rpc GetData(Null) returns (stream Data) {}`

>this can be possible with api/handler/rpc

Does this mean I have to implement my own little api gateway/service that sits in front of my GRPC service with this package ?

**Comment by vtolstov** [comment]
firstly update to go-micro and micro to v2.5.0, and we can check it.

**Comment by OGKevin** [comment]
Eh, upgrading from 2.3.0 to 2.5.0 seems to have broken something with registry, my service is no longer being recognised by micro api/web both also using mdns. Same for etcd. 

```go
	service := micro.NewService(
		micro.Name("store.data"),
		micro.Version(version.Version),
		micro.RegisterTTL(time.Second*10),
		micro.RegisterInterval(time.Second*8),
		micro.Flags(),
		micro.WrapHandler(opentracing2.NewHandlerWrapper(tracer)),
		micro.WrapSubscriber(opentracing2.NewSubscriberWrapper(tracer)),
		micro.WrapCall(opentracing2.NewCallWrapper(tracer)),
		micro.WrapClient(opentracing2.NewClientWrapper(tracer)),
	)
	service.Init()
	if err := service.Run(); err != nil {
		log.Fatal(err)
	}
```

Is there something im missing from upgrading ? Can't see anything obvious in the change logs. It looks like the log entry saying that it registered itself to the registry is also missing.

e.g. before 

```
2020-04-16 16:07:04  level=info service=store.data Registry [mdns] Registering node: store.data-7e63b078-15c7-4bc2-9dc1-342721a35b6c
```
and now in 2.5 this is gone 🤔

**Comment by OGKevin** [comment]
Interesting, it is there when I use micro in CLI 

```
$ micro list services                                                                                                                                                            
go.micro.api
go.micro.web
store.data
```

But micro api says it can't find it and its not listed in micro web 🤔

**Comment by OGKevin** [comment]
It seems also that micro api is not respecting the namespace passed to it 

```
micro --namespace store  api --address :8085 --namespace "store" --handler "rpc"
```

and then 

```
~ http localhost:8085/data/GetData                                                                                                                                                                       [20/04/16|16:23:36]
HTTP/1.1 500 Internal Server Error
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: Accept, Content-Type, Content-Length, Accept-Encoding, X-CSRF-Token, Authorization
Access-Control-Allow-Methods: POST, PATCH, GET, OPTIONS, PUT, DELETE
Access-Control-Allow-Origin: *
Content-Length: 94
Content-Type: text/plain; charset=utf-8
Date: Thu, 16 Apr 2020 14:23:41 GMT

{
    "code": 500,
    "detail": "service not found",
    "id": "go.micro.api",
    "status": "Internal Server Error"
}
```

always has the id go.micro.api instead of store in this case.

**Comment by asim** [comment]
The name has no reflection on the namespace it serves.

**Comment by OGKevin** [comment]
hmm but before the upgrade, the ID seemed to always be the namespace 🤔 (ill downgrade and reproduce to be sure)

**Comment by OGKevin** [comment]
Ok, correct, downgraded and it seems you're indeed correct @asim. Mybad.

However, downgrading back to micro 2.0.0, I can now call my service running on 2.5.0. However, streaming is still broken.

**Comment by OGKevin** [comment]
Until micro 2.4.0 I can call my service, micro 2.5.0 says it can't find the service.

**Comment by OGKevin** [comment]
Even more confusing, deployed everything to k8s. For some reason I can't seem to figure out, the streaming endpoints work in k8s. Using micro/micro:v2.0.0. However, using micro v2.0.0 on macOS fails on streaming endpoints 🤯.

**Comment by vtolstov** [comment]
run services with debug logging MICRO_LOG_LEVEL=debug
also please, try to disable firewall on you macos

**Comment by vtolstov** [comment]
i'm test locally with mdns registry (that enabled by default) and use go-examples/stream/server and don't have error about service not found.
in server i'm specify name like store.api.stream
and run micro with MICRO_LOG_LEVEL=trace ./micro --namespace store  api --address :8085  --handler "rpc" --type api  --namespace store
