### ISSUE TITLE
[BUG] env config, split on underscore problem

### ISSUE THREAD

**Issue by cuigang** [micro/go-micro#1544]
**Describe the bug**

1. What are you trying to do?
I'm trying to use config env source get the values of MICRO_REGISTRY and MICRO_REGISTRY_ADDRESS environment variable.

```
export MICRO_REGISTRY=etcd
export MICRO_REGISTRY_ADDRESS=etcd:2379
```

```
config.Load(
    env.NewSource(),
)
fmt.Println(conf["micro"])
fmt.Println("Registry:" + config.Get("micro", "registry").String(""))
```

2. What did you expect to happen?
I wish config.Get("micro", "registry").String("") return the MICRO_REGISTRY value is "etcd".

3. What happens instead?
config.Get("micro", "registry").String("") return the default value, empty string. 
Because micro_registry is a map.
```
registry:map[address:etcd:2379]]
Registry:
```
Could you have some advise, that I can get the right value of MICRO_REGISTRY, when the MICRO_REGISTRY and MICRO_REGISTRY_ADDRESS exist at the same time.
**Environment:**
go version go1.14.2 darwin/amd64

Thanks!

**Comment by asim** [comment]
You must return Map or call Get("micro", "registry", "address")
