### ISSUE TITLE
Can't redefine service's version

### ISSUE THREAD

**Issue by nextpkg** [micro/go-micro#1551]
micro version: 2.5.0
snippet: 
```go
func (c *cmd) Init(opts ...Option) error {
	for _, o := range opts {
		o(&c.opts)
	}
	if len(c.opts.Name) > 0 {
		c.app.Name = c.opts.Name
	}
	if len(c.opts.Version) > 0 {
		c.app.Version = c.opts.Version
	}
	c.app.HideVersion = len(c.opts.Version) == 0
	c.app.Usage = c.opts.Description
	c.app.RunAndExitOnError()
	return nil
}
```
I have no way to redefine `c.opts.Version` when I define the service `micro.NewService(...)`  unless I use `cmd.NewCmd(...)`

**Comment by kaisawind** [comment]
Maybe i have the same issue, i don't known how to print version when i define the service `micro.NewService(...)`.

**Comment by vtolstov** [comment]
for the last comment - use --version cmdline param.
for the first comment - get options via service.Options().Cmd.Options()
set version, and run init for cmd

**Comment by vtolstov** [comment]
may be we need simple way, don't know how this useful
