### ISSUE TITLE
[FEATURE] go-micro can not work well together with grpc-gateway

### ISSUE THREAD

**Issue by win5do** [micro/go-micro#1572]
My service need provide HTTP and GRPC API together, and swagger docs.

According https://github.com/micro/go-micro/issues/924#issuecomment-551258680, I generate  Micro and Gateway stub code to two diffenrent dirs.

Server start success, but i get these warning:
```text
WARNING: proto: file "XXX.proto" is already registered
A future release will panic on registration conflicts. See:
https://developers.google.com/protocol-buffers/docs/reference/go/faq#namespace-conflict
```

Any solution ?

**Comment by vtolstov** [comment]
Use go-micro/api/handler/rpc I'm provide example today inexamples repo. Please waiting if you have more questions

**Comment by asim** [comment]
You should generate your grpc-gateway or micro code in a separate repo for now. We have no good way of resolving these conflicts. Its naming related. You should also note that the generated code is in relation to what grpc generates.

**Comment by win5do** [comment]
proto file:
```proto
syntax = "proto3";

import "google/api/annotations.proto";

service Greeter {
    rpc Hello (Request) returns (Response) {
        option (google.api.http) = {
              post: "/v1/greeter/hello"
              body: "*"
        };
    }

    rpc Foo (Request) returns (Response) {
        option (google.api.http) = {
              get: "/v1/greeter/foo"
        };
    }

    rpc Bar (Request) returns (Response) {
        option (google.api.http) = {
              delete: "/v1/greeter/bar"
        };
    }
}

message Request {
    string name = 1;
}

message Response {
    string greeting = 2;
}
```

Makefile:
```Makefile
gen:
	protoc -I/usr/local/include -I. \
		-I${GOPATH}/src \
		-I${GOPATH}/src/googleapis \
		--micro_out=. \
		--go_out=plugins=grpc:. \
		--grpc-gateway_out=logtostderr=true:. \
                 --swagger_out=logtostderr=true:. \
		greeter.proto
```

I find out that only one func `RegisterGreeterHandler` redeclared in this block when generate into one dir.

Can we add a flag for protoc-gen-plugin  to  config generate code prefix to solve this problem?
Just like `Micro_RegisterGreeterHandler` or `Gw_RegisterGreeterHandler`.

I add a prefix manually, it's work well.

**Comment by win5do** [comment]
For `go-micro/api/handler/rpc`, I found that it seems that the  latest version support custom endpoint by `google.api.http`  option.

**Comment by win5do** [comment]
`protoc-gen-grpc-gateway` has implemented this function.

https://github.com/grpc-ecosystem/grpc-gateway/blob/ead3fc06c322daada4418abcbe00e07e5017e80a/protoc-gen-grpc-gateway/main.go#L28


new Makefile,  add flag `register_func_suffix=Gw`:
```Makefile
gen:
	protoc -I/usr/local/include -I. \
		-I${GOPATH}/src \
		-I${GOPATH}/src/googleapis \
		--micro_out=. \
		--go_out=plugins=grpc:. \
		--grpc-gateway_out=logtostderr=true,register_func_suffix=Gw:. \
        --swagger_out=logtostderr=true:. \
		greeter.proto
```

Hope helps.
This issue can be closed.
