### ISSUE TITLE
[BUG] 使用etcdv3做服务发现时，会出现数据竞争的问题。

### ISSUE THREAD

**Issue by yuanzhangcai** [micro/go-micro#1574]
https://github.com/micro/go-micro/blob/0a030f3d8ad82abc9a1cc5056e7ac406b55c28f8/logger/default.go#L130

WARNING: DATA RACE
Read at 0x00c0000ce340 by goroutine 71:
  github.com/micro/go-micro/v2/logger.(*defaultLogger).Options()
      /Users/zacyuan/go/pkg/mod/github.com/micro/go-micro/v2@v2.5.0/logger/default.go:130 +0x59
  github.com/micro/go-micro/v2/logger.(*Helper).Options()
      <autogenerated>:1 +0x78
  github.com/micro/go-micro/v2/logger.(*Helper).Options()
      <autogenerated>:1 +0x78
  github.com/micro/go-micro/v2/logger.V()
      /Users/zacyuan/go/pkg/mod/github.com/micro/go-micro/v2@v2.5.0/logger/level.go:125 +0x493
  github.com/micro/go-micro/v2/web.(*service).Run()
      /Users/zacyuan/go/pkg/mod/github.com/micro/go-micro/v2@v2.5.0/web/service.go:406 +0x447

**Comment by vtolstov** [comment]
please, try latest master, i think that we fix it already
