### ISSUE TITLE
[BUG]Get http://hosts:ip/v1/health/service/:service_name  return error:EOF by consul register plugin

### ISSUE THREAD

**Issue by MyDarkSun** [micro/go-micro#1593]
**Describe the bug**

1. What are you trying to do?
2. What did you expect to happen?
3. What happens instead?

**How to reproduce the bug:**

If possible, please include a minimal code snippet here.

**Environment:**
Go Version: please paste `go version` output here
```
please paste `go env` output here
```

I want get service from consul by using gRPC client, the call method get the service by http request (http://hosts:ip/v1/health/service/:service_name) from consul, the result is eof error when High concurrency.  This must be not appear. I find some times when high concurrency.

I get one solution that is set   http request object attribute Close  to True. 
That is off the http keep-alive.

**Comment by lockp111** [comment]
Consul has too many connets, you can update your consul config: http_max_conns_per_client=2000(default=200)

**Comment by vtolstov** [comment]
also, for consul related registry questions, file issue in go-plugins
