### ISSUE TITLE
[Urgent] consul_watcher.go:14: undefined: watch.WatchPlan

### ISSUE THREAD

**Issue by djensen47** [micro/go-micro#161]
Wanted to start by saying this project is great and we appreciate all the great work.

---
As of roughly 12 hours ago, go-micro can no longer be built. The hashicorp team refactored `WatchPlan` to `Watch` and now it breaks any and all usage of go-micro.

Here's the error:
```
vendor/github.com/micro/go-micro/registry/consul_watcher.go:14: undefined: watch.WatchPlan
```

This appears to be the commit that breaks go-micro:
https://github.com/hashicorp/consul/commit/d7e23857ad1943edeaa7e490e0642019d44812e6

---

I think it is imperative that any sort of dependency management should be added to the project but I'll add a new issue for that.

**Comment by asim** [comment]
PR has been merged. Closing this issue. Appreciate the comments and the fact that you're using the project.
