### ISSUE TITLE
Dependency management

### ISSUE THREAD

**Issue by djensen47** [micro/go-micro#162]
Given the recent issues #161 and #160 how would you feel about implementing dependency management? 

We use glide on our project but anything would might be better than nothing.

**Comment by asim** [comment]
I can appreciate the issues with dependency management and breakage but up to this point there hasn't been an elegant solution in the Go world that makes me inclined to use anything. By having no opinion on dependency management we let the users decide what works for them. If you use vendoring, go dep, glide or something else at a particular commit then you'll ensure you have working builds. 

I don't think we'll look to do any sort of dependency management in the near future (3-6 months) but always a topic of discussion. If it does come up, it's likely to be in the same style as cockroachdb which maintain a separate vendor repo https://github.com/cockroachdb/vendored. We'd likely version this along side micro/go-micro when the time came.

**Comment by djensen47** [comment]
I disagree but I guess I'm also disagreeing with the entire Go community. Coming from the Node.js world I'm finding the dependency situation in Go abysmal _but_ that's not for this library to solve. ¯\_(ツ)_/¯

If it is 3-6 months out, why not start looking at what's happening with the upcoming official `go dep`?

**Comment by asim** [comment]
I came from the java and ruby world so I understand the pain but there's nothing currently solving this issue in an elegant way. The solutions currently are brute force and very ugly resulting in either incomplete dependency management, clashes with the users tooling or very heavy vendored libs in the same repo which can make commits unintelligible. 

We'll revisit this at a later date but appreciate the comments.
