### ISSUE TITLE
deploy a micro srv in docker container

### ISSUE THREAD

**Issue by luxuze** [micro/go-micro#1620]
I run a micro service go.micro.srv.xxx and register it to Etcd , but the service address was wrong, how can I fix address problem with docker container.

**Comment by x1nchen** [comment]
I suppose the registered service address should be the ip of container network. 

A simple way to fix is let docker run in host mode.

**Comment by luxuze** [comment]
I had tried in docker host mode, but it also registered with a wrong ip

**Comment by x1nchen** [comment]
Are you using the docker on macos or windows? It will register the service using IP of virtual machine.

In this case, you can add the flags `server_address` and `server_advertise` of running command line of micro service.

Example, 

```bash
./test-srv --server_address=":9000" --server_advertise="192.168.1.2:9000"
```

and then makes docker expose the port mapping "9000:9000"

**Comment by luxuze** [comment]
Good job! thanks.
