### ISSUE TITLE
Codegen

### ISSUE THREAD

**Issue by joeblew99** [micro/go-micro#164]
I have worked up a code generator before and would like to write one for go micro.

I want to know requirements or status of thoughts on this.

Currently
1. No formal DSL. Just json for each stage.
2. Staged for each layer you are using. A top level code generator could be protobuf. The code generator can then run and output json describing the output. From then you could generate other things you need.

**Comment by asim** [comment]
Code generator for what? What would it generate? There's already grpc style code generation. We use a fork of protobuf with a micro plugin for that https://github.com/micro/protobuf

**Comment by asim** [comment]
I've also just realised this should not be opened as an issue. We use issues for bugs. Feel free to discuss in the Slack.

**Comment by joeblew99** [comment]
what i want to do is higher level code gen.
code gen the protobuf and everything else using go-micro.
