### ISSUE TITLE
{"id":"go.micro.client.transport", "code":500,"detail":"unexpected EOF","status":"Internal Server Error" }

### ISSUE THREAD

**Issue by Achle** [micro/go-micro#1642]
使用微服务是出现error：{"id":"go.micro.client.transport",
"code":500,"detail":"unexpected EOF","status":"Internal Server Error"
}，
其中服务发现采用的是consul，具体找不到问题原因。

**Comment by vtolstov** [comment]
please, use english lang

**Comment by Achle** [comment]
thank you. I have solved the problem.

**Comment by Achle** [comment]
i didn`t set the address of micro.
