### ISSUE TITLE
transport Content-Length header issue

### ISSUE THREAD

**Issue by liqiangno1** [micro/go-micro#1646]
I called a grpc service which is not written by micro framework。the Content-Length header will be transformed by micro grpc client。and then my grpc server will use this header to handle request。but the Content-Length  is not the actual one。 so my server throw the below exception。
```
Less data received than specified in the Content-Length header
```
Whether it is should be transport this header or not? same issue with Connection header.

My grpc service is written by .net core.

**Comment by asim** [comment]
Old stale issue. Is unclear to us whether this is still an issue.
