### ISSUE TITLE
network.pb.micro.go NetworkHandler and network interface  be similar

### ISSUE THREAD

**Issue by qiannianshaonian** [micro/go-micro#1649]
https://github.com/micro/go-micro/blob/master/network/service/proto/network.pb.micro.go
I don't know the essential difference between the two interface, which should be reusable
the interface is  NetworkHandler and network
type NetworkHandler interface {
	// Connect to the network
	Connect(context.Context, *ConnectRequest, *ConnectResponse) error
	// Returns the entire network graph
	Graph(context.Context, *GraphRequest, *GraphResponse) error
	// Returns a list of known nodes in the network
	Nodes(context.Context, *NodesRequest, *NodesResponse) error
	// Returns a list of known routes in the network
	Routes(context.Context, *RoutesRequest, *RoutesResponse) error
	// Returns a list of known services based on routes
	Services(context.Context, *ServicesRequest, *ServicesResponse) error
	// Status returns network status
	Status(context.Context, *StatusRequest, *StatusResponse) error
}

func RegisterNetworkHandler(s server.Server, hdlr NetworkHandler, opts ...server.HandlerOption) error {
	type network interface {
		Connect(ctx context.Context, in *ConnectRequest, out *ConnectResponse) error
		Graph(ctx context.Context, in *GraphRequest, out *GraphResponse) error
		Nodes(ctx context.Context, in *NodesRequest, out *NodesResponse) error
		Routes(ctx context.Context, in *RoutesRequest, out *RoutesResponse) error
		Services(ctx context.Context, in *ServicesRequest, out *ServicesResponse) error
		Status(ctx context.Context, in *StatusRequest, out *StatusResponse) error
	}
	type Network struct {
		network
	}
	h := &networkHandler{hdlr}
	return s.Handle(s.NewHandler(&Network{h}, opts...))
}

**Comment by asim** [comment]
This is code generated so not something we really comment on.
