### ISSUE TITLE
[BUG] go get -u and go build fail with "undefined: resolver.BuildOption"

### ISSUE THREAD

**Issue by dwschulze** [micro/go-micro#1655]
**Describe the bug**

1. What are you trying to do?
Following [this example](https://ewanvalentine.io/microservices-in-golang-part-2/) 
2. What did you expect to happen?
Successful build.

3. What happens instead?
when I run `go get -u` or `go build main.go` I get this error:

```
# github.com/coreos/etcd/clientv3/balancer/resolver/endpoint
../../../../../go3p/pkg/mod/github.com/coreos/etcd@v3.3.21+incompatible/clientv3/balancer/resolver/endpoint/endpoint.go:114:78: undefined: resolver.BuildOption
../../../../../go3p/pkg/mod/github.com/coreos/etcd@v3.3.21+incompatible/clientv3/balancer/resolver/endpoint/endpoint.go:182:31: undefined: resolver.ResolveNowOption
# github.com/coreos/etcd/clientv3/balancer/picker
../../../../../go3p/pkg/mod/github.com/coreos/etcd@v3.3.21+incompatible/clientv3/balancer/picker/err.go:37:44: undefined: balancer.PickOptions
../../../../../go3p/pkg/mod/github.com/coreos/etcd@v3.3.21+incompatible/clientv3/balancer/picker/roundrobin_balanced.go:55:54: undefined: balancer.PickOptions
```

**How to reproduce the bug:**

If possible, please include a minimal code snippet here.
This is my go.mod:

go 1.13

require (
	github.com/coreos/etcd v3.3.21+incompatible // indirect
	github.com/coreos/go-systemd v0.0.0-20191104093116-d3cd4ed1dbcf // indirect
	github.com/fsnotify/fsnotify v1.4.9 // indirect
	github.com/gogo/protobuf v1.3.1 // indirect
	github.com/golang/protobuf v1.4.2
	github.com/imdario/mergo v0.3.9 // indirect
	github.com/micro/go-micro/v2 v2.7.0
	github.com/miekg/dns v1.1.29 // indirect
	github.com/nats-io/nats.go v1.10.0 // indirect
	go.uber.org/zap v1.15.0 // indirect
	golang.org/x/crypto v0.0.0-20200510223506-06a226fb4e37 // indirect
	golang.org/x/lint v0.0.0-20200302205851-738671d3881b // indirect
	golang.org/x/net v0.0.0-20200520182314-0ba52f642ac2 // indirect
	golang.org/x/sys v0.0.0-20200519105757-fe76b779f299 // indirect
	golang.org/x/tools v0.0.0-20200521155704-91d71f6c2f04 // indirect
	google.golang.org/genproto v0.0.0-20200521103424-e9a78aa275b7 // indirect
	google.golang.org/grpc v1.29.1 // indirect
	gopkg.in/yaml.v2 v2.3.0 // indirect
	honnef.co/go/tools v0.0.1-2020.1.4 // indirect
)

**Environment:**
Go Version: please paste `go version` output here
go version go1.13.7 linux/amd64

please paste `go env` output here
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/dean/.cache/go-build"
GOENV="/home/dean/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY="github.com/dwschulze/*"
GONOSUMDB="github.com/dwschulze/*"
GOOS="linux"
GOPATH="/home/dean/src/golang/go3p"
GOPRIVATE="github.com/dwschulze/*"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/dean/bin/go1.3.1.linux-amd64/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/dean/bin/go1.3.1.linux-amd64/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/dean/src/golang/examples/blogs.and.websites/ewan.valentine/microservices.in.go/shippy-service.consignment/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build654555358=/tmp/go-build -gno-record-gcc-switches"

**Comment by asim** [comment]
Please don't do go get -u. We have a specific go.mod file with versions that work.

**Comment by dwschulze** [comment]
Running `go build main.go` has the same effect.

**Comment by yezihack** [comment]
> Please don't do go get -u. We have a specific go.mod file with versions that work.

how doing

**Comment by Kuri-su** [comment]
@dwschulze @yezihack 

maybe this issue can help you , This is a known issue between `etcd`  and `grpc`
https://github.com/etcd-io/etcd/issues/11563

you can replace `grpc` to v1.26+ or replace `etcd` to  `v3.3.4+incompatible` in `go.mod` file, like this
```go
// go.mod

replace google.golang.org/grpc => google.golang.org/grpc v1.26.0
// or
replace github.com/coreos/etcd => github.com/coreos/etcd v3.3.4+incompatible
```
