### ISSUE TITLE
some question about micro new

### ISSUE THREAD

**Issue by bluedragonflyliu** [micro/go-micro#1672]
micro --version
micro version latest

**Environment:**
Go Version: please paste `go version` output here
```
go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/aa/go"
GOPRIVATE=""
GOPROXY="https://goproxy.io"
GOROOT="/usr/lib/golang"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/golang/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/aa/go/src/micro_demo/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build365080743=/tmp/go-build -gno-record-gcc-switches"

```
micro new -namespace=com.test --type=api ./micro_demo/api/user
cd micro_demo/api/user
protoc --proto_path=.:$GOPATH/src --go_out=. --micro_out=. proto/user/user.proto

main.go

import (
	log "github.com/micro/go-micro/v2/logger"

	"github.com/micro/go-micro/v2"
	"micro_demo/api/user/handler"
	"micro_demo/api/user/client"

	user "micro_demo/api/user/proto/user"
)

func main() {
	// New Service
	service := micro.NewService(
		micro.Name("com.test.api.user"),
		micro.Version("latest"),
	)

	// Initialise service
	service.Init(
		// create wrap for the User service client
		micro.WrapHandler(client.UserWrapper(service)),
	)

	// Register Handler
	user.RegisterUserHandler(service.Server(), new(handler.User))

	// Run service
	if err := service.Run(); err != nil {
		log.Fatal(err)
	}
}

client/user.go

package client

import (
	"context"
	"github.com/micro/go-micro/v2"
	"github.com/micro/go-micro/v2/server"
	user "micro_demo/srv/user/proto/user"
)

type userKey struct {}

// FromContext retrieves the client from the Context
func UserFromContext(ctx context.Context) (user.UserService, bool) {
	c, ok := ctx.Value(userKey{}).(user.UserService)
	return c, ok
}

// Client returns a wrapper for the UserClient
func UserWrapper(service micro.Service) server.HandlerWrapper {
	client := user.NewUserService("go.micro.service.template", service.Client())

	return func(fn server.HandlerFunc) server.HandlerFunc {
		return func(ctx context.Context, req server.Request, rsp interface{}) error {
			ctx = context.WithValue(ctx, userKey{}, client)
			return fn(ctx, req, rsp)
		}
	}
}

handler/user.go
package handler

import (
	"context"
	"encoding/json"
	log "github.com/micro/go-micro/v2/logger"

	api "github.com/micro/go-micro/v2/api/proto"
	"github.com/micro/go-micro/v2/errors"
	"micro_demo/api/user/client"
	user "micro_demo/srv/user/proto/user"
)

type User struct{}

func extractValue(pair *api.Pair) string {
	if pair == nil {
		return ""
	}
	if len(pair.Values) == 0 {
		return ""
	}
	return pair.Values[0]
}

// User.Call is called by the API as /user/call with post body {"name": "foo"}
func (e *User) Call(ctx context.Context, req *api.Request, rsp *api.Response) error {
	log.Info("Received User.Call request")

	// extract the client from the context
	userClient, ok := client.UserFromContext(ctx)
	if !ok {
		return errors.InternalServerError("com.test.api.user.user.call", "user client not found")
	}

	// make request
	response, err := userClient.Call(ctx, &user.Request{
		Name: extractValue(req.Post["name"]),
	})
	if err != nil {
		return errors.InternalServerError("com.test.api.user.user.call", err.Error())
	}

	b, _ := json.Marshal(response)

	rsp.StatusCode = 200
	rsp.Body = string(b)

	return nil
}

api/user/proto/user/user.proto

syntax = "proto3";

package com.test.api.user;

import "github.com/micro/go-micro/api/proto/api.proto";

service User {
	rpc Call(go.api.Request) returns (go.api.Response) {}
}

the result about go run

go run main.go 
# command-line-arguments
./main.go:27:48: cannot use new(handler.User) (type *handler.User) as type com_test_api_user.UserHandler in argument to com_test_api_user.RegisterUserHandler:
	*handler.User does not implement com_test_api_user.UserHandler (wrong type for Call method)
		have Call(context.Context, *"github.com/micro/go-micro/v2/api/proto".Request, *"github.com/micro/go-micro/v2/api/proto".Response) error
		want Call(context.Context, *"github.com/micro/go-micro/api/proto".Request, *"github.com/micro/go-micro/api/proto".Response) error

srv/user is well

micro new -namespace=com.test --type=service./micro_demo/srv/user
cd micro_demo/srv/user
protoc --proto_path=.:$GOPATH/src --go_out=. --micro_out=. proto/user/user.proto

**Comment by asim** [comment]
Please file issue in micro/micro
