### ISSUE TITLE
I once again experienced a mDNS problem on MacOS

### ISSUE THREAD

**Issue by zhivulinal** [micro/go-micro#1673]
2 devices MacBook and Imac with Catalina show problems.
No entry: level=info service=proxy Registry [mdns]

When I make a command from an example: micro get service go.micro.srv.greeter
I get: broker=service,protocol=grpc,registry=service,server=grpc,transport=grpc
It seems that this is a massive MacOS Catalina problem. Perhaps there are solutions?

**Comment by domwong** [comment]
@zhivulinal I'm on catalina and it seems OK for me. Can you give exact steps and output to reproduce the issue please?

**Comment by vtolstov** [comment]
@zhivulinal do you have firewall enabled? macos disable mdns by default

**Comment by asim** [comment]
No response, closing.
