### ISSUE TITLE
Manually unsubscribe a subscriber

### ISSUE THREAD

**Issue by ginuerzh** [micro/go-micro#168]
Sometimes I want to subscribe a topic in server's handler temporarily, then unsubscribe it at the end of the handler. But unlike the broker.Subscriber, there is no Unsubscribe() method in the server.Subscriber, 
the alternative is to use the service.Options().Broker directly. I wonder why it does not have this method.

**Comment by asim** [comment]
This is unfortunately not something that will be supported. A server subscriber behaves like a server handler. It's done like this on purpose. It's the expectation that it exists for the lifetime of the service. You would never unregister a http handler while a server is running. In the same sense you would not unsubscribe a critical subscription. If you want control over subscribing and unsubscribing please use the broker directly.
