### ISSUE TITLE
Using v1.10.0 of go-micro encountered "reading gopkg.in/fsnotify.v1/go.mod at revision v1.4.7: unknown revision v1.4.7"

### ISSUE THREAD

**Issue by madhukant** [micro/go-micro#1689]
When build the application on 07-Jun-2020 below error encountered:

go: github.com/micro/go-micro@v1.10.0 requires
  github.com/onsi/gomega@v1.5.0 requires
  gopkg.in/fsnotify.v1@v1.4.7: reading gopkg.in/fsnotify.v1/go.mod at revision v1.4.7: unknown revision v1.4.7

I didn't changed the version. it worked 10 days ago.

After pulling the gopkg.in/fsnotify.v1@v1.4.7 manually it worked fine.

1. What are you trying to do?
compile the application on version v1.10.0 as per requirement. 

2. What did you expect to happen?
it should be compiled seamlessly as happened 10 days ago.

3. What happens instead?
it gave error from another lib while pulling the same.
gopkg.in/fsnotify.v1@v1.4.7

**Environment:**
go version is 1.12

**Comment by vtolstov** [comment]
Sorry nut this is too old version. Try to upgrade to more recent version
