### ISSUE TITLE
how can i send message to specified node?

### ISSUE THREAD

**Issue by ximigame** [micro/go-micro#1690]
>1. serverA provide websocket api to user
>2. serverB is normal stateless grpc server
>3. start two instance of serverA: serverA1 and serverA2
>4. user1 connect to serverA1, user2 connect to serverA2 with websocket

**question: I have message in serverB want to send to user1, should send to serverA1 frist, how can i do?**

**Comment by vtolstov** [comment]
you can use selector option that select needed node

**Comment by ximigame** [comment]
thanks
