### ISSUE TITLE
[BUG] Installation error 

### ISSUE THREAD

**Issue by Mido-sys** [micro/go-micro#1697]
**Describe the bug**

1. What are you trying to do?
Trying to install go-micro using 
`go install github.com/micro/micro/v2` based on this tutorial [getting-started](https://dev.m3o.com/getting-started#installation) 
2. What did you expect to happen?
No errors
3. What happens instead?
```
go: downloading github.com/coreos/go-systemd v0.0.0-20190719114852-fd7a80b32e1f
# github.com/coreos/etcd/clientv3/balancer/picker
/home/mido/go/pkg/mod/github.com/coreos/etcd@v3.3.18+incompatible/clientv3/balancer/picker/err.go:37:44: undefined: balancer.PickOptions
/home/mido/go/pkg/mod/github.com/coreos/etcd@v3.3.18+incompatible/clientv3/balancer/picker/roundrobin_balanced.go:55:54: undefined: balancer.PickOptions
# github.com/coreos/etcd/clientv3/balancer/resolver/endpoint
/home/mido/go/pkg/mod/github.com/coreos/etcd@v3.3.18+incompatible/clientv3/balancer/resolver/endpoint/endpoint.go:114:78: undefined: resolver.BuildOption
/home/mido/go/pkg/mod/github.com/coreos/etcd@v3.3.18+incompatible/clientv3/balancer/resolver/endpoint/endpoint.go:182:31: undefined: resolver.ResolveNowOption
```

**How to reproduce the bug:**

If possible, please include a minimal code snippet here.

**Environment:**
Go Version: please paste `go version` output here
`go version go1.14.4 linux/amd64`

please paste `go env` output here
```
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/mido/.cache/go-build"
GOENV="/home/mido/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOOS="linux"
GOPATH="/home/mido/go"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/mido/go/src/bitbucket.org/mido/categories-products/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build241708018=/tmp/go-build -gno-record-gcc-switches"
```

**Comment by chinajuanbob** [comment]
Hit the same issue,  it seems using `go get` w/o `-u` doesn't solve the case.

@midoNuminix  have you try with `GO111MODULE=on` ?

**Comment by Mido-sys** [comment]
@chinajuanbob, yes, I tried it with `GO111MODULE=on,` and it still didn't work. It returns the same error message.

**Comment by metauro** [comment]
try add this line to your go.mod
```
replace google.golang.org/grpc => google.golang.org/grpc v1.26.0
```

**Comment by chinajuanbob** [comment]
try adding these lines in `go.mod`

```
replace google.golang.org/grpc => google.golang.org/grpc v1.26.0

replace google.golang.org/genproto => google.golang.org/genproto v0.0.0-20191216164720-4f79533eabd1

replace google.golang.org/api => google.golang.org/api v0.15.0
```

**Comment by domwong** [comment]
This is likely an issue with the `go.mod` file in the directory that you're running go install. 

Please avoid running `go get -u`. If you run `go get -u` it will ignore the `go.mod` file that comes with micro and instead try to use the latest versions of everything. If you look at your local `go.mod` you'll probably see a lot of these entries have been added. This means that if you subsequently try to do `go install` it will use these versions recorded in the `go.mod` file. To fix this you should go to a fresh directory, initialise a blank go.mod file and then run `go install github.com/micro/micro/v2` which should ensure you pick up the versions correctly.

**Comment by Mido-sys** [comment]
@domwong, 

I haven't used `go get -u`. I deleted the go.mod file,  did a `go clean --modcache` and still no success. The culprit is the GRPC version. After downgrading GRPC to v1.26, adding @chinajuanbob recommendations and recompiling the protos it finally worked. 

For testing purposes, I set up docker and installed a fresh go1.14.4 and it still gave the same error. go-micro isn't compatible with the latest GRPC version because of etcd package.

**Comment by domwong** [comment]
Yes, we've seen this issue previously which is why our go.mod file for `micro` already has this require directive for grpc https://github.com/micro/micro/blob/master/go.mod#L34 . This is why I'm confused as to why your `go install` didn't pick this up and used the wrong version.

**Comment by vtolstov** [comment]
replace github.com/coreos/etcd => github.com/ozonru/etcd v3.3.20-grpc1.27-origmodule+incompatible
can solve this issue
