### ISSUE TITLE
Account not issued by...

### ISSUE THREAD

**Issue by coder2z** [micro/go-micro#1698]
Error using api gateway access.
Added namespace when running micro.
`micro api --namespace=go.micro.wPan`
Account not issued by go.micro.wPan
why?
thank！

**Comment by asim** [comment]
Which release are you using?

**Comment by coder2z** [comment]
```
go 1.13
github.com/micro/go-micro v1.18.0
github.com/micro/go-plugins v1.5.1
```

**Comment by asim** [comment]
What version of micro? This is the `micro api`

**Comment by coder2z** [comment]
cmd `micro --version`
==>`micro version latest`

**Comment by asim** [comment]
the actual release version? how are you downloading micro?

if you are running an old version please get the latest. Otherwise if you plan to stay with go-micro v1.18 please downgrade micro

**Comment by xiaocode337317439** [comment]
I have the same problem,  go-micro version:

go 1.13

// This can be removed once etcd becomes go gettable, version 3.4 and 3.5 is not,
// see https://github.com/etcd-io/etcd/issues/11154 and https://github.com/etcd-io/etcd/issues/11931.
replace google.golang.org/grpc => google.golang.org/grpc v1.26.0

require (
	github.com/golang/protobuf v1.4.2
	github.com/micro/go-micro/v2 v2.9.0
	google.golang.org/protobuf v1.24.0
)

github.com/micro/cli/v2 v2.1.2
github.com/micro/cli/v2 v2.1.2/go.mod
github.com/micro/go-micro v1.18.0
github.com/micro/go-micro/v2 v2.9.0
github.com/micro/go-micro/v2 v2.9.0/go.mod

**Comment by tanolsdk** [comment]
Hello, I have the same issue...
go version go1.14.2 darwin/amd64
micro version latest

**Comment by xiaohei5194** [comment]
micro  --auth_namespace=go.username  api --namespace=go.username

**Comment by joseroberto** [comment]
Me too,

go 1.14

go.mod
...
github.com/micro/go-micro/v2 v2.8.0
replace github.com/micro/go-micro/v2 => github.com/micro/go-micro/v2 v2.8.1-0.20200604083217-bd3ef6732811

docker-compose:

  micro:
    command: api --handler=api --namespace com.dinamonetworks
    image: micro/micro:latest
    ports:
      - "9090:8080"

Message:
Account not issued by com.dinamonetworks

**Comment by xox9001** [comment]
hi,all:

Me too

**Comment by dcam0050** [comment]
> micro --auth_namespace=go.username api --namespace=go.username

This works for me!

**Comment by asim** [comment]
Looks like there is a resolution, otherwise please file issue in micro/micro for any further problems
