### ISSUE TITLE
Where can I find any example using CockroachDB as Data Storage ?

### ISSUE THREAD

**Issue by goodforever** [micro/go-micro#1707]
Where can I find any example using CockroachDB as Data Storage ?

**Comment by asim** [comment]
Here's how we do it in our kubernetes deployment
https://github.com/micro/micro/blob/master/platform/kubernetes/network/store.yaml#L48L51

TLDR:

MICRO_STORE=cockroach
MICRO_STORE_ADDRESS="host=cockroachdb-public port=26257 sslmode=disable user=root"

Cockroach is not imported by default in go-micro so you will need to do

```
import "github.com/micro/go-micro/v2/config/cmd"
import "github.com/micro/go-micro/v2/store/cockroach"

cmd.DefaultStores["cockroach"] = cockroach.NewStore
```

Alternatively with options

```
store := cockroach.NewStore()

service := micro.NewService(
    micro.Store(store),
)
```

**Comment by goodforever** [comment]
@asim Thank you very much!
