### ISSUE TITLE
Is it possible to write a vanilla Python grpc client with go micro?

### ISSUE THREAD

**Issue by jones77** [micro/go-micro#174]
I am unable to create a python **grpc** client to successfully call a go micro grpc service using the following tutorial: http://www.grpc.io/docs/tutorials/basic/python.html

The Python client go micro examples seems to use json over http to query the rpc server.  eg https://github.com/micro/examples/blob/master/greeter/cli/python/rpc_client.py

I can telnet to the port where my server is running.  And have successfully used the json example to call the service.

**Comment by jones77** [comment]
erm, https://github.com/micro/go-micro/issues/89

**Comment by asim** [comment]
The default implementation for micro is proto-rpc and json-rpc over http. What's used is determined by content-type. This is in no way compatible with grpc. To use grpc with go-micro you must either use the client/server plugins in go-plugins https://github.com/micro/go-plugins or go-grpc which just initialises them for you https://github.com/micro/go-grpc

**Comment by jones77** [comment]
Thanks for the rapid response, clarified things from our end.
