### ISSUE TITLE
Possibility to read time.Duration fields in config

### ISSUE THREAD

**Issue by vkuptcov** [micro/go-micro#1749]
Hello!
I'm trying to figure out is it possible to read `time.Duration` fields in configs?
E.g. I have the next config:
```yaml
mode: shared
duration: 3s
```
and I want to read it into the next structure
```
type TestConfig struct {
	mode      string
	Duration time.Duration
}
```
when I do read it now 
```
	cfgLoader := microConf.NewConfig()
	err = cfgLoader.Load(sources...)
...
	err = cfgLoader.Scan(configDst)
```
I receive an error `json: cannot unmarshal string into Go struct field TestConfig.Duration of type time.Duration`

**Comment by NeonWizard** [comment]
@asim Can you link where this was completed?
