### ISSUE TITLE
Docker Swarm Mode registry

### ISSUE THREAD

**Issue by djensen47** [micro/go-micro#175]
We're exploring running our microservices within Swarm using Docker Swarm Mode. In the most recent versions of Swarm, service discovery is included in Docker Swarm Mode. 

Do you have any recommendations for running go-micro in a Docker Swarm using Docker Swarm Mode?

For instance, is there an existing registry plugin that will work? Or will we have to write one from scratch?

**Comment by asim** [comment]
Most plugins are located in [go-plugins](https://github.com/micro/go-plugins) or you can search via the [explorer](https://micro.mu/explore/). There is currently nothing for docker swarm integration. 

If docker swarm has an api I'm sure you could write a plugin to connect to it although considering go-micro apps create their own metadata/endpoint info to register with discovery you'll lose out on some of those benefits. 

Please ask questions in the slack. We prefer to keep issues for bugs. Thanks.
