### ISSUE TITLE
[BUG] error loading source env: cannot append two different types (map, string)

### ISSUE THREAD

**Issue by camba1** [micro/go-micro#1753]
**Describe the bug**

1. What are you trying to do?

Trying to load environment variables using the built-in env source of the config object in go-micro

2. What did you expect to happen?

Loads environment variables into memory

3. What happens instead?

I get the error: **"error loading source env: cannot append two different types (map, string)"**

**How to reproduce the bug:**
Environment Variables:

```
MICRO_SERVER_ADDRESS=:50057
MICRO_BROKER=nats
MICRO_BROKER_ADDRESS=myuser:mypwd@nats
```

Code:

```
func loadConfig() {
	conf, err := config.NewConfig()
	if err != nil {
		log.Fatal(err)
	}
	defer conf.Close()
	src := env.NewSource()
	err = conf.Load(src)
	if err != nil {
             log.Fatal(err)
	}
	test := conf.Map()
        log.Printf("conf map %v\n", test)
}
```

Error is thrown in line: `err = conf.Load(src)`
Further investigation leads to the error happening in file **go-micro/v2@v2.8.0/config/source/env/env.go, function Read, lines:**

```
		if err := mergo.Map(&changes, tmp); err != nil {
			return nil, err
		}
```

The Read function is trying to build a map of environment variables after splitting them by an underscore ('_'). The map seems to have two levels.  This breaks down when you have environment variables that looks like these:

```
MICRO_BROKER=nats
MICRO_BROKER_ADDRESS=myuser:mypwd@nats
```
In this case the code creates an entry in the map for MICRO -> BROKER and value NATS. However, when processing the second environment variable it tries to create a second entry with keys MICRO -> BROKER . At that point, it breaks trying to merge the second entry into the map.

To avoid the error all that needs to happen is change the second environment variable to something more unique like:

`MICRO_BROKER2_ADDRESS=myuser:mypwd@nats`

However since that MICRO_BROKER_ADDRESS is a go-micro defined variable and used to declare a broker,, it is not feasible to change its name 

**Environment:**

```
go version go1.14.2 darwin/amd64
```

**Comment by domwong** [comment]
Thanks for the report @camba1 . We'll need to have a think about this to define the best way forward. We'll keep you updated.

**Comment by sadwxqezc** [comment]
The same as this https://github.com/micro/go-micro/issues/1754

**Comment by Jack-Ji** [comment]
got similiar issue, here's my code:

```
	err := config.Load(
		env.NewSource(),
		file.NewSource(file.WithPath("./config.yaml")),
	)
	if err != nil {
		panic(err)
	}
```

Here's config.yaml:

```
db:
    debug: false
    type: postgres
    url: postgresql://root@localhost:26257/workflow?sslmode=disable
```

Unlike the proposed problem, I don't need to set any envirment variables, problem happens anyway.

```
micro version: 2.9.1
go version: 1.14.6
platform: windows 10
```
