### ISSUE TITLE
micro <...> --api_handler=rpc api it doesn't work

### ISSUE THREAD

**Issue by t5w0rd** [micro/go-micro#1755]
@doubleycn thanks for your reply.
My service type is ```service(grpc)```, not ```api```.
so can you test ```micro api``` by using ```--handler=rpc``` instead of ```--handler=api```?

Please follow the steps below to test.
1. create one **rpc** service:
```micro new --namespace=xxx --type=service greeter```
2. run service:
```cd greeter && make build && ./greeter-service```
3. run micro gateway in **RPC** handler type mode (**rpc rpc rpc** :) ):
```micro --auth_namespace='xxx' --api_namespace='xxx' --api_handler='rpc' api```
4. send http request:
```curl --location --request POST 'localhost:8080/service/greeter/greeter/call' --header 'Content-Type: application/json' --data-raw '{"name":"jack"}'```

And you will get this result:
```{"id":"go.micro.api","code":500,"detail":"service not found","status":"Internal Server Error"}```

go-micro version: v2.8.0
micro version: v2.9.1

I'm sure it cannot work, even if use both ```--auth_namespace``` and ```---api_namespace``` options.
btw, it works well in 1.x.x versions.

_Originally posted by @t5w0rd in https://github.com/micro/go-micro/issues/1709#issuecomment-650971081_

**Comment by t5w0rd** [comment]
please test the ```--api_handler=rpc```, thanks!

**Comment by asim** [comment]
Whats the namespace?

**Comment by asim** [comment]
namespace + path = service

**Comment by asim** [comment]
curl localhost:8080/greeter/call

**Comment by asim** [comment]
file this issue with micro repo and look at examples repo

**Comment by t5w0rd** [comment]
@asim OK, i see.
After reading the examples/api/rpc, I found the difference between the new and old versions. service name must contain **.api.**.
haha, it's my mistake :)
