### ISSUE TITLE
Go micro dashboard does not register my service when running inside docker-compose

### ISSUE THREAD

**Issue by shackra** [micro/go-micro#1757]
[Posted this on Stackoverflow](https://stackoverflow.com/q/62629980/2020214) but no luck there so far.

I'm new to go-micro, tried to have `micro server` running as another service in my docker-compose setup however my first micro-service is not getting show in Micro Web (the Go Micro dashboard). If I run `micro server` outside docker-compose I can see several go-micro-related micro-services in the dashboard, but inside docker-compose none is displayed.

I have put together an example code that reproduces what I experience, I generated the service using `micro new` and changed nothing in it, the `docker-compose.yml` reflects how I have it setup in my project where I began experiencing this:

https://github.com/shackra/go-micro-docker-compose-bug

What am I doing wrong and how do I get the Micro dashboard to work as expected inside docker-compose?

**Comment by elzorrorebelde** [comment]
moved this issue to https://github.com/micro/micro/issues/999
