### ISSUE TITLE
[BUG] "Unsupported store: redis"  when trying to use Redis as the service store

### ISSUE THREAD

**Issue by camba1** [micro/go-micro#1768]
**Describe the bug**

1. What are you trying to do?

Trying to Use Redis as store to cache information for the service

2. What did you expect to happen?

Redis replaces to built in store and I am able to read/delete values

3. What happens instead?

service throws error when initializing the store. 

**How to reproduce the bug:**
Environment variables :
```
MICRO_STORE=redis
MICRO_STORE_ADDRESS=redis:6379
```

plugins.go:

```
package main

import (
	_ "github.com/micro/go-plugins/store/redis/v2"
)
```

```
Main function:

	//instantiate service
	service := micro.NewService(
		micro.Name(serviceName),
		micro.WrapHandler(AuthWrapper),
		micro.Store(redis.NewStore()),
	)

       service.Init()
	err := proto.RegisterPromotionSrvHandler(service.Server(), new(Promotion))
	if err != nil {
		log.Fatalf(glErr.SrvNoHandler(err))
	}
      myStore := service.Options().Store
      ...
      ....

```
Error occurs on the last line above. Upon further investigation, the error is thrown in _gitHub.com/micro/go-micro/V2@v2.8.0/config/cmd.cmd.go_ . In particular it is thrown in function:

```
func (c *cmd) Before(ctx *cli.Context) error {
...
...
	// Set the store
	if name := ctx.String("store"); len(name) > 0 {
		s, ok := c.opts.Stores[name]
		if !ok {
			return fmt.Errorf("Unsupported store: %s", name)
		}

		*c.opts.Store = s(store.WithClient(microClient))
	}
....
....
```

c.opts.Stores only contains two valid stores: memory and service. Redis is not there. 

Note that all the code works fine if I use the built-in store.

**Environment:** 
go version go1.14.1 linux/amd64
```
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/go/src/goTemp/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build778202084=/tmp/go-build -gno-record-gcc-switches"
```

**Comment by asim** [comment]
Store plugins are just missing the init func used in other plugins to include them in the list. See other plugin implementations as an example.

**Comment by camba1** [comment]
I got it to work after a quick chat with the team. To use a store plugin, one has to load it manually before it can be accessed. I added an initPlugins function in plugins.go and called in the main function of the service:

Environment Variables:

```
MICRO_STORE=redis
MICRO_STORE_ADDRESS=redis:6379
```

plugins.go

```
package main

import (
	"github.com/micro/go-micro/v2/config/cmd"
	redis "github.com/micro/go-plugins/store/redis/v2"
)

func initPlugins() {
	cmd.DefaultStores["redis"] = redis.NewStore
}
```

Main function:

```
	//instantiate service
	service := micro.NewService(
		micro.Name(serviceName),
		micro.WrapHandler(AuthWrapper),
       )

        //initialize plugins (this is just needed for stores)
	initPlugins()

       service.Init()
	err := proto.RegisterPromotionSrvHandler(service.Server(), new(Promotion))
	if err != nil {
		log.Fatalf(glErr.SrvNoHandler(err))
	}
      myStore := service.Options().Store
      ...
      ....
```

Note that initPlugins must be called before service.init to use the environment variable values that point to the location of the redis instance

**Comment by Davincible** [comment]
@asim was this behavior implemented on purpose or by accident? Seems to me like registering the store plugins should be done by micro itself just like all other plugins

**Comment by asim** [comment]
Probably just overlooked

**Comment by Davincible** [comment]
Ah it's a bug in the plugins not in go-micro itself, I'll submit a PR
