### ISSUE TITLE
A question about streaming

### ISSUE THREAD

**Issue by freman** [micro/go-micro#181]
Hi.

server/pc_server.go contains

```go
		// set the timeout if we have it
		if len(to) > 0 {
			if n, err := strconv.ParseUint(to, 10, 64); err == nil {
				ctx, _ = context.WithTimeout(ctx, time.Duration(n))
			}
		}
```

Yet I can't figure out how to call it without passing a duration. Is there a way?

**Comment by asim** [comment]
Duration is always set at the edge. The first client will look for the timeout header. If it's not found it will set one to the timeout in the client. The default timeout is 5 seconds. There is no way to make a call without passing the duration. This avoids indefinitely blocking.

Please ask questions in the slack. We maintain issues for bugs.
