### ISSUE TITLE
remote address

### ISSUE THREAD

**Issue by freman** [micro/go-micro#182]
Hi.

So, I know this is very protocol dependant, but we couldn't figure out how to get remote_addr of the client for the http/rpc transport

Was wondering if you either had another route, or would accept this patch?

```
diff --git a/transport/http_transport.go b/transport/http_transport.go
index e3ab5eb..102a8e8 100644
--- a/transport/http_transport.go
+++ b/transport/http_transport.go
@@ -204,6 +204,8 @@ func (h *httpTransportSocket) Recv(m *Message) error {
 		}
 	}

+	m.Header["Remote-Addr"] = h.conn.RemoteAddr().String()
+
 	select {
 	case h.r <- r:
 	default:
```

It's useful for figuring out which client borked something

**Comment by asim** [comment]
This is what distributed tracing is for. Use zipkin or similar.

Remote address is most definitely dependent on the transport protocol. This cannot be reliably guaranteed across transports and is not included. You can have a service set its own address as a header and have that propagate through. Very easily using wrappers. Note go-micro does this https://github.com/micro/go-micro/blob/master/service.go#L27

Please ask questions in the slack.
