### ISSUE TITLE
Message Queue Support?

### ISSUE THREAD

**Issue by choveylee** [micro/go-micro#183]
when i start several service，i want to deal with the message from message queue only one service。 pub-sub broker can not work correctly。what can i do？ will go-micro support message queue？thanks。

**Comment by asim** [comment]
Please look at the godoc. You have the option of specifying a queue name as a subscribe option either to the broker or to the server. Queues with the same name distribute traffic across instances that are subscribed. 

Please also ask questions as opposed to creating issues.

https://godoc.org/github.com/micro/go-micro/broker#Queue
https://godoc.org/github.com/micro/go-micro/server#SubscriberQueue
