### ISSUE TITLE
package github.com/micro/go-micro/v2: cannot find package "github.com/micro/go-micro/v2"

### ISSUE THREAD

**Issue by Tomey** [micro/go-micro#1839]
go get github.com/micro/go-micro/v2 
package github.com/micro/go-micro/v2: cannot find package "github.com/micro/go-micro/v2" in any of:
        /usr/local/go/src/github.com/micro/go-micro/v2 (from $GOROOT)
        /Users/tomey/go/src/github.com/micro/go-micro/v2 (from $GOPATH)

Why can't I download this module?

**Comment by vtolstov** [comment]
you need to use go 1.14 or enable go modules
