### ISSUE TITLE
A question about consul discovery via DNS

### ISSUE THREAD

**Issue by choveylee** [micro/go-micro#185]
Service name "go.micro.srv.auth" will not be discoverable via DNS due to invalid characters. Valid characters include all alpha-numerics and dashes.

Maybe replace . to - better, and modify the file micro/go-api/router/route.go, replace some . to -

        // If we've got two or less parts
	// Use first part as service
	// Use all parts as method
	if len(parts) <= 2 {
		service := ns + "-" + strings.Join(parts[:len(parts)-1], "-")
		method := strings.Title(strings.Join(parts, "."))
		return service, method
	}

	// Treat /v[0-9]+ as versioning where we have 3 parts
	// /v1/foo/bar => service: v1.foo method: Foo.bar
	if len(parts) == 3 && versionRe.Match([]byte(parts[0])) {
		service := ns + "-" + strings.Join(parts[:len(parts)-1], "-")
		method := strings.Title(strings.Join(parts[len(parts)-2:], "."))
		return service, method
	}

	// Service is everything minus last two parts
	// Method is the last two parts
	service := ns + "-" + strings.Join(parts[:len(parts)-2], "-")
	method := strings.Title(strings.Join(parts[len(parts)-2:], "."))

**Comment by asim** [comment]
It's unlikely to happen for historic reasons. Please feel free to write your own consul plugin. Also as noted in the past 2 issues you've opened. Please refrain from opening issues to ask questions.

**Comment by choveylee** [comment]
OK,Thank you
