### ISSUE TITLE
go-micro supports nacos as a registry and configuration center 

### ISSUE THREAD

**Issue by binbin0325** [micro/go-micro#1856]
**Is your feature request related to a problem? Please describe.**
Go-micro plans to integrate nacos?

**Describe the solution you'd like**
For go-Micro users, nacos can be chosen as the registry and configuration center

**Additional context**

**Comment by binbin0325** [comment]
I could try to do the job.

**Comment by asim** [comment]
Feel free to PR something to go-plugins
