### ISSUE TITLE
go-micro/v2/server/grpc/grpc.go: How to do RegisterCheck in grpc?

### ISSUE THREAD

**Issue by zlmai** [micro/go-micro#1863]
hello, i want to ask how to do RegisterCheck or something like a hook before register() in grpc?

i use etcd as my registry and use grpc to transport. 

in go-micro/v2/server/rpc_server.go, i can find a RegisterCheck() before Register():
![image](https://user-images.githubusercontent.com/30550324/88014950-b0ab6200-cb52-11ea-8b74-da46f5444a84.png)

but in go-micro/v2/server/grpc/grpc.go, i don`t find it:
![image](https://user-images.githubusercontent.com/30550324/88015039-e9e3d200-cb52-11ea-9b87-932073810698.png)

so, how to do RegisterCheck in grpc? thank you.

**Comment by vtolstov** [comment]
this is really bad =(
you can provide pr, or wait then i'm ad it because i think that i'm add it to both server implementations

**Comment by vtolstov** [comment]
sorry, but you need to use this commits and apply with some fixes to go-micro
https://github.com/unistack-org/micro-server-grpc/commit/c76a334dc635c292a7c3ccdb485072f6a8cb319d
https://github.com/unistack-org/micro-server-grpc/commit/7aed6fb8b67b814bccee64116f81f6488854c62c

**Comment by hellodudu** [comment]
Hi vtolstov,
I'm looking for grpc server's RegisterCheck feature too, and wonder is there any plan to merge it into master?

@vtolstov

**Comment by vtolstov** [comment]
Hi, I'm not provide pr for go-micro, but you can switch toy fork, or patch go-micro.
