### ISSUE TITLE
[BUG] Micro API- Custom timeout value not working.

### ISSUE THREAD

**Issue by itzmanish** [micro/go-micro#1865]
I tried sending Timeout Header with value of 600 from postman. But still I got deadline exceeded after 5sec.
However I tried to print context receiving on service and I got deadline time is not modified and still is 5 sec,.

**How to reproduce the bug:**
Run micro api
Make request to service with header key Timeout and value 600

**Environment:**
go version go1.14.4 linux/amd64

```
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/manish/.cache/go-build"
GOENV="/home/manish/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/manish/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/manish/go/src/github.com/itzmanish/charted/service/accounts/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build008428856=/tmp/go-build -gno-record-gcc-switches"

```

**Comment by asim** [comment]
The timeout is processed as nano seconds. https://github.com/micro/go-micro/blob/master/server/grpc/grpc.go#L253L259

**Comment by itzmanish** [comment]
Attaching screenshot.
UPDATE 1- Just look at the header not the response because this time the error is intentional. On server side I am printing context data to see the timeout value.
```
fmt.Println(ctx)
context.Background.WithDeadline(2020-07-22 18:51:26.953241734 +0530 IST m=+3200.137908178 [4.98366557s])
```
![Screenshot from 2020-07-22 18-52-33](https://user-images.githubusercontent.com/12438068/88181698-dc127780-cc4c-11ea-9d80-f295b469425a.png)

**Comment by itzmanish** [comment]
This is still 5sec.

Expected-
```
context.Background.WithDeadline(2020-07-22 18:48:07.13930002 +0530 IST m=+3000.323966259 [9m59.991731013s])
```

**Comment by asim** [comment]
The code says its a 400 error not a timeout

**Comment by asim** [comment]
It also completes in 3 seconds

**Comment by itzmanish** [comment]
Okay, Let me show you.
![Screenshot from 2020-07-22 20-22-25](https://user-images.githubusercontent.com/12438068/88191588-39142a80-cc59-11ea-90e0-a13e4a50cd91.png)

**Comment by vtolstov** [comment]
i think that you need to create simple repo that can reproduce the issue and we are happy to fix it

**Comment by itzmanish** [comment]
Ok. I will soon provide you sample repo.

**Comment by jjjachyty** [comment]
@itzmanish  have you solve it?
