### ISSUE TITLE
A question about microservice TDD

### ISSUE THREAD

**Issue by mkozjak** [micro/go-micro#187]
First of all, thanks for this framework. It really has potential and is already looking very interesting.
This ticket is only a general question rather than an issue.

Is there anyone here familiar with TDD, BDD or any other x-driven-development paradigm in a context of microservices where the default setup is used (consul)?

Do you guys create yourself mock services which your particular developed service is dependent on or do you just use end-to-end or integration tests where you run all dependent services and then do tests on the developed service?

If you're involved in the former, do you create yourself a consul mock service which would reply as needed when the developed microservice is asking for information that's needed outside of it?

Thank you in advance!

**Comment by asim** [comment]
Please ask questions in the slack, that's where you'll likely receive more responses. We use issues for bugs.

From my experience it's a multi-step processing for testing microservices. Each service has unit tests. There may be some combined integration tests that run across a number of services in a jenkins style build system or in a test environment. There may then be an end-to-end test which operates against the api in staging and production. 

From an integration testing standpoint, the interfaces for broker/registry/transport could be mocked to allow them to be run on a single host or everything could just be set to run on localhost in their own binaries. 

I have seen some companies introduce a testing service or mock service which understands how to respond to various service requests and register itself in discovery against multiple service names to do that. 

My preferred style is unit tests per service, integration tests in a build or test environment and end-to-end tests in staging/production running continuously.

Hope that helps.
