### ISSUE TITLE
[FEATURE]The entire project uses the log interface, which can easily replace the log implementation

### ISSUE THREAD

**Issue by niaiwomattt** [micro/go-micro#1871]
**Is your feature request related to a problem? Please describe.**
The log that comes with it is not comfortable to use, I want to use another log library instead, but I found that the log output inside go-micro has not been replaced. The overall style of it and my project is very different, which looks strange! I want a unified log output.

**Describe the solution you'd like**
My commonly used log interface:

```golang
type Logger interface {
	Fatal(...interface{}) // 致命，此类错误会如果发生，当前应用将崩溃，不解决无法启动应用
	Fatalf(string, ...interface{})

	Error(...interface{}) // 错误，不会崩溃，但是影响使用，必须马上解决。
	Errorf(string, ...interface{})

	Warn(...interface{}) // 警告，系统能继续运行, 但是必须引起关注，系统服务都可用，但是数据可能有问题
	Warnf(string, ...interface{})

	Info(...interface{}) // 信息，这个应该用来反馈系统的当前状态的，报告类型的日志
	Infof(string, ...interface{})

	Debug(...interface{}) // 调试，比info 多更多相关信息，比如，模块，行，等等
	Debugf(string, ...interface{})
}

// Register and call functions are implemented here 
// RegisterDrive
// Fatal()
// Fatalf()
// ...
```

I want go-micro to call the interface library go-micro-logger uniformly, and the interface is defined above. The implementation is imported externally, similar to the go sql standard library, and the implementation of third-party drivers.

Register driver
```golang
package main

import (
	"github.com/sirupsen/logrus"
	glog "mysite.com/gloger"
)

func init(){
	l := logrus.New()
	glog.RegisterDrive(l)
}``
**Additional context**
Hope that more functions will be provided by the interface for easy replacement and realization!

**Comment by vtolstov** [comment]
to replace micro default output - set logger.DefaultLogger to you implementation
