### ISSUE TITLE
[BUG] Heavy CPU Usages Micro WEB

### ISSUE THREAD

**Issue by itzmanish** [micro/go-micro#1891]
**Describe the bug**

Heavy CPU uses on running micro web

**How to reproduce the bug:**
run `micro web`

**Environment:**
Go Version: go version go1.14.4 linux/amd64
```
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/manish/.cache/go-build"
GOENV="/home/manish/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/manish/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build817737090=/tmp/go-build -gno-record-gcc-switches"

```
![rsz_screenshot_from_2020-08-02_20-00-01](https://user-images.githubusercontent.com/12438068/89125712-0fcb8800-d4fe-11ea-851f-742e8c26a5e1.png)

**Comment by vtolstov** [comment]
i think that this is not go-micro issue, can you provide simple example that uses go-micro/web package that contains such issue?

**Comment by itzmanish** [comment]
I don't know what's wrong but I created new service with micro new and on running that service I got 100% cpu uses on all cores.
Here is sample code of main.go

```
package main

import (
	"fmt"

	"github.com/annwntech/charted/service/directory/handler"
	"github.com/annwntech/charted/service/directory/subscriber"

	"github.com/micro/go-micro/v2"
	"github.com/micro/go-micro/v2/client"
	"github.com/micro/go-micro/v2/client/grpc"
	"github.com/micro/go-micro/v2/client/selector"
	log "github.com/micro/go-micro/v2/logger"
	"github.com/micro/go-micro/v2/registry"
	"github.com/micro/go-plugins/broker/kafka/v2"
	"github.com/micro/go-plugins/wrapper/trace/datadog/v2"

	directory "github.com/annwntech/charted/service/directory/proto/directory"
)

func main() {
	broker := kafka.NewBroker()
	// New Service
	service := micro.NewService(
		micro.Name("directory"),
		micro.Version("0.0.1"),
		micro.Broker(broker),
		micro.WrapHandler(datadog.NewHandlerWrapper()),
		micro.WrapSubscriber(datadog.NewSubscriberWrapper()),
	)

	err := service.Server().Options().Registry.Register(&registry.Service{
		Name:    "SeaweedFSFiler",
		Version: "latest",
		Nodes: []*registry.Node{
			{
				Address: "127.0.0.1:18888",
				Id:      "filer-service",
				Metadata: map[string]string{
					"protocol": "grpc",
				},
			},
		},
	})
	if err != nil {
		log.Fatal(err)
	}
	// create router
	s := selector.NewSelector(
		selector.Registry(service.Server().Options().Registry),
	)
	// create client
	c := grpc.NewClient(client.Registry(service.Server().Options().Registry), client.Selector(s))

	fmt.Println(c)

	// Initialise service
	service.Init()

	// Register Handler
	directory.RegisterDirectoryHandler(service.Server(), new(handler.Directory))

	// Register Struct as Subscriber
	micro.RegisterSubscriber("com.annwntech.charted.service.directory", service.Server(), new(subscriber.Directory))

	// Run service
	if err := service.Run(); err != nil {
		log.Fatal(err)
	}
}
```

Now I don't know which generates heavy cpu usages. This doesn't seem issue only with micro web

Attaching screenshot
![Screenshot from 2020-08-03 20-30-05](https://user-images.githubusercontent.com/12438068/89197407-47ebcd00-d5c9-11ea-9e0d-fbb877bd42d2.png)

**Comment by asim** [comment]
go-micro/web is now deprecated

**Comment by itzmanish** [comment]
What about this :-

> I don't know what's wrong but I created new service with micro new and on running that service I got 100% cpu uses on all cores.
> Here is sample code of main.go
> 
> ```
> package main
> 
> import (
> 	"fmt"
> 
> 	"github.com/annwntech/charted/service/directory/handler"
> 	"github.com/annwntech/charted/service/directory/subscriber"
> 
> 	"github.com/micro/go-micro/v2"
> 	"github.com/micro/go-micro/v2/client"
> 	"github.com/micro/go-micro/v2/client/grpc"
> 	"github.com/micro/go-micro/v2/client/selector"
> 	log "github.com/micro/go-micro/v2/logger"
> 	"github.com/micro/go-micro/v2/registry"
> 	"github.com/micro/go-plugins/broker/kafka/v2"
> 	"github.com/micro/go-plugins/wrapper/trace/datadog/v2"
> 
> 	directory "github.com/annwntech/charted/service/directory/proto/directory"
> )
> 
> func main() {
> 	broker := kafka.NewBroker()
> 	// New Service
> 	service := micro.NewService(
> 		micro.Name("directory"),
> 		micro.Version("0.0.1"),
> 		micro.Broker(broker),
> 		micro.WrapHandler(datadog.NewHandlerWrapper()),
> 		micro.WrapSubscriber(datadog.NewSubscriberWrapper()),
> 	)
> 
> 	err := service.Server().Options().Registry.Register(&registry.Service{
> 		Name:    "SeaweedFSFiler",
> 		Version: "latest",
> 		Nodes: []*registry.Node{
> 			{
> 				Address: "127.0.0.1:18888",
> 				Id:      "filer-service",
> 				Metadata: map[string]string{
> 					"protocol": "grpc",
> 				},
> 			},
> 		},
> 	})
> 	if err != nil {
> 		log.Fatal(err)
> 	}
> 	// create router
> 	s := selector.NewSelector(
> 		selector.Registry(service.Server().Options().Registry),
> 	)
> 	// create client
> 	c := grpc.NewClient(client.Registry(service.Server().Options().Registry), client.Selector(s))
> 
> 	fmt.Println(c)
> 
> 	// Initialise service
> 	service.Init()
> 
> 	// Register Handler
> 	directory.RegisterDirectoryHandler(service.Server(), new(handler.Directory))
> 
> 	// Register Struct as Subscriber
> 	micro.RegisterSubscriber("com.annwntech.charted.service.directory", service.Server(), new(subscriber.Directory))
> 
> 	// Run service
> 	if err := service.Run(); err != nil {
> 		log.Fatal(err)
> 	}
> }
> ```
> 
> Now I don't know which generates heavy cpu usages. This doesn't seem issue only with micro web
> 
> Attaching screenshot
> ![Screenshot from 2020-08-03 20-30-05](https://user-images.githubusercontent.com/12438068/89197407-47ebcd00-d5c9-11ea-9e0d-fbb877bd42d2.png)
