### ISSUE TITLE
How to use Metadata to send Message?

### ISSUE THREAD

**Issue by takumi913** [micro/go-micro#1892]
I use the micro v2.0 now, and I use Metadata in client like this

![Screenshot_20200804_152550](https://user-images.githubusercontent.com/38528079/89265430-0ad61800-d667-11ea-9fa8-4c14f4e8d834.png)

So I want get the Metadata from server, but I get  "map[]"
![Screenshot_20200804_153012](https://user-images.githubusercontent.com/38528079/89265698-7324f980-d667-11ea-9f39-2628ea9e9cd3.png)
![Screenshot_20200804_153120](https://user-images.githubusercontent.com/38528079/89265795-9d76b700-d667-11ea-8828-2c882576689b.png)

Please help me

**Comment by asim** [comment]
https://godoc.org/github.com/micro/go-micro/metadata

metadata.Set(ctx, "Header", "test")
