### ISSUE TITLE
service not found

### ISSUE THREAD

**Issue by JoyCood** [micro/go-micro#1895]
1.  start server: $:`micro server`

2.  run the service: $:`go build main.go`

3.  list the services: $:`micro list service`,

 response:
  `go.micro`
  `go.micro.api`
  `go.micro.auth`
  `go.micro.bot`
  `go.micro.broker`
  `go.micro.config`
  `go.micro.debug`
  `go.micro.network`
  `go.micro.proxy`
  `go.micro.registry`
  `go.micro.router`
  `go.micro.runtime`
  `go.micro.server`
  `go.micro.store`
  `go.micro.web`
  `micro.http.broker`
  `micro/user`
  `service`

4.  call the service: $:`micro call user User.Login {\"phone\":\"123456\"}`
5.  response is : `error calling user.User.Login: {"id":"go.micro.client","code":500,"detail":"service user: not found","status":"Internal Server Error"}`
6. env:
`
      set GO111MODULE=on

    set GOARCH=amd64

    set GOBIN=
    set GOCACHE=C:\Users\DELL\AppData\Local\go-build
    set GOENV=C:\Users\DELL\AppData\Roaming\go\env
    set GOEXE=.exe
    set GOFLAGS= -mod=
    set GOHOSTARCH=amd64
    set GOHOSTOS=windows
    set GONOPROXY=
    set GONOSUMDB=
    set GOOS=windows
    set GOPATH=C:\Users\DELL\go\go1.13.5\bin
    set GOPRIVATE=
    set GOPROXY=https://goproxy.io,direct
    set GOROOT=C:\Users\DELL\go\go1.13.5
    set GOSUMDB=sum.golang.org
    set GOTMPDIR=
    set GOTOOLDIR=C:\Users\DELL\go\go1.13.5\pkg\tool\windows_amd64
    set GCCGO=gccgo
    set AR=ar
    set CC=gcc
    set CXX=g++
    set CGO_ENABLED=1
    set GOMOD=D:\xingyou\zhibo\go.mod
    set CGO_CFLAGS=-g -O2
    set CGO_CPPFLAGS=
    set CGO_CXXFLAGS=-g -O2
    set CGO_FFLAGS=-g -O2
    set CGO_LDFLAGS=-g -O2
    set PKG_CONFIG=pkg-config
    set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix- 
    map=C:\Users\DELL\AppData\Local\Temp\go-build150987062=/tmp/go-build -gno-record-gcc-switches
`

member.proto:

    syntax="proto3";

    package member;

    service MemberService {
        rpc register(registerRequest) returns (Member){};
        rpc login(loginRequest) returns (Member) {};
    }

    message registerRequest {
        string phone = 1;
        string password = 2;
        string authcode = 3;
    }

    message registerResponse {
        Member member = 1;
        string token  = 2;
    }

    message loginRequest {
         string phone = 1;
         string password = 2;
    }

    message loginResponse {
        Member member = 1;
    }

    message Member {
        int64  userID = 1;
        string nick   = 2;
        string phone  = 3;
    }

main.go:

    package main

    import (
	  "context"
	  "github.com/golang/glog"
	  "github.com/micro/micro/v3/service"
	   member "zhibo/api/proto/v1"
    )

    type User struct {}

    func (s User) Register(ctx context.Context, req *member.RegisterRequest, m *member.Member) error {
	  m.Phone = "12354566"
	  glog.Infof("register:%+v\n", m)
	  return nil
    }

    func (s User) Login(ctx context.Context, req *member.LoginRequest, m *member.Member) error {
	  return nil
    }

    func main() {
	  glog.Infoln("GO gRPC Beginners Tutorial!")
	  user := User{}

	  srv := service.New(
		  service.Name("user"),
		  service.Version("latest"),
		  service.Address(":9999"),
	  )
	  member.RegisterMemberServiceHandler(user)
	  if err := srv.Run(); err != nil {
		glog.Errorln("err:", err)
	  }
    }

go.mod:
  

        module zhibo

        go 1.13

        require (
	      github.com/golang/glog v0.0.0-20160126235308-23def4e6c14b
	      github.com/golang/protobuf v1.4.2
	      github.com/hashicorp/consul/api v1.5.0 // indirect
	      github.com/micro/cli v0.2.0 // indirect
	      github.com/micro/go-micro v1.0.0
	      github.com/micro/go-micro/v2 v2.9.1
	      github.com/micro/go-micro/v3 v3.0.0-alpha.0.20200731140532-31ed4aa0e8d3
	      github.com/micro/go-rcache v0.3.0 // indirect
	      github.com/micro/mdns v0.3.0 // indirect
	      github.com/micro/micro/v3 v3.0.0-alpha
	      golang.org/x/net v0.0.0-20200707034311-ab3426394381 // indirect
	      golang.org/x/sys v0.0.0-20200802091954-4b90ce9b60b3
	      golang.org/x/text v0.3.3 // indirect
        )

    replace (
	  github.com/coreos/go-systemd => github.com/coreos/go-systemd/v22 v22.0.0
	  google.golang.org/grpc => google.golang.org/grpc v1.26.0
    )

**Comment by asim** [comment]
Please file under micro
