### ISSUE TITLE
How to set log level for rpc_server?

### ISSUE THREAD

**Issue by veger** [micro/go-micro#1900]
I am debugging an issue we are having related to gomicro v2.9.1. The service responses are not received by client. So there is an issue on sending the response or receiving them.
I didn't get any relevant logs and started to put `fmt.Printf()` all over the code... (couldn't use debugger as it is a distributed application and debugging all services at the same time seems a (bigger) pain to me).

In the end, I ended up at `func (s *rpcServer) ServeConn(sock transport.Socket)` in _server/rpc_servicer.go_ and noticed
https://github.com/micro/go-micro/blob/94bd1025a64eaaba1d89189891ef49f3ab5eee7f/server/rpc_server.go#L437

I thought we set the logger using
```golang
log.SetLogger(outLoggerWithDebugLevel) // import "github.com/micro/go-log"
```
but we didn't get this log message (I verified that this debug log line is actually reached)

After some additional investigation I found:
https://github.com/micro/go-micro/blob/94bd1025a64eaaba1d89189891ef49f3ab5eee7f/server/server.go#L152

The `log` field is set with a default logger that seems to be completely unreachable to override or configure... (at least as far as I could see/find).

Am I missing something, and is it possible to change the log level of the RPC server? (without overriding this line, which is my current 'solution')

**Comment by vtolstov** [comment]
i'm plan to fix this, by providing logger option to client and server (also for broker at least) so you can have different log levels for each component
