### ISSUE TITLE
Consider removing unnecessary log level judges

### ISSUE THREAD

**Issue by FlyingOnion** [micro/go-micro#1907]
At least 3 `if` statements are found:
1. call of `logger.V`.
2. all `Helper` funcs: `Info`, `Infof`, etc.
3. and `if` in [`Log`](https://github.com/micro/go-micro/blob/master/logger/default.go#L83) and [`Logf`](https://github.com/micro/go-micro/blob/master/logger/default.go#L124), and these two `if`s are using different logics.

I think reserving the `if` in `Log` and `Logf` is enough.

**Comment by vtolstov** [comment]
logger.V needs only internally and for people that wants to avoid allocations for disabled log levels.
Because if you says logger.Debugf("SOME STRING :%v", xxx) and not use debug log level you allocate memory.
