### ISSUE TITLE
 dial tcp 127.0.0.1:8500: getsockopt: connection refused

### ISSUE THREAD

**Issue by liang68** [micro/go-micro#191]
### the problem background
&nbsp;&nbsp;&nbsp;&nbsp; the discovery component used nats not consul，such as --register=nats
### the operation process
1. using the prepared plugins.go file which is plugin file and to compile the executable binaries:  **common-nats**
2. `./client-nats  --transport=nats --registry=nats` , is success
```
2017/07/24 11:43:30 Listening on _INBOX.3pxECOH4edFGINs1fU7lkh
2017/07/24 11:43:30 Broker Listening on [::]:50563
2017/07/24 11:43:30 Registering node: go.micro.api.greeter-42bd0864-7022-11e7-a6fa-784f435cc863
```
this default namespace is : **go.micro.api.greeter**
3. also start namespace with different names(I'm using a system parameter to generate the namespace name that I need)  
`./client-nats mdd --transport=nats --registry=nats`
```
2017/07/24 11:51:56 Listening on [::]:52648
2017/07/24 11:51:56 Broker Listening on [::]:52649
2017/07/24 11:51:56 Registering node: go.micro.api.mddApi-6fd56a93-7023-11e7-a963-784f435cc863
2017/07/24 11:51:56 Put http://127.0.0.1:8500/v1/agent/service/register: dial tcp 127.0.0.1:8500: getsockopt: connection refused
```
my own namespace name is: **go.micro.api.mddApi**

&nbsp;&nbsp;&nbsp;&nbsp;As can be seen from the above results, even if i don't use the default discovery component consul, but namespace registration will also be written to the default discovery component consul。How can i solve the problem?

**Comment by asim** [comment]
I'm sorry but it's really hard to decipher what the problem is from your comment. The log output is indicating to you that it's trying to use the default registry (consul) as you've mentioned. This implies either the nats plugin is not being imported or not being selected correctly. 

```./client-nats mdd --transport=nats --registry=nats``` 

This line implies you are doing some sort of command line parsing yourself for "mdd". It also suggests that whatever you're doing is ignoring the flags or stopping the service from parsing flags.

**Comment by liang68** [comment]
Thank you for your reply, you remind me that "mdd" parameter may affect the following parameters. I will try it and feedback will be given

**Comment by liang68** [comment]
It's really "mdd" parameter that causes it, I'am use micro action deal with it and it's good work. thank you for much.
