### ISSUE TITLE
Prevent api being exposed to outside world

### ISSUE THREAD

**Issue by kamilikamil** [micro/go-micro#1914]
Hey guys,

Just checking out `go` and this framework in particular.

I was wondering how I would be able to do this.

Let's say I make 3 services, `api-service`, `users-service`, and `clients-service`. Is there a way for me to prevent others from discovering the `users-service` and `clients-service` via `http/rpc`? In this case, everyone will talk to `api-service` which will route to `users-service` or `clients-service` depending on some conditions?

**Comment by asim** [comment]
This comes down to the way you choose to expose something. We have an api package which lets you write an api if you want to expose via http.
