### ISSUE TITLE
How do you pass CLI flags to handers in services

### ISSUE THREAD

**Issue by yarbelkgazia** [micro/go-micro#193]
For example, how do I use the Consul Registry address inside my handler, where I use consul for various things.

**Comment by asim** [comment]
Something like this. The Action option lets you act on the command line context which contains flags.

Please look at these docs and the example below 

http://godoc.org/github.com/micro/go-micro#Action
http://godoc.org/github.com/micro/cli#Context
https://github.com/micro/go-micro/blob/master/cmd/cmd.go#L127

```
h := new(Handler)

s := micro.NewService(
    micro.Action(func(ctx *cli.Context) error {
        flag := ctx.StringFlag("registry_address")
        h.flag = flag
    })
)
```
