### ISSUE TITLE
where is document about v3

### ISSUE THREAD

**Issue by brightshin** [micro/go-micro#1956]
Before asking, please check if your question has already been answered: 

1. Check the documentation - https://micro.mu/docs/
2. Check the examples and plugins - https://github.com/micro/examples & https://github.com/micro/go-plugins
3. Search existing issues

**Comment by asim** [comment]
Use pkg.go.dev for anything related to go-micro https://pkg.go.dev/github.com/micro/go-micro/v3?tab=overview

We are no longer providing docs for go-micro since its simply a library with packages. We'll provide v3 docs for Micro once its stabilised.
