### ISSUE TITLE
how to caught grpc error in micro service?

### ISSUE THREAD

**Issue by uxgnaw** [micro/go-micro#1971]
when grpc error, such as "grpc: failed to unmarshal the received message unknown field", micro service will return err to "micro api", how to log it in micro service ?

**Comment by asim** [comment]
Write a wrapper that looks for the error

**Comment by uxgnaw** [comment]
> Write a wrapper that looks for the error

handler wrapper ( server.HandlerFunc) can't caught err. any other wrapper can do this ?

**Comment by asim** [comment]
Use grpc directly? Use a different codec? PR someway to make it possible to catch?

**Comment by uxgnaw** [comment]
> Use grpc directly? Use a different codec? PR someway to make it possible to catch?

i use micro default grpc server. codec i do some change. but codec should't cause it.
if there don't have any method to cautch, i can PR it
