### ISSUE TITLE
Sample about authentication

### ISSUE THREAD

**Issue by cesc1802** [micro/go-micro#1980]
do you have any sample about authentication? please provide how to use the authentication module. thanks

**Comment by ihippik** [comment]
I'm trying to run the `helloworld` example on version 3 and at startup I get the error:
`
file=cmd/cmd.go:485 level=fatal Error setting up auth: {"Id":"go.micro.client","Code":500,"Detail":"{\"Id\":\"go.micro.client\",\"Code\":500,\"Detail\":\"error getting next auth node: failed getting services: {\\\"Id\\\":\\\"registry.Registry.GetService\\\",\\\"Code\\\":401,\\\"Detail\\\":\\\"An account is required\\\",\\\"Status\\\":\\\"Unauthorized\\\"}\",\"Status\":\"Internal Server Error\"}","Status":"Internal Server Error"}
`
also did not find any startup examples

**Comment by dilshat** [comment]
Why are you closing the issue about Unauthorized?
It still persists with version 3.0.4

**Comment by asim** [comment]
3.0.4 of what? Go-micro has no version 3.0.4

**Comment by spyyps** [comment]
Hi, I generated the source code of helloworld by "micro new helloworld" minutes ago, then got this error: 2021-02-24 01:03:16  file=cmd/cmd.go:451 level=fatal Error setting up auth: {"Id":"auth.Auth.Generate","Code":401,"Detail":"An account is required","Status":"Unauthorized"}

I stuck here:
![image](https://user-images.githubusercontent.com/5793001/108883712-c16c0b00-7640-11eb-9117-a76c93b7b272.png)
