### ISSUE TITLE
please have a look, "panic: qtls.ConnectionState not compatible with tls.ConnectionState"

### ISSUE THREAD

**Issue by huyuanxin** [micro/go-micro#1985]
I find a same issue, but it doesn't work, so please take a look

go version 1.15
go run main.go

goroutine 1 [running]:
github.com/lucas-clemente/quic-go/internal/handshake.init.1()
        E:/Golang/pkg/mod/github.com/lucas-clemente/quic-go@v0.13.1/internal/handshake/unsafe.go:17 +0x139
exit status 2

go version 1.12.1
go version 1,12.17 
go version 1.13
go run main.go
cannot load crypto/ed25519

**Comment by vtolstov** [comment]
You have two steps:
1) use go 1.14
2) update quic-go package to latest release, author fixed the issue with go 1.15

**Comment by asim** [comment]
quic has been removed from go-micro in version 3

**Comment by huyuanxin** [comment]
Thanks
