### ISSUE TITLE
registry: services cache/watch

### ISSUE THREAD

**Issue by crackcomm** [micro/go-micro#2]
What do You think about caching service nodes on the client side and watching them when possible ?
It is possible when using consul or etcd, I don't know about kubernetes.
Or maybe there is already a mechanism for that in Consul client for example but I am not aware ?

**Comment by asim** [comment]
Yea this is definitely possible and would be the appropriate way to handle discovery client side. I left it as a second step for optimisation. I will look into this shortly.

**Comment by asim** [comment]
This is now complete. Both kubernetes and consul watchers are in the registry with caching.
