### ISSUE TITLE
Options are discarded

### ISSUE THREAD

**Issue by vans9** [micro/go-micro#200]
https://github.com/micro/go-micro/blob/e3f818d18e7137f860c5db67d52af6b642c47c38/go-micro.go#L84

This utility func is useful, but discards passed options. Shouldn't we pass options to the s.NewSubscriber(...) ?

**Comment by asim** [comment]
Feel free to submit a PR otherwise I will fix later on today

**Comment by vans9** [comment]
Ok, done
