### ISSUE TITLE
How to configure https endpoint for etcd registry

### ISSUE THREAD

**Issue by bharath-b23** [micro/go-micro#2007]
Hello!!

I am using go-micro v1.18.0 and etcd v3.4.0. I have configured secure transport at etcd and trying to configure the same for go-micro to use https endpoint when communicating with etcd. Tried configuring like below, but connection is being rejected by etcd.

### Starting a server with below command
./server --registry=etcd --registry_address=https://etcd:2379 --server_address=server:8080

### Error reported in server logs
2020-09-16 19:49:43.327662 I | Transport [http] Listening on x.x.x.x:8080
2020-09-16 19:49:43.327797 I | Broker [http] Connected to [::]:42377
2020-09-16 19:49:43.328300 I | Registry [etcd] Registering node: server-2318e1fe-2e03-4cce-93cb-a1ef70c09fd8
{"level":"warn","ts":"2020-09-16T19:49:48.336Z","caller":"clientv3/retry_interceptor.go:61","msg":"retrying of unary invoker failed","target":"endpoint://client-c46274f8-7437-4674-a7f5-2afe4a45d771/etcd:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest connection error: connection closed"}
2020-09-16 19:49:48.336437 I | Server server-2318e1fe-2e03-4cce-93cb-a1ef70c09fd8 register error: context deadline exceeded
^C2020-09-16 19:49:50.347222 I | Registry [etcd] Deregistering node: server-2318e1fe-2e03-4cce-93cb-a1ef70c09fd8

### Error reported in etcd logs
{"level":"warn","ts":"2020-09-16T19:49:53.944Z","caller":"embed/config_logging.go:279","msg":"rejected connection","remote-addr":"x.x.x.x:35138","server-name":"","error":"tls: first record does not look like a TLS handshake"}

Error "tls: first record does not look like a TLS handshake" is usually reported when the server is expecting an https connection, but received http instead.

Please let me know, how to configure go-micro to use secure transport to interact with etcd.

Thanks in advance.

**Comment by zhoub** [comment]
`--registry_address=https://etcd:2379` should be `<IP>:<PORT>`
