### ISSUE TITLE
[FEATURE] Dependent package chacha20 doesn't have a license file included.

### ISSUE THREAD

**Issue by bharath-b23** [micro/go-micro#2017]
One of the dependent package "github.com/lucas-clemente/quic-go" imported in the code which has MIT license is making use of another package "github.com/marten-seemann/chacha20", which doesn't has a license file included in the root directory of its repository and it has been archived. 

And according to github documentation regarding licensing it says, if LICENSE is missing, the project can't be used freely. Below is the excerpt
```
You're under no obligation to choose a license. However, without a license, the default copyright laws apply, 
meaning that you retain all rights to your source code and no one may reproduce, distribute, or create 
derivative works from your work. If you're creating an open source project, we strongly encourage you 
to include an open source license.
```

github.com/lucas-clemente/quic-go in the latest v0.18.0 version has removed the dependency on github.com/marten-seemann/chacha20 package.

Would it be possible to update the github.com/lucas-clemente/quic-go to latest, so that the license issue can be resolved?

**Comment by asim** [comment]
master no longer contains quic-go, so this is a non issue
