### ISSUE TITLE
Bug on web.NewService

### ISSUE THREAD

**Issue by zhoub** [micro/go-micro#2039]
Consider we have a web service
```
	svc := web.NewService(
		web.Name("go.micro.web.hello"),
		web.Version("0.1.0"),
	)
```

This service is accessible from `http://192.168.1.1:8082/hello`

But if change it to
```
	svc := web.NewService(
		web.Name("go.micro.web.v1.hello"),
		web.Version("0.1.0"),
	)
```

This service is accessible from `http://192.168.1.1:8082/v1/hello` returns error
```
192.168.1.123 - - [09/Oct/2020:19:10:48 +0900] "POST /v1/hellow HTTP/1.1" 502 0 "" ""
2020-10-09 19:10:48.723530 I | http: proxy error: unsupported protocol scheme ""
```

Any ideas ? Thanks in advance !

**Comment by vtolstov** [comment]
why you thinks that url depends on server name?

**Comment by zhoub** [comment]
Hi

Just would like to use version in namespace in web.XXXX as API service.

According the page https://github.com/microhq/docs/blob/a51db3ae57254494d2147542005f15a2073c3dbe/v2/framework/api.md

RPC Resolver works for version v1, but Proxy Resolver doesn't, is this true ? Thanks

**Comment by Kuri-su** [comment]
> Hi
> 
> Just would like to use version in namespace in web.XXXX as API service.
> 
> According the page https://github.com/microhq/docs/blob/a51db3ae57254494d2147542005f15a2073c3dbe/v2/framework/api.md
> 
> RPC Resolver works for version v1, but Proxy Resolver doesn't, is this true ? Thanks

this docs just talk about  `github.com/micro/micro` project in  CLI mode.

for web services, just request your registered route or handler .
