### ISSUE TITLE
micro api returned json int value transform to string

### ISSUE THREAD

**Issue by Verystone** [micro/go-micro#2041]
micro version:  v2.9.3
go-micro version: v2.9.1

response struct is below

type Response struct {
	Code                 int64          `protobuf:"varint,1,opt,name=code,proto3" json:"code"`
	Msg                  string         `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg"`
	Time                 int64          `protobuf:"varint,3,opt,name=time,proto3" json:"time"`
	Total                int64          `protobuf:"varint,4,opt,name=total,proto3" json:"total"`
	Data                 *Response_Data `protobuf:"bytes,5,opt,name=data,proto3" json:"data"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

but through the micro api,  result transform to string
{
    "code": "200",
    "time": "862",
    "total": "1"
}

how to remain the int value as it is

**Comment by vtolstov** [comment]
use uint64 because protobuf to json marshaling transform int64 to string to avoid overflow

**Comment by Verystone** [comment]
> use uint64 because protobuf to json marshaling transform int64 to string to avoid overflow

I change the proto file, the new struct is below,   but is still string

type Response struct {
	Code                 uint64         `protobuf:"varint,1,opt,name=code,proto3" json:"code"`
	Msg                  string         `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg"`
	Time                 uint64         `protobuf:"varint,3,opt,name=time,proto3" json:"time"`
	Total                uint64         `protobuf:"varint,4,opt,name=total,proto3" json:"total"`
	Data                 *Response_Data `protobuf:"bytes,5,opt,name=data,proto3" json:"data"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

![image](https://user-images.githubusercontent.com/50290954/95959037-8bb64a80-0e34-11eb-84d4-8cfca85395eb.png)

micro shell is :  micro --registry=etcd --registry_address=127.0.0.1:2379 api --address=0.0.0.0:9996 --handler=api --enable_rpc

curl:
`curl -X POST http://127.0.0.1:9996/rpc \
-H "Content-Type:application/json" \
-d '{
    "service": "hello.srv",
    "method": "Greet.All",
    "request": {}
}'`

**Comment by vtolstov** [comment]
in this case you need to provide full example, because this is
unexpected and in my services i don't have such issue

ср, 14 окт. 2020 г. в 10:47, Verystone <notifications@github.com>:
>
> use uint64 because protobuf to json marshaling transform int64 to string to avoid overflow
>
> I change the proto file, the new struct is below, but is still string
>
> type Response struct {
> Code uint64 protobuf:"varint,1,opt,name=code,proto3" json:"code"
> Msg string protobuf:"bytes,2,opt,name=msg,proto3" json:"msg"
> Time uint64 protobuf:"varint,3,opt,name=time,proto3" json:"time"
> Total uint64 protobuf:"varint,4,opt,name=total,proto3" json:"total"
> Data *Response_Data protobuf:"bytes,5,opt,name=data,proto3" json:"data"
> XXX_NoUnkeyedLiteral struct{} json:"-"
> XXX_unrecognized []byte json:"-"
> XXX_sizecache int32 json:"-"
> }
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.



-- 
Vasiliy Tolstov,
e-mail: v.tolstov@selfip.ru

**Comment by Verystone** [comment]
I create a demo project, please see the attachment.

micro version: v2.9.3-e60b2ca-1593774648

service: `go run main.go`
micro: `micro api --handler=api --enable_rpc`
client: `curl -X POST http://127.0.0.1:8080/rpc \
-H "Content-Type:application/json" \
-d '{
    "service": "go.micro.service.hello",
    "method": "Hello.Call",
    "request": {}
}'`


![image](https://user-images.githubusercontent.com/50290954/95974944-253b2780-0e48-11eb-8efb-2b00af30b868.png)



[micro_hello.zip](https://github.com/micro/go-micro/files/5377317/micro_hello.zip)

**Comment by vtolstov** [comment]
ah sorry, but for micro/micro usage i can't help

**Comment by Verystone** [comment]
Thank you
