### ISSUE TITLE
Suggest allow unknown fields pass jsonpb.Unmarshal

### ISSUE THREAD

**Issue by wudi** [micro/go-micro#2042]
https://github.com/micro/go-micro/blob/1a962e46fd3add04e9dca78027bbd6e3ade2256e/server/grpc/grpc.go#L69-L73
https://github.com/micro/go-micro/blob/1a962e46fd3add04e9dca78027bbd6e3ade2256e/server/grpc/codec.go#L95-L103

Hi there

grpc server register `jsonCodec` using grpc `encoding.RegisterCodec` and `jsonCodec` use default `jsonpb.Unmarshal` directly.

The following error occurred while client request json contains unknown fields.
req: `{"_none": "test", "name": "hello"}`

error: 
```json
{
  "id": "go.micro.client",
  "code": 500,
  "detail": "grpc: failed to unmarshal the received message unknown field \"_none\" in DemoReq",
  "status": "Internal Server Error"
}

```

Sometimes 

- remove fields for API upgrade, but client not upgrade immediately. So the request will contains unknown fields.
- use super set map/object request directly
- etc..

So  suggest allow unknown fields

```go
jsonpbUnmarshaler = &jsonpb.Unmarshaler{
    AllowUnknownFields: true,
}

jsonpbUnmarshaler.Unmarshal(b.NewReader(data), pb)
```

**Comment by vtolstov** [comment]
yes, this is useful. but i don't think that this will be fixed in current repo

**Comment by wudi** [comment]
> yes, this is useful. but i don't think that this will be fixed in current repo

So any other repos or stage?

**Comment by vtolstov** [comment]
i'm let asim to answer you question

**Comment by gwsee** [comment]
go.micro.client.codec","code":500,"detail":"unknown field;
when i use  protoc-go-inject-tag rewrite tags to new tag name, how to solve this problem?

**Comment by gwsee** [comment]
> 

Well, I solved this problem; This is mainly because it defaults to the application/json parsing method; Set it to application/grpc or application/grpc+json

**Comment by whiteCcinn** [comment]
```go
service := micro.NewService(
		micro.Client(client.NewClient(client.ContentType("application/protobuf"))),
	)
```

I solved the problem in this way

Supported message types:

https://github.com/go-micro/go-micro/blob/master/client/rpc_codec.go#L53-L77
