### ISSUE TITLE
https://github.com/asim/examples/greeter时不时出现下面的错误，连接不稳定

### ISSUE THREAD

**Issue by 18318553760** [micro/go-micro#2046]
{"id":"go.micro.client","code":500,"detail":"service go.micro.srv.greeter: not found","status":"Internal Server Error"}null

**Comment by Kuri-su** [comment]
please check you registry status , error log say  `service go.micro.srv.greeter: not found`

**Comment by Kuri-su** [comment]
@asim this issue can be closed
