### ISSUE TITLE
How to use rabbitmq / rabbitmq delayed message exchange to do the delay task

### ISSUE THREAD

**Issue by echobool** [micro/go-micro#2052]
I want to use rabbitmq / rabbitmq delayed message exchange to do delayed tasks. How can I use it rabbitmq.NewBroker Can you give me an example? thank you

It's now being used“ github.com/micro/go -Plugins / broker / rabbitmq / V2 "

`rabbitmq.DefaultRabbitURL = os.Getenv ("RABBIT_ URL")

rabbitmq.DefaultExchange = rabbitmq.Exchange {Name: exchange}

b := rabbitmq.NewBroker ( rabbitmq.DurableExchange ())`

**Comment by asim** [comment]
I believe fixed in go-plugins
