### ISSUE TITLE
where is micro.NewService in v3?

### ISSUE THREAD

**Issue by Deprecated-Repositories** [micro/go-micro#2053]
this is v2 version code
```
package main

import (
	"github.com/micro/go-micro"
	"github.com/micro/go-plugins/registry/etcdv3"
	"log"
	"time"
)

func main() {
	registre := etcdv3.NewRegistry()

	service := micro.NewService(
		micro.Registry(registre),
		micro.Name("greeter"),
		micro.RegisterTTL(time.Second*30),
		micro.RegisterInterval(time.Second*15),
	)
	service.Init()
	if err := service.Run(); err != nil {
		log.Fatal(err)
	}
}
```

but in v3, i can't find micro.NewService this function. where is it?

By the way, in this document(https://pkg.go.dev/github.com/asim/go-micro/v3), i can't find any information about get started. I like go-micro , i want to learn it ....   but i dont know what should i do first in v3.

**Comment by Kuri-su** [comment]
about v3 examples, maybe you can look at here  https://github.com/micro/services/blob/master/helloworld/main.go

**Comment by Deprecated-Repositories** [comment]
> about v3 examples, maybe you can look at here https://github.com/micro/services/blob/master/helloworld/main.go

I saw this, but i want to use Etcd instead of Micro... I think service.New() Can only be used for Micro

**Comment by Kuri-su** [comment]
> > about v3 examples, maybe you can look at here https://github.com/micro/services/blob/master/helloworld/main.go
> 
> I saw this, but i want to use Etcd instead of Micro... I think service.New() Can only be used for Micro

i'm sorry :joy:

v3 examples is here
```go
package main

import (
	"github.com/micro/go-micro/v3/service"
	"github.com/micro/go-micro/v3/service/mucp"
	"github.com/micro/go-plugins/registry/etcd/v3"
	"log"
	"time"
)

func main() {
	registry := etcd.NewRegistry()

	svc := mucp.NewService(
		service.Name("greeter"),
		service.Registry(registry),
		service.RegisterTTL(time.Second*30),
		service.RegisterInterval(time.Second*15),
	)
	svc.Init()
	if err := svc.Run(); err != nil {
		log.Fatal(err)
	}
}

```

and the examples repo look like it hasn't been updated yet  (https://github.com/asim/examples)

**Comment by Kuri-su** [comment]
by the way, about pkg.go.dev question, maybe you can watch here #2055

**Comment by asim** [comment]
The move from top level service definition to a package is because go-micro has grown beyond the few primitives we had and encapsulating them in a service is quite hard so seemed more appropriate as a package. I may revert that if there's more demand. The other thing was the flag and command line parsing became very complex and most people were happy to deal with it themselves.
