### ISSUE TITLE
Documentation unavailable : not displayed due to license restrictions

### ISSUE THREAD

**Issue by scorsi** [micro/go-micro#2055]
Hello,

This is not a #1956 or #1953 duplicate. :) 

I tried to access : https://pkg.go.dev/github.com/micro/go-micro/v3?tab=overview
But the documentation is unavailable due to license restrictions.

Thanks,

**Comment by asim** [comment]
Yes. Unfortunately Polyform Strict is not recognised as an open source license https://spdx.org/licenses/

But Polyform Noncommercial is. So I may switch to that. v3 is strictly licensed by default.

**Comment by scorsi** [comment]
Is there another way to access to the documentation ?

**Comment by asim** [comment]
I've pushed a new version 3.2.0 with the noncommercial licensed and hard refreshed on pkg.go.dev. It should display shortly.

https://pkg.go.dev/github.com/asim/go-micro/v3@v3.2.0

**Comment by asim** [comment]
It looks like the license restriction goes further https://pkg.go.dev/license-policy

**Comment by asim** [comment]
The alternative might be self hosting and removing the license restrictions since its open source https://github.com/golang/pkgsite

**Comment by scorsi** [comment]
Ok, you dont want to use another license I guess. :)
What about self hosting the documentation does it seems complicated ? You already have a website actually.

Let me know if you need some help

**Comment by asim** [comment]
No the goal now is to use Polyform licenses over anything else. The only pain is the documentation side. If I could self host docs or there was one hosted version of the pkgsite that doesn't do license checks that would be useful.

Have you hosted the pkg site or know of alternative docs?

**Comment by scorsi** [comment]
I don't have a self-hosted go doc nor known one. The only one alternative free and useful, is a hand-written on GitHub Wiki ? It's very time-consuming but may allow a better doc.

Can asim/go-micro can found it's place in the micro/micro doc/website (https://m3o.org/) ? (I must admit I don't know both since I was looking for documentations/examples for both :D )

**Comment by asim** [comment]
I think for v3 I'll figure out some alternative. Maybe taking the effort to self host pkg.go.dev or writing some new examples or similar. It's not clear yet. Its back to being a personal project and unrelated to m3o.org.

**Comment by asim** [comment]
I am now self hosting godoc https://go-micro.dev/docs/v3/. If this goes down just create an issue. Otherwise please close if satisfied.

**Comment by scorsi** [comment]
Awesome !

It is written that the documentation is licensed under CCA 3.0 (that's ok I guess) and code is under BSD.. The code is under Polyform right ?

**Comment by asim** [comment]
Yes, the page is auto generated by godoc so these are in relation to the actual doc generator and server. Go Micro is polyform noncommercial.

**Comment by scorsi** [comment]
Can you change it from BSD to Polyform ? (On the footer of the doc)

**Comment by asim** [comment]
The statement is in reference to godoc itself, as in the code and content created by Google that hosts documentation. So I can't actually remove that. Its the license for their software.

**Comment by scorsi** [comment]
Oh I didn't thought like that but yeah you're right thats about GoDoc itself not go-micro 😁

So it's all ok for me so ! The issue is resolved. Thanks.
