### ISSUE TITLE
How to use grpc to create new service?

### ISSUE THREAD

**Issue by illegaluid** [micro/go-micro#2060]
my code like this

```
//....
import (
	"github.com/asim/go-micro/v3/service" 
	"github.com/asim/go-plugins/service/grpc/v3" 
)

func main() { 
	svc := grpc.NewService(
		service.Name("greeter"), 
	)
	//....
}

```

I got this errors 

```
go: github.com/asim/go-plugins/service/grpc/v3@v3.0.0-00010101000000-000000000000 requires
        github.com/asim/go-plugins/client/grpc/v3@v3.0.0-00010101000000-000000000000: invalid version: unknown revision 000000000000

```

I have tried to ` go tidy` service/grpc , but it still  doesn't work

**Am I use the right way  to create service by grpc** or maybe it's a bug or something ?

Please help ~

**Comment by Kuri-su** [comment]
wait a moment , this issue is be fixing

**Comment by Kuri-su** [comment]
@illegaluid it will be fix when https://github.com/asim/go-plugins/pull/599 be merge,

**Comment by Kuri-su** [comment]
@illegaluid 

remove about `asim/go-plugins` require in go.mod , and remove go.sum file , then try `go mod tidy` again

**Comment by illegaluid** [comment]
@Kuri-su  thanks
