### ISSUE TITLE
Does go-micro v3 support etcd?

### ISSUE THREAD

**Issue by xujiangze** [micro/go-micro#2061]
I use go-micro v3.2.0. Can't not find etcd package in registry package.

**Comment by Kuri-su** [comment]
please check here : https://github.com/asim/go-plugins/tree/master/registry/etcd

> ### Where are all the plugins?
> The plugins now live in github.com/asim/go-plugins. This was to reduce the overall size and scope of Go Micro to purely a set of interfaces and standard library implementations. Go Plugins is Apache 2.0 licensed but relies on Go Micro interfaces and so again can only be used in noncommercial setting without a commercial license.

**Comment by xujiangze** [comment]
thx 👍
