### ISSUE TITLE
[BUG] Install nitro doesn't work with go mod

### ISSUE THREAD

**Issue by brandon-welsch** [micro/go-micro#2077]
**Describe the bug**

1. What are you trying to do?

Install nitro using go mod and use it with example from the README

2. What did you expect to happen?

Install nitro correctly using go mod

3. What happens instead?

```shell 
go: finding module for package github.com/asim/nitro/v3/app/rpc
go: finding module for package github.com/asim/nitro/v3/app/rpc
main.go:6:2: module github.com/asim/nitro/v3@latest found (v3.3.0), but does not contain package github.com/asim/nitro/v3/app/rpc
```

**How to reproduce the bug:**

Create a `main.go` file with example code from README and execute:

```shell
go mod init
go get ./...
```

**Environment:**
Go Version: `go version go1.15.3 linux/amd64`

Go env:
```shell
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/brandon/.cache/go-build"
GOENV="/home/brandon/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/brandon/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/brandon/go"
GOPRIVATE=""
GOPROXY="direct"
GOROOT="/usr/lib/go"
GOSUMDB="off"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build068420965=/tmp/go-build -gno-record-gcc-switches"
```

**Comment by asim** [comment]
New tag has been pushed, it did not yet contain app/rpc. This interface may change in future since its new.

**Comment by brandon-welsch** [comment]
Thanks, it works :)

One last thing, how to make a gRPC server with version 3 of the package?

I currently have a gRPC server but running version 2 of the package and the implementation is not exactly the same, and despite the examples I can't understand how to do this correctly.

**Comment by asim** [comment]
V3 does not include a service definition, so you just need to make use of the client and server independently.

```
import (
        gc "github.com/asim/nitro-plugins/client/grpc/v3"
        gs "github.com/asim/nitro-plugins/server/grpc/v3"
)

client := gc.NewClient()
server := gs.NewServer()
```

Note, v3 is noncommercial, so if you're using it for commercial purposes you need to pay for a license.
