### ISSUE TITLE
Can nitro be used for the development of company projects

### ISSUE THREAD

**Issue by kooksee** [micro/go-micro#2086]
I found that there is a **Noncommercial** description in the nitro license, I don’t understand, whether it can be used for the development of company projects, thank you

**Comment by crazybber** [comment]
yes，your company need to pay for a license

**Comment by asim** [comment]
As @crazybber said, being licensed as "noncommercial" means you can use it for personal use or non-profit companies. For anything commercial, e.g your business, you must pay for a license. I am addressing this on a case by case basis. If you'd like to discuss further let me know.
