### ISSUE TITLE
what happend?!!!!!i can't find code like plugins example again????!!!

### ISSUE THREAD

**Issue by lonerwolf** [micro/go-micro#2087]
what happend?!!!!!i can't find code like plugins example again????!!!
a complete rewrite?!
no no no
I'm already on the project -。-！！！！

**Comment by asim** [comment]
go-micro was deprecated, plugins deprecated, please see github.com/microhq for any relevant content

**Comment by lonerwolf** [comment]
> microhq

no microhq。 i want find nitro。i update git repository，some code is disappear

**Comment by asim** [comment]
Nitro won't be pluggable for the time being. Its too much effort maintaining legacy plugins as the interfaces change.
