### ISSUE TITLE
google.golang.org/grpc/naming not found

### ISSUE THREAD

**Issue by iGoogle-ink** [micro/go-micro#2091]
Before asking, please check if your question has already been answered: 

1. Check the documentation - https://micro.mu/docs/
2. Check the examples and plugins - https://github.com/micro/examples & https://github.com/micro/go-plugins
3. Search existing issues

there is somethin wrong:
google.golang.org/grpc/naming: module google.golang.org/grpc@latest found (v1.34.0), but does not contain package google.golang.org/grpc/naming

**Comment by kooksee** [comment]
google.golang.org/grpc@latest found (v1.34.0)，The version is too high。

The suitable versions of etcd and grpc are
google.golang.org/grpc v1.26.0
github.com/coreos/etcd v3.3.25+incompatible

**Comment by iGoogle-ink** [comment]
> google.golang.org/grpc@latest found (v1.34.0)，The version is too high。
> 
> The suitable versions of etcd and grpc are
> google.golang.org/grpc v1.26.0
> github.com/coreos/etcd v3.3.25+incompatible

I know your mean, but my other base service used the higher version, so I can't change the lower version of 
`google.golang.org/grpc`
I want to know if the go- micro would upgrade ?

**Comment by lzle** [comment]
I have the same question

**Comment by ecasilla** [comment]
Quick work around for anyone stuck on this

go.mod
replace google.golang.org/grpc => google.golang.org/grpc v1.26.0

https://github.com/etcd-io/etcd/issues/12124
