### ISSUE TITLE
Is go-micro ready to END?

### ISSUE THREAD

**Issue by wudi** [micro/go-micro#2095]
Follow recent activities of go-micro. Is to bad to developer use go-micro framework.

Repo Changelog

```
micro/go-micro   
    -> asim/go-micro(remove multi components)  
       -> gonitro/nitro 
           -> asim/go-micro (revert multi components)
```

Like in China, many dev teams **MUST** give up to the other framework for business.
Is go-micro have any futures for these inconclusive activities?

:(

**Comment by asim** [comment]
https://github.com/asim/go-micro/discussions/2090
