### ISSUE TITLE
Auth Example

### ISSUE THREAD

**Issue by TerminalFi** [micro/go-micro#2096]
There doesn't seem to be any simple examples of how to use the auth functionality here. Can you provide a simple short example?

**Comment by asim** [comment]
Not yet. Doing some cleanup. Trying to find the right integration path.

**Comment by T-M-A** [comment]
have any news?

**Comment by AuditeMarlow** [comment]
So far no example has been provided for the auth functionality. We are happy to accept PRs however.

**Comment by abrahamSN** [comment]
still waiting the example.

**Comment by asim** [comment]
Stale
