### ISSUE TITLE
when Generate the proto file in CentOS Linux release 7.4,  there is no RegisterxxxHandler function in xxx.pb.go

### ISSUE THREAD

**Issue by xiaogang12** [micro/go-micro#210]
hi gays, 
   when I use "protoc --go_out=plugins=micro:. hello.proto"  to generate the proto file in CentOS Linux release 7.4, there is not RegisterSayHandler function in hello.pb.go.
   but it is normal in ubuntu.

**Comment by asim** [comment]
Then you are not using the right version of protoc-gen-go. We have a fork https://github.com/micro/protobuf
