### ISSUE TITLE
[BUG] Build fails on Illumos

### ISSUE THREAD

**Issue by francescocarzaniga** [micro/go-micro#2100]
**Describe the bug**

When compiling on Illumos (more specifically OmniOS), the build fails with
```
# github.com/hpcloud/tail
/root/go/pkg/mod/github.com/hpcloud/tail@v1.0.0/tail.go:127:17: undefined: OpenFile
/root/go/pkg/mod/github.com/hpcloud/tail@v1.0.0/tail.go:191:20: undefined: OpenFile
```

This stops [owncloud-ocis](https://github.com/owncloud/ocis/issues/1164) from building on Illumos.

**Environment:**
Go Version: go version go1.15.5 solaris/amd64
```
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="solaris"
GOINSECURE=""
GOMODCACHE="/root/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="solaris"
GOPATH="/root/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/opt/local/go115"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/opt/local/go115/pkg/tool/solaris_amd64"
GCCGO="/usr/bin/gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/tmp/go-micro_temp/go-micro/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build693290589=/tmp/go-build -gno-record-gcc-switches"
```

**Comment by francescocarzaniga** [comment]
The issue comes from hpcloud/tail. 
Copy pasting what I said in the owncloud ticket:

> There has been an [issue ](https://github.com/hpcloud/tail/issues/161) open in hpcloud/tail for more than a year and a half at this point, and the package itself has not been updated in more than two years. [This ](https://github.com/nxadm/tail) seems to be a viable fork, whose inclusion would fix the above error.

@asim It seems you already use nxadm/tail but probably have not migrated everything over from hpcloud/tail.

**Comment by asim** [comment]
PR a fix?

**Comment by francescocarzaniga** [comment]
@asim Unfortunately I only have a cursory understanding of Go, I would not touch a codebase this complex. Of course this is not a priority for you - rightfully so - but since you already know the code well nxadm/tail should be a drop-in replacement so it shouldn't be too difficult.
