### ISSUE TITLE
Compatibility issue when using grpc-gateway

### ISSUE THREAD

**Issue by EwanValentine** [micro/go-micro#211]
I have the following protobuf: 

```
syntax = "proto3";
package models;

import "google/api/annotations.proto";

service Greeter {
	rpc Hello(HelloRequest) returns (HelloResponse) {
    option (google.api.http) = {
      get: "/api/v1/hello/{name}"
    };
  }
}

message HelloRequest {
	string name = 1;
}

message HelloResponse {
	string greeting = 2;
}
```

I'm generating go-micro code with the following commands: 
```
protoc -I/usr/local/include -I. -I$GOPATH/src \
  --go_out=plugins=micro:$GOPATH/src \
  -I$GOPATH/src/github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis \
  models/model.proto

protoc -I/usr/local/include -I. \
  -I$GOPATH/src \
  -I$GOPATH/src/github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis \
  --grpc-gateway_out=logtostderr=true:. \
  models/model.proto
```

I've effectively removed and updated all go-micro, protobuf and gprc-gateway libraries, but I'm getting a bunch of errors: 
```
models/model.pb.gw.go:53:54: cannot use grpc.Header(&metadata.HeaderMD) (type grpc.CallOption) as type client.CallOption in argument to client.Hello
models/model.pb.gw.go:53:88: cannot use grpc.Trailer(&metadata.TrailerMD) (type grpc.CallOption) as type client.CallOption in argument to client.Hello
models/model.pb.gw.go:80:31: cannot use ctx (type "context".Context) as type server.Server in argument to RegisterGreeterHandler:
	"context".Context does not implement server.Server (missing Deregister method)
models/model.pb.gw.go:80:31: cannot use mux (type *runtime.ServeMux) as type GreeterHandler in argument to RegisterGreeterHandler:
	*runtime.ServeMux does not implement GreeterHandler (missing Hello method)
models/model.pb.gw.go:80:31: cannot use conn (type *grpc.ClientConn) as type server.HandlerOption in argument to RegisterGreeterHandler
models/model.pb.gw.go:80:31: RegisterGreeterHandler(ctx, mux, conn) used as value
models/model.pb.gw.go:85:96: RegisterGreeterHandler redeclared in this block
	previous declaration at models/model.pb.go:120:75
models/model.pb.gw.go:86:64: not enough arguments in call to NewGreeterClient
	have (*grpc.ClientConn)
	want (string, client.Client)
```

Just wondered if this was an issue with my machine/set-up, or if there's been a regression in some of the libraries involved. 

I've created a test repo: https://github.com/EwanValentine/gateway-test 

Cheers in advance

**Comment by EwanValentine** [comment]
I'd have asked the Slack group this prior to raising a Git ticket as I'm aware this is potentially a non-issue, but I need to ask for access to that again as I'm on a new machine.

**Comment by asim** [comment]
The grpc-gateway is generating functions with the same name as go-micro which is why you're seeing this compile time issue. Separate the gateway and the service code generation.

**Comment by EwanValentine** [comment]
Ahh okay, I did suspect that, but then it seems to be generated within the same package/directory in the example: https://github.com/micro/examples/tree/master/grpc/gateway/proto/hello 

And when I separate them locally, it doesn't seem to resolve the package of the other generated code. So I get: 

```
./greeter.pb.gw.go:31:87: undefined: GreeterClient
./greeter.pb.gw.go:32:15: undefined: HelloRequest
./greeter.pb.gw.go:86:48: undefined: NewGreeterClient
./greeter.pb.gw.go:94:86: undefined: GreeterClient
```

**Comment by EwanValentine** [comment]
AHAA! Got it. Didn't realise you needed to generate using the standard grpc plugin for the grpc-gateway, and the go-micro plugin for the go-micro. That makes sense. Spotted it in these docs: https://micro.mu/docs/grpc-gateway.html
