### ISSUE TITLE
[BUG] rpc server does not return errors to the client

### ISSUE THREAD

**Issue by dh1tw** [micro/go-micro#2110]
## Update (22.02.2021)

While I'm mainly using the NATS plugin for transport, I can confirm that this problem also applies to any other, **including the default transport (grpc)**. I have updated the [super minimalistic demo app](https://github.com/dh1tw/go-micro-error-broken) to illustrate the problem.

## Bug description

Recently, I discovered that rpc calls, which result (on the server-side handler function) in an error, don't return the error back to the client. Hence the client always blocks until it hits the transport timeout. 
I think the source of the problem is located in [rpc_router.go](https://github.com/asim/go-micro/blob/master/server/rpc_router.go#L239-L245). See more details below.

## How to reproduce the bug

I have created a [minimalistic, runnable demo application](https://github.com/dh1tw/go-micro-error-broken) which demonstrates this problem. It's based on the greeter example application.

## Likely source of the problem

in [Pull Request #396](https://github.com/asim/go-micro/pull/396/files), the [func (s *service) call(...) method](https://github.com/asim/go-micro/blob/bba3107ae13fb9ce9e273106c4543c5c50a460bc/server/rpc_router.go#L202) in `rpc_router.go` was modified. Basically, if the executed handler function results in an error, the code never has the chance to reach the `router.sendResponse()` method anymore. 
I presume that therefore the error message never gets sent back to the client. Hence the client runs into the time-out.

Click [here for the lines in question](https://github.com/asim/go-micro/blob/bba3107ae13fb9ce9e273106c4543c5c50a460bc/server/rpc_router.go#L239-L245).

## Environment

Go Version: 1.16

```
GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/tobias/Library/Caches/go-build"
GOENV="/Users/tobias/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/tobias/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/tobias/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.16beta1"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/tobias/go/src/github.com/dh1tw/natsgreeter/cli/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/xd/2bg0hkdx52374p5rrj74sj_40000gn/T/go-build800051328=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

**Comment by osiloke** [comment]
This seems to be the intended behavior. In the example servers in this project, you will notice that none of them returns an error. 

I assume the server always has to return a valid response. 

As a workaround, I've added an error field to my proto definition.

**Comment by dh1tw** [comment]
Hey @osiloke, thanks for your comment! I honestly haven't thought that this behavior could actually be intended. I'm still trying to wrap my head around the idea why not returning an error would actually make sense. 
In almost all places, including the HTTP world, Errors (5xx) are actually considered valid return values. 

Would really be interesting to hear about the design thoughts which lead to the decision! 🤔

**Comment by dh1tw** [comment]
I've been investigating this problem a bit further. Actually, I get the expected behaviour when I replace the default rpc client and server with [plugins/client/grpc](https://github.com/asim/go-micro/tree/master/plugins/client/grpc) and [plugins/server/grpc](https://github.com/asim/go-micro/tree/master/plugins/server/grpc).

I added the branch [grpc-plugins](https://github.com/dh1tw/go-micro-error-broken/tree/grpc-plugins) using the grpc server and client plugin to my [minimalistic example](https://github.com/dh1tw/go-micro-error-broken) in case someone is interested in a working example.

The grpc server plugin propagates correctly the error to the client:
```
Hello John
{"id":"go.micro.client","code":500,"detail":"simulating an error","status":"Internal Server Error"}
```

Unfortunately, it doesn't solve the problem for me, because when using a transport plugins I'm stuck with the default rpc client / server. To me this still looks like a bug. I would be more than happy to submit a PR if someone could point me to the right place where to fix this issue. I still haven't completly understood the different layers of wrapping which happen in the rpc server and client.

**Comment by dh1tw** [comment]
I just stumbled over this video where Brian Ketelsen points out that the response should be "happy path" messages, not containing any error messages. Errors (from the server) will be returned as pretty wrapped error messages to the client. And that's exactly how go-micro used to work. 

https://youtu.be/OcjMi9cXItY?t=958

**Comment by osiloke** [comment]
Hi @dh1tw, you are correct. In the past, micro allowed you to return an error. I'm not sure why this was changed recently. It would be helpful if any core dev could shed some light on this issue. I know the repo is currently undergoing some changes and we might not get a feedback soon.

**Comment by asim** [comment]
Anyone can submit a PR to fix it. I'm no longer actively working on go-micro but accepting PRs

**Comment by liuaiyuan** [comment]
This problem is a headache, why is it not fixed? 😳

**Comment by vtolstov** [comment]
I'm try to fix the bug, if it present in my fork. But i cant help users of go-micro

**Comment by DMwangnima** [comment]
Hey @dh1tw , i tried to solve this problem and i found a clue. When the handler function returns an error, in rpc_server.go, serveRequestError is not nil. Please see the following pitcure.
![image](https://user-images.githubusercontent.com/33331974/113966908-89bcc980-9862-11eb-9bf6-bbcebc8141ba.png)
  So the result of sending error to client depends on rcodec.Write(). In rpc_router.go, the real performer is c.codec. See the following picture.
![image](https://user-images.githubusercontent.com/33331974/113967318-53cc1500-9863-11eb-9fdf-c29561d52777.png)
  In this situation, msg's Content-type field is application/protobuf and the corresponding codec is proto.Codec. When we focus on proto.Codec.Write(), we can find that it ignores m's information so that it doesn't write error msg to client. See the following picture.
![image](https://user-images.githubusercontent.com/33331974/113968211-3ac46380-9865-11eb-817f-f1fa3da8837f.png)
  Maybe someone could submit a RP to fix the bug of proto.Codec.Write(). Or you can choose another Codec to use just like protorpc.protoCodec, this codec is useful.

**Comment by dh1tw** [comment]
Hey @DMwangnima, 
thanks for your effort in digging into this problem. I have been trying to change for the last hours to the protorpc codec, but with limited success. It seems that some of the original document got lost. I've been reading through the old issues and the source code, but it is still not clear how to change to another codec, like the protorpc codec. Would you mind posting a brief example on how and where (server or client?) the codec has to be injected?

**Comment by dh1tw** [comment]
Thanks @DMwangnima! Based on your comment I did some further digging in the git history and the Github issues. I found a few more clues that explain IMHO the current behavior: 
- As part of PR #362 @asim introduced the [proto codec](https://github.com/asim/go-micro/tree/master/codec/proto). Apparently with the aim to allow go-micro to process standard json, protobuf and grpc requests. In this PR he changed the codec for ContentType `application/protobuf` from `protorpc.NewCodec` to `proto.NewCodec`. This didn't cause any problems, since the defaultContentType was `application/octet-stream` and still set to `protorpc.NewCodec`. 
- In PR #372 the `DefaultContentType` was changed from `"application/octet-stream"` to `"application/protobuf"`. And from then onwards, `proto.Codec` was the default Codec.

Git blame revealed that the `func (c *Codec) Write (m *Codec.Message...)` in the `proto.Codec` actually always ignored the `m *codec.Message`. So I suppose that @asim did this on purpose and that the `proto.Codec` was never supposed to return an error to the client. A short confirmation from @asim would be very much appreciated. 

So if you want to propagate error messages from the server to the client, you have to use the `protorpc` codec.

One way to do so is by setting the contentType Option when calling `client.NewClient()`.  

```golang

import (
    client "github.com/asim/go-micro/v3/client"

)

func demoFoo(){

      [...your code...]

        c := client.NewClient(
		client.PoolSize(1), // some custom options
		client.ContentType("application/proto-rpc"), // <<-----
	)
}
```

I also updated my [example code](https://github.com/dh1tw/go-micro-error-broken), in case somebody is looking for a full code example.

**Comment by DMwangnima** [comment]
Hey @dh1tw , I'm sorry about not clarifying the causal relationship and making you confused about how to change the codec. You absolutely captured the key point, content-type. And if you focus on the function setupProtocol in client/rpc_codec.go, you will find that if we don't set up the protocol of registry.Node, the default content-type will be application/proto-rpc. Just like the following picture.
![image](https://user-images.githubusercontent.com/33331974/114641720-38e71e00-9d05-11eb-9dc1-be8d01f3a40b.png)
so there is another solution that client and server choose another registry plugin which didn't set up the registry.Node.Metadata["protocol"].
Of course, changing the default client to grpc client would also be useful. But maybe the great solution is to make a RP to complete the process logic of proto.Codec.
