### ISSUE TITLE
[BUG] Problem in go.mod File

### ISSUE THREAD

**Issue by mivinci** [micro/go-micro#2111]
I was downloading `go-micro` by using the following command because this is how it is imported in the [examples](https://github.com/asim/go-micro/tree/master/examples),
```bash
go get -u github.com/asim/go-micro/v3
```
but an error occurred like this:
```
github.com/asim/go-micro: github.com/asim/go-micro@v1.18.0: parsing go.mod:
        module declares its path as: github.com/micro/go-micro
        but was required as: github.com/asim/go-micro
```
I think it is probably because the module name in [go.mod](https://github.com/asim/go-micro/blob/v1.18.0/go.mod) of `v1.18.0` is written as `github.com/micro/go-micro` while `github.com/asim/go-micro` is needed. So can you please check it out and fix it.

**Comment by asim** [comment]
```
GOPROXY=direct go get github.com/asim/go-micro/v3
```

**Comment by Mivinci** [comment]
> ```
> GOPROXY=direct go get github.com/asim/go-micro/v3
> ```
It worked, thanks! But my `GOPROXY` env variable was already set to `direct` before adding the `GOPROXY=direct`. Confusing.

**Comment by mivinci** [comment]
> ```
> GOPROXY=direct go get github.com/asim/go-micro/v3
> ```

It works, thanks! But my `GOPROXY` env variable was already set to `direct` before adding the `GOPROXY=direct`. Confusing.
