### ISSUE TITLE
can you provide some examples of using etcd for the service discovery

### ISSUE THREAD

**Issue by zenghao306** [micro/go-micro#2114]
Can you provide some examples of using etcd for the service discovery on the go-micro/v3?

**Comment by isfk** [comment]
```
package main

import (
	"context"
	"time"
	"user/config"
	"user/handler"
	"user/model"
	"user/pkg/log"
	"user/subscriber"

	"github.com/asim/go-micro/plugins/registry/etcd/v3"
	"github.com/asim/go-micro/v3"
	"github.com/asim/go-micro/v3/server"
	"github.com/micro/cli/v2"

	pb "gitee.com/izhc/proto/pb/user"
)

func main() {
	serviceName := "go.micro.srv.user"
	// New Service
	service := micro.NewService(
		micro.Name(serviceName),
		micro.Registry(etcd.NewRegistry()),
		micro.RegisterTTL(time.Second*30),
		micro.RegisterInterval(time.Second*15),
		micro.WrapHandler(logWrapper),
		micro.Version("latest"),
		micro.Flags(&cli.StringFlag{
			Name:  "nacos_ip",
			Usage: "nacos ip",
			Value: "127.0.0.1",
		}, &cli.Uint64Flag{
			Name:  "nacos_port",
			Usage: "nacos port",
			Value: 8848,
		}, &cli.StringFlag{
			Name:  "nacos_namespace",
			Usage: "nacos namespace",
			Value: serviceName,
		}, &cli.StringFlag{
			Name:  "nacos_data_id",
			Usage: "nacos data id",
			Value: "all",
		}, &cli.StringFlag{
			Name:  "nacos_group",
			Usage: "nacos group",
			Value: "all",
		}),
		micro.Action(func(c *cli.Context) error {
			config.Init(&config.NacosConf{
				IP:        c.String("nacos_ip"),
				Port:      c.Uint64("nacos_port"),
				Namespace: c.String("nacos_namespace"),
				DataID:    c.String("nacos_data_id"),
				Group:     c.String("nacos_group"),
			})

			log.Init(config.Conf.Log)
			model.Init(config.Conf)
			return nil
		}),
	)

	service.Server().Init(
		server.Wait(nil),
	)

	service.Init()

	// Register Handler
	pb.RegisterServiceHandler(service.Server(), new(handler.Server))

	// Register Struct as Subscriber
	micro.RegisterSubscriber("go.micro.srv.user", service.Server(), new(subscriber.User))

	// Register Function as Subscriber
	micro.RegisterSubscriber("go.micro.srv.user", service.Server(), subscriber.Handler)

	// Run service
	if err := service.Run(); err != nil {
		log.Fatal(err)
	}
}
func logWrapper(fn server.HandlerFunc) server.HandlerFunc {
	return func(ctx context.Context, req server.Request, rsp interface{}) error {
		log.Infof("req.endpoint=%v", req.Endpoint())
		log.Infof("req.body=%v", req.Body())
		return fn(ctx, req, rsp)
	}
}

```

**Comment by zenghao306** [comment]
I have coding an example by this:
https://github.com/zenghao306/go-micro-etcd

**Comment by Hehongyuanlove** [comment]
> I have coding an example by this:
> https://github.com/zenghao306/go-micro-etcd

运行 micro new hello  生成的模板 有几处问题
1、go.mand 还是旧引用 
     `github.com/micro/micro/v3 v3.0.0`  应当为 `github.com/asim/go-micro/v3 v3.5.0`
2、模板main.go
      `"github.com/micro/micro/v3/...."` 应当为 `"github.com/asim/go-micro/...../v3"`
micro.exe 版本 3.0.4
micro cmd 下载地址 https://github.com/micro/micro/releases

猜想应当是 micro.exe 错误导致 但是不知道如何修正

**Comment by zenghao306** [comment]
> > I have coding an example by this:
> > https://github.com/zenghao306/go-micro-etcd
> 
> 运行 micro new hello 生成的模板 有几处问题
> 1、go.mand 还是旧引用
> `github.com/micro/micro/v3 v3.0.0` 应当为 `github.com/asim/go-micro/v3 v3.5.0`
> 2、模板main.go
> `"github.com/micro/micro/v3/...."` 应当为 `"github.com/asim/go-micro/...../v3"`
> micro.exe 版本 3.0.4
> micro cmd 下载地址 https://github.com/micro/micro/releases
> 
> 猜想应当是 micro.exe 错误导致 但是不知道如何修正

micro/micro是go-micro演化出来的另外一个分支了，你应该去用
https://github.com/asim/go-micro/tree/v3.0.1/cmd/protoc-gen-micro下protoc-gen-micro而不是micro/micro/v3下的

**Comment by Hehongyuanlove** [comment]
> > > I have coding an example by this:
> > > https://github.com/zenghao306/go-micro-etcd
> > 
> > 
> > 运行 micro new hello 生成的模板 有几处问题
> > 1、go.mand 还是旧引用
> > `github.com/micro/micro/v3 v3.0.0` 应当为 `github.com/asim/go-micro/v3 v3.5.0`
> > 2、模板main.go
> > `"github.com/micro/micro/v3/...."` 应当为 `"github.com/asim/go-micro/...../v3"`
> > micro.exe 版本 3.0.4
> > micro cmd 下载地址 https://github.com/micro/micro/releases
> > 猜想应当是 micro.exe 错误导致 但是不知道如何修正
> 
> micro/micro是go-micro演化出来的另外一个分支了，你应该去用
> [https://github.com/asim/go-micro/tree/v3.0.1/cmd/protoc-gen-micro下protoc-gen-micro而不是micro/micro/v3下的]


protoc-gen-micro 已经切换过来了   make proto生成的代码 也没问题
是 micro.exe  执行 micro new xxx 的时候 生成的代码 有问题
所以想请教一下 规范的 模板生成代码

**Comment by iGoogle-ink** [comment]
the `github.com/asim/go-micro/plugins/registry/etcd/v3` etcd registry module should change to  `go.etcd.io/etcd/v3`
`github.com/coreos/etcd` can not work

**Comment by zenghao306** [comment]
> the `github.com/asim/go-micro/plugins/registry/etcd/v3` etcd registry module should change to `go.etcd.io/etcd/v3`
> `github.com/coreos/etcd` can not work

你确定不行？你有认真看过我写的那demo吗？

**Comment by iGoogle-ink** [comment]
> > the `github.com/asim/go-micro/plugins/registry/etcd/v3` etcd registry module should change to `go.etcd.io/etcd/v3`
> > `github.com/coreos/etcd` can not work
> 
> 你确定不行？你有认真看过我写的那demo吗？

你去看看他的插件里引用的 etcd包，那个包里是比较过时的
![image](https://user-images.githubusercontent.com/17245594/106706617-e7e2eb80-662a-11eb-9bdc-521639a657b8.png)

v3.3.25 etcd 内部引用的 `google.golang.org/grpc` 包是老版本，新版本的已经没有 `google.golang.org/grpc/naming` 了
