### ISSUE TITLE
 level=fatal mkdir xxxx\.micro: The system cannot find the path specified.

### ISSUE THREAD

**Issue by wzhsh90** [micro/go-micro#2115]
Hi :

I use micro server
![8](https://user-images.githubusercontent.com/16187191/106714799-4b731600-6637-11eb-9442-ad3826890e25.png)

but the command no work .

**Comment by asim** [comment]
wrong project

**Comment by wzhsh90** [comment]
I have find the problem. I need remove the old .micro file in my dir. the old .micro is an empty file . An empty file no dir.

**Comment by wzhsh90** [comment]
C:\Users\wzhsh90>micro services
Request timed out

C:\Users\wzhsh90>micro login
Enter username: admin
Enter password:
Context deadline exceeded

what is wrong ?

**Comment by wzhsh90** [comment]
NAME:
   micro - A framework for cloud native development

   Use `micro [command] --help` to see command specific help.

USAGE:
   micro [global options] command [command options] [arguments...]

VERSION:
   v3.0.0

**Comment by asim** [comment]
Wrong repo, this is go-micro, a framework, not micro. File your issue in https://github.com/micro/micro
