### ISSUE TITLE
[BUG]can't use codec bytes

### ISSUE THREAD

**Issue by lonerwolf** [micro/go-micro#2117]
**Describe the bug**

1. What are you trying to do?
2. What did you expect to happen?
3. What happens instead?

**How to reproduce the bug:**

If possible, please include a minimal code snippet here.

**Environment:**
Go Version: please paste `go version` output here
```
please paste `go env` output here
```

in codec/bytes
type Message struct {
	Header map[string]string
	Body   []byte
}
in rpc_codec
	// create new transport message
	msg := transport.Message{
		Header: m.Header,
		Body:   m.Body,
	}
if err := c.client.Send(&msg); err != nil {
		return errors.InternalServerError("go.micro.client.transport", err.Error())
	}

the transport.Message can't convert Message return nil, codec.ErrInvalidMessage

**Comment by DMwangnima** [comment]
Refer to #2110

**Comment by AuditeMarlow** [comment]
@lonerwolf, is this issue still relevant? If so, could you provide a full example illustrating the problem?
