### ISSUE TITLE
Upgrading to v3 causes timeout when getting an error

### ISSUE THREAD

**Issue by domgolonka** [micro/go-micro#2123]
I've upgraded from v2.9.1 to v3.5.0.
 I am trying to execute this error (below) in gRPC, and my API gateway is giving me a  "call timeout: context deadline exceeded".  To recap, if there isn't an error, it's working properly, 
```
if err != nil {
			return errors.InternalServerError("APP NAME", "collection create error", err.Error())
		}
```

**Comment by dh1tw** [comment]
I think this is exactly the same problem as described in #2110. Are you sure it was working well in v2.9.1 ? I was able to reproduce the bug also in v.2.9.1.

**Comment by domgolonka** [comment]
yup, it's working well in 2.9.1 I had to revert back to 2.9.1

**Comment by zibber2015** [comment]
```
cli := client.NewClient(client.ContentType("application/proto-rpc"))
```
according to @dh1tw  demo, client add this option solve my problem at version v3.5

**Comment by bighuangbee** [comment]
> ```
> cli := client.NewClient(client.ContentType("application/proto-rpc"))
> ```
> 
> 根据@dh1tw 演示，客户端添加此选项解决了我在 v3.5 版本的问题

thank you，itis worked.
