### ISSUE TITLE
How can I remove few building block (i.e. service discovery) instead of using defaults from my service?

### ISSUE THREAD

**Issue by rajaneeshgit** [micro/go-micro#2125]
I am new to go-micro, having few queries. 
1. How can I remove few building block like service discovery? As If I don't provide any replacement for service discovery then by default it picks consul/mdns based on environment.
This is just for one building block, I have this query in general suppose I don't need any feature in my service and instead of using default, Can I remove that block completely from go-micro based service.

2. I have a grpc service running, to expose grpc interfaces over http I need API gateway (part of micro). How can I do the same with go-micro without using micro.

Can someone pls share thoughts over above points.
Thanks

**Comment by AuditeMarlow** [comment]
As of right now, I'm not familiar with a method of removing blocks like you mentioned. In theory you could replace the default service registry with a custom noop implementation.

As for the API gateway, go-micro currently doesn't offer one working out of the box. This is however being tracked in #2221.
