### ISSUE TITLE
Run gateway example error

### ISSUE THREAD

**Issue by xiviu123** [micro/go-micro#2127]
Hi,
i'm getting this error with grpc-gateway example.

```
{"error":"OK: HTTP status code 200; transport: missing content-type field","code":2,"message":"OK: HTTP status code 200; transport: missing content-type field"}
```

Thank you for help

**Comment by jingshanccc** [comment]
i got the same problem

**Comment by tophgg** [comment]
i got the same problem + 1

**Comment by asim** [comment]
Are you using the grpc server?

**Comment by tophgg** [comment]
``

> Are you using the grpc server?

Hi, asim
here is my test code



server.go
```golang
package main

import (
	"context"
	"github.com/asim/go-micro/v3"
	"log"
	"sometest/proto/hello"
	"time"
)

type Say struct{}

func (s *Say) Hello(ctx context.Context, req *hello.Request, rsp *hello.Response) error {
	log.Print("Received Say.Hello request")
	rsp.Msg = "Hello " + req.Name
	return nil
}

func main() {
	service := micro.NewService(
		micro.Address(":9095"),
		micro.Name("go.micro.srv.demo"),
		micro.RegisterTTL(time.Second*30),
		micro.RegisterInterval(time.Second*10),
	)

	// optionally setup command line usage
	//service.Init()

	// Register Handlers
	hello.RegisterSayHandler(service.Server(), new(Say))

	// Run server
	if err := service.Run(); err != nil {
		log.Fatal(err)
	}
}
```

gateway.go
```golang
package main

import (
	"context"
	"flag"
	"github.com/golang/glog"
	"github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
	"google.golang.org/grpc"
	"net/http"
	"sometest/proto/gateway"
)
var(
	// the go.micro.srv.greeter address
	endpoint = flag.String("endpoint","localhost:9095","go.micro.srv.greeter address")
)
func run() error {
	ctx := context.Background()
	ctx, cancel := context.WithCancel(ctx)
	defer cancel()
	mux := runtime.NewServeMux()

	//conn, err := grpc.Dial(
	//	*endpoint,
	//	grpc.WithInsecure(),
	//)
	//err = hello.RegisterSayHandler(ctx, mux, conn)
	opts :=[]grpc.DialOption{grpc.WithInsecure()}
	err := hello.RegisterSayHandlerFromEndpoint(ctx, mux, *endpoint, opts)
	if err !=nil{
		return err
	}
	return http.ListenAndServe(":6666", mux)
}
func main(){
	flag.Parse()
	defer glog.Flush()
	if err := run(); err !=nil{
		glog.Fatal(err)
	}
}
```

hello.proto
```golang
syntax ="proto3";

option go_package="./;hello";
package hello;
import "google/api/annotations.proto";

service Say{
    rpc Hello(Request) returns (Response) {
        option (google.api.http) = {
            post:"/greeter/hello"
            body:"*"
        };
    }
}

message Request{
    string name =1;
}

message Response{
    string msg =1;
}

```



When i request http://localhost:6666/greeter/hello , it will random return two reponse 

```
{
    "msg": "Hello "
}
```

or 

```
{
    "code": 2,
    "message": "malformed header: missing HTTP content-type",
    "details": []
}
```

when i use same proto file primeval grpc without go-micro, http response is correct

 - go version: 1.15.13
 - grpc-gateway v2.6.0 (used v1.16.0 have same problem)
 - grpc  v1.40.0
 - go-micro v3.6.0

**Comment by asim** [comment]
You are not using the grpc server. Please import the grpc server from the plugin directory and pass as an option to your service

**Comment by tophgg** [comment]
> You are not using the grpc server. Please import the grpc server from the plugin directory and pass as an option to your service

thanks, it work now

**Comment by tvluongict** [comment]
> You are not using the grpc server. Please import the grpc server from the plugin directory and pass as an option to your service
Hi @asim 
I got the same problem now. could you explain more about this solution?

**Comment by medivh666** [comment]
I got the same problem now.  +1

**Comment by medivh666** [comment]
I solved the problem..  @vtolstov  

import 	"github.com/asim/go-micro/plugins/server/grpc/v4"

micro.Server(grpc.NewServer()),
micro.Address(conf.Service.ListenHost()),
micro.Name(conf.Service.ServiceName),
micro.Version(conf.Service.Version),
micro.Registry(consulRegistry),
micro.WrapHandler(RecoverWrapper),

**Comment by hhniao** [comment]
@medivh666 when you add this line.
`go run http/rpccli/main.go ` will show you error.
restore this code, it is work.
