### ISSUE TITLE
[BUG] graceful shutdown didn't take effect

### ISSUE THREAD

**Issue by keiqiu** [micro/go-micro#2137]
graceful shutdown didn't take effect
```
package main

import (
	"fmt"

	"github.com/micro/go-micro/v2"
	"github.com/micro/go-micro/v2/server"
)

func main() {
	service := micro.NewService()

	service.Server().Init(
		server.Wait(nil),
	)

	if err := service.Run(); err != nil {
		fmt.Println(err)
	}
}
```
server.Wait(nil) only set opts.context
but the server.wg is nil
[https://github.com/asim/go-micro/blob/94bd1025a64eaaba1d89189891ef49f3ab5eee7f/server/options.go#L255](url)

**Comment by AuditeMarlow** [comment]
Unfortunately we can't support v2 anymore. Please upgrade go-micro to v4 and see if the problem persists.
