### ISSUE TITLE
how to prevent multi broker subscribers receive same message

### ISSUE THREAD

**Issue by typhoonbb** [micro/go-micro#2139]
I am using go micro broker to implement message queue, I have two go processes subscribe same topic,  when I publish a message to broker,  two subscriber can receive the message at same time, how to make it receive by one subscriber ? thanks a lot !

the version I used :`github.com/micro/go-micro/v2 v2.9.1
	github.com/micro/go-plugins/broker/nsq/v2 v2.9.1`

**Comment by vtolstov** [comment]
specify subscriber queue group and messages (may be, dont know nsq) will be distributed across all subscribers

**Comment by hellodudu** [comment]
@typhoonbb Hey bro, I'm facing the same problem. I have found a solution by reading `go-micro` and `NSQ` source code. `NSQ` will send a copy of messages to all channels that subscribe the same `topic`, and it will dispatch messages to consumers in `load-balance` mode when multi consumers binding to the same channel. In `go-micro`, you can specify an `SubscriberQueue` option when consumers call `NewSubscriber` which can make all consumers binding to the same channel. If you didn't specify `SubscriberQueue`, it will create a channel name with uuid for each consumer when `NewSubscriber`.

https://github.com/microhq/go-plugins/blob/87d43a62e4addda545607c6ee148fa84eec5a737/broker/nsq/nsq.go#L246-L249

some call like this
```golang
micro.RegisterSubscriber("game.StartGate", g.mi.srv.Server(), &subStartGate{g: g}, server.SubscriberQueue("game.StartGate"))
```

**Comment by typhoonbb** [comment]
@hellodudu, thanks for the solution!
