### ISSUE TITLE
[BUG] go-micro/examples/config/grpc/srv  load files error

### ISSUE THREAD

**Issue by cuigang** [micro/go-micro#2157]
**Describe the bug**

1. What are you trying to do?
cd go-micro/examples/config/grpc/srv
go run main.go

2. What did you expect to happen?

3. What happens instead?

**How to reproduce the bug:**

```

cd go-micro/examples/config/grpc/srv
go run main.go

2021-04-28 19:27:30  file=log/log.go:136 level=info [loadConfigFile] load files error，%s[invalid character 'm' looking for beginning of value]
2021-04-28 19:27:30  file=log/log.go:128 level=info [invalid character 'm' looking for beginning of value]
2021-04-28 19:27:30  file=srv/main.go:42 level=info configServer started[]

```

**Environment:**
Go Version: go1.16.3 darwin/amd64

**Comment by DMwangnima** [comment]
By default, the DefaultConfig use json reader to unmarshal config file. So this example can't run correctly.

**Comment by cuigang** [comment]
I'm trying to run go-micro/examples/config/modify 
```
cd go-micro/examples/config/modify
go run modify.go
invalid character '#' looking for beginning of value
```
It looks like go-micro config could not enable plugins/config/encoder . 
Do you know how to enable plugins/config/encoder to support yaml file ?
It's a BUG of examples code or go-micro v3 framework ?

**Comment by DMwangnima** [comment]
1. You should write or find a yaml reader to implement config/reader/Reader interface. 

// Reader is an interface for merging changesets
type Reader interface {
	Merge(...*source.ChangeSet) (*source.ChangeSet, error)
	Values(*source.ChangeSet) (Values, error)
	String() string
}

2. Then inject this reader into config instance.

 // assume you already have a yaml reader naming yaml
conf, _ := config.NewConfig(config.WithReader(yaml))

**Comment by cuigang** [comment]
I see, Thank you very much!
