### ISSUE TITLE
Question: the right way to customize logger of go-micro

### ISSUE THREAD

**Issue by remuscl** [micro/go-micro#2170]
Hi,

I am trying to use logrus instead of the default logger:

```go
import(
  logrus "github.com/asim/go-micro/plugins/logger/logrus/v3"
  "github.com/asim/go-micro/v3/logger"
)

func init(){
  logger.DefaultLogger = logrus.NewLogger(...)
}
```

But it does not make any affect to this global `log` variable: https://github.com/asim/go-micro/blob/f48911d2c3efc45a71964c55db313604df53095b/server/server.go#L152

So I wonder what is supposed to be the right way to do this?

Thanks a lot for your contribution to this great project :-D

**Comment by JeffreyBool** [comment]
@asim Do I need to make adjustments to these logs that are written dead by default, which are not controlled externally, and I can go do something about that

**Comment by remuscl** [comment]
@JeffreyBool Thanks a lot. I'm looking forward to future updates about this issue :-)

**Comment by JeffreyBool** [comment]
@remuscl https://github.com/asim/go-micro/pull/2171

**Comment by remuscl** [comment]
Thanks a lot for your contribution 👍
