### ISSUE TITLE
how to use use  broker.PublishOption？

### ISSUE THREAD

**Issue by jsaaae** [micro/go-micro#2211]
When sending Kafka message, I want to pass more parameters. What should I do？Customize the Kafka plugin and re register it？ Why don't you use broker.PublishOption 

func (k *kBroker) Publish(topic string, msg *broker.Message, opts ...broker.PublishOption) error {
	b, err := k.opts.Codec.Marshal(msg)
	if err != nil {
		return err
	}
	_, _, err = k.p.SendMessage(&sarama.ProducerMessage{
		Topic: topic,
		Value: sarama.ByteEncoder(b),
                ....
                ....
	})
	return err
}

**Comment by xpunch** [comment]
The official kafka broker plugins may no meet your requirement, if you think it's a common requirement, you can help improve this plugin and create your PR.
If you think it's an custom requirement, you can create your own plugin like what I've done in [Kafka](https://github.com/x-punch/micro-kafka).
