### ISSUE TITLE
Can go-micro be used for multi-transport? ?

### ISSUE THREAD

**Issue by andiksetyawan** [micro/go-micro#2214]
Can gomicro be used for multi-transport ?, for example, in one service, http and grpc are available to be connected to the client.

**Comment by xpunch** [comment]
@asim 
Should this be supported in new go micro? A service can have multiple different handlers?

**Comment by asim** [comment]
Multi transport always complicates the underlying implementation so I think the most appropriate solution is to define a transport plugin that takes multiple transports as input and returns a single one confirming to the interface.

**Comment by xpunch** [comment]
The simplest way is to create separated service or  using different ports for http/grpc, seams no need to be supported by framework.
