### ISSUE TITLE
[BUG] If use the transport protocol，through the command micro call，service name is error

### ISSUE THREAD

**Issue by chinahtl** [micro/go-micro#2217]
If use the transport protocol，through the command line: **micro --registry=etcd call go.micro.hello.ds Ds.GetClass '{"comm": {"caller":""},"para":{"offset": 0,"limit":10}}'**， This will generate an error,**error calling go.micro.hello.ds.Ds.GetClass: {"id":"go.micro.client","code":500,"detail":"unknown service go.micro.hello.ds.Ds","status":"Internal Server Error"}**

service should be  go.micro.hello.ds， not go.micro.hello.ds.Ds

micro --help
NAME:
   micro - A microservice runtime

USAGE:
   micro [global options] command [command options] [arguments...]

VERSION:
   latest

I sincerely hope that the author will take a look at this bug and fix it, thank you very much

**Comment by xpunch** [comment]
Can you print your etcd registry key info?
```shell
etcdctl get /micro/registry/go.micro.hello.ds --prefix
```
If your service name is go.micro.hello.ds, and endpoint is Ds.GetClass, then the error tip is correct.

**Comment by chinahtl** [comment]
> Can you print your etcd registry key info?
> 
> ```shell
> etcdctl get /micro/registry/go.micro.hello.ds --prefix
> ```
> 
> If your service name is go.micro.hello.ds, and endpoint is Ds.GetClass, then the error tip is correct.

Thank you for your reply. There are a lot of returned information. I took some necessary information

/micro/registry/go.micro.hello.ds/go.micro.hello.ds-e90cdfd7-a68e-48bd-ba8b-413308ed6203
{
	"name": "go.micro.hello.ds",
	"version": "latest",
	"metadata": null,
	"endpoints": [{
				"name": "Ds.GetClass",
				"request": {
					"name": "ReqClassSet",
					"type": "ReqClassSet",
					"values": [{
						"name": "MessageState",
						"type": "MessageState",
						"values": [{
							"name": "NoUnkeyedLiterals",
							"type": "NoUnkeyedLiterals",
							"values": null
						}, {
							"name": "DoNotCompare",
							"type": "DoNotCompare",
							"values": null
						}, {
							"name": "DoNotCopy",
							"type": "DoNotCopy",
							"values": null
						}, {
							"name": "MessageInfo",
							"type": "MessageInfo",
							"values": null
						}]
					}, {
						"name": "int32",
						"type": "int32",
						"values": null
					}, {
						"name": "unknownFields",
						"type": "[]uint8",
						"values": null
					}, {
						"name": "comm",
						"type": "BaseReq",
						"values": [{
							"name": "MessageState",
							"type": "MessageState",
							"values": null
						}, {
							"name": "int32",
							"type": "int32",
							"values": null
						}, {
							"name": "unknownFields",
							"type": "[]uint8",
							"values": null
						}, {
							"name": "caller",
							"type": "string",
							"values": null
						}, {
							"name": "req_user_id",
							"type": "uint64",
							"values": null
						}, {
							"name": "owner_user_id",
							"type": "uint64",
							"values": null
						}, {
							"name": "seq_id",
							"type": "string",
							"values": null
						}, {
							"name": "event_id",
							"type": "string",
							"values": null
						}]
					}, {
						"name": "para",
						"type": "ReqClassSet_ReqPara",
						"values": [{
							"name": "MessageState",
							"type": "MessageState",
							"values": null
						}, {
							"name": "int32",
							"type": "int32",
							"values": null
						}, {
							"name": "unknownFields",
							"type": "[]uint8",
							"values": null
						}, {
							"name": "offset",
							"type": "uint32",
							"values": null
						}, {
							"name": "limit",
							"type": "uint32",
							"values": null
						}, {
							"name": "order_by",
							"type": "[]string",
							"values": null
						}, {
							"name": "class_type_id",
							"type": "uint64",
							"values": null
						}, {
							"name": "class_id",
							"type": "uint64",
							"values": null
						}, {
							"name": "is_used",
							"type": "uint32",
							"values": null
						}, {
							"name": "class_name",
							"type": "string",
							"values": null
						}]
					}]
				},
				"response": {
					"name": "RspClassSet",
					"type": "RspClassSet",
					"values": [{
						"name": "MessageState",
						"type": "MessageState",
						"values": [{
							"name": "NoUnkeyedLiterals",
							"type": "NoUnkeyedLiterals",
							"values": null
						}, {
							"name": "DoNotCompare",
							"type": "DoNotCompare",
							"values": null
						}, {
							"name": "DoNotCopy",
							"type": "DoNotCopy",
							"values": null
						}, {
							"name": "MessageInfo",
							"type": "MessageInfo",
							"values": null
						}]
					}, {
						"name": "int32",
						"type": "int32",
						"values": null
					}, {
						"name": "unknownFields",
						"type": "[]uint8",
						"values": null
					}, {
						"name": "result",
						"type": "BaseRet",
						"values": [{
							"name": "MessageState",
							"type": "MessageState",
							"values": null
						}, {
							"name": "int32",
							"type": "int32",
							"values": null
						}, {
							"name": "unknownFields",
							"type": "[]uint8",
							"values": null
						}, {
							"name": "code",
							"type": "ErrCode",
							"values": null
						}, {
							"name": "msg",
							"type": "string",
							"values": null
						}, {
							"name": "seq_id",
							"type": "string",
							"values": null
						}, {
							"name": "event_id",
							"type": "string",
							"values": null
						}]
					}, {
						"name": "data",
						"type": "RspClassSet_RetData",
						"values": [{
							"name": "MessageState",
							"type": "MessageState",
							"values": null
						}, {
							"name": "int32",
							"type": "int32",
							"values": null
						}, {
							"name": "unknownFields",
							"type": "[]uint8",
							"values": null
						}, {
							"name": "total_count",
							"type": "uint32",
							"values": null
						}, {
							"name": "class_set",
							"type": "[]RspClassSet_ClassInfo",
							"values": null
						}]
					}]
				},

			}

**Comment by chinahtl** [comment]
> Can you print your etcd registry key info?
> 
> ```shell
> etcdctl get /micro/registry/go.micro.hello.ds --prefix
> ```
> 
> If your service name is go.micro.hello.ds, and endpoint is Ds.GetClass, then the error tip is correct.

yes, service name is go.micro.hello.ds, and endpoint is Ds.GetClass, but what is the reason? I changed it to HTTP transport, which is OK

**Comment by xpunch** [comment]
What do you mean changed HTTP transport?
```
micro call --help    
NAME:
   micro call - Call a service e.g micro call greeter Say.Hello '{"name": "John"}

USAGE:
   micro call [command options] [arguments...]

OPTIONS:
   --metadata value  A list of key-value pairs to be forwarded as metadata [%MICRO_METADATA%]
```
Which version is your micro?
```
micro --version
```

**Comment by chinahtl** [comment]
> ```
> micro --version
> ```

go get github.com/micro/micro/v2
micro version： latest 

It means that it works if I run through the http transport protocol, but the above error occurs through the grpc transport protocol. I am a Chinese, and my English is not good.

**Comment by xpunch** [comment]
unknown service go.micro.hello.ds.Ds 
micro v2版的call也是内部的grpc client去调用的，这个错误应该是grpc server端返回的，可以查一下注册handler的代码。
micro v2因为quic-go的问题，我跑不起来。
你可以用我的这个库测试一下：https://github.com/xpunch/go-micro-example/tree/main/v2/gateway

**Comment by chinahtl** [comment]
> unknown service go.micro.hello.ds.Ds
> micro v2版的call也是内部的grpc client去调用的，这个错误应该是grpc server端返回的，可以查一下注册handler的代码。
> micro v2因为quic-go的问题，我跑不起来。
> 你可以用我的这个库测试一下：https://github.com/xpunch/go-micro-example/tree/main/v2/gateway

好的，我试试

**Comment by chinahtl** [comment]
> unknown service go.micro.hello.ds.Ds
> micro v2版的call也是内部的grpc client去调用的，这个错误应该是grpc server端返回的，可以查一下注册handler的代码。
> micro v2因为quic-go的问题，我跑不起来。
> 你可以用我的这个库测试一下：https://github.com/xpunch/go-micro-example/tree/main/v2/gateway

你好，是这样的， endpoint如果存在点. 如Ds.GetClass 

`
代码位置：go-micro/plugins/client/grpc/request.go 

// service Struct.Method /service.Struct/Method
func methodToGRPC(service, method string) string {
	// no method or already grpc method
	if len(method) == 0 || method[0] == '/' {
		return method
	}

	// assume method is Foo.Bar
	mParts := strings.Split(method, ".")
	if len(mParts) != 2 {
		return method
	}

	if len(service) == 0 {
		return fmt.Sprintf("/%s/%s", mParts[0], mParts[1])
	}

	// return /pkg.Foo/Bar
	return fmt.Sprintf("/%s/%s.%s", service, mParts[0], mParts[1])
}`

在处理的时候应该是不合理的，将第一个参数组合到servicename？

这是我修改过后的，这样能解决 unknown service go.micro.hello.ds.Ds" 错误
https://github.com/chinahtl/go-micro/commit/903b61fe17aeda04885c87babb80fb66d88f1b6d#diff-8a5f7b1000acdf76f10c7876c2e327cc859cdf3c3a308a0200867db502d07d23

请看下呢

**Comment by xpunch** [comment]
先梳理一下，go.micro.hello.ds是整个服务的名字，用于服务发现。Ds.GetClass是endpoint的名字，其中Ds是proto文件中定义的service，GetClass是proto文件中定义的rpc函数。
新版本go-micro中的grpc server，会先找去注册中心找go.micro.hello.ds，然后在本地serviceMap里找Ds这个service。
如果是go.micro.hello.ds找不到，应该会提示service go.micro.hello.ds: not found
如果是Ds找不到，应该会提示unknown service ds
你的那个错误提示unknown service go.micro.hello.ds.Ds，不知道你用的是哪个版本的go-micro grpc server，最好可以写一个example跑一下。

因为micro现在已经不兼容go-micro，你用的版本我也跑不起来，没法测试你遇到的问题。你的修改我跑了一下，原来正常的程序反而报错了。生成路径的算法，client端和server端是一致的，你改了client端可以了，说明你的server端与之前的client端不兼容。

最近新增加了一个gomu，支持原来micro支持的一些功能，你可以试试这个：
https://github.com/asim/go-micro/tree/master/cmd/gomu

**Comment by chinahtl** [comment]
> 先梳理一下，go.micro.hello.ds是整个服务的名字，用于服务发现。Ds.GetClass是endpoint的名字，其中Ds是proto文件中定义的service，GetClass是proto文件中定义的rpc函数。
> 新版本go-micro中的grpc server，会先找去注册中心找go.micro.hello.ds，然后在本地serviceMap里找Ds这个service。
> 如果是go.micro.hello.ds找不到，应该会提示service go.micro.hello.ds: not found
> 如果是Ds找不到，应该会提示unknown service ds
> 你的那个错误提示unknown service go.micro.hello.ds.Ds，不知道你用的是哪个版本的go-micro grpc server，最好可以写一个example跑一下。
> 
> 因为micro现在已经不兼容go-micro，你用的版本我也跑不起来，没法测试你遇到的问题。你的修改我跑了一下，原来正常的程序反而报错了。生成路径的算法，client端和server端是一致的，你改了client端可以了，说明你的server端与之前的client端不兼容。
> 
> 最近新增加了一个gomu，支持原来micro支持的一些功能，你可以试试这个：
> https://github.com/asim/go-micro/tree/master/cmd/gomu

好的，我这边使用了https://github.com/storyicon/powerproto，谢谢，我试试
