### ISSUE TITLE
what is the different between micro/micro and go-micro?

### ISSUE THREAD

**Issue by wwhai** [micro/go-micro#2219]
Hi，I noticed there have 2 project and another is named `micro`，I want to known what is the different between micro and go-micro?

**Comment by asim** [comment]
go-micro is a framework, micro is a platform. Go Micro provides a standalone library for distributed systems development. Micro provides an all encompassing cloud platform with api gateway, authentication, runtime, etc.

**Comment by wwhai** [comment]
> go-micro is a framework, micro is a platform. Go Micro provides a standalone library for distributed systems development. Micro provides an all encompassing cloud platform with api gateway, authentication, runtime, etc.

Thanks！
