### ISSUE TITLE
server connection error

### ISSUE THREAD

**Issue by chs97** [micro/go-micro#222]
When I used micro web query ,sometimes mistakes happen

```
{
  "id": "go.micro.client",
  "code": 500,
  "detail": "connection error: dial tcp *******:30374: connectex: No connection could be made because the target machine actively refused it.",
  "status": "Internal Server Error"
}
```
It just sometimes , not always

**Comment by asim** [comment]
This could happen for any number of reasons. If you have stale entries in the registry or if there's a server side error. The reference to "connectx" is outside the scope of micro and likely deployment related so I'm tempted to say this is related to the networking config of your containers.

**Comment by asim** [comment]
2 weeks no response, closing
