### ISSUE TITLE
[FEATURE] API Gateway

### ISSUE THREAD

**Issue by asim** [micro/go-micro#2221]
When we were using Micro, it provided an API gateway. It would be nice to have this as a standalone or programmable tool for go-micro once more. Maybe by taking the existing code from Micro. Looking for people who are actively interested in the previous Micro API who want to contribute something.

**Comment by xpunch** [comment]
Micro used to be a powerful tool for me, I can help to bring it back into go-micro.

**Comment by AuditeMarlow** [comment]
We've been discussing integrating [Gomu][1] into Go Micro in #2220. I'm currently also looking into providing an API gateway in Gomu. Perhaps it would be a wise decision to start integrating Gomu in Go Micro before we're all building stuff that might be difficult to combine?

[1]: https://github.com/auditemarlow/gomu

**Comment by asim** [comment]
My experiences with Micro tell me that the single binary approach can often be limiting or too opinionated where people need to add their own integrations. For now I'd like to treat the CLI and the API as two separate things here. The ability for someone to just go get a simple API is fine but it's more likely someone would like to import and build it themselves to include any sort of plugins or additional functionality. So we should keep that in mind and learn from the pitfalls of Micro.

**Comment by AuditeMarlow** [comment]
There's already an `api` package with a HTTP server. Wouldn't this suffice as an API gateway, or do you have other ideas?

**Comment by asim** [comment]
I think right now it's too difficult to use. It was a collection of packages created out of the micro api. Let's say I go back to micro v2. You can see how that was used here https://github.com/micro/micro/blob/5f6095b0e09b644efb24b58f87b1dda4244e2e8c/api/api.go. So I think finding a way to make it easy to use without having to piece it all together would be useful e.g I have a cmd/api that basically just copies over what the micro api did and lets me run it out of the box or 

```
import "github.com/asim/go-micro/api"

gw := api.NewAPI()
gw.Register(Endpoint)
gw.Run()
```

What most people are looking for is a http/json endpoint for their grpc based service and they ideally want to run it in the same process. They might also not want to expose the entire service but a subset of the api. So being able to just register those endpoints is useful. It might mean the current API interface just needs some work to add Run.
