### ISSUE TITLE
[FEATURE] Cache package

### ISSUE THREAD

**Issue by asim** [micro/go-micro#2227]
Furthering our building block packages, it's clear a Cache is a design pattern that's frequently used in distributed systems with a simple Get/Put/Delete interface. For anyone looking to contribute this, we welcome that plus some initial implementations. While the store package enables Read/Write/Delete semantics it also focuses on more long term storage much like a database and operates on byte values. With the cache package, it would be nice to use just simple Go interfaces and implementations such as redis, memcache and memory.

Here's an example interface:

```
type Cache interface {
  Get(key string, val interface{}) error
  Put(key string, val interface{}) error
  Delete(key string) error
}
```

We can additionally add a method for context use like so..

```
type Cache interface {
   ...
   Context(ctx context.Context) Cache
}
```

This returns a copy of Cache with the context set. This is good design practice so we don't pollute all methods with context as the first arg. Usage looks like so.

```
err := cache.Context(ctx).Put("foo", "bar")
```

**Comment by AuditeMarlow** [comment]
I'm willing to give this a go. I'll first be building an in-memory cache.
