### ISSUE TITLE
[FEATURE] Model (CRUD/SQL) Package

### ISSUE THREAD

**Issue by asim** [micro/go-micro#2228]
SQL is something we've ignored for a long time but its clear there's no way around it's need. In the past I've advocated for a potential "model" package that would act as a simple ORM and I'd like to see if there's a way we could incorporate either a simple CRUD interface backed by the likes of Gorm or something like a SQL package if there's a way to abstract over the various implementations.

**Comment by bhoriuchi** [comment]
any thoughts on where/how the models would be defined? Something like https://github.com/infobloxopen/protoc-gen-gorm would integrate with protobuf definitions but would not be useful for "noproto". Using struct tags would work for both cases but I'm not sure if the current protoc-gen supports custom tags? Either way to reduce redundant config I think the type definitions are a good place to define the model which looks like what gorm does. However this would limit support of model to things gorm supports. Would be nice to support nosql databases as well

We attacked this problem using a combination of go-templates and custom generator code driven by yaml type configs which works well for our very specific use case but not so much for a general purpose model package.
