### ISSUE TITLE
 Why does the v3 version not support YAML decoding

### ISSUE THREAD

**Issue by EnigmaOppo** [micro/go-micro#2230]
I tried to use the YAML decoder to read the YAML configuration file but found that the v3 version does not support YAML anymore, and the v2 version is supported. What is the reason for removing YAML? And how do I parse the YAML configuration file?

**Comment by asim** [comment]
The majority of third party code has moved in to the plugins directory. See https://github.com/asim/go-micro/tree/master/plugins/config/encoder/yaml

**Comment by EnigmaOppo** [comment]
> The majority of third party code has moved in to the plugins directory. See https://github.com/asim/go-micro/tree/master/plugins/config/encoder/yaml

Thank you very much for your answers
