### ISSUE TITLE
Does go-micro have a register and login module ?

### ISSUE THREAD

**Issue by zwl1619** [micro/go-micro#225]
Does `go-micro` have a register and login module ?

**Comment by asim** [comment]
No. Go-micro is an RPC framework. It does not build in user auth, registration or login. These are to be considered at the microservice level. See things like https://github.com/micro/user-srv and https://github.com/micro/auth-srv

**Comment by springe2004** [comment]
Validation of services, such as use, OAuth, OpenID connect, and some suggestions?

**Comment by k1ng440** [comment]
https://github.com/microhq/user-srv
