### ISSUE TITLE
Observability feature

### ISSUE THREAD

**Issue by Tochemey** [micro/go-micro#2255]
Sorry for asking but I cannot see it first hand on the readme page which I suppose be the place where such an important feature should be.

I would like to know whether Asim supports observability particular for the gRPC-based application. I am referring to traces and metrics.

Thank you and wonderful job for putting out this piece of art.

Before asking, please check if your question has already been answered: 

1. Check the documentation - https://micro.mu/docs/
2. Check the examples and plugins - https://github.com/micro/examples & https://github.com/micro/go-plugins
3. Search existing issues

**Comment by asim** [comment]
We have a few tracing wrappers here https://github.com/asim/go-micro/tree/master/plugins/wrapper/trace and observability wrappers here https://github.com/asim/go-micro/tree/master/plugins/wrapper/monitoring

I think you highlight that we are missing a couple of packages, metrics and tracing. I think we could advocate for the creation of these and then a way to integrate them so they are available out of the box. @AuditeMarlow has added some functionality via the cmd/gomu generator but we may need something else too.

**Comment by Tochemey** [comment]
@asim Thanks for the swift response. I will check those links out and see whether they fit our requirements and if possible add some suggestions. Once again, great work

**Comment by Tochemey** [comment]
I can see. you offered what is standard which is pretty cool. May I ask whether there is an example on how to use particularly for gRPC-based services via interceptors?

**Comment by asim** [comment]
wrappers are go-micro's version of interceptors, if you're using the go-micro grpc client/server then wrappers will provide similar features. You can find examples of using wrappers here https://github.com/asim/go-micro/tree/master/examples/wrapper

**Comment by Tochemey** [comment]
From the look of the open tracing wrapper I am having a challenge on how to use it as an interceptor because most methods require some kind of argument. It is not like the OpenCensus one which looks pretty straightforward

**Comment by Tochemey** [comment]
Never mind I think I can use this https://github.com/asim/go-micro/blob/master/plugins/wrapper/trace/opentracing/opentracing.go#L134 and it will default to the global Tracer.

**Comment by Tochemey** [comment]
@asim I have this settings for my gRPC server. I cannot see any place where I should be setting tracing and metrics endpoints. This is my code snippet :
```
	svc := micro.NewService(
		micro.Name(s.cfg.ServiceName),
		micro.WrapClient(opentracing.NewClientWrapper(tracer)),
		micro.WrapHandler(opentracing.NewHandlerWrapper(tracer)),
		micro.WrapHandler(prometheus.NewHandlerWrapper()),
		micro.WrapClient(prometheus.NewClientWrapper()),
	)
```

**Comment by AuditeMarlow** [comment]
For OpenTracing it depends entirely on what implementation you're using. I've experience using Jaeger and the OpenTracing wrappers simply send the traces to the Jaeger service, so there is no endpoint to configure. You just configure the Jaeger client itself, wrap all the things and your traces will reach Jaeger. I'm not sure how this would work for other OpenTracing implementations but I'm assuming they will be similar.

You can check out [Gomu][1] to generate a project template including the [Jaeger client][2] all set up and ready to go.

I'm not sure about the monitoring wrappers as I haven't gotten around to testing them myself yet.

[1]: https://github.com/asim/go-micro/tree/master/cmd/gomu
[2]: https://github.com/asim/go-micro/tree/master/cmd/gomu#jaeger
