### ISSUE TITLE
Protobuf not generating RegisterExampleHandler? 

### ISSUE THREAD

**Issue by mdere** [micro/go-micro#228]
Hello - first off I am new to Golang and gomicro as a whole. So trying to learn this myself through micro go examples. So I am at the point where I am playing around with the template example. One thing I noticed after I ran protoc and building main.go -

github.com/test/greeter
./main.go:20:2: undefined: go_micro_srv_template.RegisterExampleHandler

Can someone please clarify if the example was suppose to work or I have to implement that method to my proto and my handler before I run protoc?

Also I am using Ubuntu 16 as my environment and I installed protobuf using this guide https://gist.github.com/sofyanhadia/37787e5ed098c97919b8c593f0ec44d8

Thanks in an advance!

**Comment by asim** [comment]
You need to use our fork of protoc-gen-go. It's in the readme https://github.com/micro/go-micro#install-protobuf.

**Comment by mdere** [comment]
@asim - so the readme says install protobuf and is linked to the original protobuf site, am I suppose to do that? - I did earlier, but prior to that I did the following command
`go get github.com/micro/protobuf/{proto,protoc-gen-go}` and I do see the folder protobuf. But I was confused because protoc didn't work when i tried it, but as soon I installed protobuf from the gist, protoc command works.

**Comment by mdere** [comment]
Actually. I just noticed the Gist had an older version..protobuf 3.2x - you think that is my issue?

**Comment by asim** [comment]
Installing protoc-gen-go is separate from installing protobuf and protoc. Our fork of protoc-gen-go includes code that generates specific methods. Please install protobuf in the usual way and then install protoc-gen-go from our fork and ensure it's linked in your bin path. If it's not in your bin path it will not be used.

**Comment by asim** [comment]
Closing, no response. As mentioned. Please do `go get github.com/micro/protobuf/{proto,protoc-gen-go}` and ensure the correct protoc-gen-go is in your path.
