### ISSUE TITLE
[BUG] micro.NewService add new server grpc cannot be used

### ISSUE THREAD

**Issue by xufei56789** [micro/go-micro#2299]
Client grpc request error after adding Server：
{"id":"go.micro.client.transport","code":500,"detail":"404 Not Found: 404 page not found","status":"Internal Server Error"}

Server side code：
	config.Init()
	etcdCnf := config.GetEtcdCnf()
	passlCnf := config.GetBillingProductCnf()
	etcdReg := etcd.NewRegistry(
		registry.Addrs(etcdCnf.Addrs[0]),
	)
	r := router.InitRouters()
	srv := httpServer.NewServer(
		server.Name("example"),
		server.Registry(etcdReg),
		server.Address(fmt.Sprintf(":%d", passlCnf.Port)),
	)
	hd := srv.NewHandler(r)
	srv.Handle(hd)
	service := micro.NewService(
		micro.Server(srv),       //Client grpc request error after adding Server
		micro.Name("example"),
		micro.Registry(etcdReg),
		micro.RegisterTTL(time.Second*30),
		micro.RegisterInterval(time.Second*15),
	)

	service.Init()
	grpc.RegisterProductServiceHandler(service.Server(), new(api.GetProductInfoServer))
	if err := service.Run(); err != nil {
		panic(err)
	}

Client code：

type logWrapper struct {
	client.Client
}

func (l *logWrapper) Call(ctx context.Context, req client.Request, rsp interface{}, opts ...client.CallOption) error {
	md, _ := metadata.FromContext(ctx)
	fmt.Printf("[Log Wrapper] ctx: %v service: %s method: %s\n", md, req.Service(), req.Endpoint())
	return l.Client.Call(ctx, req, rsp)
}

func newLogWrapper(c client.Client) client.Client {
	return &logWrapper{c}
}

func main() {
	config.Init()
	etcdCnf := config.GetEtcdCnf()
	etcdReg := etcd.NewRegistry(
		registry.Addrs(etcdCnf.Addrs[0]),
	)
	myService  := micro.NewService(
		micro.WrapClient(newLogWrapper),
		micro.Registry(etcdReg),
	)
	myService.Init()
	pro := api.NewProductService("example", myService.Client())
	res, errs := pro.GetProduct(context.Background(), &api.ProductRequest{ProductId: 11})
	fmt.Println()
	fmt.Println(errs)
	fmt.Println(res)
	time.Sleep(5 * time.Second)
}

**Comment by xpunch** [comment]
According to your code, you're using http server, so you need to use http client too.

**Comment by xufei56789** [comment]
> According to your code, you're using http server, so you need to use http client too.

大佬可以加个微信或者qq指导一下吗？有偿

**Comment by xpunch** [comment]
> > According to your code, you're using http server, so you need to use http client too.
> 
> 大佬可以加个微信或者qq指导一下吗？有偿

把你联系方式发我邮箱吧，如果不是go-micro的问题，建议close issue
