### ISSUE TITLE
go-micro/registry/consul_watcher.go

### ISSUE THREAD

**Issue by joeblew99** [micro/go-micro#23]
This looks really nice.
Wondering about a few things in terms of roadmap:
LB:  In terms of load balancer are you thinking about Fabio i wonder ? It hooks stright into Consul too.
https://github.com/eBay/fabio

Client micro-services:
HTTP/2 means we no longer have to try to push everything into a few http paylaods anymore.
So, it makes it possible to do web components as micro-services :)
Also i do versioning hashing this way, just to give you an idea:

```

module.exports = {
  baseUrl : 'https://mysite.com/static/',
  resources : {
    vendor : {
      version : 'vendor-d41d8cd98f.js',
      pushWith : [ 'scout' ]
    },
    application : {
      version : 'application-a32e3ec23d.js',
      pushWith : [ 'scout' ]
    },
    secondary : {
      version : 'secondary-e43b8ad12f.js',
      pushWith : [ ]
    }
  }
};

```

**Comment by asim** [comment]
Hey. I've looked at fabio but not yet sure about integration points. Load balancing is definitely on the roadmap in a couple forms. One is having the notion of a "Node Selector" option in the client package which will default to random hashed load balancing but then future work is to build a pluggable router as part of the go-platform here https://github.com/micro/go-platform which can provide better global load balancing, label based routing, etc.

There's also definitely a goal of building micro web services and supporting it as part of the ecosystem. We only have our experiences from Hailo to draw on at the moment but ideas are obviously welcome. It's likely that an initial implementation will be to add a web proxy to Micro and make web apps first class citizens as micro services.

**Comment by joeblew99** [comment]
thanks.
sounds similar.
any chance you can make a roadmap ? just so i can get a sense of the journey 
also a stack diagram. you have allot of layers to this

**Comment by asim** [comment]
Yea sure, it's on the "roadmap" lol. Had my head down building stuff. Just gave the web UI a facelift https://github.com/micro/micro/tree/master/web. I'll make a mental note to put together the roadmap this week.

**Comment by asim** [comment]
Roadmap started here https://github.com/micro/micro/wiki/Roadmap

**Comment by joeblew99** [comment]
wow that was quick. thanks its a big help.
