### ISSUE TITLE
enable stopping of web server without using a signal

### ISSUE THREAD

**Issue by stefansavev-o** [micro/go-micro#231]
In `go-micro/server/server.go`, function Run, I find this code to stop the server:
```
	ch := make(chan os.Signal, 1)
	signal.Notify(ch, syscall.SIGTERM, syscall.SIGINT, syscall.SIGKILL)
	log.Logf("Received signal %s", <-ch)
```
This code relies on syscall.SIGTERM and might interact with other parts of the application.
Is it possible to expose a Stop function, which will send to the channel directly.
In the short run we are looking for a very simple fix.
For example a new run function with a signature:
```
RunWithStopChannel(ch <-channel)
```
where we have access to the channel will do for us.

**Comment by asim** [comment]
If you're looking to signal the service to stop, please see the context cancellation example https://github.com/micro/examples/blob/master/shutdown/main.go

**Comment by stefansavev-o** [comment]
Thanks a lot for the quick response. Just to make sure we are talking about the same thing.
In go-micro there is the micro service (the example you sent) and the web service (the example I sent).
Would the solution apply to the web service as well?

**Comment by asim** [comment]
The sample code you've provided is just the server package within go-micro. If you look at the top level micro service code you'll see it's using that server. If you're talking about the go-web repo that's entirely different.

**Comment by stefansavev-o** [comment]
Yes, thank you. Talking about  go-web. That's the wrong place I guess.
