### ISSUE TITLE
[BUG]go get -d github.com/asim/go-micro/plugins/server/grpc/v4 failed

### ISSUE THREAD

**Issue by bootfirst** [micro/go-micro#2316]
**Describe the bug**

go: github.com/asim/go-micro/plugins/server/grpc/v4@v4.0.0-20211019191242-9edc569e68bb requires
        github.com/asim/go-micro/plugins/client/grpc/v4@v4.0.0-20211013123123-62801c3d6883: parsing go.mod: go.mod:6:2: require github.com/asim/go-micro/plugins/registry/memory/v4: version "master" invalid: must be of the form v1.2.3

**How to reproduce the bug:**

go get -d github.com/asim/go-micro/plugins/server/grpc/v4

commit "62801c3d6883" set the wrong tag "master" for the requires in the go.mod

change it to the latest 9edc569e68bb will solve it.

**Comment by xpunch** [comment]
you can try
```
go get -u github.com/asim/go-micro/plugins/server/grpc/v4@v4.0.0-20211023082042-af3cfa0a4cac
```

**Comment by bootfirst** [comment]
OK.
Success.
Thanks.
