### ISSUE TITLE
how to send message after EOF

### ISSUE THREAD

**Issue by GaloisZhou** [micro/go-micro#2318]
I use `gomu new service user` to generate a user service project.

In the file `handler/user.go`, I see the following statements:

```go
		if err == io.EOF {
			log.Infof("Got %v pings total", count)
			return stream.SendMsg(&pb.ClientStreamResponse{Count: count})
		}
```

I don't understand how to `send msg` after `EOF`. 
My understanding is :

1. client close the stream
2. server get `EOF`

At this time. The stream is closed, server cannot send message and client cannot get message.

I look forward to your help to answer my doubts. Thank you!

**Comment by bootfirst** [comment]
if you use origin google.golang.org/grpc client, you can use grpc.CloseSend().
Then the server stream.Recv() will return io.EOF.
Then send the response back.（the stream is bidirectional)

**Comment by gz1115** [comment]
Thanks a lot! I find the method(in stream.go):

```go

func (as *addrConnStream) CloseSend() error {
	if as.sentLast {
		// TODO: return an error and finish the stream instead, due to API misuse?
		return nil
	}
	as.sentLast = true

	as.t.Write(as.s, nil, nil, &transport.Options{Last: true})
	// Always return nil; io.EOF is the only error that might make sense
	// instead, but there is no need to signal the client to call RecvMsg
	// as the only use left for the stream after CloseSend is to call
	// RecvMsg.  This also matches historical behavior.
	return nil
}
```
