### ISSUE TITLE
[FEATURE]How to use client.Stream like grpc.CloseSend()

### ISSUE THREAD

**Issue by bootfirst** [micro/go-micro#2319]
I use the plugins/client/grpc to send request, but I don't know how to close the send
(the server know the client's close and will close too, so I can get a io.EOF to finish the stream request)

https://github.com/asim/go-micro/issues/2212
xpush said "I used a workaround in my project by sending an empty object to present EOF, not a very good solution, but solved my issue."
SO, HOW? WHAT DOES "empty object" MEAN?

**Comment by xpunch** [comment]
Currently client.Stream do not support grpc.CloseSend(), cause this only supported by grpc which uses http 2.
"empty object" is used to present EOF, which can be an empty Chunk Data or something should not be empty.
For example, you can send an empty byte slice after client data sending finished,  when the server received an empty byte slice, if start to handle received chunk data.

**Comment by xpunch** [comment]
I've created an example in [stream](https://github.com/xpunch/go-micro-example/tree/main/v3/stream), you can take a look.

**Comment by bootfirst** [comment]
👍🏻
