### ISSUE TITLE
s/gomu/micro

### ISSUE THREAD

**Issue by asim** [micro/go-micro#2324]
Even though there is a "micro" in github.com/micro/micro, do we rename gomu to micro? Considering the go-micro import package is micro, maybe the naming is just better that way. Might cause a whole bunch of issues, but then there there is also an editor called micro https://github.com/zyedidia/micro. I feel like it's a second chance at creating the CLI tooling around go-micro thats needed.

Thoughts @AuditeMarlow?

**Comment by AuditeMarlow** [comment]
I agree, I've opened a new PR to address this.
