### ISSUE TITLE
Handler result error is ignore

### ISSUE THREAD

**Issue by onrik** [micro/go-micro#234]
https://github.com/micro/go-micro/blob/master/server/subscriber.go#L232
Currently it's impossible to handle return value from handler. Do you have some solution?

**Comment by asim** [comment]
What return value? This is the subscriber. A subscriber does not return anything

**Comment by onrik** [comment]
Function [fn](https://github.com/micro/go-micro/blob/master/server/subscriber.go#L232) returns error, but it's handle nowhere.

**Comment by asim** [comment]
What should be the appropriate behaviour? Please PR the change

**Comment by asim** [comment]
Now fixed with this commit https://github.com/micro/go-micro/commit/b39ec4472c0b6da5bcb6c80ab7acabe1da9d4e20
