### ISSUE TITLE
Unable to unmarshal messages containing oneofs; fixed by using jsonpb

### ISSUE THREAD

**Issue by liilac** [micro/go-micro#237]
At present, it is not possible using go-micro to accept JSON input containing messages with `oneof`s.  

This is due to the use of `encoding/json` rather than `github.com/golang/protobuf/jsonpb`, the latter of which is capable of processing `oneof`s.

When attempting to do so, the following error is encountered
```
2018/03/15 01:20:42 Unexpected error serving request, closing socket: json: cannot unmarshal object into Go struct field Backend.Config of type [redacted].isBackend_Config
```

The message definition I am using is as follows
```protobuf
// a storage backend
message Backend {
  // unique identifier for the Storage entry
  UUID uuid = 1;
  // type of the storage backend, as considered by graymeta/stow
  string kind = 2;
  // storage backend configuration
  oneof config {
    BackendConfigLocal config_local = 10;
    BackendConfigS3 config_s3 = 11;
    BackendConfigGCS config_gcs = 12;
    BackendConfigABS config_abs = 13;
    BackendConfigSwift config_swift = 14;
    BackendConfigOSCS config_oscs = 15;
    BackendConfigB2 config_b2 = 16;
  }
}
```
and the JSON I am using, noting that to ensure I was using the correct format, I marshalled this from within Go
```JSON
{"backend":{"kind":"local","Config":{"ConfigLocal":{"path":"/tmp"}}}}
```

I am testing this using `micro web`'s interface.

Please see [this issue](https://github.com/golang/protobuf/issues/446) for a potential fix.  The comments in the issue seem to indicated it is necessary to use `jsonpb` rather than `encoding/json` in order to support `oneof`s.

**Comment by asim** [comment]
The issue has been raised before. We're aware that we do not support oneof by default. Someone PRed a codec to support this but it needs to be in go-plugins https://github.com/micro/go-micro/pull/220. You can use this codec instead of the default for json.

**Comment by liilac** [comment]
Alright, thanks.  I'll look into that.

**Comment by liilac** [comment]
What issues are preventing jsonpb from being used as the default for JSON?

**Comment by asim** [comment]
The default json-rpc codec supports actual json rpc 1.0. This codec doesn't do that at all. It's a hack of the proto codec to try support oneof with json. It does not take into consideration request/response format in coordination with json-rpc. It's not the way I would solve the problem.

**Comment by liilac** [comment]
Do you have any suggestions on better ways to solve the lack of `oneof` support?

**Comment by liilac** [comment]
Also, is there any way to have the `micro` cli support `oneof`s?  Would I need to write a custom command line client in order to support `oneof`s?

@asim

**Comment by asim** [comment]
I thought you were working on this PR https://github.com/micro/go-plugins/pull/161

**Comment by liilac** [comment]
@asim I am, but I've had to modify the `micro` cli's code in order to get it to use my alternative codec.  What would the appropriate way to have it use an alternative codec be?

**Comment by asim** [comment]
Closing as I think this is unlikely to be supported any time soon.
