### ISSUE TITLE
rpc client seq always equal to 0

### ISSUE THREAD

**Issue by Leon2012** [micro/go-micro#239]
2018/03/20 12:26:06 send seq : 0, 1
2018/03/20 12:26:06 rpc client write json : {"method":"Greeter.Hello","params":[{"name":"leon"}],"id":0}
2018/03/20 12:26:06 rpc client recv json : {"id":0,"result":{"greeting":"Hello, leon"},"error":null}
127.0.0.1 - - [20/Mar/2018:12:26:06 +0000] "POST /rpc HTTP/1.1" 200 26 "" "curl/7.35.0"
2018/03/20 12:26:13 send seq : 0, 1
2018/03/20 12:26:13 rpc client write json : {"method":"Greeter.Hello","params":[{"name":"leon"}],"id":0}
2018/03/20 12:26:13 rpc client recv json : {"id":0,"result":{"greeting":"Hello, leon"},"error":null}
127.0.0.1 - - [20/Mar/2018:12:26:13 +0000] "POST /rpc HTTP/1.1" 200 26 "" "curl/7.35.0"
2018/03/20 12:26:21 send seq : 0, 1
2018/03/20 12:26:21 rpc client write json : {"method":"Greeter.Hello","params":[{"name":"leon"}],"id":0}
2018/03/20 12:26:21 rpc client recv json : {"id":0,"result":{"greeting":"Hello, leon"},"error":null}
127.0.0.1 - - [20/Mar/2018:12:26:21 +0000] "POST /rpc HTTP/1.1" 200 26 "" "curl/7.35.0"

rpc_client.go
`stream := &rpcStream{
		context: ctx,
		request: req,
		closed:  make(chan bool),
		codec:   newRpcPlusCodec(msg, c, cf),
	}`

rpc_stream.go
`func (r *rpcStream) Send(msg interface{}) error {
	r.Lock()
	defer r.Unlock()

	if r.isClosed() {
		r.err = errShutdown
		return errShutdown
	}

	seq := r.seq
	r.seq++`

**Comment by asim** [comment]
PR a fix?

**Comment by asim** [comment]
Merged
