### ISSUE TITLE
Cache selector returns stale service nodes

### ISSUE THREAD

**Issue by ginuerzh** [micro/go-micro#244]
I have a gRPC service, and there are two instances of this service for load balancing. There is also a web API service that calls this gRPC service (using consul as service discovery).

Then I use `ab` to simulate the user calling the web API service concurrently. During this process, I repeatedly restarted one of the instances.
I found that when I stop the instance, the cache selector will have a small probability of returning the stopped service instance instead of another normal running instance during the next gRPC call. 
So the RPC call failed with an error: `all SubConns are in TransientFailure`.

BTW, there is a race condition in cache selector:

```
WARNING: DATA RACE
Write at 0x00c4208af6c0 by goroutine 194:
  github.com/micro/go-micro/registry.(*consulWatcher).serviceHandler()
      github.com/micro/go-micro/registry/consul_watcher.go:165 +0x12d9
  github.com/micro/go-micro/registry.(*consulWatcher).(github.com/micro/go-micro/registry.serviceHandler)-fm()
      github.com/micro/go-micro/registry/consul_watcher.go:209 +0x5f
  github.com/hashicorp/consul/watch.(*Plan).Run()
      github.com/hashicorp/consul/watch/plan.go:96 +0x9eb

Previous read at 0x00c4208af6c0 by goroutine 427:
  github.com/micro/go-micro/selector/cache.(*cacheSelector).cp()
     github.com/micro/go-micro/selector/cache/cache.go:55 +0x751
  github.com/micro/go-micro/selector/cache.(*cacheSelector).get()
      github.com/micro/go-micro/selector/cache/cache.go:120 +0x5d7
  github.com/micro/go-micro/selector/cache.(*cacheSelector).Select()
      github.com/micro/go-micro/selector/cache/cache.go:350 +0x182
  github.com/micro/go-plugins/client/grpc.(*grpcClient).Call()
     github.com/micro/go-plugins/client/grpc/grpc.go:200 +0x214
  main.rpcCall()
```

**Comment by asim** [comment]
Caching will always involve stale data for some small window of time between a service shutting down and updates being propagated to all those watching. The caching selector is watching the registry for changes. We cannot help the milliseconds between which a request is made and the registry is updated. If you want to prevent this issue, enable retries with `CLIENT_RETRIES=3` or `--client_retries=3`. When the first request fails it will be retried against the next node in the list. This is what the selector is for. 

I'll deal with the race condition separately, thanks.
