### ISSUE TITLE
Failed to start go-micro

### ISSUE THREAD

**Issue by wugengxiong** [micro/go-micro#246]
At present, it is not possible using go-micro to start, detail as follow: 

2018-04-10 11:48:56.343074 I | Listening on [::]:59930
2018-04-10 11:48:56.343172 I | Broker Listening on [::]:31182
No private IP address found, and explicit IP not provided

**Comment by asim** [comment]
It implies it cannot find a private ip on your host

**Comment by asim** [comment]
Please provide info about your environment. If a private IP does not exist it will throw this error.
