### ISSUE TITLE
pubsub whether can using etcd?

### ISSUE THREAD

**Issue by NSObjects** [micro/go-micro#249]
![image](https://user-images.githubusercontent.com/17995427/38843730-0163ae48-4223-11e8-8a91-b6fdfcf56037.png)

![image](https://user-images.githubusercontent.com/17995427/38843741-0c48cf00-4223-11e8-99a8-ca2bdf3f0e4b.png)

i using consul,pubsub is normal,but i using etcd can't start

**Comment by asim** [comment]
This looks like a bug. I'll fix in a little while. Thanks for reporting. I think you can probably override this issue right now by importing as `_ "github.com/micro/go-plugins/registry/etcdv3"` and then `--registry=etcv3` on the command line.

**Comment by asim** [comment]
Should now be fixed with this commit https://github.com/micro/go-micro/commit/ccbc1b9cf3e0ad37494a1c7f41e7dbc783011178. Please update code, test and close issue if happy.

**Comment by NSObjects** [comment]
@asim thanks,
