### ISSUE TITLE
How to extract annotated options from grpc method?

### ISSUE THREAD

**Issue by TechMaster** [micro/go-micro#250]
Hi,

I want to add some custom properties to grpc method in protobuf. However I don't how to extract value of these properties when initializing micro server.
Below is sample proto file. I add some custom properties to method GoodBye.
[Full working demo here](https://github.com/TechMaster/GogoBuf/)
```proto
syntax = "proto2";

import "github.com/gogo/protobuf/gogoproto/gogo.proto";
import 'google/protobuf/descriptor.proto';

extend google.protobuf.MethodOptions {
	optional string description = 50056;
	optional bool internalMethod = 50057;
}

service Greeter  {
	rpc Hello(HelloRequest) returns (HelloResponse) {}
	rpc GoodBye(HelloRequest) returns (HelloResponse) {
		option(description) = "This is an internal goodbye method";
		option(internalMethod) = true;
	}

};

message HelloRequest {
	optional string name = 1 ;
}
message HelloResponse {
	optional string greeting = 2;
}
```

**Comment by asim** [comment]
Hi,

You may want to google this issue since it's directly related to Google protobuf. Unfortunately I don't have the experience to help you with this.

https://github.com/golang/protobuf/issues/179
