### ISSUE TITLE
consul TCPCheck register!

### ISSUE THREAD

**Issue by wujibing** [micro/go-micro#251]
If I set the global variable MICRO_REGISTRY_ADDRESS, then I use micro.Registry also has nothing to do with it.

service := micro.NewService(
		micro.Name("go.micro.srv.token"),
		micro.Version("latest"),
		micro.Registry(consul.NewRegistry(consul.TCPCheck(time.Second))),
	)
log.Logf("%p",service.Options().Registry)
service.Init()
log.Logf("%p",service.Options().Registry)
results：
0xc0423ffb90
0xc0423ffc00

Tracking code found that Registry was replaced in the go-micro/cmd/cmd.go 296th line.

**Comment by asim** [comment]
If you're setting the registry and options yourself then you must set the registry address yourself too. The command line initialisation replaces the registry because there's no other way to pass in the address option.
