### ISSUE TITLE
How can I use consul for service discovery?

### ISSUE THREAD

**Issue by gexinworks** [micro/go-micro#252]
I am trying to use go-micro for microservice.I install consul in my server machine,and I install the service in another machine,and I writed a go-micro client in my work machine .When I tried to use the client call the service,I don't know how to declare the service discovery address in my code.

**Comment by asim** [comment]
Type --help. It will show you the option to set the registry address.

**Comment by wjzhangcsu** [comment]
#188

**Comment by wjzhangcsu** [comment]
#188

**Comment by gexinworks** [comment]
#188

**Comment by gexinworks** [comment]
@asim ,I have the same problem.when I exec "go run client.go --registry_address 192.68.2.198",it still looks at 127.0.0.1,what should i do? #188
