### ISSUE TITLE
Does the go-micro client alse need to be registered in consul?

### ISSUE THREAD

**Issue by gexinworks** [micro/go-micro#253]
When the client 、service and consul all run my own computer ,they worked well. When I move the service and consul into k8s cluster. The client can not find the service . Does the go-micro client alse need to be registered in consul? The go-micro client has not been registered in consul. #252

**Comment by asim** [comment]
If the client can't find the service it's because the service is not registering correctly or its registering an incorrect address. I can't help without actually knowing what your configuration is. Please join the slack to get help.

**Comment by chengyayu** [comment]
@wjzhangcsu do you solve this problem? i have the same problem.

**Comment by gexinworks** [comment]
@ChengYayu Yes. Clinet and server all  go run *.go --registry_address=consul.default:8500.

**Comment by gexinworks** [comment]
@ChengYayu But I don't use go-micro Now.

**Comment by chengyayu** [comment]
Got it. Thanks

Works <notifications@github.com>于2018年8月13日 周一13:57写道：
