### ISSUE TITLE
How to run go-micro as a background deamon?

### ISSUE THREAD

**Issue by longtechmaster** [micro/go-micro#255]
~> go run main.go
2018/05/12 03:15:45 Listening on [::]:39881
2018/05/12 03:15:45 Broker Listening on [::]:46045
2018/05/12 03:15:45 Registering node: service-blog-c2d0ea3b-5592-11e8-ba4e-9c5c8e97ade3

I tried to run go-micro background , but i cant. So how to do that, thanks!

**Comment by asim** [comment]
Please search for process managers. Go-micro is a Go library.
