### ISSUE TITLE
Flag overrides default selector 

### ISSUE THREAD

**Issue by Alma-media** [micro/go-micro#256]
Hi, I was trying to use `go-micro` with custom selector and faced with an issue:
1. [`defaultSelector`](https://github.com/micro/go-micro/blob/master/selector/selector.go#L38) is never used since it is overridden by the flag:
https://github.com/micro/go-micro/blob/master/cmd/cmd.go#L146

2. As a result we should **always** use the flag to override `cacheSelector` running the application (just an import is not enough to make use of custom selector):
```go
package main

import(
	"github.com/micro/go-plugins/selector/named"
	// other imports
)

func main() {
	rpcClient := client.NewClient(client.Selector(selector))
	// other logic
}
```
in order to enable `named` (or any other custom) selector we have to provide corresponding flag:
```bash
$ go run client.go -selector=named
```

I do not know what is the best way to solve it (maybe replace `default` selector with `cache` and remove default flag value). Most probably you have a better solution, but anyway please let me know if I can help.
Regards, Alex

**Comment by asim** [comment]
If you call `cmd.Init` or `service.Init` it will set the selector to cache which means you must override it. If you do not call `Init` then whatever you set in the client will be used or it uses the `default` selector without cache.

**Comment by Alma-media** [comment]
ok! thanks a lot. I used `service.Init` (removed and it works).
