### ISSUE TITLE
Some problem when using grpc-gateway on go-micro

### ISSUE THREAD

**Issue by ShiningRush** [micro/go-micro#257]
Now i'm using grpc-gateway to proxy my grpc services.
Before i change to go-micro, everything is fine,
and after i used go-grpc to init my service , i find that my grpc-gate is not work, it will get a code:12(not implement).

Then i compare the output files between protoc-gen-grpc and protoc-gen-micro, notice a strange differences as below:
protoc-gen-micro output file(xxxx.micro.go):

```
...
func (c *reportserviceService) GetCustomerStatistic(ctx context.Context, in *GetCustomerStatisticInput, opts ...client.CallOption) (*GetCustomerStatisticOutput, error) {
	req := c.c.NewRequest(c.name, "Reportservice.GetCustomerStatistic", in) // notice the method string
	out := new(GetCustomerStatisticOutput)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}
...
```

protoc-gen-grpc output file(xxxx.pb.go)
```
...

func (c *reportserviceClient) GetCustomerStatistic(ctx context.Context, in *GetCustomerStatisticInput, opts ...grpc.CallOption) (*GetCustomerStatisticOutput, error) {
	out := new(GetCustomerStatisticOutput)
	err := grpc.Invoke(ctx, "/report.reportservice/GetCustomerStatistic", in, out, c.cc, opts...) // here is diffrent with micro's
	if err != nil {
		return nil, err
	}
	return out, nil
}
...
```

my proto file:

```
syntax = "proto3";

option csharp_namespace = "FM.CRM.Report";

package report;

// The reportservice service definition.
service reportservice {
  // GetCustomerStatistic
  rpc GetCustomerStatistic (GetCustomerStatisticInput) returns (GetCustomerStatisticOutput) {}
}

// The GetCustomerStatistic input
message GetCustomerStatisticInput {
  string SearchValue = 1;
  string SearchType = 2;
  int32 TradeTimeStart =3;
  int32 TradeTimeEnd =4;
  string RegisterTimeStart=5;
  string RegisterTimeEnd =6;
  string DynamicTimeStart=7;
  string DynamicTimeEnd=8;
  string AssignTimeStart =9;
  string AssignTimeEnd=10;
  repeated int32 FollowerUserIds=11;
  repeated int32 AutoTagTypeValues=12;
  repeated int32 FollowTagTypeValues =13;
  repeated int32 PersonalityTagValues=14;
  repeated int32 FollowModeTagTypeValues=15;
  int32 OperatorUserId=16;
  string OrderBy=17;
  bool IsDescending=18;
  repeated int32 BrokerIds=19;
  int32 GroupId=20;
  int32 PageIndex=21;
  int32 PageSize=22;
}

// The GetCustomerStatistic output
message GetCustomerStatisticOutput {
  repeated Item Items = 1;

  message Item{
    string CustomerId = 1;
    string FmUserId = 2;
    string NickName =3;
    string RealName =4;
    string TagNames=5;
    string PhoneNumber =6;
    string Email=7;
    string TotalBalance=8;
    string TotalOutAmount =9;
    string TotalIncomeAmount=10;
    string TotalProfit=11;
    string TotalStandardLots=12;
    string VCode=13;
    string AccountCount=14;
    string PromoterUserName=15;
    string FollowerUserName=16;
  }
}
```

Why method name of grpc is "/report.reportservice/GetCustomerStatistic" and micro is "Reportservice.GetCustomerStatistic"?

If i modify the grpc's method name same with micro manually, grpc-gateway will work well.

Is i missing some configurations?

**Comment by ShiningRush** [comment]
Thanks for reply,

> For the grpc-gateway use standard grpc generated code
> For go-micro/go-grpc use micro generated code

Yes, I am already did as so in code, 
but problem is that grpc-gateway's reverse proxy server can not connect service, and i can consume service normally with go-micro client, so server is work well with go-micro, maybe grpc-gateway need some special config?

**Comment by asim** [comment]
Your gateway uses `reportservice` with lowercase. Our services only register with upper case e.g `Reportservice` because Go servers do not expose internal types. `service reportservice {` should be `service ReportService {`

**Comment by ShiningRush** [comment]
You are right,  i uppercase the service name then everything work well (even method name still different, it is amazing),
But i want to know why can i still consume service with go-micro client when service name is lowercase.
Thanks!

**Comment by asim** [comment]
My assumption is that there's a discrepancy between the way in which we generate code and what we expect to register. I'll have to look into it.

**Comment by PerfecterDay** [comment]
> My assumption is that there's a discrepancy between the way in which we generate code and what we expect to register. I'll have to look into it.

Hi asim, any update here ? I come accross the same problem with the lowercase method. Does go-micro only support uppercase method name ? I look into some go-micro source code, and find out go-micro use reflect to register service and method, and the method name in generated micro.pb file is always uppercase, even I used lowercase in .proto file. I am not sure about this. So my question is does go-micro only support uppercase proto method name ?
