### ISSUE TITLE
Multiple goroutine call clients

### ISSUE THREAD

**Issue by lovelly** [micro/go-micro#265]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x87c398]

goroutine 357944 [running]:
mp/vendor/github.com/micro/go-micro/client.(*rpcClient).Call.func1(0x0, 0xc42063e7c8, 0x7b04be)
        F:/gowork/src/mp/vendor/github.com/micro/go-micro/client/rpc_client.go:299 +0x188
mp/vendor/github.com/micro/go-micro/client.(*rpcClient).Call.func2(0xc421b78720, 0xc421b786c0, 0xc42024b6d8)
        F:/gowork/src/mp/vendor/github.com/micro/go-micro/client/rpc_client.go:315 +0x33
created by mp/vendor/github.com/micro/go-micro/client.(*rpcClient).Call
        F:/gowork/src/mp/vendor/github.com/micro/go-micro/client/rpc_client.go:314 +0x4a1

**Comment by asim** [comment]
You closed the issue. Is this an actual issue?
