### ISSUE TITLE
If the service name contains an underscore, the browser path will not be found

### ISSUE THREAD

**Issue by locxiang** [micro/go-micro#266]
![image](https://user-images.githubusercontent.com/6622033/41293639-6f5cc056-6e88-11e8-8c7c-6bd87c76bbe7.png)

![image](https://user-images.githubusercontent.com/6622033/41293670-82e49d38-6e88-11e8-84ba-77057629d364.png)

![image](https://user-images.githubusercontent.com/6622033/41293679-88e62bde-6e88-11e8-9571-37f8ad76ec29.png)

```
micro --registry_address=consul:8500 --register_interval=5 --register_ttl=10 --enable_stats web --namespace=go.micro.web
```

**Comment by asim** [comment]
This is an issue with the micro toolkit, not go-micro. Please file under the micro project.
