### ISSUE TITLE
*.pb.go file     Unable to generate a function to register a micro service to the go-micro server

### ISSUE THREAD

**Issue by YJinHai** [micro/go-micro#270]
Hello, I am following this tutorial, but I have encountered a problem that cannot be solved. I want to implement a warehouse micro-service.
Attach a link to this section:[https://ewanvalentine.io/microservices-in-golang-part-2/](url)
This is my **Makefile**:
`build:
        protoc -I. --go_out=plugins=micro:$(GOPATH)/src/shippy/consignment-service \
                proto/consignment/consignment.proto
`
**consignment.proto**:
`
service ShippingService {
  rpc CreateConsignment(Consignment) returns (Response) {}
  rpc GetConsignments(GetRequest) returns (Response) {}
}`
but in **main.go**,This service function is not available in pb file after make build
`func main() {
        server := micro.NewService(
                micro.Name("go.micro.srv.consignment"),
                micro.Version("latest"),
        )
        server.Init()
        repo := Repository{}
        pb.RegisterShippingServiceHandler(server.Server(), &service{repo})
        if err := server.Run(); err != nil {
                log.Fatalf("failed to serve: %v", err)
        }
}`
**error**:
`./main.go:76:2: undefined: go_micro_srv_consignment.RegisterShippingServiceHandler`
I just learned micro service. This problem has been bothering me for two days. I can only deal with issues. I am looking forward to your reply.

Thank

**Comment by asim** [comment]
This method of building proto code is no longer supported. Please see and use the repo protoc-gen-micro

**Comment by q00148943** [comment]
After install protocols-gen-go with the following command, the problem solved:
go get -u github.com/micro/protobuf/protoc-gen-go

**Comment by asim** [comment]
github.com/micro/protobuf is deprecated. Use github.com/google/protobuf/protoc-gen-go and github.com/micro/protoc-gen-micro
