### ISSUE TITLE
how to specify the target server for client?

### ISSUE THREAD

**Issue by seaguest** [micro/go-micro#271]
Hello,

I want to run the micro service on one server, and other servers call theres services on that server, is that possible? I didn't find a proper example to do that.

```
	// Create a new service. Optionally include some options here.
	service := micro.NewService(micro.Name("greeter.client"))
	service.Init()

	// Create new greeter client
	greeter := proto.NewGreeterService("greeter", service.Client())

	// Call the greeter
	rsp, err := greeter.Hello(context.TODO(), &proto.HelloRequest{Name: "John"})
	if err != nil {
		fmt.Println(err)
	}
```

Here I want to specify the target server where creating the service, how could I achieve that ?

**Comment by asim** [comment]
Every service registers its address with service discovery. The client automatically load balances between instances of the same service. If you want to directly route to a specific service you can specify the `client.WithAddress` option at time of doing `greeter.Hello` https://godoc.org/github.com/micro/go-micro/client#WithAddress

**Comment by seaguest** [comment]
@asim 

There is one thing unclear for me here is how the service discovery works.
All code I saw seems based on the fact service discovery is available for server and client, is there are on different physical servers, only server starts consul, how could client find the server? 
even if I start consul on client, how can the two consul instances find each other? 
sorry for that I may have some misunderstanding on service discovery.

Moreover, it seems the WithAddress is removed from the code, I updated my master branch, but I didn't find anything related with WithAddress.

**Comment by seaguest** [comment]
Finally, I installed consul on both machines, and the client's side joins the server side. then it works.
On server side:
`consul agent -dev -bind=ServerIp
`
then start the service

On client side:
```
consul agent -dev -bind=ClientIp
consul join ServerIp
```

**Comment by seaguest** [comment]
It seems this is the best way to do that:
```
	reg := registry.NewRegistry(registry.Addrs("public consul ip"))

	service := micro.NewService(
		micro.Name("greeter.client"),
		micro.Version("latest"),
		micro.Registry(reg),
	)

```

**Comment by tinygg** [comment]
> @asim
> 
> There is one thing unclear for me here is how the service discovery works.
> All code I saw seems based on the fact service discovery is available for server and client, is there are on different physical servers, only server starts consul, how could client find the server?
> even if I start consul on client, how can the two consul instances find each other?
> sorry for that I may have some misunderstanding on service discovery.
> 
> Moreover, it seems the WithAddress is removed from the code, I updated my master branch, but I didn't find anything related with WithAddress.

@seaguest _WithAddress_ is still usefull, my case is below.
```
func main() {
	srvName, srvVersion := impl.SrvInfo.ToString()

	reg := consul.NewRegistry(func(op *registry.Options) {
		op.Addrs = []string{"10.0.0.13:8500"}
	})

	service := micro.NewService(
		micro.Registry(reg),
		micro.Version(srvVersion))

	service.Init()

	echoSrvService := demo.NewEchoSrvService(srvName, service.Client())

	// Call ping in a loop
	var count int64
	for {
		//set the preferred server when invoking
		rsp, err := echoSrvService.Ping(context.Background(), &demo.EchoRequest{Msg: fmt.Sprintf("xxx%d", count)},
			client.WithAddress("10.0.0.14:46663"))  <<<###############
		count++
		//rsp, err := echoSrvService.Ping(context.Background(), &demo.EchoRequest{Msg: fmt.Sprintf("xxx%d",count)})
		if err != nil {
			fmt.Println(err)
		} else {
			// Print response
			fmt.Println(rsp.Pong)
		}
		time.Sleep(500 * time.Millisecond)
	}
}
```
