### ISSUE TITLE
add license header to every source code file

### ISSUE THREAD

**Issue by xiang90** [micro/go-micro#273]
Please see http://www.apache.org/dev/apply-license.html#new

example: https://github.com/coreos/etcd/blob/master/client/auth_role.go#L1-L15

**Comment by asim** [comment]
No, not happening. It says it "should", that does not mean it "must". Nobody does this.

**Comment by xiang90** [comment]
@asim 

> that does not mean it "must". Nobody does this.

A lot of people do it:

https://github.com/kubernetes/kubernetes/blob/master/pkg/auth/authorizer/abac/abac.go
https://github.com/astaxie/beego/blob/master/cache/cache.go
https://github.com/gin-gonic/gin/blob/master/json/json.go

I am not going to add more into the list. It is easier for other people to consume your code. There is a reason why Apache mentioned it.

But it is up to you to follow it. I am just making a suggestion to you.

**Comment by asim** [comment]
Is this stopping you from using go-micro? Is Alibaba thinking of using micro?

**Comment by xiang90** [comment]
> Is this stopping you from using go-micro? Is Alibaba thinking of using micro?

As I said, it will make your code easier to consume for other people. People can simply keep the header you put there when embed your source code. I reminder you this as an open source developer.

I do not have a strong opinion either way. It is really up to you.

**Comment by asim** [comment]
Is it preventing you or Alibaba from using micro?
