### ISSUE TITLE
micro tag problem

### ISSUE THREAD

**Issue by cute-angelia** [micro/go-micro#276]
hello , i'am use " mirco api , api, and srv " , run the mistake for a moment in consul and the http status with 500

some consul log 

```
 2018/07/18 17:29:24 [DEBUG] agent: Service tag "t-789caa562a294acc2b2ec82f2a51b252ca28292950aa05040000ffff4f930768" will not be discoverable via DNS due to it being too long. Valid lengths are between 1 and 63 bytes.
    2018/07/18 17:29:24 [DEBUG] agent: Service tag "t-789caa562a4a4dcf2c2e29aa54b2524acecf2b2ecd51aa05040000ffff560f07c8" will not be discoverable via DNS due to it being too long. Valid lengths are between 1 and 63 byte
```

Is there a way?

**Comment by asim** [comment]
There's nothing that's going to fix this. We'll likely move to using service metadata soon which may resolve it. But this is just a debug message, we don't actually use consul dns.

**Comment by cute-angelia** [comment]
ok, thank you~
