### ISSUE TITLE
micro api issue

### ISSUE THREAD

**Issue by yuyongbo** [micro/go-micro#282]
I use service discovery Etcdv3,other problem had resolved,But there has a problem:I don't know how to use the micro api command for providing gateway service. please help me or  take a guide with me .

**Comment by asim** [comment]
Please read the micro readme for using plugins. https://github.com/micro/micro#plugins

**Comment by yuyongbo** [comment]
I runned this command:
`$ MICRO_REGISTRY=etcdv3 micro api
Registry etcdv3 not found`

**Comment by asim** [comment]
Read the readme, it tells you that you need to include the plugin. Read the ENTIRE section.
