### ISSUE TITLE
More Error details

### ISSUE THREAD

**Issue by cute-angelia** [micro/go-micro#285]
i got some errors when client call SRV and SRV not runing

```
     {"id":"go.micro.client","code":500,"detail":"none available","status":"Internal Server Error"}
```

in this error detail,  i don't know which SRV is "none available", 

Can there be more error informations, like SRV name, SRV function

thank you~

**Comment by asim** [comment]
How are you getting these error details though? Surely if you are using the client to call a service then you know the service name?

**Comment by cute-angelia** [comment]
ok, sometimes


list service: 
    - A : GET_INFO
    - B : SET_SOMETHIN

a "go.micro.client"  call  A & B

but A or B not runing, so we got error info with: 

```
 {"id":"go.micro.client","code":500,"detail":"none available","status":"Internal Server Error"}
```

oh, no, with this error msg , i can't konw which one is lose ?


Add the error message with call's server name, It's easier to find a problem

like this

```
 {"id":"go.micro.client", "call": "go.micro.service.A", "method": "GET_INFO", "code":500,"detail":"none available","status":"Internal Server Error"}
```

Of course,  i know the service name when  i call srv,
but as we konw, no unified processing error mechanism in golang, this means that I have to deal with every call srv error
