### ISSUE TITLE
Why don't you use broker.PublishOption

### ISSUE THREAD

**Issue by scholar-ink** [micro/go-micro#291]
rpc_client.go 

`
func (r *rpcClient) Publish(ctx context.Context, msg Message, opts ...broker.PublishOption) error 
`
instead of

`
func (r *rpcClient) Publish(ctx context.Context, msg Message, opts ...PublishOption) error 
`

such as 
`rpcClient.Publish(ctx, msg,nsq.WithDeferredPublish(ttl[0]));`

**Comment by asim** [comment]
If that's the case why not use the broker directly? There's no point in us raising the level of abstraction and letting certain functions bleed through. The Client abstracts away the broker in a way that simplifies the experience further. If you need low level features you need to either use a message broker like nsq directly or use the micro broker directly. We could potentially support some other way of passing through options like we do for the selector but again it's bleeding features.
