### ISSUE TITLE
Deploying go-micro on kubernetes using consul for service discovery

### ISSUE THREAD

**Issue by mgyong** [micro/go-micro#296]
I am deploying a simple go-micro server on kubernetes using consul for service discovery. I have successfully deployed consul in the kubernetes cluster. However it seems that by default go-micro users localhost:8500 for service discovery. How do i change it to point to my consul cluster on kubernetes for service discovery? In this case the DNS for my consul cluster is  consul-0.consul.app.svc.cluster.local

I am getting the below error 
```
2018/08/15 21:10:17 Starting server mgyongappk8.merlion-app id 9c31fd72-a0cf-11e8-872c-0a580a0c0230
2018/08/15 21:10:17 Listening on [::]:44349
2018/08/15 21:10:17 Broker Listening on [::]:36601
2018/08/15 21:10:17 Registering node: mgyongappk8.merlion-app-9c31fd72-a0cf-11e8-872c-0a580a0c0230
2018/08/15 21:10:17 Put http://127.0.0.1:8500/v1/agent/service/register: dial tcp 127.0.0.1:8500: connect: connection refused

```
```
package main

import (
	"fmt"
	"log"
	"github.com/micro/go-micro/server"
)

func main(){

	md := map[string]string{
		"name":    "merlion-app service",
		"version": "v1",
		"type":    "server",
		"url":     "mgyongappk8.merlion-app"
	}

	server.DefaultServer = server.NewServer(server.Metadata(md))

	url, ok := md["url"]
	if !ok {
		errors.New("Error parsing meta")
	}

	server.Init(
		server.Name(url),
	)

	if err := server.Run(); err != nil {
		log.Fatal(err)
	}
}
```

**Comment by asim** [comment]
`--registry_address` flag or `MICRO_REGISTRY_ADDRESS` env var

**Comment by mgyong** [comment]
@asim Can you help me a little more by referencing the code I included as to where I can add the --registry_address flag ?

**Comment by asim** [comment]
When you run your service specify the flag or env var. 

In code you need to initialise it as part of the registry

```
server.Options().Registry.Init(
    registry.Addrs("address of consul"),
)
```

**Comment by mgyong** [comment]
@asim  I am getting compile error
missing argument to conversion to server.Options: server.Options()

**Comment by zhong-shizeng** [comment]
i deploy the go-micro service with docker. and service discovery use consul.
now have problem: other go-micro client how to connect the consul?

**Comment by WissemTeyeb** [comment]
zhong-shizeng  how did you deploy go-micro with docker please !
