### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by reechou** [micro/go-micro#298]
I use the lastest version, go build with error:
../../../github.com/micro/go-micro/registry/consul_registry.go:228:6: asr.Connect undefined (type *api.AgentServiceRegistration has no field or method Connect)
../../../github.com/micro/go-micro/registry/consul_registry.go:228:18: undefined: api.AgentServiceConnect
../../../github.com/micro/go-micro/registry/consul_registry.go:257:34: c.Client.Health().Connect undefined (type *api.Health has no field or method Connect)

**Comment by asim** [comment]
What latest version? This is a PR and branch. It's not been merged.
