### ISSUE TITLE
registry: Registry flag in registry package

### ISSUE THREAD

**Issue by crackcomm** [micro/go-micro#3]
What do You think about moving [registry flag](https://github.com/asim/go-micro/blob/master/server/server.go#L37) to registry package?
I think it's how it should be done because not only on server side it's important but also on the client side.
Registry package proved to be very useful, Im using it not only to find RPC services but also databases etc. even when not using `server` package. I think it would be more convenient to have this flag in registry package and then initialize `DefaultRegistry` using `registry.Init()`.

**Comment by asim** [comment]
Makes sense. I need to give some thought to the approach with flags and whether that's the right method for the library.

**Comment by asim** [comment]
I was speaking with @dancannon, he made me realise that flags in a library are probably bad practice. I'll look to remove flags entirely and provide an example of initialisation in the template project.

**Comment by crackcomm** [comment]
I understand that defining flags in library `init` function may be a bad practice, but in such libraries like service server (like this one) I think flags should be standarized. Please take a look at how kubernetes is defining [server flags](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/master/server/server.go#L122).

Edit:
Maybe define flags in `Init()`?

**Comment by asim** [comment]
The example given here is for the kubernetes master server which is not a library but a service itself. It would make sense to perhaps extract out flags into a separate package that could be used to run go-micro from the command line. The mistake was probably having flags in the server package in the first place. It should be imported for use elsewhere rather than the defacto starting point.

**Comment by asim** [comment]
Flags have been removed from the server package. I have created a new package called cmd for cli based usage which includes flag parsing. You can call import the cmd package and call cmd.Init() to parse flags and initialise the various packages based on that. This means if you are using the client or registry for your own uses you can use it for that too.

**Comment by crackcomm** [comment]
Now it really can be seen with a naked eye it's a better way.
