### ISSUE TITLE
Can`t make pubsub work — any tips to debug?

### ISSUE THREAD

**Issue by misterion** [micro/go-micro#302]
Hi! First of all thank you for go-micro. After go-kit it`s dramatically reduce amount of service code you should write before writing your business logic itself. Right now i`m trying to test pubsub part of go-micro and can`t make my subscriber part to receive messages. 

The config
- RabbitMQ as broker
- Consul as discovery 
- gRPC as transport 

Proto part 
```
syntax = "proto3";

message Event {
    // unix timestamp
    int64 timestamp = 1;

	// message
    string payload = 2;
}
```

The publisher part looks like this 
```
type Application struct {
	service micro.Service
	publisher micro.Publisher
}
...
app.service = micro.NewService(
		micro.Name("go.p1.glutton.core-app"),
		micro.Version("latest"),
	)
app.service.Init()
app.publisher = micro.NewPublisher("glutton.topic.event-stream", app.service.Client())
ev := &proto.Event{
		Timestamp: time.Now().Unix(),
		Payload:  "some string",
	}
log.Printf("publishing %+v\n", ev)
app.publisher.Publish(context.Background(), ev)
```
and subscriber part 
```
type EventApplication struct {
}
func (app *EventApplication) Process(ctx context.Context, event *proto.Event) error {
	md, _ := metadata.FromContext(ctx)
	log.Logf("[pubsub.1] Received event %+v with metadata %+v\n", event, md)
}

service := micro.NewService(
		micro.Name("go.p1.glutton.event-subscriber"),
		micro.Version("latest"),
)
service.Init()
micro.RegisterSubscriber("glutton.topic.event-stream", service.Server(), app, server.SubscriberQueue("queue.pubsub"))
...
```

I can`t find any active connections to RabbitMQ server after client and server applications start. And not any error of `Publish` call. Could you please give some tips what`s wrong and there i can get more information about this?

**Comment by asim** [comment]
So In the subscriber case, have you started the service? e.g `service.Run()`. The service will subscribe once you run it. The messages should then be received.

**Comment by asim** [comment]
Other issue could be that docker is not allowing connections to rabbitmq, this may be blocking

**Comment by asim** [comment]
Closing as solved in Slack.

**Comment by SoulflareRC** [comment]
So how was this solved? Ran into the same issue.
