### ISSUE TITLE
not thread safe?

### ISSUE THREAD

**Issue by baofengqqwwff** [micro/go-micro#303]
hello, if i run two same client at the same time, the server struct has some data, is it not thread safe? but if one client finish, the data will reset

**Comment by asim** [comment]
Do you have example code? I'm not sure what you mean

**Comment by baofengqqwwff** [comment]
<pre><code>
type BtEngine struct {
	initCapital    map[string]map[string]float64 //初始资金，用于计算收益
	historyCapital []map[string]map[string]float64
	capital        map[string]map[string]float64 //资金
	period         string                        //时间推送周期
	dbUrl          string                        //数据库地址
	dbName         string                        //数据库名
	dbUser         string                        //数据库用户名
	dbPasswd       string                        //数据库密码
	slippage       float64                       //滑点
	rate           float64                       //佣金比例
	nowKline       *metas.Kline                  //推送的kline
	beginDate      string
	endDate        string
	finishOrders   map[string][]*metas.Order
	tradingOrders  *list.List
	maxDataLength  int64      //最大数据准备天数
	orderID        int64      //开仓的ID
	processors     *list.List //事件处理器
	backtestData   map[string]map[string][]*metas.Kline
	replayIndexs   map[string]map[string]int     //回放的索引
	beginRate      map[string]map[string]float64 //回测开始时所有品种的价格
	endRate        map[string]map[string]float64 //回测结束时所有品种的价格
}

func (btEngine *BtEngine) SetBtParams(ctx context.Context, in *protoc.SetBtParamsRequest, out *protoc.None) (error) {
	btEngine.slippage = in.Slippage
	btEngine.rate = in.Rate
	btEngine.beginDate = in.BeginDate
	btEngine.endDate = in.EndDate
	btEngine.period = in.Period
	return nil
}
func (btEngine *BtEngine) Start(ctx context.Context, in *protoc.None, out *protoc.None) (error) {
	log.Println(btEngine.rate)
	return nil
}


func main() {
	os.Setenv("MICRO_REGISTRY", "mdns")

	runserver1()
	runserver2()

}
func runserver1() {
	service1 := micro.NewService()
	service1.Init()

	cl := protoc.NewEngineService("BtEngine", service1.Client())
	cl.SetBtParams(context.Background(), &protoc.SetBtParamsRequest{Rate: 1})
	cl.Start(context.Background(), &protoc.None{})
	time.Sleep(15*time.Second)
}
func runserver2() {
	service2 := micro.NewService()
	service2.Init()

	cl := protoc.NewEngineService("BtEngine", service2.Client())
	cl.Start(context.Background(), &protoc.None{})
	cl.SetBtParams(context.Background(), &protoc.SetBtParamsRequest{Rate: 2})
	cl.Start(context.Background(), &protoc.None{})
}

</code></pre>

i expect it export 1 0 2,but the result is 1 1 2

**Comment by asim** [comment]
Ok so no, the handler is not thread safe. Handlers can be executed concurrently. If you have data within your handler you need to protect this with a mutex. This data is outside the scope of our control. If we locked around the execution of the handler we'd incur a performance degradation which some users may not want to incur. 

Please use sync.RWMutex around your own data.
