### ISSUE TITLE
Got "kubernetes.io/serviceaccount: no such file or directory" for all micro cli comands

### ISSUE THREAD

**Issue by wangyanxing** [micro/go-micro#304]
I'm not able to run `micro` cli for all micro cli commands.

```
~ $ micro                                                                                                                                                
2018/09/10 16:02:21 stat /var/run/secrets/kubernetes.io/serviceaccount: no such file or directory
```
I installed minikube on my Mac, but not sure why it affects. I've tried reinstall go and micro, still see same issue.

**Comment by asim** [comment]
This is a kubernetes related issue. Please google the error for a solution.
