### ISSUE TITLE
CheckID "xxxxxx" does not have associated TTL

### ISSUE THREAD

**Issue by lovelly** [micro/go-micro#312]
An error occurred when I used consul_tcp_check, error: CheckID "xxxxxx" does not have associated TTL.
Should use tcp check and do not register ttl, loop the PassTTL check in Register to get this error
![image](https://user-images.githubusercontent.com/13118848/46599584-4ad71d00-cb1a-11e8-847b-6d938d2a3f4e.png)
![image](https://user-images.githubusercontent.com/13118848/46599603-5a566600-cb1a-11e8-8d28-bc984a9e76c8.png)

**Comment by asim** [comment]
Submit PR to fix?

**Comment by asim** [comment]
merged pr
