### ISSUE TITLE
example of compose two or more services with single binary

### ISSUE THREAD

**Issue by vtolstov** [micro/go-micro#315]
I like go-micro design, but if i want to provide single binary with all my services together. For example that implements some api with 10 different services. How can i do that with go-micro?
All this services need to communicate via message bus (nats or etcd).

**Comment by igorrius** [comment]
You can try the Cobra Commander https://github.com/spf13/cobra and organize all services to the one binary with different run arguments.

**Comment by vtolstov** [comment]
No, i don't want different run arguments. I want to single args and use it for all services.
(registry, discovery and so).
My question is about how to initialize and register more then one service in  micro.

**Comment by vtolstov** [comment]
And also how to bundle some external software? For example i need nats server, so it needs to be started before all other services are run.

**Comment by asim** [comment]
Go Micro was not designed to run multiple services as a single binary. It's for microservice development and is geared towards process independence. To build in one binary would require some hacking to ensure everything can be initialised multiple times.

When a new service is instantiated, if values are not provided for underlying systems it will use defaults. This is where the server has to be independently initialised to prevent conflict. 

I believe doing anything like this would be an exploratory project. I think we'd welcome an example of it. 

directory structure:

```
// single process example
examples/binary
    cmd/
      main.go   // single process init
    ping/          //service 1
    pong/        // service 2
```

I think start by creating a service initialiser which replaces the registry with an in-memory registry (you can find this in go-plugins) and also creates a new server so there's no overlap in startup.

Let me know if you need further help.

**Comment by hhstore** [comment]
I'm not sure what the real reason you need a single binary is, but there's a tradeoff option: use `Dockerfile + Docker-compose(or Kubernetes)`

### Specific steps:

1. use one `Dockerfile`  pack all your `go-micro services`,  inside you can use `nginx` or `caddy` or `go-micro proxy` or `grpc-gateway` to reverse proxy the API. then `the docker image`, can build one  binary package to your customer. (which is not recommended, but works. if this is acceptable for you.)

2. use `Docker-compose` or `Kubernetes ` to deploy your services. the `Configuration files` can define the service `startup sequence`.

3. use one `docker image`to publish your application, from the outside, it's `single binary`. `the docker image` can be optimized very small. 

4. meanwhile, inside your `docker image`, can run many background  service processes.

### usage like this:

- https://github.com/service-mesh/dockerfile/blob/master/python/3.6/Dockerfile
     - dockerfile

- https://github.com/service-mesh/devops/blob/master/deploy/compose/local/common-mq-kafka.yml
    - docker-compose file


### ref projects:

- https://github.com/moby/moby
    - docker
- https://github.com/docker/compose
    - docker-compose
- https://github.com/mholt/caddy
    - caddy

**Comment by hhstore** [comment]
i use`go-micro` for a while.

## my project structure:
### multi-apps:

```
apps/
  app1/
  	- api/
  	  - main.go
  	- srv/
  	  - handler/
  	    - api-controller.go
  	  - logic/
  	    - business-logic.go
  	  - model/
  	      - model-design.go
  	      - model-dao.go
  	  - proto/
  	  - util/
  	  - main.go
  	- config/
  	- common/
  	- main.go
  app2/
    - like app1
  app3/
    - like app1

```


### one-big-app:

```
app/
  - api/
  - srv/
  	- handler/
  	- logic/
  	- model/
  	- proto/
  	- util
  - config/
  - common/
  - main.go

```

**Comment by vtolstov** [comment]
thanks, i'm try to understand

**Comment by vtolstov** [comment]
@hhstore single binary firstly for space. If i have 20 services each need 20*20 = 400Mb of binaries. But all of them use the same grpc/log and other common packages. So if i combine all to one service (that ships via rpm/deb and so) I can have 40Mb binary that do all the same things, and if somebody want to scale - they can run docker version of each component and run my binary . So i can combine two worlds

**Comment by vtolstov** [comment]
@asim so what i need to place in service1 and service2 and what in main to initialize ?

**Comment by vtolstov** [comment]
@asim also i found #96 and if i dont want to listen for tcp, does it possible to not listen ip if i use nats or etcd as async message transport?

**Comment by vtolstov** [comment]
also i'm try to create 
map[string]micro.Service
and loop via main.go to init and register all services, but:
```go
       web.Service does not implement micro.Service (wrong type for Client method)
                have Client() *http.Client
                want Client() client.Client
```

**Comment by vtolstov** [comment]
my example code https://github.com/vtolstov/centralv2
so in main.go as i see started only one service (web) and grpc is not

**Comment by vtolstov** [comment]
does it possible to combine grpc and rest on the same port as i do for grpc-gateway?

**Comment by asim** [comment]
I think what you want is likely different from what we're all talking about it. It sounds like you want the ability to start any service from one binary. For this it's just a case of higher level initialisation.

Organise your services in a mono repo then provide the ability to generate to register and start via flag for each.

```
mybinary/
    cmd/
        service1
        service2
        service3
    main.go
```

Maybe something like this. Import all the service commands in your main.go and register them in a map or something of that nature. Then parse your flag and start the service you care about.

```
import (
    "github.com/mybinary/cmd/service1"
    "github.com/mybinary/cmd/service2"
    "github.com/mybinary/cmd/service3"
)

func main() {
    r := make(map[string]micro.Service)
    r[service1.String()] = service1.Service
    r[service2.String()] = service2.Service
    r[service3.String()] = service3.Service

    flag.Parse()

    service := *myserviceflag
    if srv, ok := r[service]; ok {
        srv.Run()
    }
}
```

**Comment by vtolstov** [comment]
@asim  so i don't need to call service.Init() for each of them?(if i want to have only my flags and configure each service via own flags?

**Comment by asim** [comment]
That's right. Avoid calling service.Init and you can self initialise the command line.

**Comment by vtolstov** [comment]
Ok, if i don't use Init from service what minimal stuff i need to call to run services (without init and only run it not listen and not register).
Also - does it possible to disable listening for tcp for some services?

**Comment by vtolstov** [comment]
i found go-api in micro does it supported and can be used for my case?

**Comment by vtolstov** [comment]
Now main problem - hit control+c does not shutdown completely service.
```
./central
2018/10/25 15:34:19 Listening on _INBOX.Jeb5d71hTD2Qtwa30qLqnD
2018/10/25 15:34:19 Registering node: go-server-4b4bebdf-d852-11e8-90fa-80000208fe80
2018/10/25 15:34:21 Deregistering node: go-server-4b4bebdf-d852-11e8-90fa-80000208fe80
```

**Comment by igorrius** [comment]
You can use something like this
```
gracefulShutdownChannel := make(chan os.Signal)
signal.Notify(gracefulShutdownChannel, syscall.SIGTERM, syscall.SIGINT)
```

**Comment by vtolstov** [comment]
Oh thanks! @igorrius that is worked fine. Does i need to wait when catching this signal or can os.Exit(0) immediately?

**Comment by igorrius** [comment]
> Oh thanks! @igorrius that is worked fine. Does i need to wait when catching this signal or can os.Exit(0) immediately?

Depends on your cases. You can terminate application immediately or call other logic. E.g. context close... whatever...

**Comment by vtolstov** [comment]
thanks as i see two services in the same binary works fine.

**Comment by xmlking** [comment]
here I have an example of multiple deployable services in single  monorepo and, 
`account` microservice has   **Two Handlers** registered in one microservice.

https://github.com/xmlking/micro-starter-kit
