### ISSUE TITLE
plugin or wrapper

### ISSUE THREAD

**Issue by vtolstov** [micro/go-micro#316]
I need to oauth2 and rbac policy enforcement. What i need to develop - plugin or wrapper?
PS firstly i'm plan to use it only on gateway that accessed by users, but in feature i need to auth other nodes before it connects.

**Comment by BigJoe01** [comment]
Hi Vtolstov.
Write wrapper.

**Comment by asim** [comment]
Examples of how to write plugins for the micro api can be found here https://github.com/micro/go-plugins/tree/master/micro

Examples of how to write plugins for Go Micro applications can be found here https://github.com/micro/go-plugins/tree/master/wrapper

The micro api should be the gateway used as the public entry point. Here you can define one time executing requirements such as auth at the edge, embedded headers, etc. Micro plugins allow you to add http handler middleware to filter requests at the edge. 

Go Micro apps have wrappers for their client and handlers for all inter-service request flow, including requests made by the micro api. This is where you might have extra per service feature requirements.

**Comment by vtolstov** [comment]
but why auth service is wrapper? For example i want to some services disable auth, for example account service can provide register method that does not need to go via auth wrapper.
I think that auth in this case if full featured service that can get requests from other services

**Comment by asim** [comment]
You have the choice to use the wrapper. If you have a better way feel free to do it. Auth is option.
