### ISSUE TITLE
Does go-micro support Request/Reply pattern with Message Queue?

### ISSUE THREAD

**Issue by kulukyo** [micro/go-micro#317]
Does go-micro support Request/Reply pattern with Message Queue?
I'm currently trying go-micro with NATS, and find only Pub/Sub pattern in examples.
Thanks a lot.

**Comment by vtolstov** [comment]
request/reply is the syn, in this case use nats as transport
for pub/sub async use nats as broker

**Comment by kulukyo** [comment]
> request/reply is the syn, in this case use nats as transport
> for pub/sub async use nats as broker

What I want to do is utilizing the "1 request -> expecting N replies" feature of NATS, is it possible to achieve this using go-micro only without coding against NATS?

**Comment by vtolstov** [comment]
i think it depends of what you request. you case looks like that you need nats broker and N servers subscribe to topic, when request arrive you publish to topic.
check this https://micro.mu/blog/2016/04/11/micro-on-nats.html

**Comment by asim** [comment]
We do not support 1 request > n replies. This is what the pubsub pattern is for. Publish a message and multiple subscribers will receive it. Request/response is 1 request and 1 response. In the case of message buses, we support them as a transport. They can be setup to subscribe to one queue and delivery is spread across them.
