### ISSUE TITLE
No private IP address found, and explicit IP not provided

### ISSUE THREAD

**Issue by seefutureLee** [micro/go-micro#320]
When i run greeter demo , i got this error

2018/11/13 11:25:45 Listening on [::]:54707
2018/11/13 11:25:45 Broker Listening on [::]:54708
No private IP address found, and explicit IP not provided

I'm using mac

**Comment by asim** [comment]
Whats the ip cidr of your network?

**Comment by seefutureLee** [comment]
> Whats the ip cidr of your network?

What is cidr?

I'm trying to run it in docker, maybe my environment  is not ok.

**Comment by asim** [comment]
OK thats a different story. Your docker container either has no networking or a private IP not in our list of supported ips.

**Comment by seefutureLee** [comment]
> OK thats a different story. Your docker container either has no networking or a private IP not in our list of supported ips.

Bad news, same error on my mac without docker.

**Comment by asim** [comment]
Here's the logic that defines how to get an IP https://github.com/micro/util/blob/master/go/lib/addr/addr.go

See the block of CIDR addresses. It must fit one of those.

**Comment by seefutureLee** [comment]
> Here's the logic that defines how to get an IP https://github.com/micro/util/blob/master/go/lib/addr/addr.go
> 
> See the block of CIDR addresses. It must fit one of those.

Ok, Thank you.

**Comment by unliar** [comment]
i meet the same issue when i try to start my app on ubuntu 16.04 vps.

i resove the problem by adding private address for my vps. [Reference link](https://pydio.com/en/docs/cells/v1/troubleshooting)

hope this will help who see this issue
```
vi /etc/network/interface
systemctl restart networking
```
example
```
auto lo
iface lo inet loopback

# Auto generated venet0 interface
auto venet0
iface venet0 inet manual
	up ifconfig venet0 up
	up ifconfig venet0 127.0.0.2
	up route add default dev venet0
	down route del default dev venet0
	down ifconfig venet0 down


iface venet0 inet6 manual
	up route -A inet6 add default dev venet0
	down route -A inet6 del default dev venet0

auto venet0:0
iface venet0:0 inet static
	address 45.77.4.111
	netmask 255.255.255.255

# here is i modified. 
auto venet0:1
allow-hotplug venet0:1
iface venet0:1 inet static
address 10.0.0.1
netmask 255.255.255.0

```
