### ISSUE TITLE
Add another handler to HTTP Transport's mux

### ISSUE THREAD

**Issue by alexbilbie** [micro/go-micro#326]
The HTTP Transport `Accept` function defines a HTTP mux like so:

```go
func (h *httpTransportListener) Accept(fn func(Socket)) error {
	// create handler mux
	mux := http.NewServeMux()
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		....
```

I would like to add a single additional handler to that Mux to introduce `/metrics` endpoint for use by Prometheus:

```diff
import (
	...
+	"github.com/prometheus/client_golang/prometheus/promhttp"
	...
)

...

func (h *httpTransportListener) Accept(fn func(Socket)) error {
	// create handler mux
	mux := http.NewServeMux()
+       mux.Handle("/metrics", promhttp.Handler())
	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
	....
```

What do you think is the cleanest way of adding this? I can think of three solutions:

1. I maintain a fork
2. A transport plugin which replicates the functionality of the HTTP transport plugin
3. An option on the HTTP transport plugin which allows for the injection of additional handlers

Both options 1 and 2 require long term maintenance to ensure upstream fixes are pulled so they are no my preferred choice.

How would you feel about me submitting a PR to implement 3? Or is there another option I've not explored yet?

For a bit of additional background, I'm using Prometheus' ability to query Consul for services - this results in Prometheus discovering the RPC service which doesn't contain this _well known_ `/metric` HTTP route. There are ways around it by running a second micro service handler however this isn't as clean as just enabling another route on the RPC handler's mux.

**Comment by asim** [comment]
So I would say one of the simplest ways for us to do this is an option to set a handler like this.

```go
import (
    "github.com/micro/go-micro"
    "github.com/micro/go-micro/transport/http"
    "github.com/prometheus/client_golang/prometheus/promhttp"
)

func main() {
    t := http.NewTransport(
        http.Handle("/metrics", promhttp.Handler()),
    )

    service := micro.NewService(
        micro.Name("greeter"),
        micro.Transport(t),
    )
}
```

What do you think? It would mean providing your own transport during initialisation but would give you control over what you set.

**Comment by asim** [comment]
https://github.com/micro/go-micro/pull/328

If it looks good I will merge

**Comment by asim** [comment]
Merged. Please let me know if anything else comes up. We need to evolve the tooling to meet requirements :)

Also if I can put your company on the [users](https://micro.mu/docs/users.html) page that would be great.

**Comment by alexbilbie** [comment]
@asim  https://github.com/micro/docs/pull/5 😄

**Comment by asim** [comment]
Thanks!
