### ISSUE TITLE
How to enable service request log?

### ISSUE THREAD

**Issue by seaguest** [micro/go-micro#330]
Hello,

I have a question regarding the service request log.
In GIN framework, I can see these logs as following:
`
[GIN] 2018/11/21 - 14:44:48 | 200 |     225.511µs |    47.74.179.32 | POST     /user/login

[GIN] 2018/11/21 - 14:44:48 | 200 |     225.511µs |    47.74.179.32 | GET     /user/info
`

I wonder if there is any similar thing in go-micro, to see the service request, request time/status, response time, request ip...

best regards

**Comment by leninhasda** [comment]
In individual service you may have to write wrapper for it. But if you are using  [micro api gateway](https://github.com/micro/micro/tree/master/api), it already does that for you.

**Comment by asim** [comment]
There's currently no support for logging. You must log requests yourself.
