### ISSUE TITLE
grpcurl -plaintext  localhost:36641 list

### ISSUE THREAD

**Issue by seaguest** [micro/go-micro#337]
Hello,

I developed a service with go-micro, how ever I got some problems when I tried with [grpcurl](https://github.com/fullstorydev/grpcurl).

```
grpcurl -plaintext  localhost:36641 list

Failed to list services: rpc error: code = Internal desc = transport: received the unexpected content-type "text/plain"

```

Is there something need to be configured to make grpcurl work with service developed by go-micro?

**Comment by asim** [comment]
Go micro does not support grpc by default at the moment. You have to either include the plugins or use go-grpc

**Comment by seaguest** [comment]
Hello,

I add grpc client in code as the example:
```
import (
	"github.com/micro/go-micro"
	"github.com/micro/go-plugins/client/grpc"
)

func main() {
	service := micro.NewService(
		micro.Name("greeter"),
		micro.Client(grpc.NewClient()),
	)
}
```

then grpcurl returned the same error.

Is it possible to make grpc work with go-micro?

I am planning to replace REST API by GRPC for mobile app development, android part call methods defin ed in proto file with grpc, is this possible if I develop in go-micro?

**Comment by seaguest** [comment]
ok, I changed it to server code, and it works.

```
grpcurl -protoset *.protoset -plaintext localhost:44917 list

```
thanks
