### ISSUE TITLE
how can i get service worker id ?

### ISSUE THREAD

**Issue by mlboy** [micro/go-micro#339]
i want use snowflake  algorithm ，but it need set worker id,how can i get it?

snowflake:
+------------------------+--------------------------+-----------------+
| 43bits timestamp in ms | 8bits worker(machine) ID | 12bits sequence |
+------------------------+--------------------------+-----------------+

**Comment by asim** [comment]
I'm not sure how this is relevant to micro. What would constitute a service worker Id? You can get the Id of the server itself from options. 

service.Server().Options().Id

**Comment by mlboy** [comment]
Thank you. I just want this ID. It would be better if it was a number, but it doesn't matter. Because the number of services started is not certain, each service needs a unique ID, so it's impossible to set it manually at each start.
