### ISSUE TITLE
rpc custom context value can't receive

### ISSUE THREAD

**Issue by zjn1234** [micro/go-micro#342]
in client i use context.WithValue(ctx,"1", "1")

but in server i can't get ctx.Value("1")  it only send metadata?

**Comment by asim** [comment]
How should we pass custom values over RPC? I don't think anything does this. This is the point of a request to add data. Context provides context for the request. We will transport metadata and nothing else. If you can demonstrate where context otherwise propagates more values please let us know.

**Comment by zjn1234** [comment]
i'm using zipkin, how to pass zipkin span key if micro doesn't support custom values over rpc
