### ISSUE TITLE
cannot hit api of go-micro service in google compute engine

### ISSUE THREAD

**Issue by rampredd** [micro/go-micro#343]
Hi,

I am creating micro server as follows

	service := micro.NewService(
		micro.Name("go.micro.api.auth"),
	)

    service.Init()
	auth.RegisterAuthHandler(service.Server(), &Auth{})
	if err = service.Run(); err != nil {
		common.PrintError("auth service register error", err)
	}

   buit service with exe name as: api    

    then run above server:
   MICRO_REGISTRY=mdns micro api --handler=rpc &
   MICRO_REGISTRY=mdns ./api

    enabled ingress http in my google compute engine instance.

     now problem is:
     cannot curl api service using external ip from my local machine.
     
Please tell me what could be the problem
note: i can start apache server in compute engine and see its web page by browsing its external ip

**Comment by rampredd** [comment]
Thank you asim.

Let me try this

**Comment by rampredd** [comment]
I tried to run consul but still cannot get curl from external ip.

I run:

consul agent -dev
micro api --handler=rpc &
./api

I cannot even browse [consulPublicIp:8500] in another machine.

Please let me know what am doing wrong
OR
please gimme some link describing this in detail

**Comment by asim** [comment]
I cannot help with you setup for google compute. You need to look at how to setup machine, open ports, load balance on a public IP, etc. This is outside of the scope of the help you'll get from micro.

**Comment by rampredd** [comment]
I have done setup in google cloud with compute engine.

Now cloud load balancer does health check for VM instance.
This health check response must be http and content-type "text/html".

load balancer sends this health check http request to my go-micro app bind to localhost:80 (has to bind to 80) and it expects http response with content-type "text/html" + some simple html content:
`<!doctype html><html><body><h1>some string</h1></body></html>`

go-micro API returns json content so health check fails.
func (auth *Auth) HealthCheck(ctx context.Context, req *auth.Empty, rsp *auth.Empty) error {
	log.Print("Received Auth.HealthCheck request")

	return nil
}

How to send content-type as "text/html" from this function.

OR

I see best solution as follows but don't understand how to do.
As the http request hits (localhost:80) micro, there micro itself can return http response without forwarding to any service registered.

Please help
