### ISSUE TITLE
openid connect & Oauth2 support 

### ISSUE THREAD

**Issue by mmeliani** [micro/go-micro#344]
I'm wondering if i could use oidc(openid connect) with micro-go ? i mean i want to secure my app using an identity provider like keycloak, 
we could use the oidc go library with oauth2 but what about micro-go? 
"github.com/coreos/go-oidc"
 "golang.org/x/oauth2"
Regards

**Comment by asim** [comment]
Yes you can, you just have to implement the wrapper that call out to these libraries to do the authentication. Alternatively you can embed the http handlers into the micro api via a plugin.

**Comment by RichardLindhout** [comment]
Maybe take a look at Hydra. They have also API gateways which you van put in front of your api's

**Comment by asim** [comment]
As others have mentioned there are ways to integrate.
