### ISSUE TITLE
Bug in gossip.pb.go

### ISSUE THREAD

**Issue by sidmal** [micro/go-micro#346]
Hello!

I try to update go-micro library to latest version, I use go modules. In updating process I have next error message:

> $ go get github.com/micro/go-micro
> ....
> github.com/micro/go-micro/registry/gossip/proto
> ...github.com/micro/go-micro@v0.15.0/registry/gossip/proto/gossip.pb.go:21:11: undefined: proto.ProtoPackageIsVersion3

Previous version v0.14.1 load and work is OK.
My go version (**go version**):

> go version go1.11.2 windows/amd64

Information about my system (**go env**):

> set GOARCH=amd64
> set GOBIN=
> set GOCACHE=C:\Users\dmitr\AppData\Local\go-build
> set GOEXE=.exe
> set GOFLAGS=
> set GOHOSTARCH=amd64
> set GOHOSTOS=windows
> set GOOS=windows
> set GOPATH=C:\Users\dmitr\Documents\Projects\Go
> set GOPROXY=direct
> set GORACE=
> set GOROOT=C:\Go
> set GOTMPDIR=
> set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
> set GCCGO=gccgo
> set CC=gcc
> set CXX=g++
> set CGO_ENABLED=1
> set GOMOD=C:\Users\dmitr\Documents\Projects\Docker\www\GO\payone-project-notifier\go.mod
> set CGO_CFLAGS=-g -O2
> set CGO_CPPFLAGS=
> set CGO_CXXFLAGS=-g -O2
> set CGO_FFLAGS=-g -O2
> set CGO_LDFLAGS=-g -O2
> set PKG_CONFIG=pkg-config
> set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\dmitr\AppData\Local\Temp\go-build391083514=/tmp/go-build -gno-record-gcc-switches

**Comment by asim** [comment]
This is not a bug. It's related to golang/protobuf which needs to be updated.

**Comment by sidmal** [comment]
Omg, I very inattentive :) Thanks

**Comment by alexbilbie** [comment]
For anyone using `dep` who is encountering the same issue the solution (until `golang/protobuf` release a new version higher than `1.2.0`) is to add an override to your `Gopkg.toml` like so:

```toml
[[override]]
  name = "github.com/golang/protobuf"
  branch = "master"
```
