### ISSUE TITLE
service.Init() can't be tested, how can I test code includes service.Init()?

### ISSUE THREAD

**Issue by victorisildur** [micro/go-micro#348]
My code runs good so far until I need to test codes includes `service.Init()`, which is for client generation:

```go
service = micro.NewService(
	micro.Registry(registry),
)
service.Init()
client = someProto.someServiceName(someOtherMicroServiceName, service.Client())
```

It will stop at `service.Init()` and pop up hints about how to use command line correctly.

I see it's doable to use `service.Run()` instead of `service.Init()`, but here it's only client needed.

Any ideas? thanks

**Comment by asim** [comment]
Service.Init is used to parse the command line. A service can be used both as a client and server. Meaning as a client Run will never be called. In the case of testing you should not call init. Ideally as part of an initialisation step you accept a service but only call Init in a main method.

**Comment by victorisildur** [comment]
Thank you for the reply, But I don't quite understand:

1. `In the case of testing you should not call init`
2. `Meaning as a client Run will never be called`

Then what's recommanded method to be called in case of creating a client for test?

**Comment by victorisildur** [comment]
Thanks, I tried not to call the Init nor Run method when testing. It crashes

```go
service = micro.NewService(
	micro.Registry(registry),
)
// service.Init()
client = someProto.someServiceName(someOtherMicroServiceName, service.Client())
client.someRpcName(ctx, rpcRequest) // crash here
```

It seems like service.Init() or service.Run() is imperative before we can use a client, is it?

> I debugged the crash and it crashed at 'selector',  from selector comments it seems like the service registry is not initialized properly perhaps

**Comment by asim** [comment]
Can you perhaps provide a stack trace so we can see where it crashes? Otherwise it's difficult to help.

**Comment by asim** [comment]
No response. Closing. Please provide more detailed info about the crash if you want help. Otherwise we found that we do not get crashes here. We have no idea what your rpcRequest is or what someRpcName is.
