### ISSUE TITLE
RegisterSubscriber 

### ISSUE THREAD

**Issue by metooweb** [micro/go-micro#350]
![uypit nes5nppgnz p jhw](https://user-images.githubusercontent.com/18512517/50138654-3a8dac00-02da-11e9-9315-c2b7731e1deb.png)

**Comment by asim** [comment]
What subscriber headers? Please stop talking in screenshots.

**Comment by metooweb** [comment]
like this , set headers

<pre>
broker.Subscribe("/topic/hello", func(p broker.Publication) error {
		
 return nil
}, stomp.SubscribeHeaders(map[string]string{

"activemq.subscriptionName": "name",

}), broker.DisableAutoAck())
</pre>

**Comment by asim** [comment]
Broker options are not supported using the RegisterSubscriber function. Broker is a low level component which we abstract away in the server. If you need to use more detailed subscribe options then you should use the broker directly. It's unlikely we promote the ability to do these things at the high level.
