### ISSUE TITLE
go 1.11.2 compilation failed

### ISSUE THREAD

**Issue by tttlkkkl** [micro/go-micro#351]
/www/go/pkg/mod/github.com/micro/go-micro@v0.15.0/registry/gossip/proto/gossip.pb.go:21:11: undefined: proto.ProtoPackageIsVersion3

**Comment by asim** [comment]
This is related to the fact that golang/protobuf is pinned at version 1.2 but their master branch includes  proto. ProtoPackageIsVersion3. You will need to force the use of master.
