### ISSUE TITLE
selector: cache selector issues with gossip registry

### ISSUE THREAD

**Issue by vtolstov** [micro/go-micro#356]
when use cache selector with gossip registry error appeared: watcher stopped

when use default selector error not appeared

**Comment by asim** [comment]
Do you have more useful information than this?

**Comment by vtolstov** [comment]
simply try to use cache selector and gossip registry and do come calls to services

**Comment by vtolstov** [comment]
no problem, but i don't think that this is needs to be fixed, because gossip already cache members as i remember. so cache for cache not useful, does it possible to simple reject this combination?

**Comment by asim** [comment]
I'm doing some local service calls with zero issues with this combination. You can disable the cache if need be but we optimize for a path in which the registry fails and we want to do zero lookups.
