### ISSUE TITLE
add go.mod and go.sum to support go modules function

### ISSUE THREAD

**Issue by caofangkun** [micro/go-micro#358]
Go Modules:  https://github.com/golang/go/wiki/Modules

![image](https://user-images.githubusercontent.com/1931407/50500835-d6fc3f00-0a8e-11e9-8fbe-92ef7441fc5f.png)

**Comment by caofangkun** [comment]
```
→  go build     
# github.com/micro/go-micro/registry/gossip/proto
registry/gossip/proto/gossip.pb.go:21:11: undefined: proto.ProtoPackageIsVersion3
```
`go get github.com/golang/protobuf@master`

**Comment by asim** [comment]
We won't support go modules until it's a defacto standard. This is likely after a 1.12 release.
