### ISSUE TITLE
opts in rpcClient.Publish was not used

### ISSUE THREAD

**Issue by t5w0rd** [micro/go-micro#360]
rpc_client.go
func (r *rpcClient) Publish(ctx context.Context, msg Message, opts ...PublishOption) 
opts was not used.
publisher.go
func (p *publisher) Publish(ctx context.Context, msg interface{}, opts ...client.PublishOption)
opts was not used too.
i want to use Publisher.Publish instead of broker.Publish, but how to use client.PublishOption instead of broker.PublishOption?

**Comment by asim** [comment]
There are currently no publish options to speak of so not quite sure what the expectation is.
