### ISSUE TITLE
what's The difference between micro.NewService and grpc.NewService ?

### ISSUE THREAD

**Issue by PengjuDuan** [micro/go-micro#361]

**Comment by asim** [comment]
Grpc uses the grpc protocol

**Comment by PengjuDuan** [comment]
i mean，why service provided by grpc.NewService() need endpoint for using it and micro.NewService does not?  grpc protocol based on http2, micro.NewService() based on http2 too ? so what's the difference

**Comment by PengjuDuan** [comment]
sorry i'm confused

**Comment by asim** [comment]
Please ask these questions in the slack, don't comment in closed issues. 

Micro does not provide grpc support by default. The go-grpc library uses google's framework to provide.
