### ISSUE TITLE
{"id":"go.micro.client","code":500,"detail":"panic recovered: interface conversion: []uint32 is not proto.Message: missing method ProtoMessage","status":"Internal Server Error"}

### ISSUE THREAD

**Issue by PengjuDuan** [micro/go-micro#366]
i write a gateway using websocket, receive a proto request like

`
syntax = "proto3";

service Gateway {
    rpc Request(ReqBody) returns(ReqResponse){}
}

message ReqBody {
    string service = 1;
    string func = 2;
   []uint32 data =3;
}

message ReqResponse {
    int32 code = 1;
    string message = 2;
    []uint32 data =3;
}
`

data is an uint array canbe any other proto message, generated by pbjs(javascript proto helpler)

then i call other service

`
request := &pb.ReqBody{}
request.XXX_Unmarshal(message)

req := cli.NewRequest("go.micro.srv.user", "User.AuthLocal", request.Data)
err = cli.Call(c.session.getContext(), req, res)
`

i've tried all contentType and turn data in proto to []bytes, doesn't work.

**Comment by asim** [comment]
The method you're using here is incorrect. You can't just pass request.Data in like this. the user service would then have to be decoding the exact same data object. You need to pass a struct based proto from what I see. Basically anything defined as message in the proto file. You can't pass individual fields as a request.

**Comment by PengjuDuan** [comment]
i see /codec/bytes/bytes.go in master branch, this can used for my issue ?

**Comment by asim** [comment]
I'm not really sure what you're attempting to do but I'd advise you to use the `micro api` in the micro toolkit rather than creating your own gateway like this. We're alternatively in the midst of building a proxy that will handle your requirements.
