### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by Desmond56** [micro/go-micro#370]
I'm using etcdv3 as the registry locally, i create a project like greeter. when i request to web.service , it returned an error to me
`{
    "id": "go.micro.client",
    "code": 500,
    "detail": "connection error: dial tcp 192.168.1.126:41387: connect: connection refused",
    "status": "Internal Server Error"
}`
but The correct port  is 41647, I don't know why it chooses a wrong port

**Comment by asim** [comment]
If you have services which deregisters incorrectly then they'll be left as stale nodes. If you don't specify an address to bind to, the service will bind to a random port.
