### ISSUE TITLE
example of streaming

### ISSUE THREAD

**Issue by glycerine** [micro/go-micro#373]
> Sync Streaming - RPC based request/response with support for bidirectional streaming. We provide an abstraction for synchronous communication. A request made to a service will be automatically resolved, load balanced, dialled and streamed. 

Is there an example of streaming a large file from server to client, with optional server initiated push rather than as an RPC response? (For example, suppose I'm operating a Netflix clone).

**Comment by asim** [comment]
github.com/asim/go-file is an example of file streaming. There's nothing in the micro repo at the moment.

**Comment by asim** [comment]
You would need to test this but yes I'd assume the underlying implementation of the http and TCP protocol would handle this.
