### ISSUE TITLE
Disable output log

### ISSUE THREAD

**Issue by viettuan1807** [micro/go-micro#377]
I want to disable the output logs looks like this:
> 2019/01/09 21:58:19 Listening on [::]:51907
> 2019/01/09 21:58:19 Broker Listening on [::]:51908
> 2019/01/09 21:58:19 Registering node: greeter-294df33c-7242-4745-9cd3-6bf5c95063c9
> 2019/01/09 21:58:20 watcher stopped
> 2019/01/09 21:58:20 watcher stopped
> 2019/01/09 21:58:20 watcher stopped
> 2019/01/09 21:58:20 watcher stopped
> 2019/01/09 21:58:20 watcher stopped
> 2019/01/09 21:58:20 watcher stopped
> 2019/01/09 21:58:20 watcher stopped
> 2019/01/09 21:58:20 watcher stopped
> 2019/01/09 21:58:20 watcher stopped
> 2019/01/09 21:58:20 watcher stopped

How can I do this?

**Comment by asim** [comment]
The logger used for everything is set in `github.com/micro/go-log`. Although it would be better for you to try to understand why this is occurring. What registry and selector are you using?
