### ISSUE TITLE
Build error: undefined: proto.ProtoPackageIsVersion3

### ISSUE THREAD

**Issue by lockp111** [micro/go-micro#378]
You should look this issue: https://github.com/golang/protobuf/issues/777

**Comment by asim** [comment]
They have not made a release since October. We're waiting on that. It's unlikely we change anything. You should set your dependencies to use master of the golang/protobuf repo. This is unrelated to go-micro as we don't code generate anything in the go-micro library itself.

**Comment by asim** [comment]
Only just noticed we do have proto generated code in the library! It's been downgraded. We don't want to be affected by this issue in the core code.

**Comment by evangwt** [comment]
> Only just noticed we do have proto generated code in the library! It's been downgraded. We don't want to be affected by this issue in the core code.

I have the same problem while using protoc-gen-micro v0.7.2.
No error is reported when using v0.7.1 or earlier.Because the proto.ProtoPackageIsVersion of these  generated *.mirco.go files is 2 not 3.
