### ISSUE TITLE
Configuration through default variables

### ISSUE THREAD

**Issue by jelmersnoeck** [micro/go-micro#38]
A lot of things are loaded on runtime through variables, like [`var DefaultClient Client = newRPCClient()`](https://github.com/micro/go-micro/blob/master/client/client.go#L75).

This makes it easy to swap this element out, but also causes an issue with configuration. [This gist](https://gist.github.com/jelmersnoeck/fbc5da40c78813fb2c04) demonstrates the issue.

More concrete, the way I stumbled upon this is by configuring a different port to the consul agent. To do that, I overwrote `registry.DefaultRegistry` like this: `registry.DefaultRegistry = registry.NewRegistry([]string{"127.0.0.1:9123"})
`

The service would still look for port 8500 because within the server package, we load a [default server](https://github.com/micro/go-micro/blob/be43d827c768b33e9786ab4846746df8007ba0af/server/server.go#L90). At this point, the new configuration - the one we define within our application logic - isn't loaded yet and will thus fall back to the default port.

**Comment by asim** [comment]
Not at a computer right now to have a good look yet but defaults are
essentially there as a fallback and basically for batteries included model
where you just want to get started with minimum configuration. If you look
at the examples and the cmd package. We reinitialise a lot of these things
if flags are set. In essence a default server which depends on the default
registry will not change unless cmd.Init is called you or you forcefully
override it. If you want to initialize defaults manually inside your
application you should replace the client, server, broker, selector, etc
too.

We'll have a longer discussion on slack in a bit.

**Comment by asim** [comment]
Status report?

**Comment by jelmersnoeck** [comment]
We've moved to the suggested way of initialising our own defaults, which works fine!

**Comment by asim** [comment]
Cool. Alright closing.
