### ISSUE TITLE
rpc not working when git pull the new version

### ISSUE THREAD

**Issue by laoqiu** [micro/go-micro#380]
Unexpected error serving request, closing socket: rpc: service/method request ill-formed:

**Comment by asim** [comment]
Have you updated everything? Including micro?

**Comment by laoqiu** [comment]
go-micro/server/rpc_router.go:384:		
err = errors.New("rpc: service/method request ill-formed: " + req.msg.Method)

there req.msg.Method is nothing

**Comment by laoqiu** [comment]
./main.go:22:48: req.Method undefined (type server.Request has no field or method Method)

when go-micro pull master. how many package changed?

**Comment by laoqiu** [comment]
I just pulled it this morning.

**Comment by laoqiu** [comment]
I pulled all package above micro. 
still got:
./main.go:22:48: req.Method undefined (type server.Request has no field or method Method)

**Comment by asim** [comment]
go get -u your program to update all dependencies.

**Comment by laoqiu** [comment]
2019/01/11 16:51:04 Unexpected error serving request, closing socket: rpc: service/method request ill-formed:

Still no change.


req.Method undefined is micro.WrapHandler changed, ignore now.

**Comment by asim** [comment]
What's the flow of your request? What is calling what? The default protocol has changed internally. Anything old will not be able to speak to the new service. If you need backwards compatibility use a release tag for now.

**Comment by laoqiu** [comment]
I just create new service, and use micro web (localhost:8082) to send rpc request. 

```
{"service":"cn.meyoung.srv.stockplan","method":"Plan.LockLogs","request":{"plan_code":"test"}}
```

same response in postman. use api localhost:800/rpc
```
{
	"service": "cn.meyoung.srv.stockplan",
	"method": "Plan.UpdateOrder",
	"request": {
		...
	}
}
```

**Comment by laoqiu** [comment]
sorry,  could you give me a solution because the package is updated.
where is doc about the new protocol how to use ?

**Comment by asim** [comment]
You closed the issue. I'm assuming you updated everything.

**Comment by laoqiu** [comment]
No, everything is updated.
I forget the micro path, so build the wrong output path.

**Comment by laoqiu** [comment]
I have many question about the broker use other server, i will send you message on slack.
