### ISSUE TITLE
wsasend: An established connection was aborted by the software in your host machine.

### ISSUE THREAD

**Issue by xkisu** [micro/go-micro#383]
When trying to use either v0.17.0 or the latest master branch of micro/go-micro (and the master branch of micro/micro) I get this error when trying to query a service from the web UI, api gateway, or from a client

```
{
  "id": "go.micro.client.transport",
  "code": 500,
  "detail": "readfrom tcp 10.0.75.1:52710->10.0.75.1:52704: write tcp 10.0.75.1:52710->10.0.75.1:52704: wsasend: An established connection was aborted by the software in your host machine.",
  "status": "Internal Server Error"
}
```
This occurs both with my own microservices and with the example greeter microservice. 

The logs for the services show that the request handler functions where never called, and while the logs for the web ui show a 500 error they don't give any details

```
::1 - - [13/Jan/2019:20:09:04 -0800] "POST /rpc HTTP/1.1" 500 275 "http://localhost:8082/call" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36"
```

At first I thought this was a Window firewall problem, but realized it was not when it persisted after disabling the firewall.

Rolling back go-micro to v0.16.0 fixes the issue and everything works as expected, so it appears to be an issue caused by a change that happened between v0.16.0 and v0.17.0.

**Comment by asim** [comment]
If I run the greeter example and try the api or web ui then everything works. There are known breaks between 0.17.0 and master but I'm unaware of what would cause the problem between 0.16.0 and 0.17.0. You can either stay at 0.16.0 or incur the breaking changes to get to master. Otherwise you'll need to help debug the issue in 0.17.0.

**Comment by asim** [comment]
```go get -u github.com/micro/micro```

**Comment by xkisu** [comment]
I tested this with various version of go-micro and micro and found that it was consistently breaking whenever I used 0.17.0+ or master for `micro/go-micro` regardless of the version of `micro/micro`. I'm swamped with work at the moment but when I have some free time I'll come back and see if I can find the cause of the problem since I'd prefer to use the latest version then locking it at 0.16.0.
