### ISSUE TITLE
stream will block

### ISSUE THREAD

**Issue by liov** [micro/go-micro#384]
`	
rsp1, err := greeter.SayHelloAgain(context.TODO())
	if err != nil {
		log.Fatal(err)
	}

	go func() {
		for {
			if err := rsp1.Send(&protobuf.HelloRequest{Name: "John"}); err != nil {
				log.Fatal(err)
			}
			time.Sleep(time.Second)
		}
	}()

	for {
		reply, err := rsp1.Recv()  //there will block
		if err != nil {
			if err == io.EOF {
				break
			}
			log.Fatal(err)
		}
		fmt.Println(reply.GetMessage())
	}

	fmt.Println(rsp.GetMessage())
}`
grpc will run normally but micro will block

**Comment by asim** [comment]
Do you have a complete example that can be run? I can't test this without major overhead of reimplementing it. There are streaming examples in the examples repo which works. Please ensure all your deps are upto date.

**Comment by asim** [comment]
https://github.com/micro/examples/tree/master/stream

**Comment by PengjuDuan** [comment]
there is no bidirectional streaming in the examples repo. i block too, using micro.NewService

**Comment by asim** [comment]
I quite literally just linked to it. Please update all your dependencies.
