### ISSUE TITLE
improve get function from registrySelector.cache 

### ISSUE THREAD

**Issue by tuanhuyhcmus** [micro/go-micro#388]
**//micro/go-micro/selector/default.go**

func (c *registrySelector) **get**(service string) ([]*registry.Service, error){
....
services, ok := c.cache[service]
	// get cache ttl
ttl, kk := c.ttls[service]
if ok && kk && time.Since(ttl) < c.ttl {
		// make a copy
		cp := c.cp(services)
		// unlock the read
		c.RUnlock()
		// return servics
		return cp, nil
	}
**=> When services got from c.cache was [] , so it still passed  if condition ,so i think 
 if  statement shoud be : if ok && kk && len(services) >0 && time.Since(ttl) < c.ttl** 

....
}

**Comment by asim** [comment]
Updated to be more efficient. We don't need to check if vals exist in the maps because the zero values can be tested. Thanks for the request.
