### ISSUE TITLE
error selecting agent node: none available

### ISSUE THREAD

**Issue by xiangZgnaix** [micro/go-micro#401]
I got this error.Below is my micro command to setup api.
micro --registry=consul --register_interval=1 --register_ttl=2 api \
	  --address=localhost:8080 \
	  --handler=api \
	  --cors-allowed-headers=Content-Type,Authorization \
           --cors-allowed-origins=http://localhost:8081,http://localhost:8088 \
           --cors-allowed-methods=PUT,POST,GET\
And I also use the cors plugin to enable cors. Below is the plugin.go when build micro
![2019-01-25 2 12 24](https://user-images.githubusercontent.com/19362132/51733639-e639d100-20bc-11e9-945b-4e1ec888053b.png)
After set up the api server and call , i got below error!
I checked my consul server, it ran well!
I've stumped for a long time, really hope u can help me!! @asim @shuLhan @hlian @Taik

**Comment by xiangZgnaix** [comment]
Here is the response when i call api server.
![2019-01-25 4 22 25](https://user-images.githubusercontent.com/19362132/51733778-70823500-20bd-11e9-9588-500030a21059.png)

**Comment by xiangZgnaix** [comment]
Even I run the go-micro/examples/api/api , still get the same response
![2019-01-25 4 22 25](https://user-images.githubusercontent.com/19362132/51734197-c2778a80-20be-11e9-803a-5fb1953e93fe.png)

**Comment by asim** [comment]
It's a bug in master of go-api. The bug has been fixed but this code is not actually tagged so I won't be releasing a new version yet. If you update your dependencies everything will work.

**Comment by xiangZgnaix** [comment]
thanks a lot! I've tried your suggestion, now everything works alright!
