### ISSUE TITLE
data race

### ISSUE THREAD

**Issue by vtolstov** [micro/go-micro#403]
can't easy reproduce, have tight loop with many requests to service and in console where service running hit ctrl+c
```
==================
WARNING: DATA RACE
Write at 0x00c00019f31c by goroutine 208:
  sync.(*WaitGroup).Wait()
      /var/home/vtolstov/sdk/go1.12beta2/src/internal/race/race.go:41 +0xef
  github.com/micro/go-micro/server.(*rpcServer).Start.func2()
      /home/vtolstov/devel/projects/centralv2/vendor/github.com/micro/go-micro/server/rpc_server.go:531 +0x5ad

Previous read at 0x00c00019f31c by goroutine 162:
  [failed to restore the stack]

Goroutine 208 (running) created at:
  github.com/micro/go-micro/server.(*rpcServer).Start()
      /home/vtolstov/devel/projects/centralv2/vendor/github.com/micro/go-micro/server/rpc_server.go:496 +0x848
  github.com/micro/go-micro.(*service).Start()
      /home/vtolstov/devel/projects/centralv2/vendor/github.com/micro/go-micro/service.go:80 +0x104
  github.com/micro/go-micro.(*service).Run()
      /home/vtolstov/devel/projects/centralv2/vendor/github.com/micro/go-micro/service.go:116 +0x50
  unistack.org/centralv2/server.runService()
      /home/vtolstov/devel/projects/centralv2/server/server.go:106 +0x59

Goroutine 162 (running) created at:
  net/http.(*Server).Serve()
      /var/home/vtolstov/sdk/go1.12beta2/src/net/http/server.go:2884 +0x4c4
  github.com/micro/go-micro/transport.(*httpTransportListener).Accept()
      /home/vtolstov/devel/projects/centralv2/vendor/github.com/micro/go-micro/transport/http_transport.go:434 +0x417
  github.com/micro/go-micro/server.(*rpcServer).Start.func1()
      /home/vtolstov/devel/projects/centralv2/vendor/github.com/micro/go-micro/server/rpc_server.go:473 +0x112
==================
```

**Comment by asim** [comment]
You're seeing this issue because you're running multiple services in a single process so you're uncovering some sort of edge case bleed of resource use between multiple services. I don't support multi-service/single-process setups. The stack also doesn't provide enough information to know wher to fix the issue.

**Comment by vtolstov** [comment]
why not protect access to wg with sync.RWMutex like other cases?

**Comment by mytototo** [comment]
I have the same issue. Did you find a solution @vtolstov ?

**Comment by vtolstov** [comment]
@mytototo single service per binary or multiple?

**Comment by mytototo** [comment]
Multiple services. It wasn't really a data race though. It was a panic on closed channels.
I fixed it. I had both the the registry and the broker interfaces as options when creating a new server, as well as creating the attached service.

This : 
```go
	newServer := microgrpc.NewServer(
		server.Broker(myBroker),
		server.Registry(myRegistry),
		server.Address(":8080"),
	)

	s := micro.NewService(
		micro.Registry(myRegistry),
		micro.Broker(myBroker),
		micro.Transport(
			tgrpc.NewTransport(
				transport.Secure(true),
			),
		),
		micro.Server(newServer),
	)
```

Is now fixed using : 
```go
	newServer := microgrpc.NewServer(
		server.Broker(myBroker),
		server.Registry(myRegistry),
		server.Address(":8080"),
	)

	s := micro.NewService(
		micro.Transport(
			tgrpc.NewTransport(
				transport.Secure(true),
			),
		),
		micro.Server(newServer),
	)
```

I'm still confused on why we can pass the broker and registry both on the server and the service. I find it misleading.

**Comment by asim** [comment]
The ability to pass options to a service is syntactic sugar. It's simply to make it a cleaner and easier experience than setting it directly in the server. It's your choice to do either. Setting it twice seems entirely redundant considering a service uses a server. The service also initialises the client which is separate to the server.

**Comment by vtolstov** [comment]
@mytototo i don't think that you fix the issue.

I'm regular test single service setup and multiple services per binary. For each service you need to create dedicated transport and selector. For other stuff you can use already created registry and broker and pass it.

**Comment by mytototo** [comment]
This is what I've done. I pass on each server the already created broker and registry, and create a new transport for each service. I use the default selector.

Is it what you mean ?

**Comment by vtolstov** [comment]
Yes, after that all must be fine
