### ISSUE TITLE
propose registry interface additions

### ISSUE THREAD

**Issue by vtolstov** [micro/go-micro#405]
Registry interface need method to stop registry. Because without it we can't graceful stop registry.
For example gossip, do graceful stop service we need to call Leave and Shutdown, but this is not possible now.
Without this i can unneeded pings from other services that check alive status of node.

**Comment by asim** [comment]
Stop is not required by all registries considering most offload to a backend system. 

It is likely much better to provide Shutdown as part of a Context which signals when its done or cancelled. You can see an example of this here:

https://github.com/micro/go-micro/blob/master/service.go#L127
https://github.com/micro/go-micro/blob/master/options.go#L75L82

**Comment by vtolstov** [comment]
ok, thanks.
