### ISSUE TITLE
changing gossip broadcast method

### ISSUE THREAD

**Issue by vtolstov** [micro/go-micro#406]
As gossip registry always generate new Id via uuid, consider changing to  UniqueBroadcast
https://godoc.org/github.com/hashicorp/memberlist#UniqueBroadcast

this is faster then current approach, because avoid finding duplicates in queue.

**Comment by vtolstov** [comment]
in next day i send pr for this

**Comment by vtolstov** [comment]
not relevant before #404 solved

**Comment by asim** [comment]
Please consolidate into one issue.
