### ISSUE TITLE
Mock every interface

### ISSUE THREAD

**Issue by asim** [micro/go-micro#41]
Mock every interface so we can write tests
- [x] Broker
- [x] Registry
- [x] Client
- [x] Server
- [x] Transport

**Comment by boyand** [comment]
+1

**Comment by crufter** [comment]
+1

**Comment by asim** [comment]
PRs welcome

**Comment by crufter** [comment]
I will give this a go

**Comment by asim** [comment]
Cool. Just give it the same kind of layout at the registry/mock https://github.com/micro/go-micro/tree/master/registry/mock. [package]/mock/mock.go and provides New[Whatever] e.g registry/mock/mock.go has NewRegistry().

**Comment by asim** [comment]
So far:

https://github.com/micro/go-micro/tree/master/registry/mock
https://github.com/micro/go-micro/tree/master/broker/mock
https://github.com/micro/go-micro/tree/master/transport/mock

**Comment by asim** [comment]
https://github.com/micro/go-micro/tree/master/client/mock

**Comment by asim** [comment]
Now the question is whether there's a need for a mock server and how useful it would actually be.

**Comment by asim** [comment]
Done
