### ISSUE TITLE
registry: gossip rejoin after fail

### ISSUE THREAD

**Issue by vtolstov** [micro/go-micro#414]
we need to track failed nodes and periodically rejoin to them as hashicorp/serf does.
simple example:
i have three services on three nodes. one started first with fixed registry address, second and third joined to first.
after that i can't simply restart first service, because other two don't reconnect to it.
I think that more usable to have ability to rejoin failed nodes periodically, that specified in registry option. So we avoid to reconnect to dynamically added nodes, but track static configured. May be with some configured interval.

**Comment by asim** [comment]
Maybe it would be better to just use serf?

**Comment by vtolstov** [comment]
i have local branch with serf, main drawback - via serf i can send only 512 payload. i'm ask about this issue in issue, but don't have answer. also this is additional dep, that not really needed, because monitor delegate events not really hard.

**Comment by asim** [comment]
If you can implement the rejoin then I'm happy to accept a PR

**Comment by asim** [comment]
Close issue now?

**Comment by vtolstov** [comment]
for someone who read later, i have serf branch with working registry, but using memberlist only is fastest way to propagate changes and brings additional things like ability to pass local state with already registered services when reconnect.
