### ISSUE TITLE
Question: does micro do health checks?

### ISSUE THREAD

**Issue by darren** [micro/go-micro#418]
Start two micro services

```
go run greeter/api/api.go
go run greeter/api/api.go
```

And then kill one the them by `kill -9`,   so the service is not deregistered from the registry 

then `curl -v "http://localhost:8080/greeter/say/hello?name=abc"` will fail randomly

An hour later, the zombie service is still in the registry,  are there any tool that can monitor and remove these dead services automatically?

**Comment by asim** [comment]
You can set register ttl and interval in code or via flags. It expires entries.
