### ISSUE TITLE
How to log response in wrapper function?

### ISSUE THREAD

**Issue by t5w0rd** [micro/go-micro#421]
i can use micro.WrapHandler to log the request, but how to log the response in wrapper function like this?

```
func LogWrapper(fn server.HandlerFunc) server.HandlerFunc {
	return func(ctx context.Context, req server.Request, rsp interface{}) error {
		//meta, _ := metadata.FromContext(ctx)
		log.Logf("req|id->%s.%s|header->%+v|body->%s", req.Service(), req.Method(), req.Header(), req.Body())
		err := fn(ctx, req, rsp)
		if err != nil {
			log.Logf("err|id->%s.%s|err->%s", req.Service(), req.Method(), err.Error())
		} else {
			log.Logf("rsp|id->%s.%s|body->%s", req.Service(), req.Method(), rsp)
		}
		return err
	}
}
```

**Comment by asim** [comment]
The response is streamed directly to the client. You would have to write something that intercepts its ability to do that.

**Comment by uppercaveman** [comment]
req.Header() is empty。
![image](https://user-images.githubusercontent.com/4667056/61508391-32d2e900-aa1c-11e9-8f49-b72bf09cfac2.png)

**Comment by uppercaveman** [comment]
@asim

**Comment by uppercaveman** [comment]
@asim

**Comment by vtolstov** [comment]
i miss, question title is about logging response, but in comments you say request

**Comment by vtolstov** [comment]
ah i see, you can dump returned body and know how to unmarshal it. this is hard
