### ISSUE TITLE
Wrapper can't test if request struct implements interface

### ISSUE THREAD

**Issue by diegomarangoni** [micro/go-micro#422]
I was using tag `0.11.0` and in that version I was able to test if a request implements a interface by using the following code:

```
func (w wrappers) Events(next server.HandlerFunc) server.HandlerFunc {
	return func(ctx context.Context, req server.Request, resp interface{}) error {
		if _, ok := req.Request().(EventEmitter); ok {
			err := req.Request().(EventEmitter).EmitEvent(ctx)

			if nil != err {
				return err
			}
		}
```

Now upgrading to latest tag `0.26.1` I can't test the request anymore, because the content I do have is the raw json body.

```
func (w wrappers) Events(next server.HandlerFunc) server.HandlerFunc {
	return func(ctx context.Context, req server.Request, resp interface{}) error {
		if _, ok := req.Body().(EventEmitter); ok {
			err := req.Body().(EventEmitter).EmitEvent(ctx)

			if nil != err {
				return err
			}
		}
```

Is there any workaround?

**Comment by jiyeyuran** [comment]
the req.Body() is raw []byte now.

**Comment by asim** [comment]
If you need the decoded body please decode yourself or PR a fix. It's a complex change. We moved wrapper functionality outside of the router which makes it difficult.

**Comment by maybeTomorrow** [comment]
how to decode?
