### ISSUE TITLE
How can I know the client's real IP in inner service?

### ISSUE THREAD

**Issue by reechou** [micro/go-micro#425]
Hello,
My System Architecture is like : client -> gateway -> inner services
Then , in the inner services, how can I know the client's real IP?

**Comment by jiyeyuran** [comment]
You can check `X-Forwarded-For` field in the metadata of the context.

**Comment by asim** [comment]
Check the metadata. Remote and Local data is available.

**Comment by icarus910** [comment]
Which function or show ur code？
I cant find it. thx

**Comment by vtolstov** [comment]
Check metadata from context
