### ISSUE TITLE
cant't register to consul

### ISSUE THREAD

**Issue by eyasliu** [micro/go-micro#428]
When you add `go.mod` to `github.com/micro/go-web` spceify dependent `github.com/micro/go-micro v0.23.0` at https://github.com/micro/go-web/blob/master/go.mod#L7. But you have breaking changes after 0.2x.x on go-micro, cause I can't register web and srv to consul registry.

example code:
```go
// web.go
package main

import (
	"github.com/micro/go-web"
)

func main() {
	service := web.NewService(
		web.Name("go.micro.web.test"),
		web.Version("0.0.1"),
	)
	service.Init()
	if err := service.Run(); err != nil {
		print("some error")
	}
}
```

```go
// srv.go
package main

import (
	"github.com/micro/go-micro"
)

func main() {
	service := micro.NewService(
		micro.Name("go.micro.srv.test"),
		micro.Version("0.0.1"),
	)
	service.Init()
	if err := service.Run(); err != nil {
		print("some error")
	}
}
```

then run the service

```sh
consul agent -dev

go run web.go
go run srv.go
```

I don't see them on consul services list, I have trouble for days

**Comment by leninhasda** [comment]
That's because `MDNS` becomes the default registry after version `0.21.0`. 
Please refer here for change log and work around: https://github.com/micro/go-micro/releases/tag/v0.21.0

**Comment by printfcoder** [comment]
@eyasliu try:
use the flag **--registry=consul**
```bash
$ go run web.go --registry=consul
```

**Comment by eyasliu** [comment]
it work, thx! @leninhasda @printfcoder
