### ISSUE TITLE
rpc get too many timeout

### ISSUE THREAD

**Issue by reechou** [micro/go-micro#431]
![image](https://user-images.githubusercontent.com/949857/53810585-43655400-3f92-11e9-808b-f68ed828df43.png)

when I use call request to other node, just get so many "request timeout", I don't why, because the network is very healthy.

In the image, some request just get "timeout" in 1 second, but the default "request timeout" is 5 seconds ?  

What I can do ? This is already in the production. So It's very important.
@asim

**Comment by reechou** [comment]
```
wechat_bot.RegisterWechatBotServiceHandler(s.Service().Server(), &wechat.BotService{
    Client: s.Service().Client(),
})
```

```
func (bs *BotService) rpcSendMessage(ctx context.Context, req *wechat_bot.SendMessageRequest, nodeId string) (rsp *wechat_bot.SendMessageResponse, err error) {
	rpcClient := wechat_bot.NewWechatBotService("RealWechatBot", bs.Client)
	if rsp, err = rpcClient.SendMessage(ctx, req, client.WithSelectOption(selector.WithFilter(FilterSessionNode(nodeId)))); err != nil {
		logs.Error("rpc send message to node[%s] request: %v error: %v", nodeId, req, err)
		return nil, err
	} else {
		logs.Info("rpc send message response: %+v", rsp)
		return
	}
}
```
This is my code of call rpc .


Is the way I used wrong?

**Comment by reechou** [comment]
In my gateway, I call the request of "SendMessage"  just once, but in the service, I just receive the four request:
![image](https://user-images.githubusercontent.com/949857/53814019-d0f87200-3f99-11e9-850e-f054eddd1e73.png)

**Comment by Jasrags** [comment]
You might need to modify 
```   --client_request_timeout                             Sets the client request timeout. e.g 500ms, 5s, 1m. Default: 5s [$MICRO_CLIENT_REQUEST_TIMEOUT]
   --client_retries "0"                                Sets the client retries. Default: 1 [$MICRO_CLIENT_RETRIES]
   --client_pool_size "0"                            Sets the client connection pool size. Default: 1 [$MICRO_CLIENT_POOL_SIZE]
   --client_pool_ttl                                 Sets the client connection pool ttl. e.g 500ms, 5s, 1m. Default: 1m [$MICRO_CLIENT_POOL_TTL]
```
 if you are sending a high number of requests.

Our pool size is ~100

**Comment by reechou** [comment]
I think my requests are not very high.
My request flow is:
client -> gateway -> service1 -> service2
And my Transfer Protocol is http + json
Is this related to the three argvs: client_retries client_pool_size client_pool_ttl?

**Comment by reechou** [comment]
@Jasrags
How can I set in my code?

**Comment by umishra21** [comment]
@reechou did you manage to get this issue resolved?
