### ISSUE TITLE
rpc DATA RACE

### ISSUE THREAD

**Issue by PengjuDuan** [micro/go-micro#436]
WARNING: DATA RACE
Read at 0x00c0000d7500 by goroutine 63:
  math/rand.(*rngSource).Int63()
      /usr/local/Cellar/go/1.11.1/libexec/src/math/rand/rng.go:239 +0x3e
  math/rand.(*Rand).Int63()
      /usr/local/Cellar/go/1.11.1/libexec/src/math/rand/rand.go:85 +0x50
  math/rand.(*Rand).Int63n()
      /usr/local/Cellar/go/1.11.1/libexec/src/math/rand/rand.go:117 +0x6e
  github.com/micro/go-rcache.(*cache).run()
      /Users/pengju/go/pkg/mod/github.com/micro/go-rcache@v0.2.1/rcache.go:308 +0x17f

Previous write at 0x00c0000d7500 by goroutine 59:
  math/rand.(*rngSource).Int63()
      /usr/local/Cellar/go/1.11.1/libexec/src/math/rand/rng.go:239 +0x54
  math/rand.(*Rand).Int63()
      /usr/local/Cellar/go/1.11.1/libexec/src/math/rand/rand.go:85 +0x50
  math/rand.(*Rand).Int63n()
      /usr/local/Cellar/go/1.11.1/libexec/src/math/rand/rand.go:117 +0x6e
  github.com/micro/go-rcache.(*cache).run()
      /Users/pengju/go/pkg/mod/github.com/micro/go-rcache@v0.2.1/rcache.go:308 +0x17f

**Comment by PengjuDuan** [comment]
version 1.0.0

**Comment by asim** [comment]
This issue appears to be related to rcache? Please file issue against that project.
