### ISSUE TITLE
go-micro/codec/proto/marshaler.go

### ISSUE THREAD

**Issue by t5w0rd** [micro/go-micro#437]
go-micro/codec/proto/marshaler.go
func (Marshaler) Name() string
i think the function's name should be “String”:
func (Marshaler) String() string

codec.go:
type Marshaler interface {
	Marshal(interface{}) ([]byte, error)
	Unmarshal([]byte, interface{}) error
	String() string
}

**Comment by asim** [comment]
Your issue doesn't really make sense as it's already String

**Comment by t5w0rd** [comment]
emm.. but the function's name is "Name" [code ref](https://github.com/micro/go-micro/blob/master/codec/proto/marshaler.go#L17)

**Comment by vtolstov** [comment]
yes, may be marshaler need method String() and not Name()... but...
