### ISSUE TITLE
cmd.Init() before service.Init()

### ISSUE THREAD

**Issue by digitive** [micro/go-micro#439]
The service.Init() will invoke cmd.Init() internally. 
However, we need to perform cmd.Init() before the service.Init() in order to perform the cli flags, and using those flags to initialize the service. 

For example, we need to use subcommand to initialize different service or work as different client.

I wonder if this will cause any issue?

**Comment by asim** [comment]
I'm not sure that makes sense and I don't think that's actually possible unless you want to call cmd.Init and then just create a new service without calling service.Init. otherwise you should be able to pass flags to newservice and call action in service.Init  and pass in the service.

**Comment by digitive** [comment]
Hi Asim,
Thanks for quick reply. Can you quick look if below code works?
```go
	cmd.App().Flags = append(cmd.DefaultFlags, appFlags...)

	cmdBefore := cmd.App().Before
	cmd.App().Before = func(ctx *cli.Context) error {
		altsrc.InitInputSourceWithContext(cmd.App().Flags, altsrc.NewYamlSourceFromFlagFunc("config"))(ctx)
		return cmdBefore(ctx)
	}

	cmd.App().Commands = cli.Commands{
       ...
	}

	err := cmd.Init(
		cmd.Name(appName),
		cmd.Version(Version),
		cmd.Description(description),
	)

    ... 

	if <some flags> {
		tracer, closer := initJaeger(serviceName)
		defer closer.Close()
		ot.SetGlobalTracer(tracer)

		service := micro.NewService(
			micro.Name(serviceName),
			micro.WrapHandler(opentracing.NewHandlerWrapper(tracer)),
			micro.BeforeStart(func() error {
				microlog.SetLogger(mlogrus.NewMicroLogrus(logrus.StandardLogger()))
				return nil
			}),
		)
        ...
    }
```

**Comment by digitive** [comment]
Above code seems working well. Thanks Asim.
