### ISSUE TITLE
register a service using tls but the watcher still in http way

### ISSUE THREAD

**Issue by SgtDaJim** [micro/go-micro#445]
I register my service on Consul, with the code below:
```
micro.Registry(
			consul.NewRegistry(
				registry.Addrs("xxxx:8501"),
				registry.Secure(true),
				registry.TLSConfig(tlsConfig),
			),
		),
```
but the process got error when running:
```
[ERR] consul.watch: Watch (type: services) errored: Get http://xxxx:8501/v1/catalog/services: net/http: HTTP/1.x transport connection broken: malformed HTTP response "\x15\x03\x01\x00\x02\x02", retry in 3m0s
```

So it seems like the watcher didn't use tls.
Isn't it contradictory?

**Comment by printfcoder** [comment]
Hi, please try with the flag  '--registry=consul'. don't use **consul.NewRegistry** explicitly and directly, this method is used for telling go-micro that it should use consul as the registry center as the flag value is consul.

then use **registry.NewRegistry** to set special configs

as below:
```
reg := registry.NewRegistry(registryOptions)
...
micro.NewService(
		...
		micro.Registry(reg),
		micro.RegisterTTL(time.Minute*30),
		micro.RegisterInterval(time.Minute*10),
		...,
)

func registryOptions(ops *registry.Options) {
	consulCfg := config.GetConsulConfig()
	ops.Timeout = time.Second * 30
	ops.Addrs = []string{fmt.Sprintf("%s:%d", consulCfg.GetHost(), consulCfg.GetPort())}
}
```

```
$ go run main.go --registry=consul
```

or

```
$ MICRO_REGISTRY=CONSUL go run main.go
```

if you don't like to configure in golang, you can input the configs as flag:

```
$  go run main.go --registry=consul --registry_address=127.0.0.1:8500 --register_interval=30 --register_ttl=60
```

**Comment by SgtDaJim** [comment]
@printfcoder understand, but i don't call service.Init() in my code because i do something special for my enviornment, so go-micro's flags will not parse. So I have to use consul.NewRegistry().
Actually, i do something like that:
```
flag.StringVar(&advertiseIP, "advertise_ip", "", "Advertise for registry")
......

introspection.IntrospecteAdvertiseIP(advertiseIP)
	introspection.IntrospecteAgentServerIPsInfo()
	var b broker.Broker
	var serverAddress server.Option
	if util.InStringSlice(advertiseIP, introspection.AgentServerIPs) {
		b = http.NewBroker(
			broker.Addrs(fmt.Sprintf("%s:%d", advertiseIP, brokerPort)),
		)
		serverAddress = server.Address(fmt.Sprintf("%s:%d", advertiseIP, transportPort))
	} else {
		b = http.NewBroker(
			broker.Addrs(fmt.Sprintf("%s:%d", "0.0.0.0", brokerPort)),
		)
		serverAddress = server.Address(fmt.Sprintf("%s:%d", "0.0.0.0", transportPort))
	}
	brokerOption := micro.Broker(b)
```
Because some of our servers are bgp servers or cloud servers, it have no public IP config in network interfaces configuration. So binding the advertise IP (the public IP) might go error. I tried to parse the go-micro's flags before service.Init(), but it seemed that I could not.
So are there any better practices?

**Comment by printfcoder** [comment]
you means that you want to set the ** advertise_ip** as a flag, but go-micro does not support custom flags?

If I understand what's going on, I think you can try using **Env**:

```
$ ADVERTISE_IP='the value you need' go run main.go --registry=consul
```

```
advertiseIP:=os.Getenv("ADVERTISE_IP")
if len(advertiseIP) == 0 {
    panic(""Advertise for registry"")
}
```

**Comment by SgtDaJim** [comment]
understood. I will have a try tomorrow. thanks.

**Comment by paraths26** [comment]
@SgtDaJim 
Are you able to fix it. I am also getting same issue while using consul over tls. Service is able to register with https , but watcher is still in http mode. 
I have created a web service as below  : 

```
service := web.NewService(
			web.Name("<service-name>"),
			web.Address("<port>"),
			web.Advertise("<advertise with private IP>"),
			web.RegisterTTL(time.Second*30),
			web.RegisterInterval(time.Second*10),
			web.Registry(reg),
		)
```
where registry : 
`reg := registry.NewRegistry(registryOptions)`
registryOptions is as mentioned by @printfcoder 

```
func registryOptions(ops *registry.Options) {
	ops.Timeout = time.Second * 30
	ops.Secure = true
	ops.TLSConfig = &tls.Config{InsecureSkipVerify: true}
}
```

It seems that `go wp.Run(cr.Address)` at (https://github.com/micro/go-micro/blob/4f5ff076d4375b2518e75d62d91de9cdf0f15d33/registry/consul/watcher.go#L46) always runs consul watcher without tls configuration details.

Thanks.

**Comment by Arpit1596** [comment]
Same issue consul watcher is still giving the issue
