### ISSUE TITLE
need support broadcast function

### ISSUE THREAD

**Issue by worldyuan** [micro/go-micro#446]
I want to send a message to all server(update status) for a type of service

**Comment by asim** [comment]
You should use the Publish method of the client. This is what it's for. Services should subscribe to a topic and you can broadcast to all.

**Comment by jeek120** [comment]
thanks,I use nsqd and it cannot broadcast to all.I can run every app for create a uuid channel(queue),but nsqd can not remove chanel(quene) and store it to memory or disk.

**Comment by worldyuan** [comment]
I used nsqd as message bus.but nsqd not support broadcast, you must remove it's channel if run a service generate a random channel. otherwise nsqd will store all unread message on memory and disk.

**Comment by vtolstov** [comment]
use nats

**Comment by asim** [comment]
Nsq allows you to have ephemeral channels by using #whatever in the channel name. See the docs. Ultimately broadcast is just pubsub so we support it as that and you should ideally use that.

**Comment by worldyuan** [comment]
tks.

**Comment by asim** [comment]
Closing since we appear to have come to a resolution
