### ISSUE TITLE
Upgraded micro to 1.11 and now get codec issues

### ISSUE THREAD

**Issue by Ryan-Hancock** [micro/go-micro#447]
Hey, 

Upgraded to 1.11 and now getting this on the upgraded service. 

`{
  "id": "go.micro.client.codec",
  "code": 500,
  "detail": "json: cannot unmarshal string into Go struct field clientResponse.id of type uint64",
  "status": "Internal Server Error"
}`

Any thoughts would be greatly appreciated

**Comment by ptrkrlsrd** [comment]
I have the same issue. To me it seems to only happen if I use Go modules, and not when I create a project in the GOPATH.

**Comment by asim** [comment]
Micro or go-micro? What's the setup? How many things is the request flowing through? Is it coming through the micro api? What's the handler being used? Need more info to debug the issue.

**Comment by asim** [comment]
Off the top of my head, the codecs changed to use strings rather than uint64 for json-rpc, so this may be posing an issue but it's supposed to be backwards compatible based on certain metadata. What environment is this in? What service discovery? What client? What transport?

**Comment by Ryan-Hancock** [comment]
This is on the go-micro. I have tested this using an older version of micro and the latest locally. Service discovery is done with consul and the service is in go. Transport was tested on cli call, micro web and through the rest http proxy. As @ptrkrlsrd said would fit the change on how this service was created.

**Comment by ptrkrlsrd** [comment]
@asim I had this issue on both a fleshed out project, and a simple project created using the CLI command (`micro new <name>`). In both cases I used `go1.12.1 linux/amd64` with modules, and I called the service using both `micro call ...`, the API and the web service. Maybe it would help if I posted my go.mod/go.sum file?

**Comment by asim** [comment]
So this is Go related or go module related? Because the only change since 1.0 that should have any significance is the go modules updated. I'm not exactly sure what that issue would be.

**Comment by asim** [comment]
No response on the issue. Should it be closed?

**Comment by mytototo** [comment]
I also have an issue since I upgraded `go-micro`. I don't know if it's related.

When using a codec, my application panics. It looks like the codecs map is nil, so it can't push a new codec when passing a new one in options. I don't have the code today since I'm not on my computer but I could send you more info tomorrow if needed.

**Comment by kxion** [comment]
thanks a lot!

**Comment by asim** [comment]
Codec map should not be nil. I'm not really sure why you're seeing this. There's been no response in 2 weeks so closing the issue.
