### ISSUE TITLE
why must read os.Args?

### ISSUE THREAD

**Issue by Tcake** [micro/go-micro#449]
When I use go-micro client as a part of my project，I don't want to init it with my cmd args.
I must add **os.Args=os.Args[0:1]** before service init. Otherwise, it will exit without panic.
Do I have a parameter to skip os.Args?

I am a novice, if there is anything wrong, please forgive me.

**Comment by asim** [comment]
If you're only using the client you don't need to call service.Init. You can also initialise values yourself by passing as options.

**Comment by Tcake** [comment]
sorry,It looks like I used service.Init incorrectly. I should just use micro.NewService() with my values.
Thank you very much!
