### ISSUE TITLE
How to log request and response body in a wrapper?

### ISSUE THREAD

**Issue by victorisildur** [micro/go-micro#450]
I'm trying to log every request and response of go-micro protorpc services like this:

```go
func MicroSrvLogWrapper(fn server.HandlerFunc) server.HandlerFunc {
	return func(ctx context.Context, req server.Request, rsp interface{}) error {
		// log request body here
		err := fn(ctx, req, rsp)
                // log response body here
		return err
	}
}
```

However, from go-micro code I see I can only get bytes of request & response body

```go
func (r *rpcRequest) Body() interface{} {
	// TODO: convert to interface value
	return r.body
}
```

```go
type rpcResponse struct {
	header map[string]string
	socket transport.Socket
	codec  codec.Codec
}
```

How to print pretty form of request & response body both protobuffer encoded? Any idea is appreciated

**Comment by k1ng440** [comment]
Hello,
behind the sense, micro handles the decoding of protobuff messages.

you can [litter](https://github.com/sanity-io/litter) to pretty print the req and rsp


if i didn't answer your question correctly please contact me on micro slack, i will try my best to help you out.

**Comment by asim** [comment]
Hi. You'll have to decode the request or response yourself to be able to do this. We're no longer providing the interface value at this time.
