### ISSUE TITLE
Check client still alive

### ISSUE THREAD

**Issue by maxjust** [micro/go-micro#451]
Need a way to check from service side is service.client still alive and execute some service.handler if not.

**Comment by asim** [comment]
Can you be more clear about what you mean here? You can use the internal Debug.Health handler to ping and check the service is there.

**Comment by maxjust** [comment]
I have a client who takes the task from the server to perform certain operations. But the client may fall off. In this case, the server should mark the task taken by the client as free so that the other client of the service can pick it up. Rabbit is not suitable as the service should be able to remove tasks for some conditions, for example, a few task at once by tasks type or one task by identifier. What`s why I need to execute some handler when service client is go down. But I need to know clien ID or some other client identificator to free task taken by this client. 
P.S I need to check the client still here, not a service and check it from service side.

**Comment by asim** [comment]
I think what you're asking for is a distributed job scheduler which is not in the scope of go-micro. We have a Task interface in [go-sync](https://github.com/micro/go-sync) which is supposed to solve this problem but still a work in progress.

If you'd like to discuss design for something like this please join the community https://micro.mu/slack/
