### ISSUE TITLE
Go get fails due to testcontainers

### ISSUE THREAD

**Issue by thededlier** [micro/go-micro#457]
While running  `go get github.com/micro/go-micro`, I get the following error:

`go: github.com/testcontainers/testcontainer-go@v0.0.3: parsing go.mod: unexpected module path "github.com/testcontainers/testcontainers-go"`

This seems to be because the github path for testcontainers is 

github.com/testcontainers/testcontainer**s**-go@v0.0.3

**Comment by igorrius** [comment]
You can temporary solve this issue by adding `replace github.com/testcontainers/testcontainer-go => github.com/testcontainers/testcontainers-go v0.0.0-20190108154635-47c0da630f72` to your `go.mod` file.

**Comment by asim** [comment]
This should not be a specific issue with go-micro. Running go get locally does not produce any errors. It's likely related to surrounding usage. An answer has been provided above for a fix.

**Comment by thededlier** [comment]
Yes it was an issue in my local setup. Thanks for the help @igorrius
