### ISSUE TITLE
grpc.NewService() and RegisterSubscriber , topic:xxx Not found

### ISSUE THREAD

**Issue by qin-jd** [micro/go-micro#459]
```
service := grpc.NewService(
		micro.Name("go.micro.srv.notification"),
		micro.Version("latest"),
	)

micro.RegisterSubscriber("notification.submit", service.Server(), new(subscriber.Notification))

if err := service.Run(); err != nil {
		log.Fatal(err)
	}
```
exec `micro web` can see `go.micro.srv.notification` and `topic:notification.submit`
`go.micro.srv.notification`  broker=grpc registry=mdns server=grpc transport=grpc
but  topic:notification.submit not found

How do I use grpc broker when using grpc service

**Comment by fitzix** [comment]
@qin-jd I think this issue is already fixed at https://github.com/micro/go-plugins/pull/317 and you can update the go-plugins version.

**Comment by printfcoder** [comment]
@qin-jd please update go-plugins to the last version

**Comment by qin-jd** [comment]
@printfcoder when update go-plugins , some problems  like this https://github.com/micro/go-plugins/issues/313

**Comment by fitzix** [comment]
This means that you are using gomodule. Before the author releases a new version, you need to use `go mod edit -replace github.com/golang/lint=golang.org/x/lint@latest` to solve the import path problem. 

You may also get the error of `github.com/testcontainers/testcontainer-go`, execute `go mod edit -replace github.com/testcontainers/testcontainer-go=github.com/testcontainers/testcontainers-go@latest` to resolve this error .

**Comment by qin-jd** [comment]
@fitzix thanks for answers , after the update, when publish message and the error will still be reported.
```
2019/04/24 11:37:29 Broker Listening on [::]:60017
2019/04/24 11:37:29 Listening on [::]:60018
2019/04/24 11:37:29 Broker [grpc] Listening on [::]:60017
panic: 2019/04/24 11:37:29 Registering node: go.micro.srv.greeter-76a5a350-a145-4da1-bbe7-55363501f2ac
runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x18 pc=0xa5bf74]

goroutine 52 [running]:
github.com/micro/go-plugins/broker/grpc.(*grpcBroker).Publish.func1(0xc00027e300, 0xc0001ee080)
        D:/go_path/pkg/mod/github.com/micro/go-plugins@v1.1.0/broker/grpc/grpc.go:435 +0x3a4
created by github.com/micro/go-plugins/broker/grpc.(*grpcBroker).Publish
        D:/go_path/pkg/mod/github.com/micro/go-plugins@v1.1.0/broker/grpc/grpc.go:454 +0x40c
exit status 2

```
grpc.Dial error

**Comment by asim** [comment]
Any further update on this? Having a difficult time debugging it.

**Comment by qin-jd** [comment]
Fixed after updating go-plugins
