### ISSUE TITLE
IP of Service

### ISSUE THREAD

**Issue by leosabbir** [micro/go-micro#460]
When registering a service to Consul, you need to pass the IP of our service. How do you compute this IP?

**Comment by asim** [comment]
We extract it from the interfaces unless its already specified https://github.com/micro/util/blob/master/go/lib/addr/addr.go#L31

**Comment by shushenghong** [comment]
if we have 1 private ip, 1 public ip, can i use the public ip automatically?

**Comment by shushenghong** [comment]
i checked the code, why we use private ip first?
```
	// return private ip
	if ipAddr != nil {
		return net.IP(ipAddr).String(), nil
	}

	// return public or virtual ip
	if publicIP != nil {
		return net.IP(publicIP).String(), nil
	}
```

**Comment by shushenghong** [comment]
@asim

**Comment by asim** [comment]
You must explicitly specify the ip:port if you want to use a public IP. If an address is present we will not test it.
