### ISSUE TITLE
micro api default register in mdns，but consul

### ISSUE THREAD

**Issue by jol5** [micro/go-micro#463]
CMD:   micro api

2019/04/29 16:09:48 Registering RPC Handler at /rpc
2019/04/29 16:09:48 Registering API Default Handler at /
2019/04/29 16:09:48 HTTP API Listening on [::]:8080
2019/04/29 16:09:48 Transport [http] Listening on [::]:51748
2019/04/29 16:09:48 Broker [http] Connected to [::]:51749
2019/04/29 16:09:48 **Registry [mdns]** Registering node: go.micro.api-bd1c8eb9-a167-4cf7-8bb0-4b1ce6be989d

how can i Registry [consul]

**Comment by leninhasda** [comment]
related: #428 

short answer: use the flag `--registry=consul`

**Comment by jol5** [comment]
> related: #428
> 
> short answer: use the flag `--registry=consul`

nop! 

micro api --registry=consul is a valid config

info:

Incorrect Usage.

NAME:
   micro api - Run the api gateway

USAGE:
   micro api [command options] [arguments...]

OPTIONS:
   --address    Set the api address e.g 0.0.0.0:8080 [%MICRO_API_ADDRESS%]
   --handler    Specify the request handler to be used for mapping HTTP requests to services; {api, event, http, rpc} [%MICRO_API_HANDLER%]
   --namespace  Set the namespace used by the API e.g. com.example.api [%MICRO_API_NAMESPACE%]
   --resolver   Set the hostname resolver used by the API {host, path, grpc} [%MICRO_API_RESOLVER%]

**Comment by leninhasda** [comment]
`--registry` is a global option, so you have to use it like this:
```
// micro [global option] command ... 
micro --registry=consul api
```
