### ISSUE TITLE
Client can't find node

### ISSUE THREAD

**Issue by Allenxuxu** [micro/go-micro#464]
Hey,
I have set that with --registry=consul.
If I use "client.NewClient()", it can't work.

> Error #01: {"id":"go.micro.client","code":500,"detail":"error selecting go.micro.srv.hello node: not found","status":"Internal Server Error"}

Please see the code below.

    service := web.NewService(
		web.Name(name),
		web.Version("lastest"),
	)

	if err := service.Init(); err != nil {
		log.Fatal(err)
	}

	// cl := hello.NewExampleService("", client.DefaultClient) // it's work
	cl := hello.NewExampleService("", client.NewClient())     // error selecting go.micro.srv.hello node: not found

	apiService := handler.New(cl)
	router := gin.Default()
	router.Use(gin2micro.TracerWrapper)
	router.GET("/user/login", apiService.Anything)

	service.Handle("/", router)

	if err := service.Run(); err != nil {
		log.Fatal(err)
	}

**Comment by asim** [comment]
Please use `service.Options().Service.Client()`

A new client is not initialised when you call service.Init.

**Comment by Allenxuxu** [comment]
Thank you very much!
