### ISSUE TITLE
can api-gateway auto discover new service nodes?

### ISSUE THREAD

**Issue by xuhrc** [micro/go-micro#465]
When i deregistered a service and restarted it, the service port dynamic changed in consul.
But the api-gateway cannot discover the new service node, i have to restart the api-gateway, it that a way to make the api-gateway auto discover service nodes?

{"id":"go.micro.client","code":500,"detail":"error getting next go.micro.api.AccountServer node: none available","status":"Internal Server Error"}

**Comment by printfcoder** [comment]
maybe it is because the account-server was not exited normally. 
try to check consul services if it is keeping some dead services in it.

please join [slack](http://slack.micro.mu/)，we have a Chinese channel.

**Comment by xuhrc** [comment]
The consul already removed the old account-server from it. 
After the new account-server registered again, the api-gateway cannot auto reconnect to the new service.

**Comment by asim** [comment]
Can you provide an example we can replicate this bug with please

**Comment by asim** [comment]
Please join the slack to discuss further as this is the wrong place for this issue.

**Comment by xuhrc** [comment]
Problem solved!
After i set registerTTL and RegisterInterval to the MicroService, The ApiGateway can reconnect it right away.
