### ISSUE TITLE
expose local binding address and local advertised address via Server interface

### ISSUE THREAD

**Issue by vtolstov** [micro/go-micro#468]
this data needed for https://golang.org/pkg/crypto/x509/#CreateCertificateRequest
i'm create own mTLS service and each micro service that needs cert from mtls generate CSR and sent it to mTLS service.
in csr i need to provide ipaddresses for SANs because be ably to enable ClientAuth.
Now i need ugly hack to get remote addr via metadata context inside mtls service, but this is not right solution. because csr generated by client and not "server"

**Comment by asim** [comment]
Can you file this issue in the development repo so we can track there. Thanks.

**Comment by vtolstov** [comment]
why issues for this repo needs to go to different repo?
