### ISSUE TITLE
default rpc server-side streaming not end with io.EOF

### ISSUE THREAD

**Issue by magodo** [micro/go-micro#476]
Seems like default rpc stream will never return `io.EOF` on end of stream, `io.ErrUnexpectedEOF` instead.

I did this test with some minor change on official stream example. With dlv, i see it client finally reached below point:

```
func (r *rpcStream) Recv(msg interface{}) error {
  ...
	if err := r.codec.ReadHeader(&resp, codec.Response); err != nil {
		if err == io.EOF && !r.isClosed() {
			r.err = io.ErrUnexpectedEOF
			return io.ErrUnexpectedEOF
		}
		r.err = err
		return err // reach here! and error is micro's unexpected eof error
	}
  ...
}
```

**Comment by asim** [comment]
Can you offer a fix?

**Comment by asim** [comment]
Are you using this example? https://github.com/micro/examples/tree/master/stream

**Comment by magodo** [comment]
Yes, i modified the `serverStream()` in client side to loop forever until got an error. I expect it would be `io.EOF`, while it isn't.

**Comment by lpxxn** [comment]
i have the same error too, the service need send error to the client, and i commited codes to fix it.

**Comment by magodo** [comment]
Test now passed, close issue
