### ISSUE TITLE
There is an mistakes in your Chinese doc

### ISSUE THREAD

**Issue by luobangkui** [micro/go-micro#479]
https://micro.mu/docs/cn/architecture.html#broker

```
Broker
Broker是事件广播/订阅可插件接口。对于事件驱动的微服务架构，消息广播与订阅得放在首要位置。目前的实现有NATs、rabbitmq、http (仍在开发中)。
```
这里应该是Broker是事件广播/订阅可插拔接口吧。

**Comment by asim** [comment]
Please go to the docs repo and PR a fix or ask @printfcoder in Slack
