### ISSUE TITLE
`rpc_request.Body()` not reflect `server.Request.Body()`'s intention

### ISSUE THREAD

**Issue by magodo** [micro/go-micro#482]
The comment of `server.Request.Body()` is as:

```go
// Body is the initial decoded value
Body() interface{}
```

While the implementation of `rpc_request.Body()` is as:

```go
func (r *rpcRequest) Body() interface{} {
	// TODO: convert to interface value
	return r.body
}
```

which is the **encoded** value, not meets guarantee of interface's intention. As regard to the `TODO` comment, I guess the something(e.g. decode) should be done in `Body()` function. Is this in plan or just hanging?

**Comment by ashishu1** [comment]
I am trying to update to the newer version of micro. The version I have uses req.Request() function to get get the request that is  passed to the handler. I have this in a wrapHandler that allows me to validate all incoming requests as long as they implement an interface.

Now that I am working on migrating to the latest version , I can't use req.Body() for the reason stated by magodo.

```
// Code for my current validation handler.
func Validate(fn server.HandlerFunc) server.HandlerFunc {
	return func(ctx context.Context, req server.Request, resp interface{}) error {
		if request, ok := req.Request().(proto.ValidatableRequest); ok {
			err := request.Validate()
			if err != nil {
				return errors.Wrap(err, "request is not valid.")
			}
			err = fn(ctx, req, resp)
			return err
		} else {
			err := fn(ctx, req, resp)
			return err
		}
	}
}
```

**Comment by magodo** [comment]
Which version are you refering to? I don't see the `Request()` method in server.go's `Request` interface, and i'm at HEAD of master branch.

**Comment by ashishu1** [comment]
The Request() method used to be there in the version that used the forked protoc generator.

https://github.com/micro/go-micro/commit/d004c9624b76e048425523ee7e2ddef15c59b1c6#diff-191657a4791e9c066d2661d83f33bc18

**Comment by asim** [comment]
https://github.com/micro/go-micro/issues/482

This should fix it

**Comment by asim** [comment]
Closing as tested and its fixed.
