### ISSUE TITLE
graceful shutdown not honor goroutines launched during handler but last longer than handler

### ISSUE THREAD

**Issue by magodo** [micro/go-micro#483]
I have a rpc sequence like below:

![image](https://user-images.githubusercontent.com/7970698/58259213-ad79e200-7da6-11e9-9547-66564d98a6fc.png)

where *A* is the safe area that graceful shutdown will honor, while *B* will not.

Currently my approach to do this is to make a simple wrapper of `go` directive, which will also launch a go routine, except it will also track this go routine in some global wg. Then I pass in a function via `micro.BeforeStop()` to wait against these outstanding go routines.

But this is a broken workaround, since at the moment of `BeforeStop()`, the server is still discoverable by other ones, if there is continuous inbound request, then the shutdown process might be blocked.

My expectation is that somehow go-micro could provide a hook just after deregistering from registry.

**Comment by vtolstov** [comment]
Can you try to utilize context to shutdown goroutine?

**Comment by magodo** [comment]
Can you provide some detail/example?

What I want is a chance to wait for outstanding go routine to finish after deregistering from registry but before other shutdown process (e.g. broker should still connect because some go routine might want to publish msg).

**Comment by asim** [comment]
Currently the server has a Wait option. This could potentially be changed to to accept a sync.WaitGroup. You would need to change the Wait usage to that which is specified https://github.com/micro/go-micro/blob/master/server/rpc_server.go#L561. Likely be redefining the initialisation of the existing sync.WaitGroup to use the one pulled from context. 

You'd also need to change the implementation in the grpc/http servers in go-plugins. This is a potential solution.
