### ISSUE TITLE
etcd dependency problem

### ISSUE THREAD

**Issue by w3liu** [micro/go-micro#493]
code:
`import (
	"fmt"
	_ "github.com/micro/go-micro/config/source/etcd"
	"testing"
)

func TestHello(t *testing.T) {
	fmt.Println("Hello World!")
}`

errors:

API server listening at: 127.0.0.1:63206
2019/06/04 11:59:06 proto: duplicate proto type registered: mvccpb.KeyValue
2019/06/04 11:59:06 proto: duplicate proto type registered: mvccpb.Event
panic: proto: duplicate enum registered: mvccpb.Event_EventType

goroutine 1 [running]:
github.com/golang/protobuf/proto.RegisterEnum(0x11eba9b, 0x16, 0xc0001599b0, 0xc0001599e0)
E:/project/golang/pkg/mod/github.com/golang/protobuf@v1.3.1/proto/properties.go:459 +0x14a
go.etcd.io/etcd/mvcc/mvccpb.init.0()
E:/project/golang/pkg/mod/go.etcd.io/etcd@v3.3.13+incompatible/mvcc/mvccpb/kv.pb.go:107 +0xc7

**Comment by w3liu** [comment]
@asim
 in "github.com/micro/go-micro/config/source/etcd/etcd.go" 
 there is a conflict between the two packages:
  "go.etcd.io/etcd/clientv3" and "go.etcd.io/etcd/mvcc/mvccpb"

**Comment by asim** [comment]
I am not seeing this issue. Please run go get -u with go modules on.

**Comment by friedrichwong** [comment]
I  used github.com/micro/go-micro v1.4.0 and I got the same issue.


Sample code show as follows:

```go
package main

import (
	"github.com/micro/go-micro/config/source/etcd"
)

func main() {

	etcd.NewSource(
		etcd.WithAddress("127.0.0.1:2379"),
		etcd.WithPrefix("/prefix"),
		etcd.StripPrefix(true))
}
```

---
Error:
```go
2019/06/04 19:12:10 proto: duplicate proto type registered: mvccpb.KeyValue
2019/06/04 19:12:10 proto: duplicate proto type registered: mvccpb.Event
panic: proto: duplicate enum registered: mvccpb.Event_EventType

goroutine 1 [running]:
github.com/golang/protobuf/proto.RegisterEnum(...)
	/Users/william/Code/GO/pkg/mod/github.com/golang/protobuf@v1.3.1/proto/properties.go:459
go.etcd.io/etcd/mvcc/mvccpb.init.0()
	/Users/william/Code/GO/pkg/mod/go.etcd.io/etcd@v3.3.13+incompatible/mvcc/mvccpb/kv.pb.go:107 +0x18a
```

**Comment by asim** [comment]
Are you using go modules? Have you done go get -u to update the rest of your dependencies? Because this ia broader issue related to etcd's use of its own libraries. Again, this is working totally fine locally with the most up to date dependencies, not just go-micro but all other deps.

**Comment by w3liu** [comment]
I has resolved，go.mod add this  statement:
`
replace go.etcd.io/etcd v3.3.13+incompatible => github.com/etcd-io/etcd v0.0.0-20190603181807-35a67024f680
`

**Comment by asim** [comment]
Closing the issue
