### ISSUE TITLE
Some code question when use consul cluster

### ISSUE THREAD

**Issue by zn-cn** [micro/go-micro#499]
For your code: /registry/consul/consul.go function: configure
```
	// check if there are any addrs
	if len(c.opts.Addrs) > 0 {
		addr, port, err := net.SplitHostPort(c.opts.Addrs[0])
		if ae, ok := err.(*net.AddrError); ok && ae.Err == "missing port in address" {
			port = "8500"
			addr = c.opts.Addrs[0]
			config.Address = fmt.Sprintf("%s:%s", addr, port)
		} else if err == nil {
			config.Address = fmt.Sprintf("%s:%s", addr, port)
		}
	}
```
I'm confused about how it check all addrs? I see it only takes out the first?

**Comment by printfcoder** [comment]
it is not micro's problem. the consul golang client just allows the user to use one address to connect the server. and so it is unnecessary to check all addresses. we just need one address which works fine.

if you need to connect with the consul cluster, then you can connect the local agent, it will help you to keep the connection with servers in the cluster.
