### ISSUE TITLE
subscription problem

### ISSUE THREAD

**Issue by fztcjjl** [micro/go-micro#503]
When the service is disconnected from the messaging system, the subscription needs to be resubscribed after reconnection. So there should be provide a way to resubscribe topic.

**Comment by vtolstov** [comment]
This is not simple, because we need to store topic and options for subscription..
I'm need to think about this more

**Comment by fztcjjl** [comment]
topic and subscription options has already stored in server。
eg.
https://github.com/micro/go-micro/blob/95b8147fa12f0ac6b1df644a1a864325c86a015d/server/rpc_server.go#L29

**Comment by vtolstov** [comment]
Reconnect happens inside broker client in broker implementstion. So for
nats you dont need anything,after client reconnect it resubscribes. But for
stan you need to subscribe again inside broker implementation.

сб, 8 июн. 2019 г., 18:07 fztcjjl <notifications@github.com>:

**Comment by vtolstov** [comment]
i think that we need to fix this in stan broker in nats-io/stan.go repo (as devs says in slack nats already resubscribe after reconnect)

**Comment by vtolstov** [comment]
i'm create issue to stan.go https://github.com/nats-io/stan.go/issues/273

**Comment by asim** [comment]
Marking this as a non-fix for now. The complexity of managing reconnection and resubscription is quite tough, especially across pluggable tooling.

**Comment by vtolstov** [comment]
i think before closing this issue we need to document current behavior and add some stuff to development repo as issue?

**Comment by asim** [comment]
Closing this is fine. Add to development repo if needed. But otherwise it's fairly complex and difficult to implement across all brokers.
