### ISSUE TITLE
config package does not allow to set and del value

### ISSUE THREAD

**Issue by vtolstov** [micro/go-micro#505]
to abstract source of config we need to have set and del methods, also why top level package config have methods for Get value? Why not add Get/Set/Del methods to config interface?

**Comment by asim** [comment]
It's a question of underlying implementation. We only had a need to retrieve not set. To set or delete is to basically change the way the loader or source works. Or to determine what gets deleted or set and where. When doing this with multiple sources it becomes difficult. 

If the final merged form is to be changed then that might make more sense.

**Comment by vtolstov** [comment]
Yes, if you have multiple sources, Set for such config undesirable.... But i'm really need such stuff, and don't understand how to solve my issue

**Comment by vtolstov** [comment]
I think that source package need to have such things. Last question - how to propagate this changes to top level.... May be with via internals add event to channel?

**Comment by asim** [comment]
Config and source both have a watch method.

In regard to set/delete. It's not a simple change. Happy to see some sort of design work contributed.

**Comment by vtolstov** [comment]
I'm try to get this for mdns For it set/del is very simple. I only set/del map item and other stuff is served via mdns package.

**Comment by vtolstov** [comment]
Hm as i see config operates on ChangeSet that always hold all data, so delete part of it or replace is hard...
I need to merge/delete struct parts..

**Comment by asim** [comment]
Let's move this to feature development in the development repo
