### ISSUE TITLE
explain mdns registry

### ISSUE THREAD

**Issue by vtolstov** [micro/go-micro#511]
@asim can you explain this part of mdns registry
```go
s, err := mdns.NewMDNSService(               
  service.Name,                              
  "_services",                               
  "",                                        
  "",                                        
  9999,                                      
  []net.IP{net.ParseIP("0.0.0.0")},          
  nil,                                       
)                                            
```

**Comment by vtolstov** [comment]
Why you use txt records for info? why not utilize some parts of mdns ServiceEntry things?
For example you can implement Zone interface and serve records with name,port for query. and in txt store only metadata like version (i'm still think that this is must be moved from struct to metadata), endpoints and metadata

**Comment by asim** [comment]
Its just a hack. We should do it the correct way.
