### ISSUE TITLE
add ipv6 support for mdns registry service address

### ISSUE THREAD

**Issue by vtolstov** [micro/go-micro#512]
as i see ipv6 address in mdns registry does not supported, may be in other places too. i think that we need to collect this places and fix the ipv6 issue.

**Comment by vtolstov** [comment]
i think that this needs to be added when doing https://github.com/micro/go-micro/pull/521

**Comment by asim** [comment]
Is this done?

**Comment by vtolstov** [comment]
i rename the issue, because now this is mdns issue =)

**Comment by vtolstov** [comment]
already fixed
