### ISSUE TITLE
a question about Caching Discovery

### ISSUE THREAD

**Issue by shikbupt** [micro/go-micro#526]
Client side caching is a method of eliminating service discovery as a single point of failure. But the code shows that when cache is not within ttl, getting service name from service discovery will happen. if service discovery is down, the addresses will not get and the client will down.
So I think when the service discovery is down, the cache ttl should not checking.

**the code is:**
func (c *cache) get(service string) ([]*registry.Service, error) {
	// read lock
	c.RLock()

	// check the cache first
	services := c.cache[service]
	// get cache ttl
	ttl := c.ttls[service]

	// got services && within ttl so return cache
	if c.isValid(services, ttl) {
		// make a copy
		cp := c.cp(services)
		// unlock the read
		c.RUnlock()
		// return servics
		return cp, nil
	}

	// get does the actual request for a service and cache it
	get := func(service string) ([]*registry.Service, error) {
		// ask the registry
		services, err := c.Registry.GetService(service)
		if err != nil {
			return nil, err
		}

		// cache results
		c.Lock()
		c.set(service, c.cp(services))
		c.Unlock()

		return services, nil
	}

	// watch service if not watched
	if _, ok := c.watched[service]; !ok {
		go c.run(service)
	}

	// unlock the read lock
	c.RUnlock()

	// get and return services
	return get(service)
}

**the code can change:**
func (c *cache) get(service string) ([]*registry.Service, error) {
	// read lock
	c.RLock()

	// check the cache first
	services := c.cache[service]
	// get cache ttl
	ttl := c.ttls[service]

	// got services && within ttl so return cache
	if c.isValid(services, ttl) {
		// make a copy
		cp := c.cp(services)
		// unlock the read
		c.RUnlock()
		// return servics
		return cp, nil
	}

	// get does the actual request for a service and cache it
	get := func(service string) ([]*registry.Service, error) {
		// ask the registry
		services, err := c.Registry.GetService(service)
		if err != nil {
			return nil, err
		}

		// cache results
		c.Lock()
		c.set(service, c.cp(services))
		c.Unlock()

		return services, nil
	}

	// watch service if not watched
	if _, ok := c.watched[service]; !ok {
		go c.run(service)
	}

	// unlock the read lock
	c.RUnlock()

**//change is here**
	registryServices, err := get(service)
	if err == nil{
		return  registryServices, nil
	 }
         
	// get and return services
	return  c.cp(services), nil
}

**Comment by asim** [comment]
I can't decipher the code half pasted like this. In regard to your point. The caching could be more resilient but it also requires understanding the error types e.g if ErrNotfound it implies the registry failed to find the record. We need to know what a service discovery down error looks like.

**Comment by shikbupt** [comment]
> I can't decipher the code half pasted like this. In regard to your point. The caching could be more resilient but it also requires understanding the error types e.g if ErrNotfound it implies the registry failed to find the record. We need to know what a service discovery down error looks like.

ok, I understand. So we should define a uniform service discovery down error in the registry interface?

**Comment by asim** [comment]
Yes, something like ErrRegistryFailure or ErrConnFailure or similar. This would then need to be implemented across the registries to indicate there is a failure at that level.

**Comment by vtolstov** [comment]
i think that we need to control caching for example for some times i can use stale data, for some use-cases this is bad.
* change interface of Registry to returns error on NewRegistry (different issue)
* create ErrRegistryFailure in registry package, modify all registers to return this type in case of hard errors
* add option SelectOption to selector, that have ability to return stale data.

@asim @shikbupt what you think?

**Comment by asim** [comment]
I think what you're really talking about is a caching policy or algorithm which we need some way of configuring. The question is whether to preserve that data and filter at query time or just invalidate it. 

We should also add the ErrRegistryFailure error type.

**Comment by asim** [comment]
Any movement on this?

**Comment by vtolstov** [comment]
i want to do this after you publish your registry modifications (you close pr and say that open then it will be ready)
After that i can add new Error type, and after that add option to Selector. I can take this actions if that needed.

**Comment by asim** [comment]
Which modifications? I think the error type can probably be added right now.

**Comment by vtolstov** [comment]
this is problematic, for example NewRegistry don't return error , so we need to use log.Fatal or panic that both very bad for library.
We need first modify NewRegistry funcs to return error type too.
@asim what you say?

**Comment by vtolstov** [comment]
other workaround save some error in unexported struct and check it in all calls, if err not nil - return from all funcs ErrRegistryFailure. But this needs to use always mutex locking and recheck this variable always...

**Comment by asim** [comment]
We should probably convert all NewX functions to return an error if that's the case.

**Comment by vtolstov** [comment]
ok, i'm try to do that in own branch also create registry failure error and send pr
