### ISSUE TITLE
How to custom my own api-gateway use go-micro?

### ISSUE THREAD

**Issue by penglongli** [micro/go-micro#529]
For develop, there is simple to start api-gateway by the command:

```
$ micro api --registry consul --registry_address localhost:8500
```

I have these questions:
- For production enviroment, should i also use this way to start api-gateway?
- If i want to add authentication to api-gateway, how should id do it?

***
## i18n
在开发环境中，使用如下命令能很简单启动一个 api-gateway:
```
$ micro api --registry consul --registry_address localhost:8500
```
但是我有几个问题：
- 在生产环境，我也要用上述方式去启动 api-gateway 吗？
- 如果我想在 api-gateway 中加鉴权的话要怎么做？

**Comment by asim** [comment]
You can add auth and other plugins to the micro toolkit via its plugin api. Currently this requires you to rebuild the micro toolkit. See the plugins doc https://micro.mu/docs/runtime-plugins.html. We will support dynamic loading and an rpc based api in the future.
