### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by cooldog21** [micro/go-micro#530]
# github.com/micro/go-micro/registry/consul
src/github.com/micro/go-micro/registry/consul/watcher.go:47:33: cannot use cr.Client (type *"github.com/hashicorp/consul/api".Client) as type *"github.com/hashicorp/consul/vendor/github.com/hashicorp/consul/api".Client in argument to wp.RunWithClientAndLogger
src/github.com/micro/go-micro/registry/consul/watcher.go:212:37: cannot use cw.r.Client (type *"github.com/hashicorp/consul/api".Client) as type *"github.com/hashicorp/consul/vendor/github.com/hashicorp/consul/api".Client in argument to wp.RunWithClientAndLogger

**Comment by asim** [comment]
Duplicate of https://github.com/micro/go-micro/issues/527

**Comment by cooldog21** [comment]
thx
