### ISSUE TITLE
How to specify registry for client call?

### ISSUE THREAD

**Issue by seaguest** [micro/go-micro#531]
Hello,

I want to deploy my micro service on one machine, and call this service on several other machines (in the same local network).

I know the go-mico use consul as default registry, if I run the client code on the same machine with micro service, I get the correct response, but if I run on other machine, I got:
```
{"id":"go.micro.client","code":500,"detail":"error selecting test node: not found","status":"Internal Server Error"}
```
Here is my code:
```
package main

import (
	"common/logger"
	"context"
	"github.com/micro/go-micro"
	"github.com/micro/go-micro/registry"
	"micro/proto/cmn"
)

var cmnClient cmn.CmnService

func main() {
	reg := registry.NewRegistry(registry.Addrs("172.16.157.167:8500"))

	service := micro.NewService(micro.Registry(reg))
	c := service.Client()
	cmnClient = cmn.NewCmnService("cmn", c)

	logger.Error(IpArea("27.19.110.9"))
}

func IpArea(ip string) (string, string) {
	rsp, err := cmnClient.Area(context.TODO(), &cmn.IpAreaRequest{
		Ip: ip,
	})
	if err != nil {
		logger.Error(err)
		return "", ""
	}

	return rsp.AreaCode, rsp.Country
}
```

**Comment by lpxxn** [comment]
* the default registry has been changed to  mdns
https://github.com/micro/go-micro/blob/3f910038a3b9a0b50c227c7c68f43817455fff8c/registry/mdns_registry.go#L341

* you can change registry use [plugins registry](https://github.com/micro/go-plugins/tree/master/registry)

**Comment by seaguest** [comment]
@lpxxn 

I have installed avahi-daemon for mdns on all machines.
but still each machine can see its own service
```
micro --registry=mdns list services
```

Is there something missing here?

What I want is to make service available to other local machines, the simpler solution, the better.

**Comment by asim** [comment]
MDNS is multicast dns which requires support for multicast UDP at the network layer. If your machines do not support multicast on the network which many cloud environments do not then MDNS will not work beyond a single machine. We only invision MDNS to be a useful utility for single host zero dependency config where most development laptops run it by default.

If you would like multihost people use consul via --registry=consul or peer to peer gossip via --registry=gossip and specifying the seed node address to the rest of the nodes on the network via --registry_address flag

**Comment by seaguest** [comment]
@asim 

which is the default registry for go-micro?
I didn't run consul, but both my micro service and client call work.

I am not able to to find a proper example to specify consul address, specifying consul address seems not working in the following code:
```
package main

import (
	"common/logger"
	"context"
	"github.com/micro/go-micro"
	"github.com/micro/go-micro/registry"
	"github.com/micro/go-micro/registry/consul"
	"micro/proto/cmn"
)

var cmnClient cmn.CmnService

func main() {
	micro.Registry(consul.NewRegistry(func(op *registry.Options) {
		op.Addrs = []string{"172.16.194.193"}
	}))

	service := micro.NewService()
	c := service.Client()
	cmnClient = cmn.NewCmnService("cmn", c)

	logger.Error(IpArea("27.19.110.9"))
}

func IpArea(ip string) (string, string) {
	rsp, err := cmnClient.Area(context.TODO(), &cmn.IpAreaRequest{
		Ip: ip,
	})
	if err != nil {
		logger.Error(err)
		return "", ""
	}

	return rsp.AreaCode, rsp.Country
}

```

**Comment by seaguest** [comment]
Finally I made it work.

1, start consul 
```
consul agent -dev -client=0.0.0.0
```
2, start server
```
	reg := consul.NewRegistry(func(op *registry.Options) {
		op.Addrs = []string{"consul_ip"}
	})

	service := micro.NewService(micro.Registry(reg))

```
2, start clinet
```
	reg := consul.NewRegistry(func(op *registry.Options) {
		op.Addrs = []string{"consul_ip"}
	})

	service := micro.NewService(micro.Registry(reg))

```

then it works
