### ISSUE TITLE
Can a go-micro stream be like a grpc stream?

### ISSUE THREAD

**Issue by lockp111** [micro/go-micro#532]
go-micro stream must send then recv,but grpc not.
like this:
```go
go func() {
        for {
	    select {
		case <-ctx.Done():
		        log.Println("close...")
			return
		default:
			log.Println("send...")
			stream.Send(&steam.Request{
				Msg: time.Now().String(),
			})
		}
	}
}()

go func() {
	for {
		req, err := stream.Recv()
		if err != nil {
                         stream.Close()
			log.Println("err:", err)
                         cancel()
		}
		log.Println("recv:", req.Data)
	}
}()
```

**Comment by lpxxn** [comment]
yes go-micro can do this. 
[example](https://github.com/micro/examples/tree/master/stream)

**Comment by lockp111** [comment]
> yes go-micro can do this.
> [example](https://github.com/micro/examples/tree/master/stream)

Sorry,I don't think so.
I think you have never read the code.

**Comment by lpxxn** [comment]
???
Go-micro bidirectional stream processing steps is that
client-->connect to server
server or client -->  rev or send data 

the server side stream  function finished and  return ,  go-micro will send  EOF to client ,then the client close the stream;

**Comment by lockp111** [comment]
> ???
> Go-micro bidirectional stream processing steps is that
> client-->connect to server
> server or client --> rev or send data
> 
> the server side stream function finished and return , go-micro will send EOF to client ,then the client close the stream;

Do you know Recv() and Send() have lock?
**Please read the source code.**
If you receiving but nothing then you can not send anything.
That is the reason why I open this issue.

**Comment by lpxxn** [comment]
sorry i Misunderstanding it. i have read the source code.  the default stream Rev() and Send() have lock.
perhaps you can use the [grpc plugin](https://github.com/micro/go-plugins/tree/master/server/grpc) replace the default processing
it has no lock.  [grpc client](https://github.com/micro/go-plugins/blob/master/client/grpc/stream.go) and [grpc server](https://github.com/micro/go-plugins/blob/master/server/grpc/stream.go)

**Comment by asim** [comment]
As I see it the question is stating that that the rpc_stream.go code has a mutex around sending and receiving data. When Send is called, it locks the mutex. When Recv is called, it locks the mutex. There for only one or the other operation can be honoured at once. This essentially limits bidirectional streaming to the ability to process requests over the connection. Such that if Recv is blocking waiting for a response from the server nothing can be sent to the server. My assumption is the server code probably looks similar.

We could potentially remove the mutex lock but we may uncover some race conditions in the process. If anyone wants to perform this optimisation feel free to take a shot at it.

**Comment by lockp111** [comment]
> sorry i Misunderstanding it. i have read the source code. the default stream Rev() and Send() have lock.
> perhaps you can use the [grpc plugin](https://github.com/micro/go-plugins/tree/master/server/grpc) replace the default processing
> it has no lock. [grpc client](https://github.com/micro/go-plugins/blob/master/client/grpc/stream.go) and [grpc server](https://github.com/micro/go-plugins/blob/master/server/grpc/stream.go)

yes,but...my project inconvenient to use grpc.

**Comment by asim** [comment]
@lockp111 you have the choice of either using grpc for your requirements or submitting a PR to allow full duplex streaming in the rpc code. Feel free to do either. Otherwise, I'm closing this issue as your question is answered.
