### ISSUE TITLE
 github.com/micro/go-micro/registry/consul error

### ISSUE THREAD

**Issue by YouDail** [micro/go-micro#533]
when I build my process, it throwed these errors:

go get github.com/micro/go-micro
\# github.com/micro/go-micro/registry/consul
../../../micro/go-micro/registry/consul/watcher.go:47:33: cannot use cr.Client (type *"github.com/hashicorp/consul/api".Client) as type *"github.com/hashicorp/consul/vendor/github.com/hashicorp/consul/api".Client in argument to wp.RunWithClientAndLogger
../../../micro/go-micro/registry/consul/watcher.go:212:37: cannot use cw.r.Client (type *"github.com/hashicorp/consul/api".Client) as type *"github.com/hashicorp/consul/vendor/github.com/hashicorp/consul/api".Client in argument to wp.RunWithClientAndLogger
make: *** [deps] 错误 2

**Comment by asim** [comment]
Open issue here https://github.com/micro/go-micro/issues/527
