### ISSUE TITLE
marshal error when using google WellKnownTypes in proto

### ISSUE THREAD

**Issue by xmlking** [micro/go-micro#537]
I am using wrapper types (WellKnownTypes) from `google/protobuf/wrappers.proto` e.g., `google.protobuf.StringValue`, when calling my handler I am getting following error! 

Repo to reproduce: https://github.com/xmlking/micro-starter-kit
 
Error
```json
{
  "id": "go.micro.rpc",
  "code": 500,
  "detail": "error during request: json: cannot unmarshal string into Go struct field ProfileRequest.avatar of type wrappers.StringValue",
  "status": "Internal Server Error"
}
```

![image](https://user-images.githubusercontent.com/627951/59906728-4445b880-93be-11e9-8e2f-6fa331d66723.png)

**Comment by asim** [comment]
Answered here https://github.com/micro/go-plugins/issues/359
