### ISSUE TITLE
Draw pretty diagram

### ISSUE THREAD

**Issue by asim** [micro/go-micro#54]
Draw a diagram to demonstrate the interaction and flow between:
1. Registry aka service discovery
2. Server handler and registration
3. Client registry lookup and call
4. Request - Response
5. Pub Sub

**Comment by brasilikum** [comment]
Could you explain what you meant by that? Is it for documentation? I thought it would be cool to somehow visualize the currently available services dynamically. I guess this is unrelated?

**Comment by asim** [comment]
It was for documentation purposes.
