### ISSUE TITLE
Refine the whole project.

### ISSUE THREAD

**Issue by leaxoy** [micro/go-micro#545]
First, I think `micro` is a great project to simplify micro service develop. But there is a little trouble with lots of dependencies, it's spent lots of time to solve it. Like `consul`, `golint`, `testcontainers`, and `k8s`. 
I think we should extract this repo into multiply like:
- `core`, only include interface to define service, server, client, broker and so on, this should have few third dependencies.
- `micro-grpc`, include `client`, `server`, `transport` and `broker` which dep `core` and `grac`
- `micro-http`, same as `micro-grpc`, but only dep std/http
- `micro-rpc`, use `std/rpc`.
- `micro-middlewares`, lots of wrapper.

**Comment by asim** [comment]
Micro previously consisted of a core framework and separate repos for various concerns. We consolidated to one repo and a separate plugins repo only a month ago. It is very unlikely we split all these things. Think of go-micro as a standard library and framework for microservices.

The consistency issues you speak of may exist in go plugins at the moment but if you are using go mod then go-micro builds fine. If you want to maintain your own separate repos for plugins you should do so. We encourage that.
