### ISSUE TITLE
how to set password if using redis broker?

### ISSUE THREAD

**Issue by anotherGoogleFan** [micro/go-micro#549]
I only find way to set broker to redis by
```
MICRO_BROKER=redis,MICRO_BROKER_ADDRESS=127.0.0.1:6379
```
but redis need password to auth. How can I set redis password if I need to use redis to be my broker?

I searched the document and google but find nothing useful. Need help.

**Comment by asim** [comment]
Redis is not a broker in the defaults in go-micro. Please file the issue under go-plugins. This is currently not a supported feature. It may have to be something thats added to the broker address in url form.
