### ISSUE TITLE
how to get grpc client ip addr in go-micro

### ISSUE THREAD

**Issue by apptut** [micro/go-micro#550]
Hi, Sir:

I can get client ip by google grpc peer package when just code with the pure grpc service code :

```golang
peerAttr, ok := peer.FromContext(ctx)
if !ok {		
	return nil
}

host := peerAttr.Addr.String()
```
But after I migrated code to go-micro, now I can not get the ip addr through these code. Any help fixed this?

**Comment by asim** [comment]
This commit https://github.com/micro/go-micro/commit/d8e998ad85feac9288dd34dfb2dd75ce66bde6f4 will allow you to pull "Remote" field from the go-micro metadata or use grpc's PeerFromContext.

**Comment by hamidabdul1994** [comment]
I am not able to find client IP using above code.

**Comment by LLLLLancelot** [comment]
Hi, I can get correnct client addr from my service when requests are delivered through service[micro proxy].
but when the requests are delivered from [micro api]. I can only get the addr of service[micro api].The real addr is not visable. I wonder that how to get real client ip by anyhow.
Thank you, hope you can help me.
