### ISSUE TITLE
add micro service example

### ISSUE THREAD

**Issue by idoall** [micro/go-micro#551]
UserPowerManager open source:https://github.com/idoall/MicroService-UserPowerManager

Can I join this website?   https://micro.mu/docs/users.html

my website:https://mshk.top

**Comment by asim** [comment]
Users is limited companies. Please add a link to your example in the examples repo.

**Comment by idoall** [comment]
Can't we give individuals some opportunities? The examples are complete and can help many people.

**Comment by asim** [comment]
Examples readme contains a contents section where people can post their projects to other locations if they want. There's also an explorer https://micro.mu/explore/ for public projects on GitHub. The users page is not intended for anything being listing companies. Specifying individuals there doesn't really make any sense. It's like me asking the Go team to list go-micro on their website.

**Comment by idoall** [comment]
Okay, it's OK to join us. Thank you.



Now go micro is deployed to k8s because of the namespace problem. Is there a solution behind it?

**Comment by idoall** [comment]
https://micro.mu/explore/  Did you add it manually just now?
