### ISSUE TITLE
why does the registry_address not work ?

### ISSUE THREAD

**Issue by gaolv123tyu** [micro/go-micro#554]
when using  --registry_address 172.31.236.112:2181,it was still 127.0.0.1 .

**Comment by vtolstov** [comment]
what kind of registry used? what and how you run? we need more info

**Comment by xmlking** [comment]
not sure if this help , but in my case, when i am behind VPN, I will have two IP addresses assigned to my  NIC. I have force my service  to bind to `172` IP address to make it work

```bash
# MY_VPM_IP=$(ifconfig | grep 172 | awk '{print $2; exit}')
# go run srv/account/main.go srv/account/plugin.go --server_address=${MY_VPN_IP}:55011 --broker_address=${MY_VPN_IP}:55021
```


https://github.com/xmlking/micro-starter-kit#run

**Comment by gaolv123tyu** [comment]
> what kind of registry used? what and how you run? we need more info

my args is "--registry_address 172.31.236.112:2181 --registry zookeeper" , and the result message show me "2019/07/02 08:43:30 Failed to connect to 127.0.0.1:2181: dial tcp 127.0.0.1:2181: connect: connection refused
2019/07/02 08:43:30 zk: could not connect to a server" , this error I met when using  both micro web and go-micro .

**Comment by vtolstov** [comment]
this means that you don't init zookeper registry with this options (registry.Addrs)

**Comment by xmlking** [comment]
my case, i am using `mdns`

**Comment by asim** [comment]
Please file under go-plugins if still an issue as that's where the zookeeper registry lives
