### ISSUE TITLE
golang/lint dependency hell

### ISSUE THREAD

**Issue by Huholoman** [micro/go-micro#557]
Hello,
im importing go-micro, go-micro/broker and micro/go-plugins/broker/rabbitmq + something from standard library.

When I run `go build main.go` I get this output
```
$ go build main.go 
// some ok dependencies
go: github.com/golang/lint@v0.0.0-20190313153728-d0100b6bd8b3: parsing go.mod: unexpected module path "golang.org/x/lint"
go: github.com/testcontainers/testcontainer-go@v0.0.2: parsing go.mod: unexpected module path "github.com/testcontainers/testcontainers-go"
go: error loading module requirements
```

so I found a solution
```
replace github.com/golang/lint => golang.org/x/lint v0.0.0-20190409202823-959b441ac422
```

but as expected, it brough another problem, same problem with different packge, and again and again and I ended up with

 ```
$ go build main.go 
build command-line-arguments: cannot load github.com/hashicorp/consul/api: ambiguous import: found github.com/hashicorp/consul/api in multiple modules:
        github.com/hashicorp/consul v1.4.4 (/home/tobik/go/pkg/mod/github.com/hashicorp/consul@v1.4.4/api)
        github.com/hashicorp/consul/api v1.1.0 (/home/tobik/go/pkg/mod/github.com/hashicorp/consul/api@v1.1.0)
```

Now I have no Idea how to solve this problem.

I have go in version 1.12.6.

Any suggestions would be appriciated.

p.s. I believe Im doing something wrong, since all packages Im using are go-micro packages.

p.p.s. I am using `go modules`.

**Comment by hojulian** [comment]
try removing `go.mod` and `go.sum` then run `go get ./...`

**Comment by Huholoman** [comment]
Hello,
idk what happend, I just came back home, tried `go build` and I dont have this error anymore.

Anyway thank you for your time.
