### ISSUE TITLE
go get go-micro@v1.7.0 results in "ambiguous import"

### ISSUE THREAD

**Issue by GeorgeBills** [micro/go-micro#560]
go version go1.12.1 windows/amd64

$env:GO111MODULE is "on".

I `go get` the latest go-micro:

    PS C:\Users\george.bills\go\src\mygit.mycompany.local\myproduct\myproduct-server.git> go get github.com/micro/go-micro@v1.7.0
    go build github.com/hashicorp/consul/api: no Go files in

(sic) - "no Go files in" just ends there.

`go build` errors with "ambiguous import":

    PS C:\Users\george.bills\go\src\mygit.mycompany.local\myproduct\myproduct-server.git> go build ./...
    build mygit.mycompany.local/myproduct/myproduct-server.git: cannot load github.com/hashicorp/consul/api: ambiguous import: found github.com/hashicorp/consul/api in multiple modules:     
            github.com/hashicorp/consul v1.4.4 (C:\Users\george.bills\go\pkg\mod\github.com\hashicorp\consul@v1.4.4\api)
            github.com/hashicorp/consul/api v1.1.0 (C:\Users\george.bills\go\pkg\mod\github.com\hashicorp\consul\api@v1.1.0)

That seems to be related to this Consul issue - https://github.com/hashicorp/consul/issues/6019 - and their recommended fix is to use go.mod replace to pin the most recent Consul.

However the following replace line:

    replace github.com/hashicorp/consul => github.com/hashicorp/consul v1.5.2

Breaks the build with "cannot find module providing package hashicorp/consul/watch":

    PS C:\Users\george.bills\go\src\mygit.mycompany.local\myproduct\myproduct-server.git> go build ./...
    go: finding github.com/hashicorp/consul/watch latest
    build mygit.mycompany.local/myproduct/myproduct-server.git: cannot load github.com/hashicorp/consul/watch: cannot find module providing package github.com/hashicorp/consul/watch

The watch package was moved to be a subpackage of api as of Consul 1.5.0 - this is documented in the [Consul changelog](https://github.com/hashicorp/consul/blob/master/CHANGELOG.md#150-may-08-2019). micro/go-config source/consul/watcher.go is what's requiring that package.

Is there a way to get my project to build with the latest go-micro?

**Comment by vtolstov** [comment]
i'm try to contact hashicorp for such thing, because it really bad thing that we always have problems with consul

**Comment by vtolstov** [comment]
can you provide output of go env ?

**Comment by GeorgeBills** [comment]
```
PS C:\Users\george.bills\go\src\mygit.mycompany.local\myproduct\myproduct-server.git> go env
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\george.bills\AppData\Local\go-build
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Users\george.bills\go\
set GOPROXY=
set GORACE=
set GOROOT=C:\Go
set GOTMPDIR=
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++set CGO_ENABLED=1
set GOMOD=C:\Users\george.bills\go\src\mygit.mycompany.local\myproduct\myproduct-server.git\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\GEORGE~1.BIL\AppData\Local\Temp\go-build947503682=/tmp/go-build -gno-record-gcc-switches
```

**Comment by GeorgeBills** [comment]
In case it helps, I've run "[depth .](https://github.com/KyleBanks/depth)" on the project, and after lots of redacting to remove unrelated (?) lines I get:

```
mygit.mycompany.local/myproduct/myproduct-server.git
  - mygit.mycompany.local/myproduct/myproduct-server.git/internal/config
      - github.com/micro/go-config/source/consul
        - github.com/hashicorp/consul/api (unresolved)
        - github.com/hashicorp/consul/watch (unresolved)
      - github.com/micro/go-micro/registry/consul
        - github.com/hashicorp/consul/api
        - github.com/hashicorp/consul/watch
```

**Comment by GeorgeBills** [comment]
I think this issue was that one of my dependencies had a dependency on the (now deprecated) [micro/go-config](https://github.com/micro/go-config), which in turn had a dependency on a differing version of [hashicorp/consul/api](https://github.com/hashicorp/consul/api). It looks like the Hashicorp guys moved consul/api out from being a subpackage of the main Consul module and over to being a module in it's own right (see [consul/api/go.mod](https://github.com/hashicorp/consul/blob/master/api/go.mod)), and I'm reading "ambiguous import" as `go build` seeing one version of consul/api that's a subpackage and one version that's a full module.

Removing the transitive dependency on the deprecated micro/go-config has fixed this issue for me.
