### ISSUE TITLE
go-micro client build error for cannot find package "github.com/micro/go-micro/server/debug

### ISSUE THREAD

**Issue by gozelus** [micro/go-micro#562]
My project uses` go-vendor` to determine the package that is prompted when the build fails under the current vendor folder. 

I don't understand why the build failed. I am not familiar with the `go-mod `mechanism. This and I use `go-vendor` instead of `go-mod `related? 

thank you for your reply

**Comment by gozelus** [comment]
Supplement part of the compilation error log 

> vendor/github.com/micro/go-micro/server/debug.go:4:2: cannot find package "github.com/micro/go-micro/server/debug" in any of:
/go/src/fat-orange/capsule_api/vendor/github.com/micro/go-micro/server/debug (vendor tree)
/usr/local/go/src/github.com/micro/go-micro/server/debug (from $GOROOT)
/go/src/github.com/micro/go-micro/server/debug (from $GOPATH)

**Comment by asim** [comment]
Vendoring is likely store incompatible or old versions. You need to wipe the vendor directory.
