### ISSUE TITLE
GraphQL gateway

### ISSUE THREAD

**Issue by xmlking** [micro/go-micro#568]
like API Gateway , are there any GraphQL gateways, that work with go-micro gRPC microservices ?
please share any  recommended frameworks. if there is no perfect integratable solution,  is this something   go-micro team interested to build? 

![image](https://user-images.githubusercontent.com/627951/60758798-415ae280-9fd0-11e9-839a-53e7c836efbe.png)

**Comment by vtolstov** [comment]
As i know nobody write fully worked solution that works out of the box.

**Comment by asim** [comment]
You could probably write a graphql codec or API handler that does this. We don't have support for it right now. It's something we'd ask community support for as opposed to doing ourselves in the immediate future.
