### ISSUE TITLE
Mdns has serious performance problems

### ISSUE THREAD

**Issue by fananchong** [micro/go-micro#572]
I have 2 services on Windows 10. The mdns are used. It won’t be long before it will be very Caton.
Below is the performance report fetched with pprof ：
[mdns.pdf](https://github.com/micro/go-micro/files/3372620/mdns.pdf)

**Comment by asim** [comment]
Maybe switch to a different registry? Or help optimise the mdns registry? We're essentially using a fork of hashicorp/mdns. Our focus is to provide plugins for various systems, we don't implement these directly. You are free to chose a different service discovery mechanism.

**Comment by vtolstov** [comment]
@fananchong i'm plan to publish rewritten mdns registry, and it performance must be better.
How much services in network? And do you have any other mdns capable servers in your network?

**Comment by fananchong** [comment]
There is no such problem in linux

**Comment by fananchong** [comment]
I found the reason :  https://github.com/micro/mdns/issues/18
