### ISSUE TITLE
Is there any way to receive metadata by go-micro's gRPC client?

### ISSUE THREAD

**Issue by mileschao** [micro/go-micro#574]
Hi, @asim  , thank you for your excellent job!
Is there any way to receive **metadata** from server side  by go-mirco's gRPC client?

I've notice the gRPC's document on [gRPC-metadata](https://github.com/grpc/grpc-go/blob/master/Documentation/grpc-metadata.md)
```go
var header, trailer metadata.MD // variable to store header and trailer
r, err := client.SomeRPC(
    ctx,
    someRequest,
    grpc.Header(&header),    // will retrieve header
    grpc.Trailer(&trailer),  // will retrieve trailer
)

```

But, It seems there is no option on go-micro's  [gRPC Invoke](https://github.com/micro/go-micro/blob/97282a5377938e2e44b50c338ade770a449f39ae/client/grpc/grpc.go#L130)
```go
go func() {
		err := cc.Invoke(ctx, methodToGRPC(req.Service(), req.Endpoint()), req.Body(), rsp, grpc.ForceCodec(cf))
		ch <- microError(err)
	}()
```
Any thing wrong?
It would be appreciated if you could answer.

**Comment by asim** [comment]
There is no way to retrieve metadata sent by the server. Feel free to PR a way to do so if you feel its appropriate. We've otherwise not had requests for this feature.

**Comment by sixhuan** [comment]
> Hi, @asim , thank you for your excellent job!
> Is there any way to receive **metadata** from server side by go-mirco's gRPC client?
> 
> I've notice the gRPC's document on [gRPC-metadata](https://github.com/grpc/grpc-go/blob/master/Documentation/grpc-metadata.md)
> 
> ```go
> var header, trailer metadata.MD // variable to store header and trailer
> r, err := client.SomeRPC(
>     ctx,
>     someRequest,
>     grpc.Header(&header),    // will retrieve header
>     grpc.Trailer(&trailer),  // will retrieve trailer
> )
> ```
> 
> But, It seems there is no option on go-micro's [gRPC Invoke](https://github.com/micro/go-micro/blob/97282a5377938e2e44b50c338ade770a449f39ae/client/grpc/grpc.go#L130)
> 
> ```go
> go func() {
> 		err := cc.Invoke(ctx, methodToGRPC(req.Service(), req.Endpoint()), req.Body(), rsp, grpc.ForceCodec(cf))
> 		ch <- microError(err)
> 	}()
> ```
> 
> Any thing wrong?
> It would be appreciated if you could answer.



> Hi, @asim , thank you for your excellent job!
> Is there any way to receive **metadata** from server side by go-mirco's gRPC client?
> 
> I've notice the gRPC's document on [gRPC-metadata](https://github.com/grpc/grpc-go/blob/master/Documentation/grpc-metadata.md)
> 
> ```go
> var header, trailer metadata.MD // variable to store header and trailer
> r, err := client.SomeRPC(
>     ctx,
>     someRequest,
>     grpc.Header(&header),    // will retrieve header
>     grpc.Trailer(&trailer),  // will retrieve trailer
> )
> ```
> 
> But, It seems there is no option on go-micro's [gRPC Invoke](https://github.com/micro/go-micro/blob/97282a5377938e2e44b50c338ade770a449f39ae/client/grpc/grpc.go#L130)
> 
> ```go
> go func() {
> 		err := cc.Invoke(ctx, methodToGRPC(req.Service(), req.Endpoint()), req.Body(), rsp, grpc.ForceCodec(cf))
> 		ch <- microError(err)
> 	}()
> ```
> 
> Any thing wrong?
> It would be appreciated if you could answer.

Hi mileschao , I meet this question too.   How do you handle this problem finally?
