### ISSUE TITLE
github.com/micro/go-micro/selector not found

### ISSUE THREAD

**Issue by 7x7x7eq51** [micro/go-micro#588]
```bash
../../../../github.com/micro/util/go/lib/http/http.go:7:2: cannot find package "github.com/micro/go-micro/selector" in any of:
        /usr/local/go/src/github.com/micro/go-micro/selector (from $GOROOT)
        /home/tpt/Go/src/github.com/micro/go-micro/selector (from $GOPATH

```
Please help me!
I have been updated newest!

**Comment by vtolstov** [comment]
don't use micro/util package anymore. it archived.
@asim can we move/drop this older repos? I think that users of this repos may have problems for long time...

**Comment by 7x7x7eq51** [comment]
When 
```bash
go get -v
# or 
go mod download
```
Show this error when 
```bash
go run main.go
```

> don't use micro/util package anymore

It's package default when i get

**Comment by asim** [comment]
Please run go get -u

**Comment by reyvababtista** [comment]
I have the same issue here. Tried to run `go get -u github.com/micro/go-micro/selector ` and still produces same error result.

**Comment by vtolstov** [comment]
run go get -u
and check that you code not imports github.com/micro/go-micro/selector bacuse path is changed to github.com/micro/go-micro/client/selector

**Comment by reyvababtista** [comment]
The one's importing go-micro/selector is http library from micro/util which called by go-web lib which called by Gin lib. I was just following API using Gin examples given in the repo. Currently fixed the issue myself by renaming import syntax from go-micro/selector to go-micro/client/selector. Is there any updates from the go-micro developers regarding to this fix?

**Comment by vtolstov** [comment]
don't use micro/util, use github.com/micro/go-micro/util instead
@asim i think that we need to drop old repos. more then one a week we have this questions...

**Comment by vtolstov** [comment]
another case - drop repo contents, and create submodule that points to go-micro repo dir, but i don't check this case.

**Comment by 7x7x7eq51** [comment]
Umm! Should clear all archived repo!
Thanks all, i have fixed too.

**Comment by milosgajdos** [comment]
Thanks for the heads up. We’re closing this issue now.
