### ISSUE TITLE
go: github.com/nats-io/nats.go@v1.8.2-0.20190607221125-9f4d16fe7c2d: unknown revision 9f4d16fe7c2d

### ISSUE THREAD

**Issue by calentang** [micro/go-micro#589]
hello, guys!

i am a new learner for go-micro.when i fllow this guid https://micro.mu/docs/install-guide.html doing this command 'go get github.com/micro/examples/greeter/srv && srv
' , i get this error:
go: finding github.com/micro/examples/greeter/srv latest
go: finding github.com/micro/examples/greeter latest
go: finding github.com/nats-io/nats.go v1.8.2-0.20190607221125-9f4d16fe7c2d
go: github.com/nats-io/nats.go@v1.8.2-0.20190607221125-9f4d16fe7c2d: unknown revision 9f4d16fe7c2d
go: error loading module requirements

may be the version error?

**Comment by wallyqs** [comment]
I believe this has been in master, see also: https://github.com/nats-io/nats.go/issues/493

**Comment by milosgajdos** [comment]
I believe this has been fixed in https://github.com/micro/examples/pull/75 

Feel free to re-open the issue if you still have problems getting the dependency.
