### ISSUE TITLE
register service error  too many colons in address

### ISSUE THREAD

**Issue by leeson1995** [micro/go-micro#593]
Server go.micro.srv.account-bd38633c-bed9-4b33-a93a-c44fcb6d8c9c register error: address fe80::8df9:4308:4a19:829b:49485: too many colons in address
![image](https://user-images.githubusercontent.com/48010956/61344619-785cae00-a884-11e9-90f2-2d366a07cdf5.png)
![image](https://user-images.githubusercontent.com/48010956/61344653-988c6d00-a884-11e9-99dd-181fabfd62c1.png)

pls help ~

**Comment by vtolstov** [comment]
Micro does not support currently ipv6 addresses, please you ipv4

**Comment by leeson1995** [comment]
The address is assigned by default. How can I switch to ipv4 @vtolstov

**Comment by vtolstov** [comment]
check do you have some internal ipv4 addresses on you box.

**Comment by vtolstov** [comment]
@leeson1995 after #594 was merged may be some of issues with ipv6 only fixed.
