### ISSUE TITLE
Register error: Failed to join multicast group on all interfaces !

### ISSUE THREAD

**Issue by techbro76** [micro/go-micro#597]
I am running the consul discovery service as needed, however when creating even an example service I get thrown the following message in the console.

Server go.micro.srv.hello-151a8cbb-bab6-4a61-88f9-08bca64b4259 register error: Failed to join multicast group on all interfaces!

I don't know if its a consul problem with registering on the network or something to do with the service.

**Comment by vtolstov** [comment]
this issue comes from fact, that go-micro initialize defaults for registry, and default registry is mdns. When you import registry package you always have mdns registry. And if it can't start this error happens.

**Comment by milosgajdos** [comment]
@djboboch if you want to use `consul` registry you need to explicitly "request" it by setting `MICRO_REGISTRY=consul` environment variable. Otherwise the default registry is used like @vtolstov says.

**Comment by techbro76** [comment]
Thank you setting the variables and restarting the machines has solved the problem.
