### ISSUE TITLE
Client stream does not support selector

### ISSUE THREAD

**Issue by fananchong** [micro/go-micro#599]

**Comment by asim** [comment]
This is not a very helpful title. Please provide more info.

**Comment by fananchong** [comment]
I see begin Stream ，have select node:
```go
func (r *rpcClient) Stream(ctx context.Context, request Request, opts ...CallOption) (Stream, error) {
	// make a copy of call opts
	callOpts := r.opts.CallOptions
	for _, opt := range opts {
		opt(&callOpts)
	}

	next, err := r.next(request, callOpts)
	if err != nil {
		return nil, err
	}
        ...
```
but , how I can in stream handler function， send one msg to other stream obj

**Comment by asim** [comment]
The stream is created by connecting to a node. To one node. We use the selector to find that node. See the next method for that call to the selector. The stream has Send/Recv methods to talk to that node. If you're expecting to send messages to all nodes you need to call Publish.
