### ISSUE TITLE
Cannot registering services

### ISSUE THREAD

**Issue by reyvababtista** [micro/go-micro#600]
Hello. First of all, thank you for this awesome library.

I have difficulties on executing `micro api` and registering it's services. It always stuck on `Registering node:..` but when I run `micro list services`, it returns empty. Tried to register the services into Consul, still stuck.

Here are my environment definition:
- Oracle Linux 6.10
- Consul v1.5.2
- Micro v1.7.0
- Go v1.11.5 linux/amd64

I am pretty sure the problem lays on my environment, but I have no idea which part cause the problem. I tried to run the same exact code in my macOS, and it runs smoothly. Can anybody help me pointing out the problem? Thank you.

**Comment by milosgajdos** [comment]
Could you give us a list of commands you run so we get a better idea of what's happening?

**Comment by reyvababtista** [comment]
> Could you give us a list of commands you run so we get a better idea of what's happening?

run
`micro api --handler api --address localhost:8081`

output
```
2019/07/20 12:18:10 Registering RPC Handler at /rpc
2019/07/20 12:18:10 Registering API Request Handler at /
2019/07/20 12:18:10 HTTP API Listening on 127.0.0.1:8081
2019/07/20 12:18:10 Transport [http] Listening on [::]:29856
2019/07/20 12:18:10 Broker [http] Connected to [::]:36032
2019/07/20 12:18:10 Registry [mdns] Registering node: go.micro.api-f8d4c268-1522-43a5-808f-8e66eb45768d
```

run
`go run srv/main.go`

output
```
2019/07/20 12:08:34 Transport [http] Listening on [::]:24562
2019/07/20 12:08:34 Broker [http] Connected to [::]:62026
2019/07/20 12:08:34 Registry [mdns] Registering node: go.micro.srv.shell-e153778e-3552-4a1b-b779-1a43af43a4dc
```

run
`go run api/api.go`

output
```
2019/07/20 12:09:16 Transport [http] Listening on [::]:18683
2019/07/20 12:09:16 Broker [http] Connected to [::]:34131
2019/07/20 12:09:16 Registry [mdns] Registering node: go.micro.api.shell-712d1db4-dffb-46bf-8388-aafa4630d0ed
```

Both `api.go` and `main.go` are simple microservices as written in repo's greeter examples.

run
`micro list services`

output
`*empty*`

**Comment by milosgajdos** [comment]
Very strange, I've done the exact same thing myself and everything seems to be working fine for me 


API gateway:
```shell
$ micro api --handler api --address localhost:8081
2019/07/20 13:50:28 Registering RPC Handler at /rpc
2019/07/20 13:50:28 Registering API Request Handler at /
2019/07/20 13:50:28 HTTP API Listening on 127.0.0.1:8081
2019/07/20 13:50:28 Transport [http] Listening on [::]:62553
2019/07/20 13:50:28 Broker [http] Connected to [::]:62554
2019/07/20 13:50:28 Registry [mdns] Registering node: go.micro.api-705c3f42-705d-4f89-b590-8f506ebfa9c8
```

Micro service:
```shell
$ go run main.go
2019/07/20 13:50:49 Transport [http] Listening on [::]:62561
2019/07/20 13:50:49 Broker [http] Connected to [::]:62562
2019/07/20 13:50:49 Registry [mdns] Registering node: go.micro.srv.blob-20f4efbd-c1fe-4e1b-9b10-f3442f1fe8b5
```

List services:
```shell
$ micro list services
go.micro.api
go.micro.srv.blob
```

Which makes me think....what version of `micro` are you using? I'm using the latest one:
```shell
$ micro --version
micro version 1.7.0
```

Have you tried running the same example using `consul` for service registry instead of the default `mdns` registry?

**Comment by reyvababtista** [comment]
> Which makes me think....what version of `micro` are you using? I'm using the latest one:
> Have you tried running the same example using `consul` for service registry instead of the default `mdns` registry?

The answers for both of your questions are in [my first comment](https://github.com/micro/go-micro/issues/600#issue-470126070).

**Comment by asim** [comment]
If you believe you need to be using consul then please specify MICRO_REGISTRY=consul to all commands or export it. If your consul agent is bound to a specific address please specify MICRO_REGISTRY_ADDRESS env var also.

**Comment by milosgajdos** [comment]
@reyvababtista you are right. I'm sorry, somewhere trying to think of possible scenario I forgot you had already mentioned them in the first update.

If the `mdns` registry does not work for you please try doing what @asim suggest wrt `consul` and paste the results here please.

**Comment by asim** [comment]
Considering the first comment related to the fact that consul is running the obvious fix is specifying MICRO_REGISTRY=consul. Closing as this should be fairly straightforward.

**Comment by reyvababtista** [comment]
> If you believe you need to be using consul then please specify MICRO_REGISTRY=consul to all commands or export it. If your consul agent is bound to a specific address please specify MICRO_REGISTRY_ADDRESS env var also.

> If the `mdns` registry does not work for you please try doing what @asim suggest wrt `consul` and paste the results here please.

What I mean by 
> Tried to register the services into Consul, still stuck.

in my first comment is running exact comments written [here](https://github.com/micro/go-micro/issues/600#issuecomment-513436862), added with `--registry=consul`, but still no luck.

I've executed **the same commands** either with `Consul` or `mdns` **in my macOS** and **it's running smoothly**. So I'm sure it's not my command nor my script that cause the problem. I need help to defining problem that is why I open this issue. @asim @milosgajdos83

**Comment by asim** [comment]
This is more so a debugging issue with your environment rather than an issue with micro. If your service can't reach consul or you specify an incorrect address it will block.

**Comment by buddingleader** [comment]
Amazingly, this is also the case with my running example
![image](https://user-images.githubusercontent.com/35793667/76484056-b762f380-6453-11ea-9d1f-3ba65aac3236.png)
So, how should I locate this problem？
Looking forward to someone reply。

**Comment by buddingleader** [comment]
server code:
```
package main

import (
	"context"
	"fmt"

	proto "github.com/rabbit/greeter/proto"
	micro "github.com/micro/go-micro/v2"
)

type Greeter struct{}

func (g *Greeter) Hello(ctx context.Context, req *proto.Request, rsp *proto.Response) error {
	rsp.Greeting = "Hello " + req.Name
	return nil
}

func main() {
	// Create a new service. Optionally include some options here.
	service := micro.NewService(
		micro.Name("greeter"),
	)

	// Init will parse the command line flags.
	service.Init()

	// Register handler
	proto.RegisterGreeterHandler(service.Server(), new(Greeter))

	// Run the server
	if err := service.Run(); err != nil {
		fmt.Println(err)
	}
}
```

**Comment by buddingleader** [comment]
client code:
```
package main

import (
	"context"
	"fmt"

	proto "github.com/rabbit/greeter/proto"
	micro "github.com/micro/go-micro/v2"
)

func main() {
	// Create a new service
	service := micro.NewService(micro.Name("greeter.client"))
	// Initialise the client and parse command line flags
	service.Init()

	// Create new greeter client
	greeter := proto.NewGreeterService("greeter", service.Client())

	// Call the greeter
	rsp, err := greeter.Hello(context.TODO(), &proto.Request{Name: "John"})
	if err != nil {
		fmt.Println(err)
	}

	// Print response
	fmt.Println(rsp.Greeting)
}

```

**Comment by vtolstov** [comment]
@buddingleader i'm try to run go-examples/service example (modified to use /v2 micro) and it works fine. Please check it.

**Comment by JoyCood** [comment]
i use v4, and run command: ```micro run . --name helloworld```, but ```micro services``` not list the helloworld service here, when run ```go run .```, the service can start success, but also cannot list with ```micro services``` command, 

os: ```mac os m1```
go version: ```go version go1.20.11 darwin/amd64```
protobuf: ```libprotoc 25.1```
etcd version: ```etcd Version: 3.5.9```
micro version:  ```micro version v4.3.1```

```micro status``` output:
```
knight@knightdeMacBook-Pro helloworld % micro status         

2023/11/23 12:09:25 /home/runner/go/pkg/mod/gorm.io/gorm@v1.24.1-0.20221019064659-5dd2bb482755/gorm.go:206
[error] failed to initialize database, got error Binary was compiled with 'CGO_ENABLED=0', go-sqlite3 requires cgo to work. This is a stub
NAME		VERSION	SOURCE					STATUS	BUILD	UPDATED		METADATA
helloworld	latest	/Users/knight/Projects/y/helloworld	error	n/a	1h2m31s ago	owner=admin, group=micro, error=n/a
```

 code :
```
package main

import (
	"github.com/go-micro/plugins/v4/registry/etcd"
	"go-micro.dev/v4"
	"go-micro.dev/v4/logger"
	"helloworld/handler"
	pb "helloworld/proto"
)


func main() {
	// Create service
	reg := etcd.NewRegistry()
	srv := micro.NewService(
		micro.Name("helloworld"),
		micro.Address(":9090"),
		micro.Registry(reg),
	)

	// Register handler
	pb.RegisterHelloworldHandler(srv.Server(), handler.New())

	// Run service
	if err := srv.Run(); err != nil {
		logger.Fatal(err)
	}
}

```

**Comment by jochumdev** [comment]
@JoyCood please don't cross-post.
