### ISSUE TITLE
Rpc server has performance issues

### ISSUE THREAD

**Issue by fananchong** [micro/go-micro#602]
I see that the rpc server sends a message in receive data coroutine ServeConn , which has two problems:
1. The coroutine will be blocked when sending a message
2. Cannot merge packets to send, each package will have RTT

**Comment by asim** [comment]
The server ServeConn method is passed into the transport Accept method which creates a separate go routine per connection. Any blocking on a per connection basis is a design constraint. If you'd like to provide support for any enhancements please feel free to create an issue in the development repo to start a discussion around it with any further details on what you mean.
