### ISSUE TITLE
Is there any way to handle muiltiple router in one service?

### ISSUE THREAD

**Issue by MXWXZ** [micro/go-micro#603]
Hi, I'm study go micro recently. Now I'm handling api with Gin just like `examples/greeter/api/gin` and it works well.

But I noticed that I can only register one service in a single main file, thus I can only handle one router one time. For the example in `examples/greeter/api/gin`, the service name is `go.micro.srv.greeter` and gin router `/greeter` `/greeter/:name` can work well, but I just want another router like `/another`. Because the api mapped `go.micro.srv.greeter` to `/greeter`, I get 500 when I access `/another`.

I've tried using go routine to create another service like
```
go func(){
		if err := service.Run(); err != nil {
			log.Fatal(err)
		}
	}()
```
for the first service and 
```
if err := service2.Run(); err != nil {
		log.Fatal(err)
	}
```
for the second. It failed and I could only find one service in consul.

So my question is can I handle 2 or more routers in one service using gin? Or the only way is to create another service in another file. Thanks a lot!

**Comment by asim** [comment]
We do not support running multiple services in one process. This is not how microservices are designed to operate. We do not support sending multiple paths to a single service either. The breakdown in paths is related to a separation in responsibilties. You may want to aggregate this functionality elsewhere or use a different method for doing it. There's no plans as of yet to support multiple paths in a single service.
