### ISSUE TITLE
Consul registry broken after upstream update in hashicorp/go-cleanhttp

### ISSUE THREAD

**Issue by boyand** [micro/go-micro#61]
[This commit](https://github.com/hashicorp/go-cleanhttp/commit/875fb671b3ddc66f8e2f0acc33829c8cb989a38d) breaks the consul registration and makes services panic right after startup. 

Details:
We are using latest version of consul running as 3 node cluster on K8s. The consul cluster is exposed as a K8S_SERVICE to our micro services. The error we get is: 
Unexpected response code: 500 (CheckID does not have associated TTL)

**Comment by asim** [comment]
What's the method for reproducing the issue? I cannot reproduce this locally.

**Comment by boyand** [comment]
I am closing this. The issue was actually that the consul client was not the latest version
