### ISSUE TITLE
[bug] go get -u github.com/micro/go-micro/ error

### ISSUE THREAD

**Issue by DuckulaGL** [micro/go-micro#612]
command: go get -u github.com/micro/go-micro/

output errors:
GoWork/src/github.com/micro/go-micro/registry/consul/watcher.go:48:33: cannot use cr.Client (type *"github.com/hashicorp/consul/api".Client) as type *"github.com/hashicorp/consul/vendor/github.com/hashicorp/consul/api".Client in argument to wp.RunWithClientAndLogger
GoWork/src/github.com/micro/go-micro/registry/consul/watcher.go:212:37: cannot use cw.r.Client (type *"github.com/hashicorp/consul/api".Client) as type *"github.com/hashicorp/consul/vendor/github.com/hashicorp/consul/api".Client in argument to wp.RunWithClientAndLogger

**Comment by milosgajdos** [comment]
Are you using `go mod` @DuckulaGL?

**Comment by DuckulaGL** [comment]
I`m not using go mod

**Comment by milosgajdos** [comment]
@DuckulaGL can you please try `go get` with Go modules turned on? It will be on by default in the next `go` release so we're switching to it:

```
export GO111MODULE=on
go get -u github.com/micro/go-micro
```

**Comment by DuckulaGL** [comment]
thank you
