### ISSUE TITLE
[bug] go get -u github.com/micro/micro error

### ISSUE THREAD

**Issue by DuckulaGL** [micro/go-micro#613]
command: go get -u github.com/micro/micro

output errors:
GoWork/src/github.com/micro/micro/router/router.go:197:19: cannot use &handler.Router literal (type *handler.Router) as type "github.com/micro/go-micro/network/router/proto".RouterHandler in argument to "github.com/micro/go-micro/network/router/proto".RegisterRouterHandler:
	*handler.Router does not implement "github.com/micro/go-micro/network/router/proto".RouterHandler (missing Advertise method)

**Comment by milosgajdos** [comment]
Can you paste output of `go version` here, please? Also, again, do you have `go mod`ules turned on?

**Comment by DuckulaGL** [comment]
➜  ~ go version
go version go1.12.7 darwin/amd64

**Comment by milosgajdos** [comment]
This is a duplicate of https://github.com/micro/micro/issues/297. Let's track it in `micro/micro` not in `go-micro`.
