### ISSUE TITLE
Does go-micro support yaml reader?

### ISSUE THREAD

**Issue by nuczzz** [micro/go-micro#614]
I want to get yaml data from consul, but I just found json reader in go-micro/config/reader. How can I get yaml or other format data from consul with go-micro? thanks.

**Comment by milosgajdos** [comment]
Right now we only provide `json` reader, but it should not be hard to convert between `json` and `yaml` since `yaml` is a superset of `json` data format.

We would of course welcome PR.

**Comment by asim** [comment]
You can pass yaml encoder to the source https://micro.mu/docs/go-config.html#set-source-encoder

We support multiple encoders. The reader is just for reading the merged sources

**Comment by nuczzz** [comment]
It works after add yaml encoder, thanks very much.
```
e := yaml.NewEncoder()

s := consul.NewSource(
	source.WithEncoder(e),
)
```

**Comment by ryanrain2016** [comment]
It does not work in v4.
