### ISSUE TITLE
请问大神用new生成的api模板都有什么功能呢

### ISSUE THREAD

**Issue by SkyWingZhang** [micro/go-micro#619]
没有文档，看不懂喔。例子又不是用micro new生成的

**Comment by milosgajdos** [comment]
Pinging @printfcoder :-)

**Comment by printfcoder** [comment]
@milosgajdos83 pong
@SkyWingZhang 我们有中文示例，请翻阅下方链接：

[micro new](https://github.com/micro-in-cn/all-in-one/tree/master/middle-practices/micro-new)

**Comment by milosgajdos** [comment]
Thanks @printfcoder 

Can we close this issue and maybe move somewhere to https://github.com/micro-in-cn or do you want carry on tracking it here?

**Comment by printfcoder** [comment]
@milosgajdos83 yes, we can close it.
@SkyWingZhang 我们先关闭这些问题了，如果有其它问题可以继续提或者到中文站去提，我们都会尽快回复

**Comment by SkyWingZhang** [comment]
为什么产生的proto文件在handler文件中引入路径为path/to/service/proto/xxxx，这个文档对于api的解析不是很清晰。也可能自身技术有限

**Comment by printfcoder** [comment]
@SkyWingZhang 不是很清楚您的问题，如果是指protoc生成的文件，那么其实不用关心这个，protoc指令生成的文件是相对的，都是基于go包引入风格，建议多尝试几下，这一部分和go-micro是无关的。

如果可以，请移步到中文站去开问题，这里适合英文，因为可能有同样问题的朋友，这样能帮到他们。

**Comment by SkyWingZhang** [comment]
![1564369848(1)](https://user-images.githubusercontent.com/49492372/62019470-91a11b00-b1f1-11e9-9d56-fabd39b55900.png)
我用命令micro new --type=api ./项目名/intend-api  创建了一个api，但是在生成的handler/intend.go中引入路径为path/to/service/proto/intend.proto，对于路径path/to/service/不是很理解。好的。非常感谢，我以后都会在micro中文站提交，谢谢告知有中文站点

**Comment by codlin** [comment]
@SkyWingZhang 这个我猜测是因为模板并不知道具体你需要使用哪个service，因此需要你自己根据实际情况来修改。

**Comment by SkyWingZhang** [comment]
恩恩。但是我改为正确路径后，编译运行会发生找不到proto的错误信息，但是，在编译器中并没有显示错误的信息，只是标红。是否在路径中把proto当成了一个独立的私有包。怎么解决呢。
![TIM图片20190729171334](https://user-images.githubusercontent.com/49492372/62036369-45bb9980-b224-11e9-9cc7-5d02f080836f.png)
![TIM图片20190729171330](https://user-images.githubusercontent.com/49492372/62036377-49e7b700-b224-11e9-9e6e-76e67b62703e.png)
![TIM图片20190729171339](https://user-images.githubusercontent.com/49492372/62036383-4c4a1100-b224-11e9-9082-c6ac61dbc27e.png)

**Comment by milosgajdos** [comment]
@printfcoder Let's move this to https://github.com/micro-in-cn. I'm closing this now.

**Comment by printfcoder** [comment]
@SkyWingZhang Hi，抱歉回复比较晚，我给到的文档是基于7月19号之前的版本，之后的模板生成的文件有些许改动，也就是您提到的'path/to/service'的问题。

看上去目录和文件没什么问题，是不是Goland的go mod没配置好

**Comment by SkyWingZhang** [comment]
![4(R07O}EGB$V{T4~10`X)UR](https://user-images.githubusercontent.com/49492372/62097297-ef4c6a80-b2b8-11e9-8535-a04e1b406d5d.png)
哈哈，大神很有礼貌。设置了mod为no。
请问下大神，new生成api中proto中的文件，使用go.api.Request还是自定义Request，如下图
![4%BA @OTU~7}Y0G9BEE(P_1](https://user-images.githubusercontent.com/49492372/62098947-00987580-b2bf-11e9-8246-1482b8867cba.png)

**Comment by printfcoder** [comment]
生成的这里有个bug，应该要用go-micro的api，不能自定义，go-api风格的接口定义了Method，Path，Header等等，是服务端接口解析时彼此遵循的风格，可理解为协议。

**Comment by entere** [comment]
micro new api 用于暴露的API服务

micro api 启动后  通过http入口可以访问到暴露的API服务

**Comment by SkyWingZhang** [comment]
> micro new api 用于暴露的API服务
> 
> micro api 启动后 通过http入口可以访问到暴露的API服务

楼上回答刚好解答我今天的疑惑，之前一直用web模板，因为前后端分离，想使用api模板，但是和micro概念未能分清纠结了一早上。但是，请问各位，api模板是否不能使用consul来服务发现，go mod get回来的go-micro未有consul包,自己尝试修改go-micro版本为v1.9.1，提示
verifying github.com/lucas-clemente/quic-go@v0.12.0: checksum mismatch
        downloaded: h1:dYHUyB50gEQlK3KqytmNySzuyzAcaQ3iuI2ZReAfVrE=
        sum.golang.org: h1:TRbvZ6F++sofeGbh+Z2IIyIOhl8KyGnYuA06g2yrHdI=

死活拉不下来
