### ISSUE TITLE
Consul warning: WARN Service tag "..." will not be discoverable via DNS due to invalid characters. Valid characters include all alpha-numerics and dashes.

### ISSUE THREAD

**Issue by asim** [micro/go-micro#62]
This is a warning but an issue people continually bring up. Fix this so it no longer occurs. Most likely requiring encoding of tag values using gzip and hex.

**Comment by basilex** [comment]
Hi!
Very quickly regarding the topic issue:
github.com/micro/go-micro/registry/consul_registry.go

[consul_registry.go.diff.gz](https://github.com/micro/go-micro/files/176173/consul_registry.go.diff.gz)

Probably we've to implement according to rfc2782?
Here's details: https://www.consul.io/docs/agent/dns.html

Alex

**Comment by basilex** [comment]
Hi!
Very quickly regarding the topic issue:
github.com/micro/go-micro/registry/consul_registry.go

Probably we've to implement according to rfc2782?
Here's details: https://www.consul.io/docs/agent/dns.html https://www.consul.io/docs/agent/dns.html
Alex

**Comment by asim** [comment]
The only comment Consul provides on this is that tags are opaque strings and must be of the alpha-numeric format. Converting to hex is probably going to be the easiest solution. I welcome any more appropriate solutions to convert JSON to something of a valid format.

**Comment by asim** [comment]
https://github.com/micro/go-micro/pull/63

**Comment by asim** [comment]
https://github.com/micro/go-micro/pull/63 now merged. Next step will be to stop registering old encoding entirely, while still decoding them if they exist. That should completely remove the warnings but will be the point at which any old service cannot read new services.

**Comment by asim** [comment]
It's been sometime since the encoding fix was merged. In the next few weeks I will strip the old encoding so it removes the warnings.

**Comment by asim** [comment]
now stripped https://github.com/micro/go-micro/commit/06ee80fd0a9594fc38e68d16d2e7a7e9b2ed0ecf
