### ISSUE TITLE
Documentation is contradictory

### ISSUE THREAD

**Issue by PeterBocan** [micro/go-micro#622]
The [documentation](https://micro.mu/docs/go-micro.html#service-discovery) seems broken to me, on one hand:

> ## Service Discovery
> ...
> The **default discovery system is multicast DNS** which requires zeroconf...

on the other hand, right after that, there's a section on Consul

> ## Consul
> Consul is **used as the default service discovery system**.

so which one is it? Or are they nonexclusive (you can use both at the same time)?

**Comment by asim** [comment]
Mdns is the default. Consul used to be the default. We'll change the doc thanks.
