### ISSUE TITLE
Configuring brokers

### ISSUE THREAD

**Issue by waeljammal** [micro/go-micro#623]
Hi,

I've been trying to get my head around broker configuration, I can't seem to find a way to create subscribers that are durable etc. Always ends up being an auto delete consumer. Are there any examples on how to pass in parameters for a queue for instance? Like setting TTL, Durable, Delivery mode etc. 

If not is the only alternative to use a broker client directly? Can the broker be disabled completely? So a custom implementation can be used? I need to be able be able to create things like persistent queues with DLQ's etc, which are an important aspect of many micro services for things like being able to re-play failed messages after deploying a fix etc. And other times if service is down you want the messages to be held by the broker.

Thanks

**Comment by asim** [comment]
A broker's durability is entirely dependendent on the underlying implementation. The default broker is just for notifications, there's no persistence. The broker like all other interfaces is pluggable and can be swapped out. You can find plugins in the go-plugins repo which includes brokers like rabbitmq which are durable. Hope that helps.

**Comment by waeljammal** [comment]
Hi, I am using the rabbit broker but can only seem to find a way to rename the queue and nothing else. An example or documentation would really help.

Thanks

**Comment by waeljammal** [comment]
So found out what was wrong,

looks like broker options can only be applied when using 
`Options().Broker.Subscribe("", handler, rabbitmq.DurableQueue())`

But can not be used when using 
`micro.RegisterSubscriber() `

Is there any way to get it working with that API? It's more user friendly and allows proto types to be sent, while Subscribe( ) only accepts `broker.Publication`

**Comment by asim** [comment]
I think @vtolstov has some experience here

**Comment by waeljammal** [comment]
Guess I'll wait for his reply, running into brick walls here haha. It's quite confusing.

**Comment by vtolstov** [comment]
Can you provide list of options that you need?
We can add it to rabbitmq server.SubscriberOption and after that you can use it.

**Comment by waeljammal** [comment]
> Can you provide list of options that you need?
> We can add it to rabbitmq server.SubscriberOption and after that you can use it.

@vtolstov Thanks, it would be handy for most brokers like nats/rmq/kafka to be able to at least do some of the following, this is speaking from my experience having built several large scale platforms using kube/java microservices over the years. I'm now working on a new one using GO.

For myself right now I would like to be able to set queue arguments, durability, exchange. Though I will be switching to nats streaming once that plugin is available (or will write my own)

1. Define queue/topic/etc. arguments as a map is acceptable, different brokers have different options like ttl, priorities etc.
2: Should be able to create dead letter queues, this is pretty important in a lot of situations, kafka/rmq/nats streaming or any broker that supports persistence it provides you a way to avoid trying to handle the exception for every use case and store it at the service level, what if the service crashes? If no ack received then your message should retry n times and end up in a DLQ or errors topic etc. optionally of course.
3: Based on above my suggestion is that we should have the option of creating queues/exchanges/whatever (other brokers) separately and pass as configuration to subscribe like use queue name instead of creating new queue etc., there are just too many important variables unless you want to abstract the most important ones away? Which seems like a big hassle for all available permutations and not all brokers support same feature sets. The only reason I use different brokers is for features (cqrs I use kafa, complex routing I use Rabbit, IOT etc. I use Nats)
4: Pretty much all libraries I've played with Nats streaming/Rabbit/Kafka provide a client to do all these things and structs containing all available options when creating topics/queues etc. Maybe these should be left to the user and go-micro just makes the connection/factories available to use based on what broker you have configured. Sure it would result in if broker.Name == 'rabbitmq' then setup everything this way else if kafka do it that way etc. But I don't see much choice there. I understand go-micro is opinionated  but the defaults imo are too limited when you are building very large and complex systems that rely on guaranteed event delivery / retry-ability / error handing / much more and make use of many features that you get for free depending on the broker you use. If you don't want to provide that flexibility then maybe more configuration hooks allowing us to decorate/replace/extend the queue/topic/exchange/etc. creation/configuration at certain points even if we need to do it per broker type (dev/prod) I'm perfectly fine with that, would have to do the same thing in Java etc.

Thanks for your time.

**Comment by vtolstov** [comment]
I'm try to add neededo stuff. Please wait

**Comment by vtolstov** [comment]
@waeljammal can you say what broker in priority for you with this options? (stan already have that you need)

**Comment by yexm** [comment]
I have a similar problem on July 30. i used rabbitmq as a plug-in, but can't set durable options. i tried many methods, such as : rabbitmq.DurableQueue()

**Comment by yexm** [comment]
I have a similar problem .on July 30, i used rabbitmq as a plug-in, but can't set durable option. i tried many methods, such as rabbitmq.DurableQueue(). i dug the source code of go-plugins and found it impossible
