### ISSUE TITLE
undefined log method

### ISSUE THREAD

**Issue by codlin** [micro/go-micro#624]
Hi, there are some erros occured when I use log package:
handler/url.go:17:2: undefined: "github.com/micro/go-micro/util/log".Trace
handler/url.go:21:2: undefined: "github.com/micro/go-micro/util/log".Debug
handler/url.go:25:3: undefined: "github.com/micro/go-micro/util/log".Info
handler/url.go:31:2: undefined: "github.com/micro/go-micro/util/log".Debug
But I checked log.go file, these methods are exist in fact

Do you know the root cause?
Thanks

**Comment by milosgajdos** [comment]
I can't think of anything other as some *outdated* dependencies.

I'm wondering, can you do `go get -u github.com/micro/go-micro` whilst having `Go modules` enabled/turned on?

**Comment by codlin** [comment]
@milosgajdos83 Yes, I use the newst go-micro and Go modules is enabled, so I'm wondering, too. 
and I have switched log mod to zap now, you may close the issue.
Thanks for you concern with the issue.
