### ISSUE TITLE
etcdv3 error

### ISSUE THREAD

**Issue by yushuailiu** [micro/go-micro#626]
I've tried to use etcdv3,but I get error message error 

> Error"}calling go.micro.srv.klass.Klass.Call: {"id":"go.micro.client","code":500,"detail":"connection error: dial tcp: address 172.16.2.115: missing port in address","status":"Internal Server Error"}`

**Comment by milosgajdos** [comment]
Hi @yushuailiu thanks for opening the issue!

Can you please open this issue in https://github.com/micro/go-plugins? `etcd` is supported only as a plugin in `go-micro`. Thanks!
