### ISSUE TITLE
Crash when starting with different registry and selector 

### ISSUE THREAD

**Issue by dulithag** [micro/go-micro#629]
I am starting my app like so
```
./platform --registry=memory --selector=static
```

I have a crash as follows. 
```
reflect.Value.Int(...)
        /usr/local/go_1.11.4/src/reflect/value.go:961
golang.org/x/net/internal/netreflect.socketOf(0x1298720, 0xc00000e098, 0xc00000e098, 0x1298720, 0xc00000e098)
        /xxx/golang.org/x/net/internal/netreflect/socket_posix.go:26 +0x2ca
golang.org/x/net/internal/netreflect.PacketSocketOf(0x12977c0, 0xc00000e098, 0x0, 0x0, 0x3)
        /xxx/golang.org/x/net/internal/netreflect/socket.go:33 +0x7d
golang.org/x/net/ipv4.(*dgramOpt).JoinGroup(0xc0000fe330, 0xc000063c88, 0x128a520, 0xc000063c58, 0x0, 0x0)
        /xxx/golang.org/x/net/ipv4/dgramopt_posix.go:111 +0x53
github.com/micro/mdns.newClient(0xc000063d70, 0x457990, 0xc000063db8)
        /xxx/github.com/micro/mdns/client.go:218 +0x573
github.com/micro/mdns.Query(0xc0000fe280, 0x0, 0x0)
        /xxx/github.com/micro/mdns/client.go:67 +0x2e
github.com/micro/go-micro/registry.(*mdnsRegistry).ListServices(0xc000160000, 0xc000001c80, 0xc00047fc00, 0x0, 0x456be0, 0x8)
        /xxx/github.com/micro/go-micro/registry/mdns_registry.go:315 +0x207
github.com/micro/go-micro/network/router.(*router).manageRegistryRoutes(0xc000265c70, 0x12981e0, 0xc000160000, 0x1110a2d, 0x6, 0x0, 0x0)
        /xxx/github.com/micro/go-micro/network/router/default.go:153 +0x49
github.com/micro/go-micro/network/router.(*router).run(0xc000265c70)
        /xxx/github.com/micro/go-micro/network/router/default.go:479 +0xbf
created by github.com/micro/go-micro/network/router.newRouter
        /xxx/github.com/micro/go-micro/network/router/default.go:81 +0x273
```

My concern is this:
``` 
DefaultRouter = NewRouter()
```

in `github.com\micro\go-micro\network\router\router.go`

This router will start a go routine run with default registry. The registry will be over written from command line flags at a later point. Since my setup has no support for mdns it is bound to crash. We have a rouge go routine spawned by NewRouter with wrong registry.
(Note: think moving this go routine to Init method might help but i am not too sure)

Is this a concern or have i got this wrong  ?

**Comment by milosgajdos** [comment]
Thanks for the report @dulithag 

Your assessment is spot on. This is definitely a bug.
There are different ways to go about fixing it:
* the one suggested by you where we might be able to override the registry option
* we don't create `DefaultRouter` at all, unless it's explicitly requested by client/caller

I'm personally in favor of the second option as I would like to avoid having unknown side effects in different parts of codebase.

Pinging @asim for his assessment/opinion.

**Comment by asim** [comment]
Do you have the full stack trace?

In an ideal world we'd strip out defaults but that requires a major rework across the entire repo. For now I believe the router needs to be initialised in the same way as all the other interfaces. 

I'd like to see the full stack trace first though.

**Comment by dulithag** [comment]
Thanks for quick response. This is full stack trace, from start of go-routine to end. The xxx is just the path to my gopath which i replaced cause its large.

**Comment by asim** [comment]
Usually a stack trace after a panic actually provides more info at the start of the trace. This feels like a snippet of that. We need the info from the top of the trace to know what the caller is and where the panic is.

We have a number of things which initialise based on defaults so I'm less inclined to just throw out current methods of initialisation which have worked since the beginning of the project. 

If I run the same flags locally I have no panic so I feel like jumping to quick conclusions on whats happening is really wrong. I think the assumptions of whats actually happening might be wrong.

**Comment by vtolstov** [comment]
@dulithag can you go get github.com/micro/go-micro@v1.9.1 and recheck ?
