### ISSUE TITLE
how does micro solve mysql or redis database sync  

### ISSUE THREAD

**Issue by bluedragonflyliu** [micro/go-micro#630]
how does micro solve mysql and redis database sync ,if any one can give me a hint thinks.

**Comment by asim** [comment]
Can you clarify what you mean here? We don't currently support any database.

**Comment by bluedragonflyliu** [comment]
I mean if I run multi services for example many  user service but when I remove data from one of them then other user service  still have the data that delete, does micro solve by Subscriber

**Comment by asim** [comment]
We do not currently deal with state, we are not responsible for syncing data in mysql, redis or any other data store.

**Comment by bluedragonflyliu** [comment]
OK leave aside Database Manager ,  memory still have this problem if run serivce at different machine, so do you have any advice?

**Comment by asim** [comment]
We do not have a solution for replication in the framework at the moment. So I think you may have to rely on an external source like a distributed database for this.
