### ISSUE TITLE
all integer become string in 1.8.0

### ISSUE THREAD

**Issue by XiangChen666** [micro/go-micro#635]
we have message such as

message Group {
    int64 id = 1;
} 
we use go-micro with micro:kubernetes gateway. we found recently it automatic change all integer to string when we get json response. This break a lot of our production website. Why go-micro decide to make this break changee?

**Comment by vtolstov** [comment]
As i know this can be related to using jsonpb for grpc and proto stuff.
But for spec proto3 always use for int64 strings
