### ISSUE TITLE
The Latest version have some performance bugs

### ISSUE THREAD

**Issue by jzhongming** [micro/go-micro#636]
Today, I updated the latest code. After running Demo for a while, CPU usage was much higher without a request.
![image](https://user-images.githubusercontent.com/1579005/62366971-ec70a480-b55a-11e9-9df0-a871e72a6478.png)

```go
func main() {
	// New Service
	service := grpc.NewService(
		micro.Name("go.omi.srv.say"),
		micro.Version("latest_demo"),
	)

	// Initialise service
	service.Init()

	say.RegisterSayHandler(service.Server(), new(handler.SayImpl))

	// Run service
	if err := service.Run(); err != nil {
		log.Fatal(err)
	}
}
```

**Comment by milosgajdos** [comment]
@jzhongming what was the version you were running before? 

We need to determine the code change that may have made the performance drop you are noticing.

**Comment by jzhongming** [comment]
go-plugins version: 635d628 [26 hours ago] Asim Aslam ✑  Merge pull request #384 from lqczzz/master (HEAD -> master, orig
in/master, origin/HEAD)
go-plugins version before: 453dd4a [3 days ago] Asim Aslam ✑  Fix breaking grpc code (tag: v1.2.0)

go-micro : 0440444 [13 hours ago] Asim Aslam ✑  Merge pull request #634 from micro/rcache-stop (HEAD -> master, origin/master, origin/HEAD)

go-micro befor: 89fc142 [2 days ago] Asim Aslam ✑  Update to use mdns 0.2.0 (tag: v1.8.1) 


By the way, I don't  know the Cpu stats befor, I didn't notice it at that time.

**Comment by milosgajdos** [comment]
Thanks @jzhongming I'm not sure how #634 could cause the performance drop, though it does spin a new goroutine, but I would not expect that to have had a huge CPU perf hit.

The plugin part I'm not sure about, although arguable both PRs seem to be addressing similar issues. Can you provide some handler code so we can try to reproduce this?

**Comment by jzhongming** [comment]
```go
package handler

import (
	"context"

	say "com.omi/demo/proto/say"
)

type SayImpl struct{}

var c int64

func (s *SayImpl) Hello(ctx context.Context, req *say.Request, rsp *say.Response) error {
	c++
	// log.Info("Received Say.Hello request", c)
	rsp.Msg = "Hello " + req.Name
	return nil
}
```
At first, the CPU will not be high, need to wait for a while.

**Comment by milosgajdos** [comment]
How intriguing!

it looks like it's a basic Greeter microservice?

So I picked up https://github.com/microhq/greeting-srv and launched 2 instances of it:
```
~/go/src/github.com/microhq/greeting-srv (master)$ go run main.go
2019/08/02 13:49:59 Transport [http] Listening on [::]:54712
2019/08/02 13:49:59 Broker [http] Connected to [::]:54713
2019/08/02 13:49:59 Registry [mdns] Registering node: go.micro.srv.greeting-b2979fef-a223-4e87-a1ec-b99b2b5f77d1


~/go/src/github.com/microhq/greeting-srv (master)$ go run main.go
2019/08/02 13:54:48 Transport [http] Listening on [::]:55033
2019/08/02 13:54:48 Broker [http] Connected to [::]:55034
2019/08/02 13:54:48 Registry [mdns] Registering node: go.micro.srv.greeting-cfe3c0bc-dba7-44fe-b6a5-565c168e2779
```

Just to confirm, as you can see I'm using `mdns` registry here...

I wrote a little shell script to test if the CPU increases:
```shell
for i in $(seq 1 100)
do
        micro call go.micro.srv.greeting Say.Hello '{"name": "Jason"}'
        sleep 0.5
done
```

the script adds 0.5s latency between subsequent RPC calls. I did not notice any CPU spikes o_O

I also removed the latency and hammered the service even more, but can't seem to have noticed any CPU spike in that scenario either. This is indeed tested on the latest `go-micro` build.

Would you be able to get some trace profile using something like `pprof`?

**Comment by jzhongming** [comment]
Yes, It's greeting demo.  But I  compiled it into binary. Run it. Wait half an hour ....  The Macbook pro 's CPUs will jump high... ORZ...

**Comment by asim** [comment]
I've had this issue before. It's related to a slow leak of time tickers where they are not stopped when a go routine exits. This may fix it https://github.com/micro/go-micro/commit/d7929ef8f37886169e80b79981b7de944f99e2f3. It may be occurring elsewhere also. If this doesn't fit it, it may also be related to other go routine leaks where they have a for loop of time.After causing a continuous loop. But most likely related to a slow leak of go routines unrelated to the request flow.
