### ISSUE TITLE
config source configmap from kubernetes

### ISSUE THREAD

**Issue by anakin** [micro/go-micro#638]
May I ask, How can I read config from kubernetes configmap?I can't find the source type of that...

**Comment by asim** [comment]
You can find the source here https://github.com/micro/go-plugins/tree/master/config/source/configmap

Just do 

```
import "github.com/micro/go-micro/config"
import "github.com/micro/go-plugins/config/source/configmap"

config.Load(
    configmap.NewSource(),
)
```

**Comment by anakin** [comment]
@asim thank u so much.
