### ISSUE TITLE
Stan should allow user defined clientId

### ISSUE THREAD

**Issue by waeljammal** [micro/go-micro#639]
When using stan broker and setting durable name there is no way to set the client id as well which is important when you use durable.

`clientID := uuid.New().String()`

Also I have noticed that if nats streaming goes down or network connection is lost stan plugin does not reconnect instead just complains that connection is down over and over, restarting the service re-connects fine.

`2019/08/03 11:04:58 Accept error: nats: connection closed`

**Comment by vtolstov** [comment]
do you try https://godoc.org/github.com/micro/go-plugins/broker/stan ?

**Comment by mti-platform** [comment]
strange I ran glide update and I don't have that in my version, will try to install again and see if it pulls it down. Thanks

**Comment by vtolstov** [comment]
@mti-adapter can you close the issue if all ok
