### ISSUE TITLE
read k8s configmap error

### ISSUE THREAD

**Issue by anakin** [micro/go-micro#647]
I got the error message below :
```shell
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/micro/go-plugins/config/source/configmap.split(...)
	/Users/anakin/Documents/go/pkg/mod/github.com/micro/go-plugins@v1.2.0/config/source/configmap/util.go:53
```
my configmap yaml:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-config
  namespace: default
data:
  log.level: WARNING
  log.location: LOCAL
```
Please help me~~~

**Comment by Linnkenn** [comment]
data:
  log.level: WARNING
  log.location: LOCAL

should be like this
data:
  log: level=WARNING\nlocation=LOCAL


my usuage now:

data:
  projectconf: registerlimit=1000
  registry: enablek8s=0

**Comment by anakin** [comment]
@Linnkenn Thank you for your reply!

**Comment by milosgajdos** [comment]
I'm assuming this has now been resolved so I'm closing this.
