### ISSUE TITLE
please have a look, "panic: qtls.ConnectionState not compatible with tls.ConnectionState"

### ISSUE THREAD

**Issue by oldshipmaster** [micro/go-micro#654]
consul has running -> consul agent -dev  
do run micro/examples/helloworld/main.go 
in the following exception ,please have a look

panic: qtls.ConnectionState not compatible with tls.ConnectionState

goroutine 1 [running]:
github.com/lucas-clemente/quic-go/internal/handshake.init.0()
	/Users/xinsui/project/go/git-source/src/github.com/lucas-clemente/quic-go/internal/handshake/unsafe.go:17 +0x12f

**Comment by asim** [comment]
Please upgrade to Go 1.12

**Comment by oldshipmaster** [comment]
谢谢你！解决了

**Comment by gabrielcuvillier** [comment]
The issue seems to be back again on go 1.15 (that was ok with 1.12, 13 and 14)
Any hints about how to fix it ?

**Comment by vtolstov** [comment]
update go-micro or update quic-go and fix go-micro

**Comment by shushenghong** [comment]
any update on 1.15?

**Comment by vtolstov** [comment]
you can take a look to github.com/unistack-org/micro - my maintained fork

**Comment by lxyz123** [comment]
thanks , download v3 and solved
