### ISSUE TITLE
HTTP2 transport receive body larger than 4Kb

### ISSUE THREAD

**Issue by ClydeZhao** [micro/go-micro#655]
the max buffer size is hard-coded as `4*1024`, which makes client cannot send http2 request with larger body size.

i think the buffer size should be configurable.

https://github.com/micro/go-micro/blob/0d85e35da06b0dc93703653487341d833a09111b/transport/http_transport.go#L239

**Comment by xiehui3651** [comment]
I faced the same problem.

**Comment by asim** [comment]
Anyone want to PR that change?

**Comment by milosgajdos** [comment]
Should we make that a `transport.Option` @asim?

**Comment by asim** [comment]
Potentially some option. The question is how we make this useful cross transport. In this case is it just a fixed size buffer we have for http2? We will incur this issue elsewhere? 

```
DefaultMaxSendBuffer
DefaultMaxRecvBuffer
```

Maybe we can set these for now as a temporary measure.

**Comment by vtolstov** [comment]
I think that this is must be transport option. For other transports we can later have the same things, so after some time we can move this option to transport.Option
