### ISSUE TITLE
Error message is helpless when client occur service not found

### ISSUE THREAD

**Issue by xpunch** [micro/go-micro#659]
When client is request a service, but the service is not registered or service name is incorrect, we'll get an error like this:
```
{"id":"go.micro.client","code":500,"detail":"not found","status":"Internal Server Error"}
```
It's really hard to determine which service is not found, especially multiple service is called through the request chain.

Can we change the error message like this:
```
if err != nil && err == ErrNotFound {
	return nil, errors.NotFound(service, "service not found")
} else if err != nil {
	return nil, errors.InternalServerError("go.micro.client", err.Error())
}
``` 
Previous code is:
```
if err != nil && err == ErrNotFound {
	return nil, errors.NotFound("go.micro.client", err.Error())
} else if err != nil {
	return nil, errors.InternalServerError("go.micro.client", err.Error())
}
```

**Comment by asim** [comment]
Sounds good. Feel free to PR the change

**Comment by asim** [comment]
Your issue has been fixed. In future please reference the implementation you're speaking about.
