### ISSUE TITLE
Why consulRegistry make tags encoding to unreadable byte array?

### ISSUE THREAD

**Issue by hellodudu** [micro/go-micro#667]
https://github.com/micro/go-micro/blob/dc0fbfc3c0cf9b38afaa22cd27234838028402e4/registry/consul/consul.go#L227-L229

I'm using consul as a registry, and found service tags very long and unreadable. May I have a question why didn't use readable strings as tags?

I usually got tags like the followings:

      "ServiceTags": [
            "t-789caa562a4a4dcf2c2e29aa54b2524acecf2b2ecd51aa05040000ffff560f07c8",
            "t-789caa562a28ca2fc94fcecf51b252ca2d4d2e50aa05040000ffff46a906e2",
            "t-789caa562a294acc2b2ec82f2a51b252ca28292950aa05040000ffff4f930768",
            "t-789caa564a2acacf4e2d52b252ca2b2e54aa05040000ffff301d0592",
            "t-789caa562a4e2d2a4b2d52b252ca2d4d2e50aa05040000ffff37200607",
            "e-789c7c8eb10ac2401044ff65ea60a1dd75826067a1a5582c3a42e0ee8cb77b8120f7ef921853a4b8729999f7f683288170d82746b930f5ed9d9b236dba0f6272ca010d12df996a70cb60d539cf85063674d5bc179fa970317b5f46b276afa8aca13b3f54c0bff48fbd2e98387d3eafda68bbedda7e2b0d024d1e6232fad51225c0e1295e8952be010000ffff6d4f63a6",
            "e-789c74cc410ac2301085e1bbbc75f100d9890bf77a82419f58984c63665a2892bb4b514484acff9fef09934c24ec2b4dceaccb78e1eec838dc259771320ca87cccf440face3ffdf48903622dddb688ce74249b55db267a99ccd9238bae1df05dfeb8cc90ab846c9c47a56424dc449d68ed150000ffff4ba44fbf",
            "e-789c7ccc310ec2301044d1bb4c1d7100775434d0c00956618048f662bceb4811f2dd5104a248e17afebc37541211b02f54b9b0ccd3c8dd817e121f1f93de8f93390614be2acd11fe874d73fe05037cc9dd7d965869085a636cab6cf9a9c61e9de3d281bfeb864d74b98acbca9a174a42c04da211ad7d020000ffff4bb857b7",
            "e-789c6c8e310bc2301484ffcbcdc541c5219b937b1d45e4614f29a63126af8522f9ef522cad95ac77dfbdf7bde1a4210cf6814e8e0c5d7de5ea402dc53d5020f0d5322acc048e5d391605b4f7d9bc13db32c29ca6a9b7d2335cea6a5ed54e77db1fd8b5d6a6625ec89d0b78b3fe87cf69b08cfee922739adef619c96fbafc8a862a95a80c67a2064a03839bd848a4f4090000ffff115b6574",
            "e-789c848eb10ac2401044ff65ea60a1dd75dad858482cc562d1518297f3bcdd0482dcbf4b48088a10eb7df3f6bd10a4261cd689410e4c6d75e6624b2b25dc7795daa6dbcb8d2890f86ca806374d7ea872440a5817ff10adf8860a779c7471f8334eab60abe507171aeff329f71d1a1f41391f127d379b31dcbfe4056a9a5cc4a457ab254a0d87ab7825727e070000ffffab8167fe",
            "e-789c9490c14ac4301086df65cec59378e84d11c46b3d4a29433b4a609ac4c9a41224ef2ea9dad62ddd658fc9fcdf7cc3ff051647821aee852cbe904ca6a79b27d2867a27c3437a7e840a843e2205857a89ff4b34bfe30a34f933d309395280fa75596386153256ef6e37291b99739b8b3d7867031deb3da743f9cf6caf9639b3627301cddfe73eef19134977f1e26a21de8c04eddec545bfb9ae3c779a53d231bbcf2bd0762e6a24c501154b514185702cbb900341cedf010000ffffd9b2a7c6",
            "e-789c74ceb10ac2401004d07f993a5868779d959d452cc562494608dc5de2ed5e20c8fdbb44631021f5ccbed927a204c2e19818e5c234760d77275acda64fed390754487c64aac1adeddf42bda4156c1ab6c3517ca6c2c5ec7d994d1dfaa8dc44073f6d919fe80b5e5720bebf5d4eba6887fdffeead54083469c5645e564b940087bb78254a79050000ffffd3285e9c",
            "e-789c7ccc310ac3301044d1bb4c6d720075a9d2a4524eb0d8133048b2ac5d194cd0dd834970e142f5fc791f248984c3bd30c98b659b47de1e34cf712993e7fa9cd530a070ad54833b1fd7c8ff8b01b6e77eb049a854b854436887ad7949ca2e9ec3dea37ff3058e3499c4e480d50a25c2e12d4189d6be010000ffff097e5983",
            "e-789c8490bdaac2401046df65ea708b6bb79d20d89b52240ce61302bb93b8331b0861df5de24f44255a9ff39d81194938801cad23844bc4be39e26f0b2bc1daca868da9a08873821ab9597f3176775c900ddd17dab34f507292bccf5355bb5614cbd9ce0f8bd11b7b24f77342afce73d688adfe3f8ebfe915a4aeac09f8b13be482028cebe92f6e24b5080ee4e8c45e41395f020000ffff2e577482",
            "e-789c74cc410ac2301844e1bbccba7880ecc41bd8130c3a62214963fe2450247797a2880859bfc7f74464101c8e5991b3725b2e3acc6c3add19d2b2464cc87a545981fbdebfc3f95327942d8d63a3af32b858bdefbb69698da6219afc3622dfe90f0c2abcb27007ad6431c0e1466f42efaf000000ffff150c51ea",
            "e-789c6ccc31aa02411084e1bb54bcbc034cf6022fa08171e39620f6b4e374cfc2227377595c0c64d2fa8bef05934c24fc579a9c5897db857f67f27eb019132a9f8d1e48dfe3de8e7b98106b19ee8b68a3235953ed9be4e561ce1155741d409ff587c90c992564633c2a2523e12aea44efef000000ffffc0894763",
            "e-789c6c8ebdaac2401046dfe5ab43aacb2df6096e7321602916b39bc12c6c36717e04917d77094ab4b09d3967cedc51696604cc6469caf57cf0f847752c2cfd204b62557410be38ab21ecf8e0b1649dfe5f163ad86dfdbeb852715684e32ee7f1cde76abf3f1f54f552daa96d4d5d97aafc1c7598d96824a3ed09f5a8497264418089f3766f597342000957eaf77e6b8f000000ffff1d984eac",
            "e-789c94cf3f4bc5301405f0ef72e7d0491c3a3a39161d45e426bd68f036a9f78f2292ef2e4169fb1ebce1ad497ee7e4fc40c185608488664c0fa4cef6e8f11ecbcc24c32435912a0410fa70528371239347cefa76779010c0bed7cb979fc84e0ae3d316826698de5ff2bcd35cecf6e6f0b838730b9b309457b26bc47fc7572e3b89b5f2b9786e7da6aeb528fd1d0558c87046c3be5b3d6a921c49fa37c4a9c7d535a7de2154703899dbda6f000000ffffc2c179d4",
            "e-789c9490414bc3310cc5bf4bce6527f1d0db4e7a1c7a9431d2366a216b6bd22863f4bb4b15ffffa128784cf27e79bc77868247020f98d21dc52ae9dec22d96c4249b9dd448aae040e8c5483bf845bfb3c0599fb75f1838e8a7f6cbe515d948c13f2c78c28e2bb2152af887ba319e480ef9c225977e7d75212ec63cdc423c66d17e78926a6d656ee6f8c3e63b5999ebdb3fd0fdd88fd990b65a943e970e8ed4f123a43f835ad028399080872e46f36f6d39cede67f4cd5ad618ef010000ffff60628b6c",
            "v-789cca492c492d2e01040000ffff08cc028e"
        ],

**Comment by asim** [comment]
We use tags to store endpoint metadata which is json encoded. Unfortunately consul does not support certain character sets because it registers these entries in dns TXT records. We have to base64 encode them to be able to store them. Consul now supports maps but we have not moved to using them. We do not personally view consul, its merely a datastore for us.

**Comment by hellodudu** [comment]
thx!
