### ISSUE TITLE
how to resolve this problem

### ISSUE THREAD

**Issue by bluedragonflyliu** [micro/go-micro#671]
/src/github.com/micro/util/go/lib/http/http.go:7:2: cannot find package "github.com/micro/go-micro/selector" in any of:
/go/src/github.com/micro/go-micro/selector (from $GOROOT)
/src/github.com/micro/go-micro/selector (from $GOPATH)

**Comment by bluedragonflyliu** [comment]
after update micro today.  I  go run my code but terrible thing happen

 ../../../github.com/micro/util/go/lib/http/http.go:7:2: cannot find package "github.com/micro/go-micro/selector" in any of:
	/usr/lib/golang/src/github.com/micro/go-micro/selector (from $GOROOT)
	/home/go/src/github.com/micro/go-micro/selector (from $GOPATH)

Is there an easy way to solve this?

**Comment by asim** [comment]
github.com/micro/util was deprecated long ago. Whatever library you are using is likely deprecated. Which library are you using?

**Comment by bluedragonflyliu** [comment]
below  message  
src/github.com/micro/util/go/lib/http/http.go:7:2: cannot find package "github.com/micro/go-micro/selector"

**Comment by bluedragonflyliu** [comment]
does these import code can case the problem
"github.com/micro/go-config"
"github.com/micro/go-config/source/file"

**Comment by milosgajdos** [comment]
@bluedragonflyliu both of those packages no longer exist in dedicated repos, but have been moved into `github.com/micro/go-micro/config`

Besides, if you want to investigate imports in your codebase you might want to use `go list` 

To see the Dependency errors and their positions in the source files you can run something like this:
```
go list -f '{{ .DepsErrors }}'
```

Or simply just print out all deps in one `json` output:
```
go list -json
```

Check out the [docs](https://golang.org/cmd/go/#hdr-List_packages_or_modules) for more options.

**Comment by asim** [comment]
As Milos has mentioned micro/go-config has been deprecated and you can see its no longer in the org. Please move to using micro/go-micro/config. Closing as its solved in relation to import paths changing.
