### ISSUE TITLE
github.com/micro/util/go/lib/http/http.go:7:2:

### ISSUE THREAD

**Issue by bluedragonflyliu** [micro/go-micro#674]
when i go run mycode 
export GO111MODULE=off

go list -f '{{ .DepsErrors }}'
./../../github.com/micro/util/go/lib/http/http.go:7:2: cannot find package "github.com/micro/go-micro/selector" in a
	/usr/lib/golang/src/github.com/micro/go-micro/selector (from $GOROOT)
	/home/go/src/github.com/micro/go-micro/selector (from $GOPATH)

after that
export GO111MODULE=on 
and then run code again

go list -f '{{ .DepsErrors }}'
build mycode/web/aaa: cannot load github.com/hashicorp/consul/api: ambiguous import: found github.com/hashicorp/consul/api in multiple modules:
	github.com/hashicorp/consul v1.4.2 (/home/go/pkg/mod/github.com/hashicorp/consul@v1.4.2/api)
	github.com/hashicorp/consul/api v1.1.0 (/home/go/pkg/mod/github.com/hashicorp/consul/api@v1.1.0)

**Comment by asim** [comment]
micro/util was deprecated. If you depend on a library that no longer exists in the org it has been deprecated. Please switch your imports to use go-micro.

**Comment by bluedragonflyliu** [comment]
that all report I not i use micro/util it is mico inner use that

**Comment by asim** [comment]
You are likely using micro/go-config or similar. Any micro library you are using that is not go-micro has likely been deprecated.

**Comment by bluedragonflyliu** [comment]
but i have change to  "github.com/micro/go-micro/config"

**Comment by bluedragonflyliu** [comment]
yesterday is "github.com/micro/go-config"

**Comment by asim** [comment]
Your errors indicate there's still some other dependency on deprecated code. We do not suffer from these build errors.

**Comment by bluedragonflyliu** [comment]
it seems no case by go-micro config Even if you don't use it still have the bug .

**Comment by asim** [comment]
Have you done go get -u github.com/micro/go-micro?

There are no references to micro/util in this repo.

**Comment by bluedragonflyliu** [comment]
yes do that many times; I use micro go-web

**Comment by bluedragonflyliu** [comment]
Just now I do it again after remove all package in gopath

**Comment by asim** [comment]
Please look at the repos in github.com/micro. Any repository that does not exist here is deprecated. 

The library go-web is deprecated.

Please use go-micro/web.

**Comment by milosgajdos** [comment]
@bluedragonflyliu I suspect you are not using [go mod](https://github.com/golang/go/wiki/Modules) properly hence your local dependencies do not seem to be resolved to the latest code.

Please switch to it as we will no longer support the old mode as `go` language will make the `go mod` default in the next version.

**Comment by asim** [comment]
Closing as this is most definitely related to the use of old libraries such as go-web which have been deprecated.
