### ISSUE TITLE
{"id":"go.micro.client","code":500,"detail":"✗","status":"Internal Server Error"}

### ISSUE THREAD

**Issue by yuanrenguang715** [micro/go-micro#683]
"detail":"✗"   ？？？？？？？？？？？？？？？？？？？？？
Api calls the rpc interface once，Actually the rpc interface ran twice。
Then I returned this strange error！

{"id":"go.micro.client","code":500,"detail":"✗","status":"Internal Server Error"}

**Comment by asim** [comment]
This is not enough debugging information. What request are you making? What pieces of software are involved? What's the configuration. We can't really debug this without more info.

**Comment by asim** [comment]
Please provide a repeatable test case.

**Comment by asim** [comment]
Are you executing this request in the browser? Because chrome is known to execute requests multiple times. If you have this behind nginx, it is also known to retry failed requests.

**Comment by yuanrenguang715** [comment]
okay!By looking at your source code，Can figure out your intentions！
```
func (s *SysSrv) Test(ctx context.Context, req *message.Req, resp *message.Resp) error {
	return errors.New("")  //Can not do this
}
```
Thank you for your answer！

**Comment by asim** [comment]
This is incredibly limited information for debugging. My assumption based on this is that the client is retrying because there was an error. We set client retries to 1. If you need to disable this please set retries to 0.

**Comment by asim** [comment]
I'll take the thumbs up as a sign that it addresses your issue.

**Comment by lcg635** [comment]
@asim 
So how should I handle business errors?

**Comment by yuanrenguang715** [comment]
Protobuf custom error to resp, avoid errors.New("")

**Comment by lcg635** [comment]
#281
