### ISSUE TITLE
Can improve related to documents?

### ISSUE THREAD

**Issue by li1234yun** [micro/go-micro#688]
Hi, Sorry to disturb you. I'm new to Go and go-micro, I have a bit advice that I hope you can take a minute to consider.

I want to learn go-micro and user it, but I find some comprehensive tutorial to learn hardly. I hope you can provide some relative comprehensive tutorial. I learned django before and I think it has comprehensive documents. Hope to think about it.

> I had read go-micro website documents and some github examples, but I still confused.

At last,  please tolerate my poor English :-)

Thank you for your work and share!

**Comment by asim** [comment]
Thanks, we'll be working on the docs in time. There is simple chinese translation here https://micro.mu/docs/cn/. You can also join the slack to learn more https://micro.mu/slack/.

**Comment by li1234yun** [comment]
Thank you for reply me immediately. I will read it later.


Thanks! 👍
