### ISSUE TITLE
return value type error

### ISSUE THREAD

**Issue by magengbin** [micro/go-micro#691]
https://github.com/micro/go-micro/blob/0cdac2aa361fa29d9626de18c15affaac792ba26/server/rpc_handler.go#L16

I think this should be a `*Handler`, or the return value is changed to a value type `return rpcHandler{...`.

**Comment by vtolstov** [comment]
Handler is the interface, so we return proper type &rpcHandler{}, so pointer to rpcHandler satisfies Handler interface

**Comment by magengbin** [comment]
thanks
