### ISSUE TITLE
service xxx: not found

### ISSUE THREAD

**Issue by liup1211** [micro/go-micro#692]
When I use consul,it is work well,otherwise, service xxx: not found.
--------------------------Server code:
package main

import (
	model "RPCGoMicroDemo/proto"
	"context"
	"fmt"
	"github.com/micro/go-micro"
)

type Say struct {
}

func (s *Say) Hello(ctx context.Context, req *model.SayParam, rsp *model.SayResponse) error {
	fmt.Println("received:", req.Msg)
	rsp.Header = make(map[string]*model.Pair)
	rsp.Header["name"] = &model.Pair{Key: 1, Values: "abc"}

	rsp.Msg = "hello world"

	rsp.Values = append(rsp.Values, "a", "b")
	rsp.Type = model.RespType_ASCEND

	return nil
}

func main() {
	//reg := consul.NewRegistry(func(op *registry.Options) {
	//	op.Addrs = []string{
	//		"127.0.0.1:8500",
	//	}
	//})

	grpcService := micro.NewService(
		//micro.Registry(reg),
		micro.Name("say.server"),
	)
	
	grpcService.Init()

	err2 := model.RegisterSayHandler(grpcService.Server(), new(Say))
	fmt.Println("err2:", err2)

	if err := grpcService.Run(); err != nil {
		panic(err)
	}
}

![图片](https://user-images.githubusercontent.com/13359281/63493913-32cc7a00-c4ef-11e9-96e4-f55355bf7185.png)

------------------Client code：
package main

import (
	model "RPCGoMicroDemo/proto"
	"context"
	"fmt"
	"github.com/micro/go-micro"
)

func main() {
	//reg := consul.NewRegistry(func(op *registry.Options) {
	//	op.Addrs = []string{
	//		"127.0.0.1:8500",
	//	}
	//})

	grpcService := micro.NewService(
		//micro.Registry(reg),
		micro.Name("say.client"),
	)

	grpcService.Init()

	sayClient := model.NewSayService("say.server", grpcService.Client())
	rsp, err := sayClient.Hello(context.TODO(), &model.SayParam{Msg:"hello server"})
	if err != nil {
		panic(err)
	}

	fmt.Println(rsp)
}

![图片](https://user-images.githubusercontent.com/13359281/63494017-67d8cc80-c4ef-11e9-9164-813094fe84b0.png)

**Comment by asim** [comment]
It sounds like your machine does not support mDNS. Looking at your screenshots, it seems you are on windows. Windows does not support mDNS by default. You either need to run something or use consul. https://stackoverflow.com/questions/23624525/standard-mdns-service-on-windows

**Comment by liup1211** [comment]
Yes, thanks for your help.
