### ISSUE TITLE
load balance

### ISSUE THREAD

**Issue by jwrookie** [micro/go-micro#693]
How do I choose RoundRobin as the default load balance strategy？
Sorry, I didn't understand the document of client/selector，can you give me a demo?
thanks !

**Comment by milosgajdos** [comment]
You can do something like this @jwrookie (you will have to revise the actual code, properly)

```go
	client := client.NewClient(
		client.Selector(
			selector.NewSelector(
				selector.SetStrategy(selector.RoundRobin),
			),
		),
	)
```

**Comment by jwrookie** [comment]
Thank you very much. It was very helpful for me
