### ISSUE TITLE
How can i select a static service?

### ISSUE THREAD

**Issue by h-hy** [micro/go-micro#704]
There are many server (same service) registerd ,like server A , srever B ..etc .
How can I send the request to select static one (always A) for DEBUG / TRACE  the program problem ?

The only way I know is to run 
```shell
micro --selector static call 127.0.0.1:9999 XXXXX.XXXX '{}'
```

Is there another way to send (without write program) , 
like through `micro web`  ?

If not , what about provide a  support  in web ?  (I am happy to make a pull request.)

Thanks ..

**Comment by vtolstov** [comment]
i think that we need some static selector that always use predefined ip:port
