### ISSUE TITLE
when I use the etcd locker, the go routine continuous increase

### ISSUE THREAD

**Issue by coconutskin** [micro/go-micro#719]
when I use the etcd locker, the go routine continuous increase , the demo as follow:

```go
locker := etcd.NewLock(lock.Nodes(etcdclient.GetDefaultAddress()), lock.Prefix("hshs"))
	tool.Startpprof("9999")
	for {
		if err := locker.Acquire("123"); err != nil {
			log.Error("Lock failed:", err.Error())
			continue
		}
		log.Info("Get locker")
		tool.Sleep(2)
		if err := locker.Release("123"); err != nil {
			log.Error("Release error:", err.Error())
			continue
		}
		log.Info("release")
	}
```

**Comment by vtolstov** [comment]
Do you have any messages? for me you code is invalid.
if locker.Release returns error you continue loop and try to Acquire new lock

**Comment by coconutskin** [comment]
sorry, this is a test demo,I just want to test the locker, please try this:

package main

import (
	"fmt"
	"github.com/micro/go-micro/sync/lock"
	"github.com/micro/go-plugins/sync/lock/etcd"
	"time"
)

func main() {
	locker := etcd.NewLock(lock.Nodes("127.0.0.1:2379"), lock.Prefix("test"))
	for {
		if err := locker.Acquire("123"); err != nil {
			fmt.Println("Lock failed:", err.Error())
			continue
		}
		fmt.Println("Get locker")
		time.Sleep(2 * time.Second)
		if err := locker.Release("123"); err != nil {
			fmt.Println("Release error:", err.Error())
			continue
		}
		fmt.Println("release")
	}
}

I get the locker without error, but the go routine add 2 per loop.

please tell me, is my usage correct?

**Comment by asim** [comment]
There are no go routines fired anywhere in our code. Maybe the etcd client library is doing his beneath the covers?

**Comment by vtolstov** [comment]
sorry but new code for me is not correct again:
```
if err := locker.Release("123"); err != nil {
			fmt.Println("Release error:", err.Error())
			continue
		}
```

if err != nil you continue, so previous lock is held.
try without loop and check number of goroutines before lock/unlock and after

**Comment by coconutskin** [comment]
> There are no go routines fired anywhere in our code. Maybe the etcd client library is doing his beneath the covers?

you are right, the go goroutine is from etcd client. I use go mod, the etcd client version is 3.3.15,  there is the information:

goroutine profile: total 465
226 @ 0x1030aaf 0x10078ba 0x1007890 0x10075bb 0x15d8943 0x105dc71
#	0x15d8942	github.com/coreos/etcd/clientv3/concurrency.NewSession.func1+0x72	/Users/ShenDY/Documents/Code/code-src/go-dependence/pkg/mod/github.com/coreos/etcd@v3.3.15+incompatible/clientv3/concurrency/session.go:66

226 @ 0x1030aaf 0x1040258 0x15ba75f 0x105dc71
#	0x15ba75e	github.com/coreos/etcd/clientv3.(*lessor).keepAliveCtxCloser+0x10e	/Users/ShenDY/Documents/Code/code-src/go-dependence/pkg/mod/github.com/coreos/etcd@v3.3.15+incompatible/clientv3/lease.go:327

**Comment by coconutskin** [comment]
> sorry but new code for me is not correct again:
> 
> ```
> if err := locker.Release("123"); err != nil {
> 			fmt.Println("Release error:", err.Error())
> 			continue
> 		}
> ```
> 
> if err != nil you continue, so previous lock is held.
> try without loop and check number of goroutines before lock/unlock and after

The code is for test and I get or release the locker without any error. The log as follow:

Get locker
release
Get locker
release
Get locker
release
Get locker
release
Get locker
release

**Comment by vtolstov** [comment]
ok, so the next step is update etcd to latest release and recheck again.
