### ISSUE TITLE
Improve consul registration logic

### ISSUE THREAD

**Issue by boyand** [micro/go-micro#72]
Currently the logic for the consul registry creates a TTL health check and re-registers the service every N seconds. 
The drawback of the current approach is that this behaviour constantly changes the service index on the consul side interfering with long-polling. As the number of service instances and services grows, this renders long-polling for changes useless and in turn prevents us from doing a proper client side caching. 

We suggest a slight improvement in the registration logic which leverages the Consul idempotent health check API: 
1) On startup the service registers as it currently does creating a TTL health check
2) Every N seconds it updates the state of the health check ( This operation is idempotent and does not trigger unneeded updates on the Consul side ) 
3) If for any reason the health check returns 3xx or 4xx code which may happen if the whole Consul cluster is re-initialised, the service should re-register

**Comment by asim** [comment]
https://github.com/micro/go-micro/pull/73

**Comment by asim** [comment]
Merged.
