### ISSUE TITLE
go-micro/web  too many colons in address

### ISSUE THREAD

**Issue by bluedragonflyliu** [micro/go-micro#738]
when I run code, at one comput not work and have this word (too many colons in address)
even i run with --server_address 0.0.0.0:5678
![image](https://user-images.githubusercontent.com/14164607/64410006-ac05c880-d0bc-11e9-9ff2-e250916be79d.png)

**Comment by milosgajdos** [comment]
Can you provide a code sample you're trying to run?

**Comment by bluedragonflyliu** [comment]
not need special code i just use temple code

1. micro new --type web micro_test/user
2. remove needless code, just print now time
3. go build -i -o user main.go

but not every compute have this problem

**Comment by milosgajdos** [comment]
What version of `micro` and `go-micro` are you using? I can't reproduce this with the latest versions.

**Comment by bluedragonflyliu** [comment]
![image](https://user-images.githubusercontent.com/14164607/64424253-28a79f80-d0db-11e9-8431-ec63d4da65fe.png)

**Comment by bluedragonflyliu** [comment]
go-micro@v1.9.1, micro@v1.9.1

**Comment by milosgajdos** [comment]
Interesting. I have not been able to reproduce this, but I'll try few more things and get back to you. Unless someone else beats me to it

**Comment by kid7st** [comment]
I am facing this issue too. Looks like it can be reproduced in an ipv6 network environment. Our team has two guys facing this issue.

**Comment by kid7st** [comment]
> I am facing this issue too. Looks like it can be reproduced in an ipv6 network environment. Our team has two guys facing this issue.

I believe I was wrong, the ipv6 issue has been resolved a couple of weeks ago: https://github.com/micro/go-micro/pull/594.

I just found that there is a `:` at the end of the address and port. Maybe this is the issue.

**Comment by milosgajdos** [comment]
Ah I see. Not having used ipv6 with micro explains why I could not reproduce it. Thanks for the heads up @kid7st 

> I just found that there is a : at the end of the address and port. Maybe this is the issue.

Yes, this seems like a plausible cause. Could you pinpoint this to the source code?

**Comment by asim** [comment]
What's printing the address here? I can imagine there's some sort of parsing issue here https://github.com/micro/go-micro/blob/master/web/service.go#L50 

But what's strange is you're binding to a standard loopback while someting else is specifying ipv6.

**Comment by vtolstov** [comment]
can you provide minimal repro code? also say what ipv6 addresses do you have when fail

**Comment by vtolstov** [comment]
this is fixed in latest go-micro release
