### ISSUE TITLE
micro/go-grpc cannot be compatible with the latest version 1.9

### ISSUE THREAD

**Issue by songmingming121** [micro/go-micro#739]
When I use the go-micro version 1.9, but the micro/go-grpc version 1.0 of the reference version of the micro/examples quoted github.com/micro/go-micro/cmd, forced to refer to micro/examples v0.2.0, but v0.2.0 version of micro/go - plugins latest version is not compatible with the go - micro version 1.9

**Comment by milosgajdos** [comment]
`micro/go-grpc` has been deprecated and archived. Please use `go-micro/service/grpc`

**Comment by x1nchen** [comment]
@milosgajdos83 micro/go-grpc has been archived? but I cannot find it. I mean my old project with go.mod  has dependency on micro/go-grpc@0.9.0, and it's now been built error due to this issue.

**Comment by x1nchen** [comment]
the same problem with project

- micro/go-web
- micro/go-config
- micro/go-grpc

I have to mirror the repo to the local gitlab, and replace them in the go.mod.

**Comment by asim** [comment]
All projects were consolidated into go-micro. Please use go-micro/service/grpc instead of go-grpc and go-micro/web instead of go-web. These projects were deprecated 4 months ago.

**Comment by xroba** [comment]
Hello Asim, great thxs for your reply ! but when i want to use https://github.com/micro/go-micro/web or https://github.com/micro/go-micro/service/grpc (using the dep init) it stated 404 ?
do not know if it's normal.
Best Regards

**Comment by asim** [comment]
Import paths are

```
github.com/micro/go-micro/service/grpc
```

and

```
github.com/micro/go-micro/web
```

**Comment by asim** [comment]
The links you are specifying would 404 because github adds tree/master to the path when viewing in the browser. https://github.com/micro/go-micro/tree/master/service/grpc

**Comment by x1nchen** [comment]
@asim I'am sorry, but in my case, we have two bunches of services, one applies go-micro v1.x.x, and the other, for old project, applies go-micro v0.6.0. It's hard to upgrade the go-micro version to v1.x. I think it's better to archive the project than to remove it.
