### ISSUE TITLE
update go-micro error fatal: refusing to merge unrelated histories

### ISSUE THREAD

**Issue by DuckulaGL** [micro/go-micro#743]
[bug]When I use go get to update go-micro, it will report "fatal: refusing to merge unrelated histories",
error

**Comment by DuckulaGL** [comment]
error report: package github.com/marten-seemann/qtls: exit status 128

**Comment by milosgajdos** [comment]
Why are you trying to update `go-micro` dependencies? We can't provide any guarantees `go-micro` will work with dependencies other than the ones specified in `go.mod`.

**Comment by DuckulaGL** [comment]
It was always good. Suddenly something started to go wrong the day before yesterday

**Comment by DuckulaGL** [comment]
go get github.com/micro/go-micro (there are problems too without -u)
# github.com/lucas-clemente/quic-go/internal/handshake
GoWork/src/github.com/lucas-clemente/quic-go/internal/handshake/aead.go:77:24: undefined: qtls.CipherSuiteTLS13
GoWork/src/github.com/lucas-clemente/quic-go/internal/handshake/updatable_aead.go:46:9: undefined: qtls.CipherSuiteTLS13

**Comment by DuckulaGL** [comment]
with export GO111MODULE=on

report : 
GoWork/pkg/mod/google.golang.org/grpc@v1.23.0/status/status.go:37:2: google.golang.org/genproto@v0.0.0-20190905072037-92dd089d5514: unexpected EOF

**Comment by mikaelmorvan** [comment]
I've got the same error.
Did you manage to get a solution ?
