### ISSUE TITLE
build command-line-arguments: cannot load crypto/ed25519: cannot find module providing package crypto/ed2551

### ISSUE THREAD

**Issue by songdony** [micro/go-micro#748]
When I run the go-micro,it tips build command-line-arguments: cannot load crypto/ed25519: cannot find module providing package crypto/ed25519,but i find the module is exists in gopath.

**Comment by milosgajdos** [comment]
Unfortunately this is not enough information to work with.

Can you provide the output of the command you run? Also, what version of `go` are you running?

**Comment by sswanv** [comment]
Unfortunately, I also encountered this problem, my go version is 1.12.7

**Comment by aaronstaves** [comment]
I'm also seeing this as well:

```sh
/go # go version
go version go1.12.4 linux/amd64

/go # go get -u github.com/micro/go-micro
package crypto/ed25519: unrecognized import path "crypto/ed25519" (import path does not begin with hostname)
```

**Comment by asim** [comment]
If you are not using go modules please use Go version 1.13

**Comment by songdony** [comment]
I use the Go version 1.13 ,it encountered this problem again.

**Comment by songdony** [comment]
go version go1.12.9 windows/amd64

**Comment by songdony** [comment]
> If you are not using go modules please use Go version 1.13

I use the Go version 1.13 ,it encountered this problem again.

**Comment by asim** [comment]
Please use Go version 1.13 as the change in library is related to the go version change. This is tracked by a third party depedency and if you are not using go modules we cannot effectively pin that.

**Comment by songdony** [comment]
However I tried to update 1.13,it also occurs this problem.

**Comment by baxiang** [comment]
$mkdir -p $GOPATH/src/github.com/micro
$cd !$
$git clone https://github.com/micro/go-micro.git
$go mod download
verifying github.com/lucas-clemente/quic-go@v0.12.0: checksum mismatch
	downloaded: h1:TRbvZ6F++sofeGbh+Z2IIyIOhl8KyGnYuA06g2yrHdI=
	go.sum:     h1:dYHUyB50gEQlK3KqytmNySzuyzAcaQ3iuI2ZReAfVrE=
$rm go.sum
$go mod download

**Comment by leeyongda** [comment]
### golang version 1.12.9
### go build  main.go
### build fail panic error
### cannot load crypto/ed25519:  cannot find module providing package crypto/ed25519

### golang version 1.13 std support "crypto/ed25519" 
### golang version < 1.13 use "golang.org/x/crypto/ed25519" replace "crypto/ed25519" 

### Suggest:
### 1. use golang 1.13
### 2. use golang < 1.13 && go-micro <= 1.8.2  &&  go get -u github.com/micro/go-micro@v1.8.2

**Comment by Himanshuxone** [comment]
tried everything still not resolved

**Comment by amelkikh** [comment]
> tried everything still not resolved

Try to use package **github.com/gogo/protobuf/proto** instead ~~github.com/golang/protobuf/proto~~ 
It seems like it helped me.

**Comment by oussaki** [comment]
having the same issue here.

package crypto/ed25519: unrecognized import path "crypto/ed25519" (import path does not begin with hostname)

**Comment by sennajox** [comment]
> > did you resolve
> 
> I have solved it.The ways:
> 1.Reset the Go Path
> 2.Put the go.mod in a new project and enable Go Modules;
> 3.Run " go mod download";
> 4.Run " go get -u github.com/micro/go-micro";

Hi, did you fix it by following these steps after upgrading to go 1.13 ? or still with go 1.12

**Comment by sennajox** [comment]
> > did you resolve
> 
> I have solved it.The ways:
> 1.Reset the Go Path
> 2.Put the go.mod in a new project and enable Go Modules;
> 3.Run " go mod download";
> 4.Run " go get -u github.com/micro/go-micro";

Hi, did you fix it by following these steps after upgrading to go 1.13 ? or still with go 1.12 ?
and which version the go-micro is ? 
i've tried go-micro v1.9.1 and v1.11.0 with go 1.12, not work...
@songdony

**Comment by sennajox** [comment]
> > > did you resolve
> > 
> > 
> > I have solved it.The ways:
> > 1.Reset the Go Path
> > 2.Put the go.mod in a new project and enable Go Modules;
> > 3.Run " go mod download";
> > 4.Run " go get -u github.com/micro/go-micro";
> 
> Hi, did you fix it by following these steps after upgrading to go 1.13 ? or still with go 1.12 ?
> and which version the go-micro is ?
> i've tried go-micro v1.9.1 and v1.11.0 with go 1.12, not work...
> @songdony

well, it's fixed by upgrading to go 1.13

**Comment by mitra42** [comment]
Unfortunately this is breaking existing docker files that include anything go-based :-( 

We are using ubuntu:rolling, and apt-get gets go 1.12, I'd be happy to upgrade to 1.13 but its not clear (to a non-go coder like me) how to go about doing that within a docker.

**Comment by Himanshuxone** [comment]
> Unfortunately this is breaking existing docker files that include anything go-based :-(
> 
> We are using ubuntu:rolling, and apt-get gets go 1.12, I'd be happy to upgrade to 1.13 but its not clear (to a non-go coder like me) how to go about doing that within a docker.

There is a file go.sum and go.mod. In that file please delete all the lines with crypto package. and then run the docker.

**Comment by mitra42** [comment]
I've no idea how you would find those files in a docker installation. Someone posted a fix in https://github.com/ipfs/ipfs-update/issues/114 which  worked for us, which was to change command line from `GO111MODULE=on go get -u -v github.com/ipfs/ipfs-update` to `GO111MODULE=on go get -v github.com/ipfs/ipfs-update`. I don't know if that will work for other situations.

**Comment by sezzna** [comment]
clientconn.go:49:2: use of internal package google.golang.org/grpc/internal/resolver/dns not allowed
