### ISSUE TITLE
go-config dependency issue

### ISSUE THREAD

**Issue by chmorgan** [micro/go-micro#760]
go: github.com/micro/go-config@v1.1.0 requires
	gocloud.dev@v0.12.0 requires
	contrib.go.opencensus.io/exporter/ocagent@v0.4.2 requires
	github.com/census-instrumentation/opencensus-proto@v0.1.0-0.20181214143942-ba49f56771b8: invalid pseudo-version: version before v0.1.0 would have negative patch number

**Comment by asim** [comment]
micro/go-config is no longer supported please use go-micro/config

**Comment by chmorgan** [comment]
Hi @asim. I'm following the docs here, https://micro.mu/docs/go-config.html#sample-config are these out of date now? I can't find a reference that shows go-config usage with the package path you are mentioning.

**Comment by milosgajdos** [comment]
@chmorgan aas @asim says, `go-config` is no more maintained. 

It's been moved to [go-micro/config](https://github.com/micro/go-micro/tree/master/config)

**Comment by chmorgan** [comment]
@asim, @milosgajdos83 what is the proper import?

I was using:

        "github.com/micro/go-config"
        "github.com/micro/go-config/source/file"

which is the cause of the above message, but if I switch this to import:

        "github.com/go-config/config"
        "github.com/go-config/config/source/file"


I get:

build bitbucket.org/chmorgan/solar_control/src/basiccontroller: cannot load github.com/go-config/config: git ls-remote -q origin in /Users/cmorgan/go/pkg/mod/cache/vcs/147e6d321d2e56acee364e13da41fea4b714e6757f710388ee519842fd55e97b: exit status 128:
	remote: Repository not found.
	fatal: repository 'https://github.com/go-config/config/' not found


What is the proper import?

**Comment by asim** [comment]
Please read the doc https://micro.mu/docs/go-config.html#new-config

The import path is clearly stated as 

```
github.com/micro/go-micro/config
```

**Comment by chmorgan** [comment]
@asim it was close enough to the old path that I thought it was the same one or that you were suggesting it didn’t have the micro prefix, there are a number of projects moving to short url modules these days.

Thank you for the clarification and pointer to the docs with the correct import path.
