### ISSUE TITLE
Can't call grpc service written in other languages?

### ISSUE THREAD

**Issue by YahuiWong** [micro/go-micro#767]
When I use go-micro as the client to call the grpc service written by c#, this error occurs, there is no error message, just saying that there is an error. . .

{"id":"go.micro.client","code":500,"detail":"","status":"Internal Server Error"}

**Comment by asim** [comment]
Are you using grpc to call this service? Are you specifying the correct service name to call? This must be the same as how grpc constructs it's methods /service.Foo/Bar

**Comment by YahuiWong** [comment]
> Are you using grpc to call this service? Are you specifying the correct service name to call? This must be the same as how grpc constructs it's methods /service.Foo/Bar

The code generated from the same proto file, and the c# code as the grpc client can successfully call the go-micro grpc server, but when go-micro is used as the grpc client, there will be this error, the important thing is that there is no error message.
    "detail":""
how Can I display more error information for reference?

**Comment by GeorgeBills** [comment]
Is this https://github.com/micro/go-micro/issues/561?

**Comment by vtolstov** [comment]
if you use in service name the same name as in micro server registration all must works fine
