### ISSUE TITLE
github.com/micro/go-grpc has been removed

### ISSUE THREAD

**Issue by gyurobenjamin** [micro/go-micro#768]
now all of our micro based micro service is broken

**Comment by milosgajdos** [comment]
`go-grpc` was deprecated 3-4 months back

It has been moved to `go-micro/service/grpc`

**Comment by gyurobenjamin** [comment]
I use go-micro 0.7.0. The service/grpc is not part of that. I really don't understand why it was necessary to remove a package. I've never seen anything like this before. Now I can't install my dependencies. Also can't use multiple go-micro version and use just the services/grpc from one of them even if I could, it would have to modify re-test and re-deploy all my services.
