### ISSUE TITLE
Streaming handlers do not work

### ISSUE THREAD

**Issue by utrack** [micro/go-micro#77]
Trying to run the `examples/server` ([this one](https://github.com/micro/go-micro/tree/master/examples/server)); the streaming handler's metadata is empty and the call itself does not quite work.

**Comment by utrack** [comment]
Here's the screenshot from `micro web`:

![scrot-20160426_171905](https://cloud.githubusercontent.com/assets/3862920/14821553/3737d186-0bdc-11e6-8df0-ac02d1e964ef.jpg)

It's odd that meta has `stream=false` as well.

**Comment by utrack** [comment]
Woops, nevermind. The client itself works.

**Comment by asim** [comment]
Can you specify what you mean by "streaming handler's metadata is empty"?

So looks like the streaming handler does work but its incorrectly registering stream=false. The code that takes care of this uses reflection and I'm thinking perhaps a new version of Go behaves slightly differently.

If you run the client you should get this output 

```
go run client/main.go 

--- Call example ---

Call: 0 rsp: d4ebe824-0bbc-11e6-ac38-68a86d0d36b6: Hello John
Call: 1 rsp: d4ebe824-0bbc-11e6-ac38-68a86d0d36b6: Hello John
Call: 2 rsp: d4ebe824-0bbc-11e6-ac38-68a86d0d36b6: Hello John
Call: 3 rsp: d4ebe824-0bbc-11e6-ac38-68a86d0d36b6: Hello John
Call: 4 rsp: d4ebe824-0bbc-11e6-ac38-68a86d0d36b6: Hello John
Call: 5 rsp: d4ebe824-0bbc-11e6-ac38-68a86d0d36b6: Hello John
Call: 6 rsp: d4ebe824-0bbc-11e6-ac38-68a86d0d36b6: Hello John
Call: 7 rsp: d4ebe824-0bbc-11e6-ac38-68a86d0d36b6: Hello John
Call: 8 rsp: d4ebe824-0bbc-11e6-ac38-68a86d0d36b6: Hello John
Call: 9 rsp: d4ebe824-0bbc-11e6-ac38-68a86d0d36b6: Hello John

--- Streamer example ---

Stream: rsp: 0
Stream: rsp: 1
Stream: rsp: 2
Stream: rsp: 3
Stream: rsp: 4
Stream: rsp: 5
Stream: rsp: 6
Stream: rsp: 7
Stream: rsp: 8
Stream: rsp: 9
recv err EOF
stream err: <nil>

--- Ping Pong example ---

Sent ping 1 got pong 1
Sent ping 2 got pong 2
Sent ping 3 got pong 3
Sent ping 4 got pong 4
Sent ping 5 got pong 5
Sent ping 6 got pong 6
Sent ping 7 got pong 7
Sent ping 8 got pong 8
Sent ping 9 got pong 9
Sent ping 10 got pong 10

--- Publisher example ---

2016/04/26 15:40:38 Broker Listening on [::]:53925
Published: &{topic.go.micro.srv.example application/octet-stream 0xc820187ac0}
```

**Comment by utrack** [comment]
@asim sorry, bad wording. I meant that the `Request` and `Response` helper fields are empty when trying to get the service's metadata.
Also, `micro` tool can't query the streaming endpoints. I'll try to fix that.

**Comment by asim** [comment]
https://github.com/micro/go-micro/commit/decb70b97c34db0c964f7c7e3a780f8f7f4da507 fixed metadata issue.

The micro tool can handle streams using the `micro stream` command but it only supports streaming from the server. Useful for logs and events. Bidirectional streaming from the command line seems difficult given the output would be streaming to you at the same time.

**Comment by asim** [comment]
On the `Request` and `Response` being empty. Its because we use the method signature to determine what those types are. In this case, the Stream is an interface rather than a concrete type.
