### ISSUE TITLE
error calling go.micro.srv.greeter.Say.Hello

### ISSUE THREAD

**Issue by zuimei0603** [micro/go-micro#774]
I install go-micro and micro according to this page, [url](https://micro.mu/docs/install-guide.html)，but when I run `micro call go.micro.srv.greeter Say.Hello '{"name": "John"}'`，this error happens.

```
error calling go.micro.srv.greeter.Say.Hello: {"id":"go.micro.client.transport","code":500,"detail":"unexpected EOF","status":"Internal Server Error"}
```

please tell me how to solve it.

**Comment by milosgajdos** [comment]
Examples had outdated dependencies.

This PR: https://github.com/micro/examples/pull/87 should fix this
