### ISSUE TITLE
go-micro：How to add a random unique port to grpc throughout the microservice

### ISSUE THREAD

**Issue by wubo0067** [micro/go-micro#776]
Excuse me！I have a question i'd like to ask.

How to randomly give grpc a unique port throughout the microservice？I want to randomad a port to net/http/pprof in a grpc service。

micro version：
	github.com/micro/cli v0.2.0
	github.com/micro/go-api v0.6.0
	github.com/micro/go-micro v1.10.0
	github.com/micro/go-plugins v1.2.0
	github.com/micro/micro v1.10.0

**Comment by asim** [comment]
A random port is already assigned but you can change the address with the Address option

**Comment by wubo0067** [comment]
@asim ，In grpc service，I use "github.com/DeanThompson/ginpprof", Now is listenport this field I don't know how to fill in, need a random global unique port。

	ginpprof.Wrap(ginRouter)

	httpSrv = &http.Server{
		Addr:    fmt.Sprintf("%s:%d", listenAddr,**listenPort**),
		Handler: ginRouter,
	}

**Comment by asim** [comment]
Neither of these tools is micro related

**Comment by wubo0067** [comment]
@asim 
Please tell where the grpc's transport port is randomly generated?

Transport [grpc] Listening on [::]:**38340**

**Comment by asim** [comment]
The address is defined as ":0" in the server package.

**Comment by wubo0067** [comment]
@asim Thank you so much，Listen for 0 port, the system will randomly assign you a

listener, err := net.Listen("tcp", "0.0.0.0:**0**")
port := listener.Addr().(*net.TCPAddr).Port
logger.Printf("Listen on port:%d\n", port)
