### ISSUE TITLE
How to view customized web page.

### ISSUE THREAD

**Issue by wahello** [micro/go-micro#779]

**Comment by asim** [comment]
The web app starts on a http port and logs the port. You can browse to that url.

**Comment by wahello** [comment]
What you means is that defined by web.Address()? Just like the following

```
	// create new web service
	service := web.NewService(
	    web.Name("cn.zlito.go.micro.web.api_1_0"),
	    web.Address(":9876"),
	    web.Version("latest"),
	)
```

And `http://0.0.0.0:9876` works.

The document should has more explicit instruction about it.
