### ISSUE TITLE
Can't build service for kubernetes

### ISSUE THREAD

**Issue by Dartonian303** [micro/go-micro#791]
Can't build service with go mod, after i added k8s "github.com/micro/kubernetes/go/micro" import

go: github.com/micro/go-web@v0.6.0: unknown revision v0.6.0
go: github.com/micro/go-config@v0.14.0: unknown revision v0.14.0
go: finding sigs.k8s.io/structured-merge-diff v0.0.0-20190130003954-e5e029740eb8
go: finding github.com/micro/go-grpc v0.11.0
go: error loading module requirements

**Comment by milosgajdos** [comment]
`github.com/micro/kubernetes` has been deprecated and archived.

Please use K8s plugin in https://github.com/micro/go-plugins

**Comment by Dartonian303** [comment]
thx, it works
