### ISSUE TITLE
how can i register host ip&port to consul?

### ISSUE THREAD

**Issue by shushenghong** [micro/go-micro#819]
environment:
host server
micro services, each service a single docker container on host server, which mapped service port to host
consul

my question is, is there a solution, each service register with the host ip and the mapped port to consul?

**Comment by milosgajdos** [comment]
You can use [server.Advertise()](https://godoc.org/github.com/micro/go-micro/server#Advertise) to do that

**Comment by milosgajdos** [comment]
Feel free to re-open the issue if the above does not answer it. CLosing this now due to inactivity.
