### ISSUE TITLE
How to run mirco api in the Windows 

### ISSUE THREAD

**Issue by NullYing** [micro/go-micro#826]
I have build binary and run it in the Windows
```
CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -a -installsuffix cgo -ldflags '-w' -i -o micro ./main.go 
```

![image](https://user-images.githubusercontent.com/10618381/66362246-8b2edc80-e9b4-11e9-963c-fb6e5d6b460a.png)

But it didn't run as I expected

![image](https://user-images.githubusercontent.com/10618381/66362261-9c77e900-e9b4-11e9-8625-d9021e33d659.png)

**Comment by milosgajdos** [comment]
What do you expect to happen?

**Comment by NullYing** [comment]
@milosgajdos83 I think it will run the api gateway

**Comment by milosgajdos** [comment]
Can you please pull the latest code and build from that.

**Comment by milosgajdos** [comment]
Are you still experiencing these issues on the latest release? If not, please feel free to reopen the issue.

**Comment by NullYing** [comment]
yes,  I still experiencing these issues on the latest release.
```
	github.com/micro/go-micro v1.16.0
	github.com/micro/micro v1.16.0 // indirect
```

**Comment by asim** [comment]
Are you changing something? Because we have literally nothing named "go.micro.api.web"
