### ISSUE TITLE
registry/cache/cache.go  appear Deadlock

### ISSUE THREAD

**Issue by SkywardSky** [micro/go-micro#840]
go-micro/registry/cache/cache.go

![15707760595870](https://user-images.githubusercontent.com/19143486/66630086-14087b00-ec36-11e9-864f-e4a73447bfea.png)

**Comment by asim** [comment]
This is old code. It has since been updated. Please pull 1.11.1 or master.

**Comment by SkywardSky** [comment]
Code already 1.11.1

**Comment by asim** [comment]
This is the code in 1.11.1 https://github.com/micro/go-micro/blob/c8d71e051adc848ce711e0085f47448ed138e8ad/registry/cache/rcache.go

It does not match your code

**Comment by SkywardSky** [comment]
![image](https://user-images.githubusercontent.com/19143486/66632386-ee31a500-ec3a-11e9-9e5d-be8779be5248.png)

**Comment by vtolstov** [comment]
lock in 182 must be RLock() and released after c.cache[res.Service.Name]

**Comment by bufio** [comment]
mutex := new(sync.RWMutex)
mutex.Lock()

mutex.RLock()
mutex.RUnlock()

mutex.Unlock()

This logic will not deadlock?

**Comment by SkywardSky** [comment]
Thank you
