### ISSUE TITLE
Disable timeout on RPC stream connection

### ISSUE THREAD

**Issue by veger** [micro/go-micro#853]
For a stream RPC connection I'd like to get rid of timeout, I see/found two solutions:

1. Set timeout to some huge value and hope the client never stays connected long enough.
2. Set timeout to `-1` which 'somehow' seems to work.
    (Actually [strconv.ParseUint()](https://github.com/micro/go-micro/blob/a725998c0aa75edd594baea8cc7d4d34b5937f7e/server/rpc_server.go#L180) chokes on it and context timeout is not set (and no error is issued...))

Both options feel hacky to me... Is there a better/recommended solution instead?

**Comment by vtolstov** [comment]
i don't think that disabling timeout is good. why not set some big but useful timeout?

**Comment by veger** [comment]
We want to have a connection to the server for an indefinite period, basically the full lifetime of either client or server (due to deployment they restart, but that is it).

So define 'some big but useful timeout'?
One day is definitely too short, one week maybe or one month, but what if we do not a deploy in this (longer) period? Ultimately, we can do `(2^64)-1` (or some `Int.Max` assuming golang has such a constant) but that seems ridiculous.
Building some reconnect mechanism for timeouts (broken connection?) is possible, but wastes our time and maintenance for nothing as we didn't want to have this timeout in the first place...

That is why I'd like to have an option to get rid of this timeout properly.

**Comment by yarbelk** [comment]
in our context the 'big useful context' is: never disconnect automatically.  the connections are expected to run forever and the disconnect/reconnect is bad.

**Comment by asim** [comment]
I think we've resolved this

**Comment by veger** [comment]
@asim 'resolved' is a big word...
I am using the `-1` hack and hope that proper error handling won't be added here, or my application will break...

**Comment by vtolstov** [comment]
@veger i have streams that lives for hour-two. How long you streams?

**Comment by veger** [comment]
We cannot say/determine, the streams are used by a sort-of proxy (our WebSocket API/gateway) to internal services, so as long as the users keep their WebSockets open. When they close, we close the(ir) corresponding streams.

So it really depends on our users and their usage of our applications, therefore we assume they are open indefinitely and do not desire the timeout to be set.

**Comment by vtolstov** [comment]
i'm also use streams with websocket (vnc proxy, file streaming). So may be i have short lived conns, but i don't see any timeouts and unexpected stuff

**Comment by sadwxqezc** [comment]
I think an idle connection recycling mechanism is  better than timeout&reconnect

**Comment by vtolstov** [comment]
no, idle conn not mean unneeded. For example i have SPICE websocket (for usb device redir, when device not used connection steel alive) When user uses device - connection not idle. So I need only explicit control like client close websocket and i'm close the stream. Or reading from websocket return io.EOF

**Comment by vtolstov** [comment]
so absence of timeout is useful.

**Comment by vtolstov** [comment]
@veger - do you have info about timing when connection closed by go-micro ?

**Comment by veger** [comment]
Sure
As I wrote when the client closes his WebSocket connection we close the go-micro RPC stream. (That is why we don't know how long the RPC stream should live as it fully depends on the client and (his) application life-time)

Basically same as your situation

**Comment by vtolstov** [comment]
but if you have the same situation why you worry about timeouts? i don't have any issues with timeouts, mostly api/handler/rpc may be need support for ping/pong websocket messages to speedup close timeouts

**Comment by veger** [comment]
> So I need only explicit control like client close websocket and i'm close the stream. Or reading from websocket return io.EOF

I meant we do a similar thing as you described here.

With this setup timeouts are not desired, as the stream gets closed on client disconnect/EOF.
So I 'worry' about timeouts, because I cannot disable them. (except by using the hackish workaround)

**Comment by vtolstov** [comment]
hm, not close the stream? sorry i'm not understand problem. i'm check grpc source code:
https://github.com/grpc/grpc-go/blob/master/stream.go#L183
and also
https://pkg.go.dev/google.golang.org/grpc?tab=doc#WithKeepaliveParams

so if you not pass timeout via options it not set and stream lives forever.

**Comment by veger** [comment]
I am talking about [go-micro RPC server side](https://github.com/micro/go-micro/blob/master/server/rpc_server.go#L276) as stated in my OP. This timeout is used (by the server) to close the connection and kick the (RPC) client out.

In our case it is not desired as the client will close the connection when it is not active anymore (Websocket connection to outside world is closed). If the RPC server closes the connection premature, we have to add reconnect logic, and tend to lose messages (or we need to add buffering as well).
