### ISSUE TITLE
confused handler when rpc client catch serve rerror

### ISSUE THREAD

**Issue by btfak** [micro/go-micro#87]
we know it is common that server return an error, but blacklist of default selector limit 3 error, then we have no services available. can we turn off blacklist?

**Comment by asim** [comment]
The selector is pluggable. You can write a new selector that suits your requirements. We could potentially provide one that doesn't blacklist. But the fact that the call fails 3 times implies there's an issue, hence blacklisting the node. Only that specific node is blacklisted. So if you're only running one instance of a service, yes it's going to return no service available. Why is it throwing an error? Can you run more instances of the service?

**Comment by btfak** [comment]
I guess the key is 

```
what is the best way to throwing error?
```

for example：invalid request params and so on，they will return error，but not reason to block that specific node. People will benchmark wrong request and make all node not available

**Comment by btfak** [comment]
I have use my own selector,problem solved.

**Comment by asim** [comment]
great

**Comment by asim** [comment]
Let us know if you open source it. Would be great to see what it looks like.

**Comment by btfak** [comment]
ok,my team use micro on a  e-commerce project, we will open source some plugins when code stable.
your great job help us reduce much work,thanks

**Comment by asim** [comment]
Cool. Feel free to add your company to the Users list https://github.com/micro/micro/wiki/Users
