### ISSUE TITLE
ReplaceEnvVars should not be intrusive

### ISSUE THREAD

**Issue by dfilipovic39** [micro/go-micro#873]
Hi,

ReplaceEnvVars function strips the values of format '${myVar}'. This is kind of an issue in my case where I'm trying to implement expressions on top of the configuration where all placeholder of the aforementioned format would be replaced with my values. IMHO, this should be an optional feature with configurable regex/placeholder using Option.

**Comment by milosgajdos** [comment]
Can you provide a code sample which would demonstrate your use case?

**Comment by milosgajdos** [comment]
Feel free to reopen the issue if you have anything more to add.

**Comment by dfilipovic39** [comment]
Hi,
the problem is as follows:
```Go
package main

import (
	"fmt"
	"github.com/micro/go-micro/config"
	"github.com/micro/go-micro/config/source/memory"
)

func main() {
	_ = config.Load(memory.NewSource(memory.WithYAML([]byte(`a: ${m_var}`))))
	fmt.Println(string(config.Bytes()))
}
```
outputs:

`'{"a":""}'`

and I cant get the `'${m_var}'` value to replace with my own value

**Comment by colinhoglund** [comment]
@milosgajdos @asim 

I am also surprised by this behavior. This seems to ignore the case where i might want a literal string value that happens to look like an environment variable.

For example, i noticed this when trying to load proxy configuration that included a redirect string:

code
```
package main

import (
	"fmt"

	"github.com/micro/go-micro/v2/config"
	"github.com/micro/go-micro/v2/config/source/memory"
)

func main() {
	bytes := []byte(`{"regex": "^http://example.com/(.*)", "redirect": "http://example.com/${1}"}`)
	c, _ := config.NewConfig(config.WithSource(memory.NewSource(memory.WithJSON(bytes))))
	fmt.Println(string(c.Bytes()))
}
```

output (notice the missing `${1}`)
```
$ go run main.go
{"redirect":"http://example.com/","regex":"^http://example.com/(.*)"}
```

**Comment by colinhoglund** [comment]
Should probably also point out that this currently interpolates invalid environment variable names, such as `${1BADNAME}`.
