### ISSUE TITLE
Micro service communication debugging 

### ISSUE THREAD

**Issue by alexneamtu** [micro/go-micro#891]
I created a service with:
```
syntax = "proto3";
...
service ServiceExample {
    rpc Call (Request) returns (Response) {
    }
}
...
message Request {
    string name = 1;

    enum PhoneType {
      MOBILE = 0;
      HOME = 1;
      WORK = 2;
    }

    message PhoneNumber {
      string number = 1;
      PhoneType type = 2;
    }
}
...
```

And when trying to do a call, I get this error 60% of the time:
```
micro call go.micro.srv.service-example ServiceExample.Call '{"name":"test", "level": 2}'

error calling go.micro.srv.service-example.ServiceExample.Call: {"id":"go.micro.client.transport","code":500,"detail":"404 Not Found: 404 page not found\n","status":"Internal Server Error"}
```

Of course that there may be an issue in my code, but is there any way to find out more about what happened?

Is there any transport logging?

How can I debug this?

**Comment by asim** [comment]
Your service returning a 404 error is very strange. Is there some proxy sitting in between your http usage?

**Comment by alexneamtu** [comment]
Thanks @asim for help:
```You need to change the topic names so they are not the same as the service name. The default broker is a http broker which uses service discovery to register its topics. If the same is the same then it registers them under the service name, when you then make a service call it attempts to connect to the broker and throws a 404. ```
