### ISSUE TITLE
v1.14.0 unable to run

### ISSUE THREAD

**Issue by echobool** [micro/go-micro#899]
![060A7C659BC5DF1D274EF5DA3CD2E8AE](https://user-images.githubusercontent.com/8441357/68015713-c380bc80-fccd-11e9-8d65-7eec976f2404.jpg)
Normal operation after using v1.13.0

**Comment by asim** [comment]
Youve not specified your usage but I'm assuming you're using consul. This was moved out to go-plugins. Please see the blog for the latest. Otherwise import consul from go-plugins.

**Comment by vtolstov** [comment]
i think that this issue can be closed.
