### ISSUE TITLE
Cant deregistery node

### ISSUE THREAD

**Issue by justintv90** [micro/go-micro#9]
When i exited the server, it did show the log info

Deregisterying node : .....

But when i checked at http://127.0.0.1:8500/v1/catalog/nodes, this node was being there, when is startting and restartig this node a few time, The site http://127.0.0.1:8500/v1/catalog/nodes gave alot of node like the screenshot below, and then the client couldnt understand  which server is running and it received the 500 error code

The catalog:
http://i.imgur.com/Nd6YhtU.png
The result:
http://i.imgur.com/NOCYo7N.png

Please check and fix it

**Comment by asim** [comment]
How are you "exiting" the server. Sounds like a potential issue where it dies before it can make the call to deregister.

**Comment by justintv90** [comment]
Exiting by Ctrl+C in terminal @asim

**Comment by justintv90** [comment]
I fixed by myselft

The problem is the ServiceID in CatalogRegistration interface at Consul Deregister method, i check the node with postman and nothing named ServiceID in his propertice

His propertice : 
http://i.imgur.com/L5yjymA.png

I removed the ServiceID in CatalogRegistration, and then everything worked smooth, please check and correct it

**Comment by asim** [comment]
Fixed.
