### ISSUE TITLE
Service register failed

### ISSUE THREAD

**Issue by winyh** [micro/go-micro#900]
example： gretter

micro version: 1.7.0
go-micro@v1.14.0
mdns@v0.3.0
micro@v1.14.0
go version go1.13.3 darwin/amd64
MacBook Pro:10.14.6

I do this list one by one.

`go run srv/main.go`

`go run cli/main.go`

`go run api/api.go`

`micro api --handler=api`

`curl http://localhost:8080/greeter/say/hello?name=John`

`go run web/web.go `

`micro web`

show error：
`{"id":"go.micro.api","code":500,"detail":"not found","status":"Internal Server Error"}`

but run script：
`go run cli/main.go  `

The result is ture.

Then I run script:
`micro list services`

Just get two services:

```
go.micro.api

go.micro.web
```

I run script:
`micro get service go.micro.api.greeter`
`micro get service go.micro.srv.greeter`

show the same error : 
Service not found

I think the service don't resgister successful, but I can't find the reason.
Who can give me some advice？Thank you！

**Comment by winyh** [comment]
> example： gretter
> 
> micro version: 1.7.0
> go-micro@v1.14.0
> mdns@v0.3.0
> micro@v1.14.0
> go version go1.13.3 darwin/amd64
> MacBook Pro:10.14.6
> 
> I do this list one by one.
> 
> `go run srv/main.go`
> 
> `go run cli/main.go`
> 
> `go run api/api.go`
> 
> `micro api --handler=api`
> 
> `curl http://localhost:8080/greeter/say/hello?name=John`
> 
> `go run web/web.go `
> 
> `micro web`
> 
> show error：
> `{"id":"go.micro.api","code":500,"detail":"not found","status":"Internal Server Error"}`
> 
> but run script：
> `go run cli/main.go `
> 
> The result is ture.
> 
> Then I run script:
> `micro list services`
> 
> Just get two services:
> 
> ```
> go.micro.api
> 
> go.micro.web
> ```
> 
> I run script:
> `micro get service go.micro.api.greeter`
> `micro get service go.micro.srv.greeter`
> 
> show the same error :
> Service not found
> 
> I think the service don't resgister successful, but I can't find the reason.
> Who can give me some advice？Thank you！

I find the reason.
Version don't match！
go.mod  depend on go-micro@1.11
But I upgrade to go-micro@1.14.0
So change the version (go.mod) to go-micro@1.14.0 can handle the question.

**Comment by milosgajdos** [comment]
Glad you got it resolved.
