### ISSUE TITLE
Rpc don't work

### ISSUE THREAD

**Issue by winyh** [micro/go-micro#905]
example:greeter
go-micro@1.14.0
micro@1.14.0
MacBook Pro:10.14.6

```
curl "http://localhost:8080/greeter/say/hello?name=John"

hello John
```
can get true response

But. rpc can't get true
```
curl -H 'Content-Type: application/json' \
     -d '{"service": "go.micro.srv.greeter", "method": "Say.Hello", "request": {"name": "John"}}' \
     http://localhost:8080/rpc


{"id":"go.micro.api","code":500,"detail":"service not found","status":"Internal Server Error"}
```

**Comment by winyh** [comment]
> example:greeter
> go-micro@1.14.0
> micro@1.14.0
> MacBook Pro:10.14.6
> 
> ```
> curl "http://localhost:8080/greeter/say/hello?name=John"
> 
> hello John
> ```
> 
> can get true response
> 
> But. rpc can't get true
> 
> ```
> curl -H 'Content-Type: application/json' \
>      -d '{"service": "go.micro.srv.greeter", "method": "Say.Hello", "request": {"name": "John"}}' \
>      http://localhost:8080/rpc
> 
> 
> {"id":"go.micro.api","code":500,"detail":"service not found","status":"Internal Server Error"}
> ```

I find the reason. 
should add tag --enable_rpc
```
micro api --handle=api   --enable_rpc
```

**Comment by milosgajdos** [comment]
Glad your figured this out.
