### ISSUE TITLE
web service need modify registry service nodes while register interval

### ISSUE THREAD

**Issue by hb-chen** [micro/go-micro#907]
1. when I start web service,  host IP:`192.168.1.2`
2. then I switch network, host IP:`192.168.43.6`, but web service's nodes will not modify, it's always `192.168.1.2`

https://github.com/micro/go-micro/blob/bd1918900e8cf554f8a08777397ad237614bcd3b/web/service.go#L93
https://github.com/micro/go-micro/blob/bd1918900e8cf554f8a08777397ad237614bcd3b/web/service.go#L111

**Comment by milosgajdos** [comment]
Are you suggesting the service should re-bind to a different IP address once you've changed the host network settings?

**Comment by hb-chen** [comment]
Yes, I have make a pull request for this.
https://github.com/micro/go-micro/pull/908
