### ISSUE TITLE
artificial delay in http_broker Unsubscribe

### ISSUE THREAD

**Issue by HeavyHorst** [micro/go-micro#91]
if i run a service and stop it: 

```
130 rkaufmann@rkaufmann ~/micro/go/src/github.com/testService % GOPATH=/home/rkaufmann/micro/go go run main.go --registry=etcdv3                                                                                                             :(
2016/05/26 12:17:58 Listening on [::]:35325
2016/05/26 12:17:58 Broker Listening on [::]:44141
2016/05/26 12:17:58 Registering node: go.micro.srv.testService-1e97b357-232b-11e6-8b9d-c0cb380679de
^C2016/05/26 12:18:05 Deregistering node: go.micro.srv.testService-1e97b357-232b-11e6-8b9d-c0cb380679de
2016/05/26 12:18:06 Unsubscribing from topic: topic.go.micro.srv.testService
2016/05/26 12:18:06 Unsubscribing from topic: topic.go.micro.srv.testService
```

 i see messages like 

> 2016/05/26 12:15:39 grpc: Server.processUnaryRPC failed to write status: connection error: desc = "transport: write tcp 127.0.0.1:2379->127.0.0.1:52332: use of closed network connection"
> 2016/05/26 12:16:12 grpc: Server.processUnaryRPC failed to write status: stream error: code = 1 desc = "context canceled" 

in etcd.

Beacause of this etcd gets filled with dead nodes over time.

```
/micro-registry/topic:topic.go.micro.srv.testService/broker-4a52d6aa-232a-11e6-a6fc-c0cb380679de.4a5873ba-232a-11e6-a6fc-c0cb380679de
{"name":"topic:topic.go.micro.srv.testService","version":"ff.http.broadcast","metadata":null,"endpoints":null,"nodes":[{"id":"broker-4a52d6aa-232a-11e6-a6fc-c0cb380679de.4a5873ba-232a-11e6-a6fc-c0cb380679de","address":"192.168.0.203","port":42250,"metadata":{"secure":"false"}}]}
```

after increasing the delay to 100 Milliseconds everything works as expected.

**Comment by boyand** [comment]
Are you using TTLs for the registry ? I would expect those nodes to be deleted. 

The artificial delay won't help when services just drop dead.

**Comment by HeavyHorst** [comment]
You're right TTL's work.

But wouldn't it be better to wait until the node is ungregistered before returning  ?
This could work for example:

```
func (h *httpSubscriber) Unsubscribe() error {
    h.ch <- h
    <-h.ch
    return nil
}
```

```
        // unsubscribe subscriber
        case subscriber := <-h.unsubscribe:
            h.Lock()
            var subscribers []*httpSubscriber
            for _, sub := range h.subscribers[subscriber.topic] {
                if sub.id == subscriber.id {
                    h.r.Deregister(sub.svc)
                    subscriber.ch <- &httpSubscriber{}
                }
                subscribers = append(subscribers, sub)
            }
            h.subscribers[subscriber.topic] = subscribers
            h.Unlock()
```

**Comment by asim** [comment]
The HTTP broker uses register TTL so the entry will expire if it doesn't deregister cleanly. Its non blocking because we don't really want to wait on exit. HTTP broker is a hack so that there's at least some form of pub/sub without another dependency. The behaviour is unlikely to be modified.
