### ISSUE TITLE
micro.NewService method can not set "RegisterTTL" and "RegisterInterval"

### ISSUE THREAD

**Issue by liuxuech** [micro/go-micro#911]
```go
package main

import (
	"fmt"
	"github.com/micro/go-micro"
	"time"
)

func main() {
	service := micro.NewService(
		micro.Name("test.health.check"),
		micro.RegisterTTL(time.Second*10),
		micro.RegisterInterval(time.Second*5),
	)
	service.Init()

	fmt.Println(service.Server().Options().RegisterTTL)	// 1m0s
	fmt.Println(service.Server().Options().RegisterInterval)	// 30s

	if err := service.Run(); err != nil {
		fmt.Println(err)
	}
}

```

**Comment by zqkgo** [comment]
`RegisterTTL` and `RegisterInterval` are `Server` options as you know, they are initialized to default value when `service.Init()` is called by the `Cmd` implementation `cmd`.

**Comment by yeaze** [comment]
The same problem.
if you run main.go by:
`go run main.go  --register_ttl=0  --register_interval=0`
you will find your setting worked

**Comment by liuxuech** [comment]
@zqkgo 通过service.Init()这个方法去设置RegisterTTL and RegisterInterval这两个参数也不行。
不过，通过修改一下service.Init()这个函数的源码可以生效。
//   改之前
for _, o := range opts {
    o(&s.opts)
}
s.once.Do(func() {
   // 省略... ...
})
// 改之后
s.once.Do(func() {
   // 省略... ...
})
for _, o := range opts {
    o(&s.opts)
}
这样修改后，设置可以生效

**Comment by zqkgo** [comment]
@liuxuech no need to change source code, try what @yeaze said.

**Comment by liuxuech** [comment]
@zqkgo  嗯 明白。我试了@yeaze说的是可以的。但是我希望能通过代码进行设置，成为一个配置，后面可以通过配置中心进行设置。

**Comment by zqkgo** [comment]
@liuxuech another way to achieve what you want is calling `service.Init()` twice

```go
service.Init()
service.Init(
	micro.RegisterTTL(80*time.Second),
	micro.RegisterInterval(200*time.Second),
)
```
