### ISSUE TITLE
Add custom metadata for handler endpoint

### ISSUE THREAD

**Issue by xujinzheng** [micro/go-micro#92]
the method name and others info will set into endpoint and store in registry, but we could not set custom
`Metadata` into this handler's Endpoint.  

``` go
return &registry.Endpoint{
        Name:     method.Name,
        Request:  request,
        Response: response,
        Metadata: map[string]string{
            "stream": fmt.Sprintf("%v", stream),
        },
    }
```

my other service will list services from registry and get service handler from `Endpoint`, if we could set more metadata into endpoint, my service could known more details about this handler, so I really need this feature. thanks!!!

**Comment by asim** [comment]
https://github.com/micro/go-micro/pull/93

**Comment by asim** [comment]
It should be possible to add in the following ways

```
        example.RegisterExampleHandler(
                server.DefaultServer,
                new(handler.Example),
                server.EndpointMetadata("Example.Call", map[string]string{
                        "foo": "bar",
                }),
        )
```

or

```
        server.Handle(
                server.NewHandler(
                        new(handler.Example),
                        server.EndpointMetadata("Example.Call", map[string]string{
                                "foo": "bar",
                        }),
                ),
        )
```

**Comment by asim** [comment]
The above PR has been merged which should allow you to defined endpoint metadata. Please close the issue if you're happy with that.

**Comment by xujinzheng** [comment]
👍 💯 , Thank you very much!
