### ISSUE TITLE
Cannot load google.golang.org/grpc/resolver/dns while building 

### ISSUE THREAD

**Issue by EgorkZe** [micro/go-micro#922]
When make "go build" get this error `cannot load google.golang.org/grpc/resolver/dns: module google.golang.org/grpc@latest found (v1.25.0), but does not contain package google.golang.org/grpc/resolver/dns `

**Comment by jakexks** [comment]
Did you ever use go get -u? (don't do that!) If you've changed go.mod from what's in the repo you will have problems, a completely clean checkout works fine: 

https://gist.github.com/jakexks/40a9095c08f2980b6e2189035dfe3b35

**Comment by leaxoy** [comment]
This is etcd issue https://github.com/etcd-io/etcd/issues/11338

**Comment by met7or** [comment]
so how to fix this bug

**Comment by syinwu** [comment]
change go.mod "google.golang.org/grpc" version to 1.23.1

**Comment by yifanes** [comment]
> change go.mod "google.golang.org/grpc" version to 1.23.1

我刚刚和同事看了半天,我个人觉得作为 `etcd` 这么优秀的开源产品, 客户端没有添加mod,出现这种问题,真的不应该.
谢谢你的回答!

**Comment by vtolstov** [comment]
close now, as i'm cant reproduce it with current master
