### ISSUE TITLE
Use go-micro with gateway and grpc cause problems

### ISSUE THREAD

**Issue by EgorkZe** [micro/go-micro#924]
Hi! Trying to make service with micro, grpc and gateway.
have such model 
```
syntax = "proto3";

import "google/api/annotations.proto";

package myhello;

service Greeter {
	rpc SayHello (HelloRequest) returns (HelloReply) {
		option(google.api.http) = {
			get: "/api/hello/{name}",
		};
	}
}

message HelloRequest {
	string name = 1;
}

message HelloReply {
	string message = 1;
}
```

and Makefile
```
build: 
	protoc -I${GOPATH}/src/github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis \
	 --plugin=protoc-gen-go=$(GOPATH)/bin/protoc-gen-go \
	 --plugin=protoc-gen-micro=$(GOPATH)/bin/protoc-gen-micro \
	 --proto_path=$(GOPATH)/src:. \
	 --micro_out=. --go_out=plugins=grpc:. \
	 --grpc-gateway_out=logtostderr=true:. \
	 proto/myhello/hello.proto
```

All creates without errors but appears one problem - gateway and micro generate same methods RegisterGreeterHandler and error RegisterGreeterHandler redeclared in this block.
As I understand I should use different Proto models for micro and grpc, but it is not good option, because I should support both models at the same time. Is there a way to handle this situation?

**Comment by vtolstov** [comment]
Can you try to generate gateway and micro files to different dirs?

**Comment by EgorkZe** [comment]
@vtolstov But what is the profit? Anyway it has one package name and an error about redeclaration will appear .

**Comment by allenkaplan** [comment]
I had this problem as well. After finding @EwanValentine had this problem with no resolution, I decided to use `micro api`. The rpc handler will automatically route your methods from each service.  Hopefully this solution works for you..

**Comment by vtolstov** [comment]
what kind of stuff you need from grpc-gateway? i have some generator that can create http.Handler that uses micro client and interact with go-micro server. So technically it works like grpc-gateway (i'm plan to add gorilla support to it, not it have only echo mux internally)

**Comment by vtolstov** [comment]
Now grpc-gateway can't be used with micro. In near feature we provide something that acts like grpc-gateway but uses all micro core stuff.
