### ISSUE TITLE
confuse about the real ip when addr.Extract() is called

### ISSUE THREAD

**Issue by nextpkg** [micro/go-micro#936]
When we have two private interfaces in server, like docker, addr.Extract() will return unexpected ip, for example, when we use `172.32.91.3/24` and `127.0.0.1/8`, it will return 127.0.0.1, but 172.32.91.3 can be better, because 127.0.0.1 is loopback address
```go
	a1, a2, _ := net.ParseCIDR("172.32.91.3/24")
	b1, b2, _ := net.ParseCIDR("127.0.0.1/8")

	addrs := []net.Addr{&net.IPNet{IP: a1, Mask: a2.Mask}, &net.IPNet{
		IP:   b1,
		Mask: b2.Mask,
	}}

	var ipAddr []byte
	var publicIP []byte

	for _, rawAddr := range addrs {
		var ip net.IP
		switch addr := rawAddr.(type) {
		case *net.IPAddr:
			ip = addr.IP
		case *net.IPNet:
			ip = addr.IP
		default:
			continue
		}

		b := ip.String()

		if !isPrivateIP(b) {
			publicIP = ip
			continue
		}

		ipAddr = ip
		break
	}

	// return private ip
	if ipAddr != nil {
		tool.Info(net.IP(ipAddr).String())
		return
	}

	// return public or virtual ip
	if publicIP != nil {
		tool.Info(net.IP(publicIP).String())
		return
	}
```

**Comment by aimpsmile** [comment]
I so have same  question!
I do't known how to solve it.  
how about now?

**Comment by nextpkg** [comment]
> I so have same question!
> I do't known how to solve it.
> how about now?

In summary,
1. I use `etcd` as my registry
2. Try to telnet `etcd` url and get local address before startup(I assume if I can connect `etcd`,I can connect the micro service)
3. Use this local address as my advice IP.

Now,it work well.

**Comment by aimpsmile** [comment]
> > I so have same question!
> > I do't known how to solve it.
> > how about now?
> 
> In summary,
> 
> 1. I use `etcd` as my registry
> 2. Try to telnet `etcd` url and get local address before startup(I assume if I can connect `etcd`,I can connect the micro service)
> 3. Use this local address as my advice IP.
> 
> Now,it work well.

It's the only way
