### ISSUE TITLE
Connection leak in grpc stream client

### ISSUE THREAD

**Issue by nixbo** [micro/go-micro#940]
It occurs when server returns any error from stream handler because grpc client closes connection only when receive `io.EOF` i.e. grpc status OK.

**Comment by vtolstov** [comment]
and can you provide minimal code line which contains this

**Comment by nixbo** [comment]
Looks like grpc stream does not use connection pool (https://github.com/micro/go-micro/blob/master/client/grpc/grpc.go#L200)
But in grpc stream implementation, we expect that connection may be reused (https://github.com/micro/go-micro/blob/master/client/grpc/stream.go#L76).

**Comment by vtolstov** [comment]
grpc stream does not need connection pooling, also stream are long-lived connections, so pooling is not needed. About error and io.EOF may be we have some error here. Needs investigation

**Comment by tegk** [comment]
gRPC streams not closed properly can lead to Go routine leaks indeed.

You could use leakcheck to make sure they do not run anymore:
https://github.com/grpc/grpc-go/blob/8fba5fc8fd4073dd1452d6b2c7335030848a41b1/test/leakcheck/leakcheck.go#L22

**Comment by vtolstov** [comment]
fix in https://github.com/micro/go-micro/pull/980

**Comment by vtolstov** [comment]
please recheck and close the issue, my limited testing says that no goroutine leak present (change merged to master)
