### ISSUE TITLE
go: verifying github.com/coreos/etcd@v3.3.17+incompatible: checksum mismatch

### ISSUE THREAD

**Issue by chriswilliams1977** [micro/go-micro#944]
Hi All,

I am trying to build a go-micro service and continually get the following error:

go: verifying github.com/coreos/etcd@v3.3.17+incompatible: checksum mismatch

I have seen posts which suggest to use Go modules and version 1.13. I have both and still get the error.
I have tried replacing the etcd import using replace go.etcd.io/etcd v3.3.17+incompatible => github.com/etcd-io/etcd v0.0.0-20190603181807-35a67024f680

I have tried to update the dependencies and clean the modules cache but cannot resolve this issue. Any suggestions?

Best
Chris

**Comment by asim** [comment]
What is your workflow?

```
export GO111MODULE=on

go get github.com/micro/go-micro
```

Does this not work? If you apply the `-u` flag it will attempt to update dependencies and usually this is where things fail.

**Comment by chriswilliams1977** [comment]
Hey Asim,

Thanks for getting back to me and sorry about the delay replying.
I fixed the problem. Basically I had an old version of go as a base image in the Dockerfile. Once I updated to 1.13.0 and turned GOModules on the build worked.

Thanks
Chris
