### ISSUE TITLE
Suggestion: add mock as dependency to improve unit test

### ISSUE THREAD

**Issue by spacewander** [micro/go-micro#953]
As been mentioned in https://github.com/micro/go-micro/pull/909, it would be better to introduce https://github.com/golang/mock to improve the quality of the unit tests.

There are three advantages:
1. It could allow us to write stubs without boilerplate.
2. It is easier to check the expected calls/call arguments with the generated mock stubs than manual writing ones.
3. By reducing the cost of writing mock stub, it encourages the developer to write more tests and test more deeply.

What about your guys' opinion?

**Comment by vtolstov** [comment]
Thanks, I'm prefer mockery to generate mocks for full interface of micro service server and client

**Comment by spacewander** [comment]
Thanks for your advise. I have just submitted a PR: https://github.com/micro/go-micro/pull/970 to improve my previous test case via mock generated by mockery.
