### ISSUE TITLE
Problem with running multiple servers in one application

### ISSUE THREAD

**Issue by phifty** [micro/go-micro#96]
For a test-setup I tried to run multiple `Server` instances in one application.

```
one := server.NewServer(server.Address("localhost:1600"), server.Registry(r), ...)
one.Start()
one.Register()

two := server.NewServer(server.Address("localhost:1601"), server.Registry(r), ...)
two.Start()
two.Register()
```

The second `Start` fails with the error `already listening on localhost:1600`. Is there a global shared state? I wonder why the address is needed anyway, since all (Registry, Transport and Broker) is run over nats (in my case). What is the local port needed for?

Many thanks in advance.

**Comment by asim** [comment]
So I do this

```
package main

import (
    "github.com/micro/go-micro/server"
)

func main() {
    one := server.NewServer(server.Address("localhost:1600"))
    one.Start()

    two := server.NewServer(server.Address("localhost:1601"))
    two.Start()
}
```

And I get this

```
2016/06/01 14:09:35 Listening on 127.0.0.1:1600
2016/06/01 14:09:35 Broker Listening on [::]:52515
2016/06/01 14:09:35 Listening on 127.0.0.1:1601
```

Can you provide a full example so I can reproduce the problem?

**Comment by phifty** [comment]
I should clearify, that I use the `mock` implementations of Registry, Transport and Broker for the test setup. The error to be thrown in the transport mock's `Listen` function. I'll try to assemble a more complete example.

**Comment by phifty** [comment]
Found it. My bad! There was a third server that took the address. Excuse the confusion.

I'm still curious why a listen address has to be speicifed for every implementation. Shouldn't it left to the implementation if a local port is needed (the `nats` plugin doesn't need one)?

**Comment by asim** [comment]
It doesn't have to be specified. It's an option. Options are optional. If you do not specify an address then it defaults to ":0", which lets the host allocate a port and binds to the first address it has. If you use nats it ignores the port.

**Comment by phifty** [comment]
The design makes sense. My first approach was to remove the `Address` option, but that resulted in the `already listening on :0` error. I guess the mock implementation needs some adjustment here (https://github.com/micro/go-micro/blob/master/transport/mock/mock.go#L129), since it doesn't seem to handle an address of `:0` right.

**Comment by asim** [comment]
Ah ok yea if you're talking about the mock implementation then its rather naive. Should be easy to fix the issue by randomly assigning an int to the port where its not set.

**Comment by asim** [comment]
https://github.com/micro/go-micro/commit/702072f177a4dad9de63e78c1f1433d12511159c

Pull master and try now. If its all good please close the issue. Cheers.
