### ISSUE TITLE
Is there an up-to-date example based on consul and grpc?

### ISSUE THREAD

**Issue by YahuiWong** [micro/go-micro#961]
The current example is not based on the latest version and cannot be debugged.

**Comment by veryrich** [comment]
同求。。。 现在要怎么使用consul呀？ 网上找的文档都不能用了

	"github.com/micro/go-micro"
	"github.com/micro/go-micro/registry"
	"github.com/micro/go-micro/registry/consul"

请问楼主解决了吗？

**Comment by asim** [comment]
Consul was deprecated
