### ISSUE TITLE
panic on proto.RegisterFooHandler() with server.HandlerOption/api.Endpoint{} since micro 1.16.0

### ISSUE THREAD

**Issue by crashdump** [micro/go-micro#966]
There seem to be a regression with 1.16.0 as it's now throwing `panic: assignment to entry in nil map`. This was working fine with 1.15.1 and below.

It's reproducible with the micro "api/meta" example [micro/examples/api/meta](https://github.com/micro/examples/tree/master/api/meta). 

The code below seem to be causing the error:

```go
_ = proto.RegisterFooHandler(service.Server(), new(Foo),
		api.WithEndpoint(&api.Endpoint{
			Name:        "Foo.Bar",
			Path:          []string{"/test"},
			Method:    []string{"GET"},
			Handler:     rpc.Handler,
		}),
```

```go
panic: assignment to entry in nil map
goroutine 1 [running]:
github.com/micro/go-micro/server.newRpcHandler(0x4a197a0, 0xc00013db60, 0xc00013db40, 0x2, 0x2, 0x538f601, 0xc00013db60)
/Users/_/Go/pkg/mod/github.com/micro/go-micro@v1.16.0/server/rpc_handler.go:36 +0x40c
github.com/micro/go-micro/server.(*router).NewHandler(...)
/Users/_/Go/pkg/mod/github.com/micro/go-micro@v1.16.0/server/rpc_router.go:389
github.com/micro/go-micro/server.(*rpcServer).NewHandler(0xc0000e28c0, 0x4a197a0, 0xc00013db60, 0xc00013db40, 0x2, 0x2, 0x49d38a0, 0xc00013fb01)
/Users/_/Go/pkg/mod/github.com/micro/go-micro@v1.16.0/server/rpc_server.go:373 +0x5a
github.com/micro/examples/api/meta/proto.RegisterExampleHandler(0x4ccf7a0, 0xc0000e28c0, 0x4cb1580, 0x53ab518, 0xc00013db40, 0x2, 0x2, 0xc000147c00, 0xc00013f920)
/Users/_/Go/src/github.com/micro/examples/api/meta/proto/api.micro.go:95 +0xd7
main.main()
/Users/_/Go/src/github.com/micro/examples/api/meta/meta.go:59 +0x3ff
exit status 2
```

This compiles and run fine on go-micro 1.15.1 and before.

**Comment by vtolstov** [comment]
i don't understand how this can bring this panic
@asim or @milosgajdos83 do you know?
as i see extractor always returns non nil metadata, also if endpoint is nil, no assigning happened

**Comment by vtolstov** [comment]
what server - grpc? if this is grpc i think that this is possible, because for grpc we have map[string]map[string]string

so inner map may be nil
but i don't understand context, why for grpc we have map[string]map[string]string

**Comment by milosgajdos** [comment]
Can't see off the top of my head. I had a quick look and can see that `extractEndpoint` can return `nil` but we handle that situation; unfortunately I'm not near my computer so can't investigate further at the moment. Will look either later tonight or tomorrow.

**Comment by crashdump** [comment]
Thank you for your quick replies, it's much appreciated!

It seems to be something to do with the function `extractEndpoint(method reflect.Method) *registry.Endpoint` in `server/extractor.go`.

It used to return:

```go
e := registry.Endpoint{
		Name:     "Foo",
		Request:  request,
		Response: response,
		Metadata: map[string]string{
			"stream": false,
		},
	}
```

and now returns:

```go
e := registry.Endpoint{
		Name:     "Foo",
		Request:  request,
		Response: response,
		Metadata: map[string]string{},
	}
```

which is a problem later in `server/rpc_handler.go:35` when trying to access `e.Metadata[k]`:

```go
			for k, v := range options.Metadata[e.Name] {
				e.Metadata[k] = v
			}
```

My apologies, I am not familiar (yet) with go-micro to propose a bug-fix.

**Comment by asim** [comment]
This bug was recently fixed but no patched release has been created yet. https://github.com/micro/go-micro/commit/72522a869ad7435a6f5de2f77431c9ce1ec57e65

**Comment by crashdump** [comment]
Thank you @asim, I can confirm that it's not a problem anymore with `github.com/micro/go-micro v1.16.1-0.20191120145442-11d81221cc90`.

Apologies for the noise, I should have started with this!
