### ISSUE TITLE
Multi network within the same DC needs to optimize gateway

### ISSUE THREAD

**Issue by hb-chen** [micro/go-micro#967]
Such as graphic, have 3 network `gateway-a-1` `gateway-a-2` `gateway-a-3`. Multi network within the same DC just broadcast it's directly connected network‘s routes.In this way, any call can only have a maximum of 2 routes to access the services of other `DC`.

|gateway|`go.micro.srv.s-2` routes|
|----|-----|
|gateway-a-1|gateway-b ~~gateway-a-2~~ ~~gateway-a-3~~|
|gateway-a-2|gateway-a-1 ~~gateway-a-3~~|
|gateway-a-3|gateway-a-1 ~~gateway-a-2~~|

![network_problem_ha](http://hbchen.com/img/micro/network_problem_ha.png)

**Comment by milosgajdos** [comment]
Can you please elaborate on this a bit more? It's a bit hard to "decrypt" the point you're trying to make on a few lines.

**Comment by hb-chen** [comment]
First I want network to be HA.
- Start three network in `DC A`, `gateway-a-1` `gateway-a-2` `gateway-a-3`
- Start one network in `DC B`, `gateway-b`, and `gateway-b` connect `gateway-a-1`
- Start one srv(`go.micro.srv.s-2`) in `DC B` ,  srv's routes as below.

|gateway|`go.micro.srv.s-2` routes|
|----|-----|
|gateway-a-1|gateway-b gateway-a-2 gateway-a-3|
|gateway-a-2|gateway-a-1 gateway-a-3|
|gateway-a-3|gateway-a-1 gateway-a-2|

`go.micro.srv.s-1` call `go.micro.srv.s-2` may have multi paths:
- `gateway-a-1` -> `gateway-b`
- `gateway-a-2` -> `gateway-a-1` -> `gateway-b`
- `gateway-a-2` -> `gateway-a-3` -> `gateway-a-1` -> `gateway-b`
- `gateway-a-3` -> `gateway-a-1` -> `gateway-b`
- `gateway-a-3` -> `gateway-a-2` -> `gateway-a-1` -> `gateway-b`

But I think this would be better, srv's routes don't need `gateway-a-2` `gateway-a-3`

|gateway|`go.micro.srv.s-2` routes|
|----|-----|
|gateway-a-1|gateway-b ~~gateway-a-2~~ ~~gateway-a-3~~|
|gateway-a-2|gateway-a-1 ~~gateway-a-3~~|
|gateway-a-3|gateway-a-1 ~~gateway-a-2~~|

Now `go.micro.srv.s-1` call `go.micro.srv.s-2`:
- `gateway-a-1` -> `gateway-b`
- `gateway-a-2` -> `gateway-a-1` -> `gateway-b`
- `gateway-a-3` -> `gateway-a-1` -> `gateway-b`
