### ISSUE TITLE
go-micro compiler error

### ISSUE THREAD

**Issue by cashwar3** [micro/go-micro#968]
<img width="716" alt="bug" src="https://user-images.githubusercontent.com/19532785/69325494-3524a880-0c85-11ea-992c-6944f6f88ccb.png">

os: windows10
version: go version go1.13.4 windows/amd64

**Comment by asim** [comment]
This was fixed. Please update the codebase.

**Comment by cashwar3** [comment]
![complier-err](https://user-images.githubusercontent.com/19532785/69327231-1e338580-0c88-11ea-8214-1908157ac8f8.jpg)
The latest code compilation still reports an error.

**Comment by asim** [comment]
Please try now

**Comment by cashwar3** [comment]
thank you，issue is fixed

**Comment by cashwar3** [comment]
thank you，issue is fixed

**Comment by crazybber** [comment]
some details : https://github.com/micro/micro/pull/436
