### ISSUE TITLE
Rules and the blacklist

### ISSUE THREAD

**Issue by asim** [micro/go-micro#97]
The blacklist is causing people some pain. Its blanket blacklisting across errors is not good enough. Blacklisting needs to be context specific. This makes life a bit difficult. It's best to turn this off by default but also provide an easier way to add features like this.

Proposal. Create something like a rule (maybe think of a better name) that basically allows the core of the selector to be chained. 

The interface

```
type Rule interface {
  Filter(services []*registry.Service) []*registry.Service {
  Mark(service string, node *registry.Node, err error)
  Reset(service string)
}
```

The internals

```
Select ...

for _, r := range s.opts.Rules {
  services = r.Filter(services)
}

Mark ...

for _, r := range s.opts.Rules {
  r.Mark(service, node, err)
}

Reset ...

for _, r := range s.opts.Rules {
  r.Reset(service)
}
```

The provide a way to add this as an options

```
func WithRule(r ...Rule) Option {
  return func(o *Options) {
    o.Rules = append(o.Rules, r...)
  }
}
```

Usage

```
selector.NewSelector(selector.WithRule(blacklist))
```

or

```
selector.Init(selector.WithRule(blacklist))
```

**Comment by phifty** [comment]
We've also some trouble with the blacklist. Is there currently a way to switch this feature off?

**Comment by asim** [comment]
There's no way to turn it off at the moment. I'll look into this tomorrow. You can implement a selector fairly easily if you have specific requirements.

**Comment by asim** [comment]
The blacklisting has been temporarily disabled until a better solution can be created.

**Comment by asim** [comment]
I've stripped blacklisting from the default and caching selectors. It's causing more problems than its worth. Reworking the selector interface is proving to be a problem and it's unlikely that I'll find a better solution than how it is now. It highlights the fact that one should not attempt to conflate a single selector but build one that's fit for purpose. Making something pluggable and then shoving more pluggability into it is pretty useless. I've created a separate blacklisting selector in go-plugins which can then be worked on to add options for specifying the types of errors to fail on. Otherwise for anything more advanced, I'll be building that into go-platform/router.

**Comment by phifty** [comment]
Thanks for stripping the blacklisting. That should help with our problem for now. I was about to implement an own selector.

Basically, blacklisting is a useful feature, but I agree that it's tricky to implement well. In our case, it would have helped to get some insight in the process. I was mostly unclear to me why a service is blacklisted and how many instances of that service are left. Maybe some callback would help here to log the error or influence the decision (if the service should be blacklisted or not).
