### ISSUE TITLE
example.Call Response Interesting question

### ISSUE THREAD

**Issue by superpluss** [micro/go-micro#977]
if call method
```go
func (e *Example) Call(ctx context.Context, req *example.Request, rsp *example.Response) error {
	log.Log("Received Example.Call request")
	rsp=&example.Response{
		Msg:                  "Hello " + req.Name,
	}
	//rsp.Msg = "Hello " + req.Name
	return nil
}
```
response
```json
{}
```
result is empty
but
```go
func (e *Example) Call(ctx context.Context, req *example.Request, rsp *example.Response) error {
	log.Log("Received Example.Call request")
	//rsp=&example.Response{
	//	Msg:                  "Hello " + req.Name,
	//}
	rsp.Msg = "Hello " + req.Name
	return nil
}
```
response
```json
{
    "msg": "Hello king"
}
```
result success

micro command
```bash
MICRO_REGISTRY=etcd \
MICRO_API_HANDLER=rpc \
MICRO_API_NAMESPACE=go.micro.srv \
micro api
```
What is the difference between the two ways of writing, why do you get different results?

**Comment by asim** [comment]
`rsp` is a pointer to a value. What you're essentially doing in the first example is reassigning the pointer to that value. This will not work. You would have to dereference it `*rsp = example.Response{`

**Comment by superpluss** [comment]
thanks

> `rsp` is a pointer to a value. What you're essentially doing in the first example is reassigning the pointer to that value. This will not work. You would have to dereference it `*rsp = example.Response{`
