### ISSUE TITLE
why change the etcd registry prefix?

### ISSUE THREAD

**Issue by weisd** [micro/go-micro#983]
we use etcdv3 registry for 2 years
the prefix  value is "/micro-registry"
but now it been change to /micro/registry/

**Comment by zycbobby** [comment]
It makes sense, I also wondered

**Comment by milosgajdos** [comment]
Semantically `/micro/registry` makes more sense than `/micro-registry` as `micro` might end up using `etcd` to store other data than the service registration records under the same `/micro/` prefix. 
Apologies if this has caused any issues for you. I'm closing this issue now.
