### ISSUE TITLE
Is there any example on consul cluster-go micro 

### ISSUE THREAD

**Issue by ghost** [micro/go-micro#985]
let me know any example on consul cluster -go micro, complete flow of registration of service to cluster and client/services querying the cluster about other services

**Comment by milosgajdos** [comment]
There are plenty of examples for wide range of use cases in https://github.com/micro/examples

Please note,`consul` is now a plugin so if you want to use it, please make sure you read how to use plugins https://github.com/micro/go-plugins

I'm closing this issue as everything is documented in official docs, examples and plugins repo.
